neo4j-contrib/neo4j-apoc-procedures

- build.gradle
- readme.adoc
- src/main/java/apoc/algo/Algo.java
- src/main/java/apoc/path/PathExplorer.java
- src/main/java/apoc/path/RelationshipTypeAndDirections.java
- src/test/java/apoc/algo/AlgoTest.java
- src/test/java/apoc/path/RelationshipTypeAndDirectionsTest.java
For now a wrapper for GraphAlgoFactory.dijkstra is available.
Note: I've refactored the existing parsing of relationship types and directions from PathExplorer into a reusable class together with tests.
> first batch of graph algo functions

- src/main/java/apoc/date/Date.java
- src/test/java/apoc/date/DateTest.java
> Fixes date test

- src/main/java/apoc/date/Date.java
- src/test/java/apoc/date/DateTest.java
Reverts neo4j-contrib/neo4j-apoc-procedures#14
Does not build on other locales.
> Revert "Fixes date test"

- docs/spatial.adoc
- readme.adoc
- src/main/java/apoc/result/DistancePathResult.java
- src/main/java/apoc/spatial/Distance.java
- src/test/java/apoc/spatial/DistanceTest.java
Example : 
```
MATCH (a:City {name:'bruges'}), (b:City {name:'dresden'})
MATCH p=(a)-[*]->(b)
WITH collect(p) as paths
CALL apoc.spatial.sortPathsByDistance(paths) YIELD path, distance
RETURN path, distance
```
> spatial - sort collection of paths by distance

- build.gradle
- docs.sh
- index.html
The additional copy task is necessary as asciidoctor cannot directly output to the root of the project in a Windows system due to [file locking](https://discuss.gradle.org/t/error-with-a-copy-task-on-windows/1803/4). Having it output to a build folder then copying from there ensures that the task will run in any system.
*Removed the shell script, as it's no longer needed.*
Note that the index.html is 100% generated by asciidoctor
> Added new Gradle task to run asciidoctor and build the index.html file

- build.gradle
- src/main/java/apoc/result/MapResult.java
- src/main/java/apoc/result/RowResult.java
This Pull Request is meant as a discussion starter and needs
some clarifications before it can be merged.
> Use Neo4j Stored Procedure compiler

- src/main/java/apoc/cypher/Cypher.java
now it can be found with apoc.help
> fixed procedure annotation for apoc.cypher.doIt

- pom.xml
- src/main/java/apoc/date/Date.java
... and cheekily adding myself to the list of DEVs, there will be more stuff coming from GraphAware as we will retire some of our modules and migrate the functionality to APOC
> Fixing a failing test

- src/main/java/apoc/index/FreeTextQueryParser.java
- src/test/java/apoc/index/FreeTextSearchTest.java
depending if query string begins with ? or * either the classic parser is used or another instance configured with "setAllowLeadingWildcard(true)"
> adding support for leading wildcards in query strings

- .travis.yml
- enable caching
- only one gradle invocation (skip install phase)
- no gradle daemon
> tweak travis settings

- build.gradle
- src/main/java/apoc/coll/Coll.java
- src/main/java/apoc/result/ListListResult.java
- src/main/java/apoc/result/ListResult.java
- src/main/java/apoc/schema/Properties.java
It now rejects List rawtypes, this commit fixes them.
> Upgrade stored procedure compiler to 1.0.1

- src/main/java/apoc/util/Util.java
References https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/193
I did not add tests as the original methods did not have tests either and all the affected lines are covered by other tests.
> exposed node and relationship methods in Util

- docs/overview.adoc
- src/main/java/apoc/date/Date.java
- src/test/java/apoc/date/DateTest.java
> added apoc.date.systemTimezone() for 3.0

- docs/index.html
- docs/overview.adoc
- docs/text.adoc
- src/main/java/apoc/text/Strings.java
- src/test/java/apoc/text/StringsTest.java
This function returns the matching groups based on regex.
> adding new function apoc.test.regexGroups

- docs/overview.adoc
- src/main/java/apoc/coll/Coll.java
- src/test/java/apoc/coll/CollTest.java
Going to use the 3.1 branch for this the additions can be functions instead of procedures, and so we can allow optional parameters.
> Added new functions to apoc.coll - shuffle(), randomItem(), randomItems().

- src/test/java/apoc/coll/CollTest.java
- src/test/java/apoc/convert/ConvertTest.java
Ignore annotations removed for all the tests related to user defined functions.
> Fixes #333

- src/main/java/apoc/es/ElasticSearch.java
- src/test/java/apoc/es/ElasticSearchTest.java
Refactoring of some methods in ElasticSearch class in order to do unit test for the url creation (according to the parameters: index, type, id, query ...)
> rest url should have not final question mark if no query fixes #318

- docs/elasticsearch.adoc
- src/main/java/apoc/es/ElasticSearch.java
- src/test/java/apoc/es/ElasticSearchTest.java
The elasticsearch.adoc is now updated with a section that is focused on pagination with ES.
> Add documentation for the integration of ES pagination fixes Issue #179

- src/main/java/apoc/gephi/Gephi.java
- src/test/java/apoc/gephi/GephiTest.java
I added an optional weight property parameter, so you can pick which property do you want to use as a weight or set it at null for standard 1.0 weight
> GephiWeightedRelationships

- src/main/java/apoc/path/PathExplorer.java
- src/test/java/apoc/path/ExpandPathTest.java
> Fixed path expander 'limit' interaction with 'minLevel'

- src/main/java/apoc/cypher/Cypher.java
- src/test/java/apoc/cypher/CypherTest.java
New procedures apoc.when(), apoc.when.do(), apoc.whenMany(), and apoc.whenMany.do()
This fulfills feature request #396.
Open for suggestions and improvement, please don't merge yet.
Documentation will be updated once final suggestions and improvements are applied.
> Added conditional cypher execution

- docs/expand.adoc
- docs/overview.adoc
- src/main/java/apoc/path/PathExplorer.java
- src/test/java/apoc/path/ExpandPathTest.java
- src/test/java/apoc/path/SubgraphTest.java
This fulfills feature request #420
> Allowed optional config param in path expander procedures

- docs/cypher.adoc
- docs/overview.adoc
This is the documentation for PR #398
> Added documentation for conditional cypher execution procedures

- docs/gephi.adoc
did you mean by `// TODO also generate clustering information.` to show examples/tutorial of Gephi usage ?
> added-gephi-export-weighted-network-docs

- src/main/java/apoc/path/PathExplorer.java
This should prevent some unnecessary object creation
> Replaced putIfAbsent() with computeIfAbsent() for some map defaults

- src/main/java/apoc/util/Utils.java
Added SHA256, SHA384, SHA512 user functions under `apoc.util.*` with the same logic of `apoc.util.sha1`.
> Added some hashing alghoritms to apoc.util

- docs/periodic.adoc
- src/main/java/apoc/periodic/Periodic.java
- src/test/java/apoc/periodic/PeriodicTest.java
"Countdown" function is now annotated as a procedure. I added also a test and a simple example for the documentation.
> re-introduce countdown fixes #260

- docs/big-graph-from-cypher.adoc
- docs/index.adoc
- docs/script/performanceCypherTest.sh
We added the documentation with link to the issue and the commands that we used.
> Fixes #439 - test export / import of larger graphs to/from cypher

- src/test/java/apoc/index/UpdateFreetextIndexTest.java
not yet merge, this PR is mostly for triggering a travis build.
> shrinking pagecache for less memory consumption

- src/test/java/apoc/export/csv/ExportCsvTest.java
- src/test/java/apoc/index/FulltextIndexTest.java
- src/test/java/apoc/monitor/IdsProcedureTest.java
- src/test/java/apoc/refactor/GraphRefactoringTest.java
- src/test/java/apoc/schema/SchemasTest.java
- src/test/java/apoc/trigger/TriggerTest.java
- src/test/java/apoc/util/TestUtil.java
- src/test/java/apoc/util/UtilsTest.java
amended fixes to failing tests due to changes in `testCall`
> fixes #550 test call silent failure

- src/main/java/apoc/text/Strings.java
- src/test/java/apoc/text/StringsTest.java
Rebased changes for:
- apoc.text.random(length, [valid_chars]) - #563
- apoc.text.capitalize, apoc.text.capitalizeAll, apoc.text.decapitalize, apoc.text.swapCase, apoc.text.camelCase, apoc.text.snakeCase, apoc.text.toUpperCase functions - #530
> Random Strings and Text Functions (v2)

- src/test/java/apoc/refactor/GraphRefactoringTest.java
See https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/590 -- i tried reproducing the issue, it seems the test is passing fine.
> Issue #590 - test passing fine

- docs/gephi.adoc
- docs/overview.adoc
- src/main/java/apoc/gephi/Gephi.java
- src/test/java/apoc/gephi/GephiTest.java
Added support for exporting all properties from neo4j to gephi minus the reserved gephi parameter.  When approved I can also create a separate PR for 3.1 branch
> Add exporting properties to gephi

- src/main/java/apoc/export/util/FormatUtils.java
- src/test/java/apoc/export/util/FormatUtilsTest.java
fix issue #579: consistent Label order using export csv
> Consistent Label order (#579)

- src/main/java/apoc/load/LoadCsv.java
- src/test/java/apoc/load/LoadCsvTest.java
- src/test/resources/test-pipe-column.csv
Change array pattern to be handled as a simple separator character rather than a regular expression
> Enable pipe as CSV arraySep character, fix #626

- docs/overview.adoc
@jexp I wasn't familiar with the adoc, but I think I found the right place. Let me know if you agree. Thanks for pointing that out.
> #639 #640 add adoc for distinct and distinctCount

- src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java
- src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
- src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java
- src/main/java/apoc/export/cypher/formatter/CypherFormatter.java
- src/main/java/apoc/export/cypher/formatter/CypherFormatterUtils.java
- src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java
- src/main/java/apoc/export/util/ExportFormat.java
- src/test/java/apoc/export/cypher/ExportCypherTest.java
Quick'n'dirty attempt to fix the issue, while listening to the end keynote of Devoxx Morocco :)
> [#663] Support composite indices in Cypher export

- src/main/java/apoc/export/util/ExportFormat.java
Change the case inside the constant CYPHER_SHELL.
Junit test passed.
> Fix #659 Change CYPHER_SHELL format from upper case to lower case.

- src/test/java/apoc/periodic/PeriodicTest.java
Try several times instead of hardcoding a wait period.
> Fix flaky periodic test

- docs/overview.adoc
- src/main/java/apoc/nodes/Nodes.java
Fixed mongodb formatting.
Added apoc.nodes.delete() to Lookup and Manipulation Procedures subsection.
Added the following missing documentation to new Node Functions subsection in the Helpers section:
apoc.nodes.isDense()
apoc.nodes.connected()
apoc.node.relation.exists()
apoc.node.relationship.types()
apoc.node.degree()
apoc.create.uuid()
> Fixed some overview adoc formatting and added missing documentation.

- docs/overview.adoc
- src/main/java/apoc/nodes/Nodes.java
- src/test/java/apoc/nodes/NodesTest.java
Also provided an example of the rel-direction-pattern syntax
> Allowed apoc.node.degree() to use untyped directions

- src/main/java/apoc/export/graphml/XmlGraphMLReader.java
- src/test/java/apoc/export/graphml/ExportGraphMLTest.java
First of all, thanks for this awesome project!
This commit adds functionality to import lists, as exported by the GraphML exporter.
> Enable parsing of lists in GraphML Import

- src/main/java/apoc/algo/PathFinding.java
- src/main/java/apoc/util/Util.java
- src/test/java/apoc/algo/PathFindingTest.java
* fixing #763 
* deprecating dijkstraWithDefaultWeight in favour of using a default parameter in dijkstra
> fix for #763

- .travis.yml
- build.gradle
- src/main/java/apoc/path/PathExplorer.java
- src/test/java/apoc/periodic/PeriodicTest.java
this PR is there for triggering a travis build.
Please DO NOT MERGE THIS PR.
> fixing travis build

- docs/loadcsv.adoc
Add missing dependency to xlsx docs.
> Fixes #822

- src/main/java/apoc/cypher/CypherFunctions.java
Updated docs for runFirstColumnMany an runFirstColumnSingle with correct number of arguments.
> fixes #941 - Updated docs for runFirstColumnMany and runFirstColumnSingle

- docs/loadcsv.adoc
Some minor clarifications in the CSV importer's documentation.
> Reword and clarify CSV import documentation

- docs/loadjdbc.adoc
> Fix example.

- src/main/java/apoc/export/csv/CsvEntityLoader.java
- src/main/java/apoc/export/csv/CsvLoaderConfig.java
- src/test/java/apoc/export/csv/ImportCsvTest.java
Fixes #948. Also fix handling quotation characters, which was made possible by PR #879
> Handle separator and quote chars properly, fixes #948

- src/test/java/apoc/load/LoadS3Test.java
> Fixes #959 in v3.5

- src/test/java/apoc/export/csv/ImportCsvTest.java
> Add test case to check duplicate nodes

- src/test/java/apoc/index/IndexUpdateTransactionEventHandlerTest.java
The test is disabled for now. Once https://github.com/neo4j/neo4j/commit/7b8baa607cd63a70303437de7ebb1e254a9e42ff is part of a release (3.4.10) we expect this test to succeed.
> fulltext: new (disabled) test for delete anomalies

- docs/data/exportJSON/query_node_labels.json
- docs/exportCypher.adoc
- docs/exportJson.adoc
- docs/overview.adoc
- src/main/java/apoc/export/cypher/formatter/CypherFormatterUtils.java
- src/main/java/apoc/export/graphml/ExportGraphML.java
- src/main/java/apoc/export/json/ExportJson.java
- src/main/java/apoc/export/json/JsonFormat.java
- src/main/java/apoc/export/json/JsonFormatSerializer.java
- src/main/java/apoc/export/util/FormatUtils.java
- src/main/java/apoc/export/util/MetaInformation.java
- src/main/java/apoc/export/util/PointSerializer.java
- src/main/java/apoc/export/util/TemporalSerializer.java
- src/main/java/apoc/util/JsonUtil.java
- src/test/java/apoc/export/csv/ExportCsvTest.java
- src/test/java/apoc/export/cypher/ExportCypherTest.java
- src/test/java/apoc/export/graphml/ExportGraphMLTest.java
- src/test/java/apoc/export/json/ExportJsonTest.java
Fixes #930 
​
export function label ordering
​
​
​
- All label exported are ordered ascending
> fixes #930 - export function label ordering

- docs/overview.adoc
Fixes #1021
Add documentation to changes made by #1005
- Update description of config parameter related to export procedures
> fixes #1021 - Add documentation to changes made by #1005

- docs/overview.adoc
- docs/refactor.adoc
- src/main/java/apoc/refactor/util/PropertiesManager.java
- src/main/java/apoc/refactor/util/RefactorConfig.java
- src/test/java/apoc/refactor/GraphRefactoringTest.java
Fixes #1027 
Graph Refactoring Procedures Documentation
- Update documentation with right parameter value
> fixes #1027 - Graph Refactoring Procedures Documentation

- src/main/java/apoc/convert/Json.java
- src/test/java/apoc/convert/ConvertJsonTest.java
Fixes #810
apoc.convert.toTree returns invalid data?
- Fix bug when export data from apoc.convert.toTree
> fixes #810 - apoc.convert.toTree returns invalid data?

- .travis.yml
- src/test/java/apoc/periodic/PeriodicTest.java
> fix travis config to work with updated gradle

- docs/loadxml.adoc
- src/main/java/apoc/load/SkipWhitespaceInputStream.java
- src/main/java/apoc/load/Xml.java
- src/test/java/apoc/load/SimpleXmlTest.java
- src/test/java/apoc/load/SkipWhitespaceInputStreamTest.java
- src/test/java/apoc/load/XmlTest.java
Implemented additional features in close sync with @kuczera
> character index and more config options for `apoc.xml.import`

- src/main/java/apoc/data/url/ExtractURL.java
- src/test/java/apoc/data/url/ExtractURLTest.java
> #1077 : replace URL by URI to allow non standard protocol

- docs/hashing.adoc
- docs/index.adoc
- src/main/java/apoc/hashing/Fingerprinting.java
- src/test/java/apoc/hashing/FingerprintingTest.java
> add functions for node, relationship or graph hash calculation

- src/main/java/apoc/coll/Coll.java
Fixes #1076 
Replaced single level flatten of lists with any-level flatten of lists
- added recursive parameter to apoc.coll.flatten
- apoc.coll.flatten does now allow plain objects at the lowest level
> fixes #1076 - apoc.coll.flatten recursive

- src/test/java/apoc/export/cypher/ExportCypherEnterpriseFeaturesTest.java
- src/test/java/apoc/export/cypher/ExportCypherTest.java
- src/test/java/apoc/util/TestUtil.java
Fixes #1101 
Added the `ExportCypherEnterpriseFeaturesTest` for specific enterprise features tests. On Travis we get FileNotFoundException with "Permission Denied" so we test "stream" feature using the result map in orde to assert the statement
- Added the `ExportCypherEnterpriseFeaturesTest` for specific enterprise features tests
> fixes #1101: Test Export CSV Enterprise version

- .gitignore
- src/test/java/apoc/spatial/GeocodeTest.java
- src/test/java/apoc/trigger/TriggerDisabledTest.java
Removed two broken tests that made the CI fail (non-deterministically?). The idea is to raise an issue for both and then merge this PR.
> Remove broken tests from build

- src/main/java/apoc/export/xls/ExportXls.java
- src/main/java/apoc/export/xls/XlsExportConfig.java
- src/main/java/apoc/util/FileUtils.java
- src/test/java/apoc/export/csv/ExportXlsTest.java
This PR addes couple of procedure for exporting to an Excel file using the POI library.
Note: docs are still missing. Working on this.
> #1153 export to excel

- docs/asciidoc/custom.adoc
- src/main/java/apoc/custom/CypherProcedures.java
- src/test/java/apoc/custom/CypherProceduresTest.java
Fixes #1104
- created the structure `CustomProcedureInfo` which contains the info about procedures/functions
- created the procedure `apoc.custom.list`
> Issue 1104: CALL apoc.custom.list() returning list of custom procedures and functions

- src/main/java/apoc/Pools.java
Fixes #965
The RejectedExecutionHandler used by the APOC Pools for all sorts of asynchronisity and parallelism, was attempting to block the submitting thread until the task was accepted by the executor.
This was done by letting the rejected execution handler submit the rejected task to the executor again. If the task was once again rejected, the handler would be called again, and so on.
The troubling part of this is that this happened recursively. This could produce some enourmous stack depths for many threads.
Some threads would get StackOverflowErrors when trying to submit tasks, which could break invariants and compromise the integrity of the system.
The solution is to make use of the blocking APIs on the internal task queue of the executor, to manually enqueue tasks in a blocking way. …
> Avoid using recursion for re-submitting rejected tasks in the Pools.

- src/main/java/apoc/mongodb/MongoDB.java
- src/test/java/apoc/mongodb/MongoDBTest.java
Fixes #1177
Changed the way that the MongoDB procedures are executed.
- created a new method `executeMongoQuery` which removes the `try-with-resource` and manage close of the `Coll` when the stream is closed with the `Stream#onClose` method
> fixes #1177: MongoDB Connection State is not 'open'

- src/main/java/apoc/load/LoadCsv.java
- src/main/java/apoc/metrics/Metrics.java
- src/main/java/apoc/util/FileUtils.java
- src/test/java/apoc/metrics/MetricsTest.java
Fixes #1181
Fixed the bug and created a Test case with Testcontainers
- fixed the bug
- created the testing class `MetricsTest`
> fixes #1181: APOC 3.5.0.3 changes import file URL paths too aggressively

- src/test/java/apoc/bolt/BoltTest.java
- src/test/java/apoc/couchbase/CouchbaseConnectionIT.java
- src/test/java/apoc/couchbase/CouchbaseIT.java
- src/test/java/apoc/couchbase/CouchbaseManagerIT.java
- src/test/java/apoc/couchbase/CouchbaseTest.java
- src/test/java/apoc/custom/CypherProceduresClusterTest.java
- src/test/java/apoc/es/ElasticSearchTest.java
- src/test/java/apoc/export/csv/ExportCsvIT.java
- src/test/java/apoc/export/cypher/ExportCypherEnterpriseFeaturesTest.java
- src/test/java/apoc/export/cypher/ExportCypherTest.java
- src/test/java/apoc/load/CassandraJdbcTest.java
- src/test/java/apoc/load/PostgresJdbcTest.java
- src/test/java/apoc/metrics/MetricsTest.java
- src/test/java/apoc/model/ModelTest.java
- src/test/java/apoc/mongodb/MongoDBTest.java
- src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
- src/test/java/apoc/util/TestContainerUtil.java
Fixes #1212 
- fixed tests into `ExportCypherEnterpriseFeaturesTest.java`
- disabled docker tests in Travis
> fixes #1212: Fix ignored tests

- src/test/java/apoc/bolt/BoltTest.java
- src/test/java/apoc/custom/CypherProceduresClusterTest.java
- src/test/java/apoc/date/DateTest.java
- src/test/java/apoc/export/csv/ExportCsvIT.java
- src/test/java/apoc/export/cypher/ExportCypherEnterpriseFeaturesTest.java
- src/test/java/apoc/metrics/MetricsTest.java
- src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
Fixes #1217
- Restored the `clean` phase for docker based tests
- Corrected the procedure name in `DateTest.java`
> fixes 1217: Fix Pre Relase Tests

- build.gradle
> update build to generate maven compliant directory structure

- src/main/java/apoc/cypher/CypherInitializer.java
- src/test/java/apoc/cypher/CypherInitializerTest.java
Fixes #1231 
- support for single initializer
- support for apoc procedures being used in initializers
> Neo4j apoc procedures 1231

- src/main/java/apoc/algo/Cliques.java
Correction of the procedure output's name in the @Description
-
-
-
> Documentation correction

- docs/asciidoc/help.adoc
Fixes #1171
Added documentation to `apoc.version()`function
> fixes #1171: request to document apoc.version

- docs/asciidoc/utilities/collection.adoc
- docs/asciidoc/utilities/conversion.adoc
- docs/asciidoc/utilities/map.adoc
- docs/build.gradle
> Apoc docs 3

- src/main/java/apoc/export/csv/CsvFormat.java
- src/test/java/apoc/export/csv/ExportCsvTest.java
Fixes #1246
Fixed the bug.
- Fixed the bug in the export
> fixes #1246: Incorrect headers order after apoc csv export in community edition 3.5.6

- src/main/java/apoc/export/csv/ExportCSV.java
- src/main/java/apoc/export/cypher/ExportCypher.java
- src/main/java/apoc/export/json/ExportJson.java
- src/main/java/apoc/util/FileUtils.java
- src/test/java/apoc/export/ExportStreamsStatementsTest.java
> fixes #1266: apoc.export streaming still checks for export=true config

- docs/asciidoc/utilities/text.adoc
Fixes https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/331#issuecomment-522374371
> Add details to fuzzyMatch docs

- src/test/java/apoc/export/cypher/ExportCypherEnterpriseFeaturesTest.java
Allow reading files to ExportCypherEnterpriseFeaturesTest
> fixes #1214: Allow reading files to ExportCypherEnterpriseFeaturesTest

- docs/asciidoc/export/exportCypher.adoc
- src/main/java/apoc/export/cypher/ExportCypher.java
- src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java
- src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
- src/main/java/apoc/export/cypher/formatter/CypherFormatter.java
- src/main/java/apoc/export/util/ExportConfig.java
- src/main/java/apoc/export/util/ExportFormat.java
- src/test/java/apoc/export/cypher/ExportCypherTest.java
- src/test/java/apoc/load/LoadS3Test.java
Fixes #1291
Provide support to full-text indexes
> fixes #1291: apoc.export.cypher.query bug on multiple node index

- build.gradle
- docs/asciidoc/import/webapis.adoc
- src/main/java/apoc/util/ApocUrlStreamHandlerFactory.java
- src/main/java/apoc/util/FileUtils.java
- src/main/java/apoc/util/google/cloud/GCStorageURLConnection.java
- src/main/java/apoc/util/google/cloud/GCStorageURLStreamHandler.java
- src/main/java/apoc/util/google/cloud/GCStorageURLStreamHandlerFactory.java
- src/test/java/apoc/load/LoadGoogleCloudStorageTest.java
- src/test/java/apoc/util/HdfsTestUtils.java
Fixes #1253 
- Added support for `gs://` protocol
> fixes: #1253: Add support for gs:// file prefix for Google Cloud Storage

- docs/asciidoc/utilities/collection.adoc
- src/main/java/apoc/coll/Coll.java
- src/test/java/apoc/coll/CollTest.java
Fixes #151
This is an attempt at implementing the new function coll.isEqualCollection that returns true if the two collections contain the same elements with the same cardinality in any order
- new UserFunction coll.isEqualCollection, internally uses an HashMap of object => cardinality to keep track of the cardinality of each element
> fixes #151 coll.isEqualCollection compare 2 collections in any order

- docs/asciidoc/utilities/text.adoc
- src/main/java/apoc/text/Strings.java
- src/test/java/apoc/text/StringsTest.java
Fixes https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1338
Added string multiplication with `apoc.text.repeat(item,count)`
> Add string mulitiplication apoc.text.repeat

- docs/asciidoc/import/loadjson.adoc
- src/test/java/apoc/load/LoadJsonTest.java
Fixes #1279
Added example
- Added example into docs
- Added test
> fixes #1279: Add information on POST request to apoc.load.jsonParams

- src/main/java/apoc/export/cypher/formatter/CypherFormatterUtils.java
- src/test/java/apoc/export/cypher/ExportCypherTest.java
> fixes #1366: apoc.export.cypher.* bug with multiple labels sorted

- src/main/java/apoc/periodic/Periodic.java
Fixes #1363
Improved the logging of `apoc.periodic.*` procedures by wrapping the runnable with the `wrapTask` method
- Improved the logging without breaking the execution chain (if the runnable throws an exception we just log the error and rethrow it)
> fixes #1363: Improve logging in Periodic procedure execution

- src/main/java/apoc/export/csv/CsvFormat.java
- src/test/java/apoc/export/csv/ExportCsvNeo4jAdminTest.java
Fixes #1335
Removed the `id` name for the property as default name for the `:ID` field
- Fixed the bug 
- added a test case
> fixes #1335: Using apoc.export.csv.graph with bulkImport:true produces wrong result for id property

- src/main/java/apoc/RegisterComponentFactory.java
Fixes #1385
Use ConcurrentHashMap to handle concurrent updates in the lifecycle
> Make RegisterComponentFactory use ConcurrentHashMap to handle concurrent updates in the lifecycle

- build.gradle
Fixes #1380
- Removed the unused dependencies
- tested the project
> fixes #1380: Update Jackson from org.codehaus.jackson to com.fasterxml.jackson

- build.gradle
- src/test/java/apoc/export/csv/ExportXlsTest.java
Fixes #1433
- updated poi to 4.1.2
> fixes #1433: Update poi version for security vulnerability

- build.gradle
Fixes #1423
- Updated BeanUtils to `1.9.4`
> fixes #1423: Upgrade common beantuils from 1.9.3

- docs/asciidoc/path-finding/expand-config.adoc
- docs/asciidoc/path-finding/expand-spanning-tree.adoc
- docs/asciidoc/path-finding/expand-subgraph-nodes.adoc
- docs/asciidoc/path-finding/expand-subgraph.adoc
- docs/asciidoc/path-finding/expand.adoc
- docs/asciidoc/path-finding/sequences.adoc
> Expand docs 2

- docs/asciidoc/path-finding/config-params.adoc
- docs/asciidoc/path-finding/expand-config.adoc
- docs/asciidoc/path-finding/expand-subgraph-nodes.adoc
- docs/asciidoc/path-finding/expand-subgraph.adoc
- docs/javascript/version.js
- docs/javascript/versionswitcher.js
> Expand nodes subgraph docs

- src/main/java/apoc/trigger/TriggerHandler.java
The kernel event handling creates a big expensive transaction snapshot
for every transaction if there are registered event handlers.
To avoid paying that overhead, unregister from the kernel if there
are no triggers.
This works as a complement to the config option, so you can deploy
large groups of databases with the config enabled but only pay the
overhead on those databases that use trigger.
> Only register with kernel if there are triggers

- docs/asciidoc/import/jsonpath.adoc
- docs/asciidoc/import/loadjson.adoc
Update json path documentation for explanation and move to an include file.
> Jmr expiry changes

- build.gradle
- docs/build.gradle
- src/main/java/apoc/coll/Coll.java
- src/test/java/apoc/meta/CollEnterpriseTest.java
> Coll min patch

- build.gradle
- docs/build.gradle
- src/main/java/apoc/coll/Coll.java
- src/test/java/apoc/coll/CollTest.java
- src/test/java/apoc/meta/CollEnterpriseTest.java
> Coll min patch2

- src/main/java/apoc/ApocKernelExtensionFactory.java
- src/main/java/apoc/trigger/Trigger.java
- src/test/java/apoc/trigger/TriggerRestartTest.java
Note: I'll cherry pick this to 4.0 as well.
> fix triggers not active after a restart

- src/test/java/apoc/util/TestcontainersCausalCluster.java
added timeout to container cluster formation
> added timeout to container cluster formation

- docs/asciidoc/_path_finding.adoc
- docs/asciidoc/advanced-querying/path-functions.adoc
- src/main/java/apoc/path/Paths.java
> Docs path manipulation

- docs/asciidoc/temporal/datetime.adoc
- src/main/java/apoc/date/Date.java
- src/main/java/apoc/temporal/TemporalProcedures.java
> Jennifer date conversion

- src/test/java/apoc/util/Neo4jContainerExtension.java
- src/test/java/apoc/util/TestcontainersCausalCluster.java
> fix cluster test on Teamcity

- docs/asciidoc/_cypher_execution.adoc
- docs/asciidoc/cypher-execution/cypher.adoc
- docs/asciidoc/cypher-execution/multi-statements.adoc
- docs/asciidoc/cypher-execution/parallel-cypher.adoc
- docs/docbook/content-map.xml
- src/main/java/apoc/cypher/Cypher.java
> Cypher execution docs

- readme.adoc
I only fixed a small typo error
> (docs): fixed small error

- src/test/java/apoc/load/JdbcTest.java
added test for apoc.load.jdbc with apoc.periodic.iterate
> added test for apoc.load.jdbc with apoc.periodic.iterate

- docs/asciidoc/utilities/hashing.adoc
- src/main/java/apoc/hashing/Fingerprinting.java
- src/main/java/apoc/hashing/FingerprintingConfig.java
- src/test/java/apoc/hashing/FingerprintingTest.java
Fixes #1562
- Added a new procedure `apoc.hashing.fingerprinting` in order to maintain the old one as deprecated
- added tests
- added documentation
> fixes #1562: Improve fingerprinting

- src/main/java/apoc/systemdb/SystemDb.java
The systemdb procedures should check if the current user is admin and fail otherwise.
> SystemDB procs check admin

- build.gradle
- src/main/java/apoc/custom/CypherProcedures.java
- src/main/java/apoc/custom/Signatures.java
- src/main/java/apoc/schema/Schemas.java
Fixes #1581
This PR contains two changes the one related to #1518 (because otherwise I had compilation problems) and the changes required to fix the problem raised in the #1581 
Fix the problem has been not quite straightforward because seems there is a bug in the Neo4j so I had to provide the workaround that you can find in `Schemas.java` from line 438 to 451.
> fixes #1581: Error in query - CALL apoc.schema.nodes()

- src/main/java/apoc/ApocSettings.java
Fixes #1589
Added settings into `ApocSettings.java`
> fixes #1589: Some settings don't work with Docker containers

- src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java
- src/main/java/org/neo4j/cypher/export/DatabaseSubGraph.java
- src/main/java/org/neo4j/cypher/export/SubGraph.java
removing license headers
please cherry-pick this to 4.1 and 4.2
> remove wrong license headers

- src/main/java/apoc/util/Util.java
please cherry-pick this one to 4.1/4.2 as well
> fixes #1606 add database name when calling dbms.cluster.role

- docs/asciidoc/modules/ROOT/partials/createExportGraph.adoc
> Missing [ before source

- src/main/java/apoc/Pools.java
- src/main/java/apoc/cypher/Cypher.java
- src/main/java/apoc/cypher/CypherInitializer.java
- src/main/java/apoc/index/SchemaIndex.java
- src/main/java/apoc/util/Util.java
please cherry pick this one to 4.1 and 4.2
> fixes #1592: apply setDaemon(true) everywhere a new thread is created

- src/main/java/apoc/monitor/Transaction.java
- src/test/java/apoc/monitor/TransactionProcedureTest.java
please cherry pick this to 4.1 and 4.2 branches
> fixes #1616: using TransactionIdStore for lastTx

- core/src/main/java/apoc/export/graphml/XmlGraphMLReader.java
- core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
Fixes #1610
Related to #1585
- Adjusted condition in `getRelationshipType(XMLEventReader reader)`
> fixes #1610: apoc.import.graphml fails reading file if readLabels param set

- docs/asciidoc/modules/ROOT/pages/export/json.adoc
> Added link to jsonlines.org and format explanation.

- build.gradle
- core/src/main/java/apoc/trigger/TriggerHandler.java
- core/src/test/java/apoc/trigger/TriggerTest.java
- docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc
expose tx metadata as an additional trigger parameter
please cherry pick that one to 4.2 as well.
> neo4j-apoc-procedures-1666

- core/src/main/java/apoc/export/graphml/XmlGraphMLWriter.java
- core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
Fixes #1449
NB: I've request to @mneedham a feedback for this change, so I'll remove this pr from draft after his reply.
- Changed `keyTypes` from `"label"` to `"labels"`
- Added test for `apoc.export.graphml.data`
> Fixes #1449: Possible bug in apoc graphml export

- src/test/java/apoc/bolt/BoltTest.java
Fixes the broken test of apoc.bolt.load.fromLocal on branch 4.0
> fixes apoc.bolt.load.fromLocal broken test on 4.0

- docs/asciidoc/modules/ROOT/pages/operational/init-script.adoc
Adding multiple cypher call example and change the config option to be less ambiguous as it references to the Neo4j configuration file.
> Update init script documentation

- core/src/test/java/apoc/export/cypher/ExportCypherTest.java
- settings.gradle
> fix apoc.export.cypher.all failing test

- core/src/main/java/apoc/convert/Convert.java
- core/src/main/java/apoc/util/Util.java
- full/src/test/java/apoc/get/GetProceduresTest.java
Fixes #1650
Fixed the bug
- Added test
> fixes #1650: apoc.get.rels() rejects some ID arrays

- build.gradle
- deps_after.log
Fixes #1719
Update the jetty version in order fix the CVE problem inside APOC
- updated jetty version
> fixes #1719: CVE reported within a sub-dependency

- docs/asciidoc/modules/ROOT/pages/import/web-apis.adoc
> fixes #1272: Documentation - Questionable location on exclamation point on compressed CSV

- docs/asciidoc/modules/ROOT/pages/database-integration/load-jdbc.adoc
Added links to Simba JDBC driver for BigQuery. Included example for additional autoCommit parameter that needs to be used along with link to Adam's blog that gives more detail
> Added description for BigQuery

- test-utils/src/main/java/apoc/util/TestContainerUtil.java
downgraded docker to 4.2.1 as 4.2.2 does not exists
> downgraded docker to 4.2.1 as 4.2.2 does not exists

- build.gradle
- core/src/test/java/apoc/test/EnvSettingRule.java
- core/src/test/java/apoc/util/UtilIT.java
updated testcontainers to `1.15.1`
> updated testcontainers

- src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
- src/main/java/apoc/util/Util.java
- src/test/java/apoc/export/cypher/ExportCypherEnterpriseFeaturesTest.java
- src/test/java/apoc/export/cypher/ExportCypherTest.java
- src/test/java/apoc/util/UtilQuoteTest.java
> Backport quote #1707 and export relationship #1708 fixes to 3.5

- core/build.gradle
- full/build.gradle
> Remove CVE-2020-25649

- core/src/main/java/apoc/periodic/Periodic.java
We've noticed that `apoc.periodic.iterate` has not been obeying the `concurrency` parameter setting. 
Looking into the code, it seems the procedure uses the default pooled executor when running with parallel=true, but the pool is `#cpus * 2`...so the concurrency ends up actually being **2x** the cpu cores and not what the user sets.
This PR changes the behavior to use a set cap via an `AtomicInteger` and keeps the same Future creation/submission logic but adds the decrement of the counter to the future's callback. 
If `parallel == false`, the gating is short-circuited at the expense of some small overhead for manipulating the `AtomicInteger` counter (for now?) and the single-threaded executor will force concurrency to zero.
> fix apoc.periodic.iterate not obeying concurrency

- core/src/test/java/apoc/StartupTest.java
- core/src/test/java/apoc/export/csv/ExportCsvIT.java
- core/src/test/java/apoc/export/cypher/ExportCypherEnterpriseFeaturesTest.java
- core/src/test/java/apoc/meta/CollEnterpriseTest.java
- core/src/test/java/apoc/meta/MetaEnterpriseFeaturesTest.java
- core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
- full/src/test/java/apoc/CoreExtendedTest.java
- full/src/test/java/apoc/cypher/CypherEnterpriseTest.java
- full/src/test/java/apoc/metrics/MetricsTest.java
- full/src/test/java/apoc/ttl/TTLMultiDbTest.java
- full/src/test/java/apoc/uuid/UUIDMultiDbTest.java
- test-utils/src/main/java/apoc/util/Neo4jContainerExtension.java
- test-utils/src/main/java/apoc/util/TestContainerUtil.java
Fixes TeamCI build for branch 4.3
> fixes neo4j container tests in case the container not exists

- docs/asciidoc/modules/ROOT/pages/export/csv.adoc
Just got tripped up reading, sorry if change is too small.
Fixing a typo.
> Pedantic: fix space in export to csv description

- core/src/main/java/apoc/export/graphml/XmlGraphMLReader.java
- core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
Fixes #1723
Fixes #1451
Changed node assignment from `this.tx` to `tx.getTransaction()`.
> Fixes #1723: Problem importing graphml which was exported graphml from apoc

- build.gradle
- full/src/main/java/apoc/bolt/Bolt.java
- full/src/main/java/apoc/bolt/BoltConfig.java
- full/src/test/java/apoc/bolt/BoltTest.java
- test-utils/src/main/java/apoc/util/TestContainerUtil.java
> fixes #1336: Create apoc.export.cypher format and outputs optimised for passing to apoc.bolt.execute

- core/src/main/java/apoc/trigger/TriggerHandler.java
- core/src/main/java/apoc/trigger/TriggerMetadata.java
- core/src/main/java/apoc/util/Util.java
- core/src/test/java/apoc/trigger/TriggerTest.java
- docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.periodic.csv
- docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.periodic.truncate.adoc
- full/src/test/java/apoc/trigger/TriggerExtendedTest.java
Fixes #1840
The `afterAsync` phase needs to rebind the entities
- Added test
> fixes #1840: [TRIGGER] createdRelationships after crash and afterAsync do nothing

- core/src/main/java/apoc/math/Maths.java
- docs/asciidoc/modules/ROOT/partials/usage/apoc.math.round.adoc
Based on https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/1804
Signed-off-by: Florent Biville <florent.biville@neo4j.com>
> Document rounding modes, add missing quotes around values

- core/src/main/java/apoc/periodic/BatchAndTotalCollector.java
- core/src/main/java/apoc/periodic/BatchAndTotalResult.java
- core/src/main/java/apoc/periodic/Periodic.java
- core/src/main/java/apoc/periodic/PeriodicUtils.java
- core/src/main/java/apoc/util/Util.java
- core/src/test/java/apoc/diff/DiffTest.java
- core/src/test/java/apoc/periodic/PeriodicTest.java
- docs/asciidoc/modules/ROOT/pages/overview/apoc.periodic/apoc.periodic.iterate.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.periodic/apoc.periodic.rock_n_roll.adoc
- full/src/main/java/apoc/periodic/PeriodicExtended.java
- full/src/test/java/apoc/periodic/PeriodicExtendedTest.java
cherry picking stuff from `4.2` to `4.1`
> 41 cherry picking stuff

- docs/asciidoc/modules/ROOT/pages/graph-updates/ttl.adoc
Added description of additional options to TTL
> Added description of additional options to TTL

- core/src/main/java/apoc/refactor/GraphRefactoring.java
- core/src/main/java/apoc/refactor/util/RefactorConfig.java
- core/src/main/java/apoc/refactor/util/RefactorUtil.java
Signed-off-by: Jennifer Reif <jennifer.reif@neo4j.com>
> Adjust relationship copy behavior when merging nodes

- .github/workflows/auto-cherry-pick.yml
Same as #1833 but for branch `4.2`
> Added auto cherry-picking action: branch 4.2

- .github/workflows/auto-cherry-pick.yml
Same as #1833 but for branch `4.3`
> Added auto cherry-picking action: branch 4.3

- docs/asciidoc/modules/ROOT/pages/nlp/aws.adoc
- docs/asciidoc/modules/ROOT/pages/nlp/azure.adoc
- docs/asciidoc/modules/ROOT/pages/nlp/gcp.adoc
Helping solve the https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1869.
I am only not sure about the Azure if there is an error or not for unsupported language.
> Add NLP language note in docs

- core/src/test/java/apoc/export/ExportStreamsStatementsTest.java
- core/src/test/java/apoc/export/csv/ExportCsvNeo4jAdminTest.java
- core/src/test/java/apoc/export/csv/ExportCsvTest.java
- core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
- full/src/test/java/apoc/monitor/TransactionProcedureTest.java
This setting is being removed from product now
> Remove usages of RelationshipTypeScanStoreSettings

- docs/antora/package-lock.json
- docs/antora/package.json
See https://github.com/neo4j-contrib/neo4j-apoc-procedures/security/dependabot/docs/antora/package-lock.json/handlebars/open
> Fix CVE-2021-23369

- core/src/main/java/apoc/convert/Json.java
- core/src/test/java/apoc/convert/ConvertJsonTest.java
> Fixes #1900: apoc.convert.toJson throws NullPointerException for null values in maps

- core/src/test/java/org/neo4j/test/rule/ImpermanentDbmsRule.java
- full/src/test/java/org/neo4j/test/rule/ImpermanentDbmsRule.java
Neo4j has moved to JUnit 5 and this rule is no longer available there.
> Include ImpermanentDbmsRule

- core/src/test/java/apoc/periodic/PeriodicTest.java
Fix failing testSubmitStatementWithParams
> Fix failing testSubmitStatementWithParams

- .github/workflows/CI.yaml
- build.gradle
- full/src/main/java/apoc/load/LoadDirectoryHandler.java
- full/src/main/java/apoc/load/LoadDirectoryItem.java
- full/src/test/java/apoc/load/LoadDirectoryTest.java
- full/src/test/java/apoc/ttl/TTLTest.java
The CI returns green even if there are failing tests
> fix CI false negative

- build.gradle
manage gradle ignoreFailures in GH Actions and TC build
> manage gradle ignoreFailures in GH Actions and TC build

- full/src/main/java/apoc/custom/CypherProceduresHandler.java
- full/src/test/java/apoc/custom/CypherProceduresStorageTest.java
This fixes #1744 like @vga91 already fixed for version 4.1
Fixes #1744 
fix loading custom procedures on neo4j restart
@vga91 fixed this issue for branch 4.1, but facing the same issue on 4.2 as there where conflicts merging those changes directly into the 4.2 branch I "reapplied" those changes on the 4.2 branch.
-
-
-
> fix loading custom procedures on neo4j restart

- full/src/main/java/apoc/load/LoadDirectory.java
- full/src/test/java/apoc/load/LoadDirectoryTest.java
Fixes #1911
- Bug with white spaces and empty string as path
> Fixes #1911: bug with white spaces

- docs/asciidoc/modules/ROOT/partials/usage/apoc.coll.containsAll.adoc
> Fixes #1857: Typos in doc for apoc.coll.containsAll

- docs/antora/package-lock.json
- docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.schema.node.constraintExists.adoc
- docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.schema.node.indexExists.adoc
- docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.schema.relationship.constraintExists.adoc
Currently breaking all dev guides/labs docs builds: 
https://github.com/neo4j-documentation/docs-refresh/runs/3088798991?check_suite_focus=true
> Fixes 4.1 xrefs

- build.gradle
> Bump to last Neo4j version

- core/src/main/java/apoc/meta/Meta.java
- core/src/test/java/apoc/meta/MetaTest.java
> Fixes #1925: Relationships in apoc.meta.schema can have wrong type result with a relatively small sample

- docs/asciidoc/modules/ROOT/pages/virtual/graph-grouping.adoc
Fixes #2024
Fixes #2042
Fixes #2043
> Fixes #2024: Fix doc per this document

- core/src/main/java/apoc/meta/Meta.java
fix bug generating by merging #2116 and #2057
> fix bug generating by merging #2116 and #2057

- core/src/main/java/apoc/atomic/util/AtomicUtils.java
- core/src/test/java/apoc/atomic/AtomicTest.java
> Fixes #1157: apoc.atomic.add and related procedures do not work with Integer properties

- core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java
- core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
- core/src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java
- core/src/main/java/apoc/export/cypher/formatter/CypherFormatter.java
- core/src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java
- core/src/test/java/apoc/export/cypher/ExportCypherTest.java
> Fixes #2048: Don't support relationship indexes in apoc.export.cypher.all

- core/src/main/java/apoc/CoreApocGlobalComponents.java
- core/src/main/java/apoc/SystemLabels.java
- core/src/main/java/apoc/trigger/Trigger.java
- core/src/main/java/apoc/trigger/TriggerHandler.java
- core/src/test/java/apoc/trigger/TriggerDisabledTest.java
- docs/asciidoc/modules/ROOT/partials/triggers.adoc
- full/src/test/java/apoc/trigger/TriggerClusterTest.java
- test-utils/src/main/java/apoc/util/TestContainerUtil.java
- test-utils/src/main/java/apoc/util/TestUtil.java
Fixes #2193
Fixes the replication problem 
- Improved docs
- Added tests in cluster env
> Trigger replication failing

- build.gradle
removed bintray as it will be closed in Feb 2022
> removed bintray as it will be closed in Feb 2022

- build.gradle
- core/build.gradle
- extra-dependencies/couchbase/build.gradle
- extra-dependencies/email/build.gradle
- extra-dependencies/mongodb/build.gradle
- extra-dependencies/nlp/build.gradle
- extra-dependencies/redis/build.gradle
- extra-dependencies/xls/build.gradle
> Additional patched for JDK 17 compatibility

- extra-dependencies/gradle/wrapper/gradle-wrapper.properties
> Extra dependencies gradle 7.2

- build.gradle
- full/src/test/java/apoc/monitor/KernelProcedureTest.java
- test-utils/build.gradle
> Update module options, gradle dependency, KernelProcedureTest

- core/src/main/java/apoc/export/csv/CsvLoaderConfig.java
- docs/asciidoc/modules/ROOT/pages/database-integration/bolt-neo4j.adoc
- docs/asciidoc/modules/ROOT/pages/import/xls.adoc
Fixes #1511
- checked and fixes other `http` links (`ConfigBuilder`)
> Fixes #1511: Additional Libraries for apoc.load.xls need to be https links not http

- core/src/main/java/apoc/util/ApocUrlStreamHandlerFactory.java
- full/src/main/java/apoc/metrics/Metrics.java
- full/src/test/java/apoc/metrics/MetricsTest.java
> fixed Metrics

- core/src/main/java/apoc/util/Util.java
The method was deprecated and is now removed.
> Remove Log.bulk usage

- build.gradle
> bumb neo4j version

- full/src/main/java/apoc/couchbase/CouchbaseConnection.java
- full/src/test/java/apoc/couchbase/CouchbaseIT.java
- full/src/test/java/apoc/couchbase/CouchbaseTestUtils.java
> Fixes #2093: Add check of the number of connections in couchbase test

- core/src/main/java/apoc/CoreApocGlobalComponents.java
- core/src/main/java/apoc/trigger/Trigger.java
- core/src/main/java/apoc/trigger/TriggerHandler.java
- core/src/test/java/apoc/trigger/TriggerDisabledTest.java
- docs/asciidoc/modules/ROOT/partials/triggers.adoc
- full/src/test/java/apoc/trigger/TriggerClusterTest.java
- test-utils/src/main/java/apoc/util/TestContainerUtil.java
- test-utils/src/main/java/apoc/util/TestUtil.java
> Trigger replication failing (#2195)

- core/src/main/java/apoc/schema/Schemas.java
- core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
Fixes schema enterprise test 4.4
- Added `filter(isRelConstraint)` and `filter(isNodeConstraint)` to avoid Exceptions in case of constraints of both types.
- Added `@Before` with drop schema, coherently with SchemasTest
- Changed `List` to `Set` in `testKeptNodeKeyAndUniqueConstraintIfExistsAndDropExistingIsFalse` test, not to consider order
> Fixes schema enterprise test 4.4

- core/src/main/java/apoc/trigger/Trigger.java
- docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc
Fixes #2329
- Added adoc
- Updated `@Description`
> Fixes #2329: Better document the datastructures of triggers and the afterAsync phase

- core/src/main/java/apoc/util/FileUtils.java
> Fixes #2400: The apoc load procedures fails with 'file:///FILENAME' in windows

- core/src/main/java/apoc/index/SchemaIndex.java
> Adapt to product cursors product changes

- core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
Fix schema enterprise test 4.3
> Fix SchemasEnterpriseFeaturesTest 4.3

- docs/asciidoc/modules/ROOT/pages/import/import-csv.adoc
- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.import.csv.adoc
Followup of issue #1471 and PR #2497 - I noticed that the links to the import tool documentation are broken so I fixed them.
> Fix import tool URLs

- core/src/main/java/apoc/periodic/Periodic.java
- core/src/main/java/apoc/periodic/PeriodicUtils.java
- docs/asciidoc/modules/ROOT/pages/graph-updates/periodic-execution.adoc
- full/src/main/java/apoc/periodic/PeriodicExtended.java
Fixes #1617
Cherry-pick from 4.1, commit id: `749f56653316cd808ab1f0a4fc699ffc81520a83`
> Fixes #1617: Logging for apoc.periodic.*

- full/build.gradle
Change driver dependency to compile only
> Change driver dependency to compile only

- core/src/test/java/apoc/trigger/TriggerTest.java
Ignores a couple of tests until we can figure out why they are not ever working
> Makes the build green

- test-utils/src/main/java/apoc/util/TestUtil.java
Includes TeamCity in checks regarding whether we are running in a CI
There are some tests that aren't even working locally 😢, we cannot expect them to work in any CI
Investigate this
> Checks whether we are running in TeamCity as CI

- docs/gradle/wrapper/gradle-wrapper.properties
- extra-dependencies/couchbase/gradle/wrapper/gradle-wrapper.properties
- extra-dependencies/email/gradle/wrapper/gradle-wrapper.properties
- extra-dependencies/gradle/wrapper/gradle-wrapper.properties
- extra-dependencies/mongodb/gradle/wrapper/gradle-wrapper.properties
- extra-dependencies/nlp/gradle/wrapper/gradle-wrapper.properties
- extra-dependencies/redis/gradle/wrapper/gradle-wrapper.properties
- extra-dependencies/xls/gradle/wrapper/gradle-wrapper.properties
- full/build.gradle
- full/src/main/kotlin/apoc/nlp/azure/AzureProcedures.kt
- full/src/main/resources/extended.txt
- gradle/wrapper/gradle-wrapper.properties
- test-utils/build.gradle
This PR fixes some Kotlin procedures not being included in the packaging of apoc.
Kotlin procedures weren't being included in the package due to kotlin version targetting old jvm.
> Fixes Kotlin procedures not being listed in full package. No AUTO cherry-pick

- docs/gradle/wrapper/gradle-wrapper.properties
- extra-dependencies/gradle/wrapper/gradle-wrapper.properties
- extra-dependencies/mongodb/gradle/wrapper/gradle-wrapper.properties
- gradle/wrapper/gradle-wrapper.properties
To align with the other branches after merging #2635, #2634, #2633
> Bumps gradle version. No AUTO cherry-pick

- test-utils/src/main/java/apoc/util/TestContainerUtil.java
> Fixes #2332: improve neo4j testcontainers performance

- build.gradle
Dev branch version of https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/2671
> Update junit version to be consistent

- full/src/main/java/apoc/custom/CypherProceduresHandler.java
- full/src/main/java/apoc/custom/Signatures.java
- full/src/test/java/apoc/custom/CypherProceduresStorageTest.java
- full/src/test/java/apoc/custom/CypherProceduresTest.java
Fixes #1714 - NOTE: Also to auto cherry-pick for 4.2 and 4.3
Cherry pick (commit id `1bef1b4e5d0341e2a5f3e1c3b64006aeac46a900`)
> Fixes #1714: Weirdness around custom functions with node return types (4.3)

- full/src/main/java/apoc/cypher/CypherExtended.java
- full/src/test/java/apoc/cypher/CypherExtendedTest.java
- full/src/test/resources/in_transaction.cypher
> Fixes #2418: "apoc.cypher.runFile" cannot run IN TRANSACTIONS OF successfully

- core/src/main/java/apoc/ApocConfigExtensionFactory.java
- core/src/main/java/apoc/ApocExtensionFactory.java
- core/src/main/java/apoc/PoolExtensionFactory.java
- core/src/main/java/apoc/RegisterComponentFactory.java
- core/src/main/java/apoc/TTLConfigExtensionFactory.java
- core/src/main/resources/META-INF/services/org.neo4j.configuration.SettingsDeclaration
- core/src/main/resources/META-INF/services/org.neo4j.kernel.extension.ExtensionFactory
- full/src/main/resources/META-INF/services/org.neo4j.kernel.extension.ExtensionFactory
(cherry-pick)  - `cb28c5682af0af2bc083ea0e8c28e20d8c0f7c73`
> use `@ServiceProvider` annotation instead of META-INF/services files 

- .github/workflows/auto-cherry-pick.yml
Bumps version of the cherry-pick plugin
https://github.com/conker84/github-action-cherry-pick/
> Bumps version of the cherry-pick action

- .github/workflows/auto-cherry-pick.yml
Cherry-picks #2751
Bumps version of the cherry-pick plugin
https://github.com/conker84/github-action-cherry-pick/
> Updates version of the cherry-pick action

- core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
We fixed some tests and then enabled the file to run in CI.
- fixed tests
- enabled tests to run in CI
> Schema tests

- core/src/main/java/apoc/export/json/JsonFormat.java
- core/src/test/java/apoc/export/json/ExportJsonTest.java
> Fixes #2607: apoc.export.json.data JSON format missing brace (#2698)

- core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
> Fix apoc.schema tests

- test-utils/src/main/java/apoc/util/TestContainerUtil.java
(cherry picked from commit 1c70a9aaaa8b7886db8766f65cb13f91f96260f5)
> Attempt to fix TeamCity build

- core/src/main/java/apoc/export/graphml/XmlGraphMLWriter.java
- core/src/main/java/apoc/export/util/ExportFormat.java
- core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
- docs/asciidoc/modules/ROOT/pages/export/graphml.adoc
Cherry picks #2421 that was reverted in f73f4e9 due to failures in the CI and forgotten to be introduced again.
> Update graphml procedure to support tinkerpop format

- core/src/test/java/apoc/export/json/ImportJsonTest.java
Same as #2844, just checking the CI
> Fix shouldTerminateImportWhenTransactionIsTimedOut 5.0 test

- full/src/main/java/apoc/custom/CypherProcedures.java
- full/src/main/java/apoc/custom/CypherProceduresHandler.java
- full/src/main/java/apoc/custom/Signatures.java
- full/src/test/java/apoc/custom/CypherProceduresStorageTest.java
Fixes #2833
Other changes:
- code clean: removed unnecessary  `throws Exception`
> Fixes #2833: The custom procedures and functions create wrong default null parameters and show duplicated via show procedures

- full/src/main/java/apoc/monitor/Kernel.java
> Fixing a compilation issue

- build.gradle
- core/build.gradle
- full/build.gradle
Cherry pick `7d53862ece23832d6f40f720ffeaa326b3bff130`
Cherry pick `448c27455dd316668b1fbf9a0162517c4df1e0cc`
> Cherry picks dependencies 4.2

- core/build.gradle
- full/build.gradle
- test-utils/build.gradle
Cherry pick: 7d53862ece23832d6f40f720ffeaa326b3bff130
Updated `org.apache.arrow` in `test-utils/build.gradle`
> updated packages passing dependecy-check (#2804) (NO AUTO)

- core/src/main/java/apoc/log/Neo4jLogStream.java
- docs/asciidoc/modules/ROOT/partials/usage/apoc.log.stream.adoc
Trello issue:
https://trello.com/c/n0RPQDPV/548-add-admin-check-for-the-stream-read-logs-functions
> Add admin check for the stream/read-logs functions

- docs/asciidoc/modules/ROOT/pages/import/web-apis.adoc
- docs/asciidoc/modules/ROOT/partials/enableS3Export.adoc
- docs/asciidoc/modules/ROOT/partials/s3-protocol.adoc
S3 docs small fixes
- Created partials
- Updated old packages
> S3 docs small fixes

- docs/asciidoc/modules/ROOT/pages/import/web-apis.adoc
- docs/asciidoc/modules/ROOT/pages/import/xml.adoc
- docs/asciidoc/modules/ROOT/pages/usage/index.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.import.xml.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.load.xml.adoc
- readme.adoc
> Fixes some wrong urls in docs

- full/src/test/java/apoc/load/LoadDirectoryTest.java
Added `assertCreatedOrRunning` to fix flaky LoadDirectoryTest, trello card: https://trello.com/c/hN3xF0Tl/1000-flaky-test-apocloadloaddirectorytesttestfolderlistenernotmatchingpattern-is-flaky-on-several-43-builds
---
Added `System.out.println` too, in order to try to figure out how to solve https://trello.com/c/hxxOGim3/999-flaky-test-apocloadloaddirectorytesttestwithfiltercsv-is-flaky-on-several-43-builds and https://trello.com/c/Tm9BMZNh/998-flaky-test-apocloadloaddirectorytesttestwithfilterallrecursivefalse-is-flaky-on-several-43-builds
> Fix flaky LoadDirectoryTest

- full/src/main/java/apoc/load/LoadHtmlBrowser.java
- full/src/main/java/apoc/load/LoadHtmlConfig.java
- full/src/test/java/apoc/load/LoadHtmlTest.java
> Fixes #2933: Add configurations for apoc.load.html via selenium browser

- core/src/main/java/apoc/path/LabelMatcher.java
- core/src/main/java/apoc/path/LabelMatcherGroup.java
- core/src/main/java/apoc/path/PathExplorer.java
cherry-pick: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3027
> Avoid reusing the AmbientCursor in node.getLabels() 

- core/src/test/java/apoc/meta/MetaTest.java
- core/src/test/java/apoc/nodes/GroupingTest.java
- docs/asciidoc/modules/ROOT/pages/overview/apoc.meta/apoc.meta.data.of.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.meta/apoc.meta.graph.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.meta/apoc.meta.graph.of.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.meta/apoc.meta.schema.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.meta/apoc.meta.subGraph.adoc
- docs/asciidoc/modules/ROOT/pages/virtual/graph-grouping.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.meta.nodeTypeProperties.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.meta.schema.adoc
- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.meta.data.adoc
- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.meta.data.of.adoc
- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.meta.graph.adoc
- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.meta.graph.of.adoc
- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.meta.nodeTypeProperties.adoc
- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.meta.relTypeProperties.adoc
- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.meta.schema.adoc
- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.meta.subGraph.adoc
- docs/asciidoc/modules/ROOT/partials/usage/config/sample.config.adoc
Added adoc test meta configs
- `maxRels` test config
- `excludes` test and adoc config
- `includeLabels`/`excludeLabels`/`includeRels`/`excludeRels` adocs
- changed `assertEquals(true,` with `assertTrue`
> Added var. adoc and test for meta configs

- build.gradle
- docs/build.gradle
- extra-dependencies/build.gradle
- readme.adoc
Bumps neo4j, java driver and apoc version for final 3.5 release
> NO AUTO Bumps version of neo4j, driver and apoc for release

- core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java
- core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
- core/src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java
- core/src/main/java/apoc/export/cypher/formatter/CreateCypherFormatter.java
- core/src/main/java/apoc/export/cypher/formatter/CypherFormatter.java
- core/src/main/java/apoc/export/cypher/formatter/CypherFormatterUtils.java
- core/src/main/java/apoc/export/cypher/formatter/UpdateAllCypherFormatter.java
- core/src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java
- core/src/main/java/apoc/export/util/ExportConfig.java
- core/src/test/java/apoc/export/cypher/ExportCypherMultiRelTest.java
- core/src/test/java/apoc/export/cypher/ExportCypherTestUtils.java
- docs/asciidoc/modules/ROOT/pages/export/cypher.adoc
Cherry pick 5.0 https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/8f8c2f4357fc5e575139fc5c4ba2a67cdf7384b2
> Export cypher overwrite relationships in case of merge with multi-rels with the same nodes and type (#3035) 

- core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java
- core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
- core/src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java
- core/src/main/java/apoc/export/cypher/formatter/CreateCypherFormatter.java
- core/src/main/java/apoc/export/cypher/formatter/CypherFormatter.java
- core/src/main/java/apoc/export/cypher/formatter/CypherFormatterUtils.java
- core/src/main/java/apoc/export/cypher/formatter/UpdateAllCypherFormatter.java
- core/src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java
- core/src/main/java/apoc/export/util/ExportConfig.java
- core/src/test/java/apoc/export/cypher/ExportCypherMultiRelTest.java
- core/src/test/java/apoc/export/cypher/ExportCypherTestUtils.java
- docs/asciidoc/modules/ROOT/pages/export/cypher.adoc
Cherry pick 4.3 https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/8f8c2f4357fc5e575139fc5c4ba2a67cdf7384b2
> Export cypher overwrite relationships in case of merge with multi-rels with the same nodes and type (#3035)

- core/build.gradle
- full/build.gradle
Changed `commons-configuration2` version
> Upgrade commons-configuration2 to 2.8.0

- .github/workflows/CI.yaml
- core/build.gradle
> NO AUTO Forces dependency to especific version to avoid binary incompatibilities

- core/build.gradle
- full/build.gradle
Cherry pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/ccc6305402d3ae91b77edb183963e3da8d2e2596
Removed duplicated `commons-lang3` import
> Upgrade commons-configuration2 to 2.8.0 (#3063)

- full/src/test/java/apoc/load/LoadDirectoryTest.java
Fix flaky LoadDirectoryTest 5.0
> Fix flaky LoadDirectoryTest 5.0

- core/src/main/java/apoc/log/Neo4jLogStream.java
cherry-pick: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3080
> vuln-fix: Partial Path Traversal Vulnerability (#3080)

- core/src/test/java/apoc/ApocSplitTest.java
- full/src/test/java/apoc/ApocSplitTest.java
Ignores newly created tests that require docker.
The docker container startups are really flaky at the moment.
> NO AUTO Ignores some container tests until their startup is fixed

- build.gradle
- docs/asciidoc/antora.yml
- extra-dependencies/build.gradle
- readme.adoc
> Bump versions for 4.4.0.8 release

- core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
- full/src/test/java/apoc/model/ModelTest.java
`ModelTest` needs to set a more modern version of TLS to avoid:
```
javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
```
`SchemasEnterpriseFeaturesTest` had a wrong assertion.
> NO AUTO Fixes SchemasEnterpriseFeaturesTest wrong assertion and ModelTest protocol

- core/src/main/java/apoc/refactor/GraphRefactoring.java
- core/src/main/java/apoc/refactor/rename/Rename.java
- core/src/main/java/apoc/schema/Schemas.java
- core/src/main/java/apoc/util/Util.java
- core/src/test/java/apoc/refactor/GraphRefactoringTest.java
- core/src/test/java/apoc/refactor/rename/RenameTest.java
- core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
- core/src/test/java/apoc/schema/SchemasTest.java
- core/src/test/java/apoc/util/UtilTest.java
Cherry Picked: https://github.com/neo4j/apoc/pull/2
> Sanitize back-ticks in strings when there is a possibility of Cypher injection

- core/src/main/java/apoc/util/Util.java
- full/src/main/java/apoc/cypher/CypherExtended.java
- full/src/test/java/apoc/cypher/CypherExtendedTest.java
- full/src/test/resources/constraints.cypher
- full/src/test/resources/schema.cypher
> Fixes #2395: The apoc.cypher.runSchemaFile doesn't support full text indexes

- full/src/main/java/apoc/custom/CypherProcedures.java
- full/src/test/java/apoc/custom/CypherProceduresTest.java
Cherry pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/29051f331c0aa1eb760d15382408ade249ecbb27
> Fixes #2605: The apoc.custom.declareProcedure throws exception "Query results do not match requested output" with some queries (#3146)

- core/src/main/java/apoc/cypher/CypherInitializer.java
- core/src/main/java/apoc/meta/Meta.java
- core/src/test/java/apoc/meta/MetaTest.java
Fixes #2934
Fixed the bug
- Added a test case
> fixes #2934: `apoc.meta.relTypeProperties` doest not return relationship information

- core/src/main/java/apoc/cypher/CypherInitializer.java
- core/src/main/java/apoc/meta/Meta.java
- core/src/test/java/apoc/meta/MetaTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/985463e5812f8e35fe1991c1d96f72b433593daa
> fixes #2934: `apoc.meta.relTypeProperties` doest not return relationship information (#2935)

- extra-dependencies/nlp/build.gradle
To be consistent with the version changed [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3031/files#diff-deadf6efe000da8ebc139809f628f296da1b5a6a04f4d31017862f44912d5fffR130)
> Upgrade jackson-module-kotlin in extra-dependency

- core/src/main/java/apoc/load/Xml.java
- core/src/test/java/apoc/load/XmlTest.java
(cherry picked from commit 65774511bea87675767605bd86e19336889c0fbd)
The cherry-pick is in another repo.
> [hcaaOlXR] Make XML procedures resistant to XXE (#202)

- core/src/main/java/apoc/load/Xml.java
- core/src/test/java/apoc/load/XmlTest.java
- core/src/test/resources/xml/billion_laughs.xml
(cherry picked from commit 6c5f9234ac264e4a7ac7d0ef1adca020be9bfdb0) which is in github.com/neo4j/apoc
> [hcaaOlXR] Protect from Billion Laughs

- core/src/main/java/apoc/periodic/Periodic.java
- core/src/main/java/apoc/refactor/rename/Rename.java
Cherry pick https://github.com/neo4j/apoc/commit/26b30f805d0e1d8c48a22f6a7df549f1402b59ce
> Fixes neo4j/apoc#18: Default parallel concurrency of 50 is too high

- core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
- core/src/main/java/apoc/export/cypher/formatter/CreateCypherFormatter.java
- core/src/main/java/apoc/export/cypher/formatter/CypherFormatterUtils.java
- core/src/test/java/apoc/export/cypher/ExportCypherTest.java
Cherry pick https://github.com/neo4j/apoc/commit/a0661556d7cfc86378733e2d93dbd81a766b5f57
> [tYbuDF2B] The apoc.export.cypher.* procedures don't create relationships with start/end node without properties

- core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java
- core/src/main/java/apoc/export/cypher/formatter/CreateCypherFormatter.java
- core/src/main/java/apoc/export/cypher/formatter/CypherFormatterUtils.java
- core/src/test/java/apoc/export/cypher/ExportCypherTest.java
Cherry pick https://github.com/neo4j/apoc/commit/a0661556d7cfc86378733e2d93dbd81a766b5f57
> [tYbuDF2B] The apoc.export.cypher.* procedures don't create relationships with start/end node without properties (neo4j/apoc#181)

- full/src/test/java/apoc/load/LoadHtmlTest.java
- full/src/test/java/apoc/load/LoadHtmlTestParameterized.java
- full/src/test/java/apoc/load/LoadHtmlTestParameterizedTest.java
cherry-picks: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3221
> [4zKlPDoa] Remove FIREFOX LoadHtmlTests

- .github/workflows/CI.yaml
(cherry picked from commit fa0104ad4b0b141f89ce40b81145d41d593dffca)
> [UHxIZ8JO] Grant CodeQL permissions (#212)

- core/build.gradle
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/pages/import/includes/jsonpath.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.convert.fromJsonList.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.convert.fromJsonMap.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.convert.getJsonProperty.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.convert.getJsonPropertyMap.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.json.path.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.load.jsonArray.adoc
- full/build.gradle
Cherry pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/bf1b662a0663c851708ff3981d47abe92876f689
> (NO AUTO) Fix docs cve 2021-27568 (#2953)

- docs/asciidoc/modules/ROOT/pages/config/index.adoc
- docs/asciidoc/modules/ROOT/pages/installation/index.adoc
- docs/asciidoc/modules/ROOT/pages/introduction/index.adoc
- readme.adoc
Update the readme and docs to reflect split
> 5.x update documentation

- core/src/main/java/apoc/refactor/rename/Rename.java
- core/src/test/java/apoc/refactor/rename/RenameTest.java
Cherry-pick https://github.com/neo4j/apoc/commit/d54b804af2e259b50af51b8e33b7ec6475b3250a
> [pDw6xmRG] Fixes neo4j/apoc#26: apoc.refactor.rename.label delets label if oldLabel is equal to newLabel (#209)

- core/build.gradle
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/dc01551ea8f5bbb7fc803d7ab52814722da7cd89
> Update commons-text (#3235)

- docs/asciidoc/modules/ROOT/pages/export/csv.adoc
Cherry-picked: https://github.com/neo4j/docs-apoc/pull/49
Update CSV docs to contain more info about config
> Fix export to csv docs

- core/src/main/java/apoc/periodic/Periodic.java
- core/src/main/java/apoc/periodic/PeriodicUtils.java
- core/src/main/java/apoc/util/Util.java
- core/src/test/java/apoc/periodic/PeriodicTest.java
Cherry-pick https://github.com/neo4j/apoc/commit/3700669999172b7383bc81220b0aa6269be9593a
Cherry-pick https://github.com/neo4j/apoc/commit/e5264e06a1423ebf9f9f8eef88e020e84fa83d28
> Fixes neo4j/apoc#126: apoc.periodic.submit fails with schema operations (neo4j/apoc#208)

- build.gradle
- docs/asciidoc/antora.yml
- docs/build.gradle
- extra-dependencies/build.gradle
Bumps neo4j and apoc version ahead of release
> [NOID] Bumps 4.4 version for release

- build.gradle
- docs/asciidoc/antora.yml
- docs/build.gradle
- extra-dependencies/build.gradle
Bumps neo4j and apoc version ahead of release
> [NOID] Bumps 4.3 version for release

- readme.adoc
Description
Added Hypertext Transfer Protocol Secure
-
> Update readme.doc file with HTTPS

- readme.adoc
Cherry-picked: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3253
> [NOID] Cherry Pick https update

- docs/asciidoc/modules/ROOT/pages/index.adoc
- docs/asciidoc/modules/ROOT/pages/overview/index.adoc
Give a heads up that the new docs are moved so people coming to these from Google will get directed to the right place.
> Add notes to send user to Core docs in 4.x series

- docs/asciidoc/modules/ROOT/pages/index.adoc
- docs/asciidoc/modules/ROOT/pages/overview/index.adoc
- readme.adoc
> 4.3 add note about apoc split

- docs/asciidoc/modules/ROOT/pages/index.adoc
- docs/asciidoc/modules/ROOT/pages/overview/index.adoc
- readme.adoc
Cherry Picked: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3264
> 4.2 add note about apoc split

- docs/asciidoc/modules/ROOT/pages/index.adoc
- docs/asciidoc/modules/ROOT/pages/overview/index.adoc
- readme.adoc
Cherry Picked: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3264
> 4.0 add note about apoc split

- docs/asciidoc/modules/ROOT/pages/config/index.adoc
- docs/asciidoc/modules/ROOT/pages/deprecations-and-additions/index.adoc
- docs/asciidoc/modules/ROOT/pages/index.adoc
- docs/asciidoc/modules/ROOT/pages/installation/index.adoc
- docs/asciidoc/modules/ROOT/pages/introduction/index.adoc
- docs/asciidoc/modules/ROOT/pages/overview/index.adoc
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- readme.adoc
Cherry picked: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3263
> 5.0 update docs

- readme.adoc
Cherry picked: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3263/files
> Bring over readme updates

- docs/antora/package-lock.json
- docs/antora/package.json
Update Antora dependencies suggested from dependabot.
* https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3215
* https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3214
* https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3257
> Update Antora Dependencies

- core/build.gradle
- core/src/main/java/apoc/export/csv/CsvEntityLoader.java
- full/build.gradle
- full/src/main/java/apoc/load/LoadCsv.java
- full/src/test/java/apoc/load/LoadCsvTest.java
- full/src/test/resources/test-escape.csv
- full/src/test/resources/test-escaped-delimiters.csv
cherry-picks: https://github.com/neo4j/apoc/pull/226
> [NOID] Fixes CVE-2022-42889 in transitive dependencies

- core/build.gradle
- core/src/main/java/apoc/export/csv/CsvEntityLoader.java
- full/build.gradle
- full/src/main/java/apoc/load/LoadCsv.java
- full/src/test/java/apoc/load/LoadCsvTest.java
- full/src/test/resources/test-escape.csv
- full/src/test/resources/test-escaped-delimiters.csv
cherry-picks: https://github.com/neo4j/apoc/pull/226
> [NOID] Fixes CVE-2022-42889 in transitive dependencies 

- extended/src/test/java/apoc/couchbase/CouchbaseTestUtils.java
- extended/src/test/java/apoc/load/LoadHtmlTest.java
- extended/src/test/java/apoc/load/LoadHtmlTestParameterized.java
- extended/src/test/java/apoc/ttl/TTLMultiDbTest.java
- extended/src/test/java/apoc/util/s3/S3Container.java
Try to fix various flaky tests in 5.1
- Added a retry mechanism via `withStartupAttempts(3)` hoping it can solve the problem similar to https://github.com/neo4j/apoc/pull/177
- Added check if browser is compatible/existing in `LoadHtmlTest`s
- Added availability database check in `TTLMultiDbTest.java`
> Try to fix various tests in 5.1

- full/src/test/java/apoc/couchbase/CouchbaseTestUtils.java
- full/src/test/java/apoc/load/LoadHtmlTest.java
- full/src/test/java/apoc/load/LoadHtmlTestParameterized.java
- full/src/test/java/apoc/ttl/TTLMultiDbTest.java
- full/src/test/java/apoc/util/s3/S3Container.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/c8565c4ab20b2c845f3c4869885aaf1cad2e9b3a
> Fix various flaky and local tests in 4.x (#3286)

- docs/asciidoc/functions.adoc
- docs/asciidoc/jmh.adoc
- docs/asciidoc/modules/ROOT/pages/config/index.adoc
- docs/asciidoc/modules/ROOT/pages/cypher-execution/index.adoc
- docs/asciidoc/modules/ROOT/pages/database-integration/bolt-neo4j.adoc
- docs/asciidoc/modules/ROOT/pages/database-integration/couchbase.adoc
- docs/asciidoc/modules/ROOT/pages/database-integration/index.adoc
- docs/asciidoc/modules/ROOT/pages/database-integration/redis.adoc
- docs/asciidoc/modules/ROOT/pages/database-introspection/index.adoc
- docs/asciidoc/modules/ROOT/pages/export/index.adoc
- docs/asciidoc/modules/ROOT/pages/general-considerations/index.adoc
- docs/asciidoc/modules/ROOT/pages/graph-updates/index.adoc
- docs/asciidoc/modules/ROOT/pages/import/index.adoc
- docs/asciidoc/modules/ROOT/pages/import/web-apis.adoc
- docs/asciidoc/modules/ROOT/pages/index.adoc
- docs/asciidoc/modules/ROOT/pages/introduction/index.adoc
- docs/asciidoc/modules/ROOT/pages/misc/index.adoc
- docs/asciidoc/modules/ROOT/pages/operational/index.adoc
- docs/asciidoc/modules/ROOT/pages/overview/index.adoc
- docs/asciidoc/modules/ROOT/pages/transaction/index.adoc
- docs/asciidoc/modules/ROOT/pages/virtual-resource/index.adoc
- docs/asciidoc/modules/ROOT/partials/docker.adoc
- docs/asciidoc/modules/ROOT/partials/email-dependencies.adoc
- docs/asciidoc/modules/ROOT/partials/mongodb-dependencies.adoc
- docs/asciidoc/modules/ROOT/partials/nlp-dependencies.adoc
Rename APOC library to APOC Extended library.
> Rename APOC library to APOC Extended library 

- full/build.gradle
- full/src/main/java/apoc/load/LoadHtml.java
Cherry-pick of https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3305
> [7kTG3Jb3] Upgraded jsoup to v.1.15.3 to mitigate CVE-2022-36033

- core/src/main/java/apoc/export/cypher/ExportCypher.java
- core/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java
- core/src/test/java/apoc/export/cypher/ExportCypherTest.java
Partial cherry-pick of https://github.com/neo4j/apoc/pull/229
> [4Bmcyc2U] Fix ignored ExportCypherTests

- core/src/test/java/apoc/spatial/GeocodeTest.java
Cherry-pick https://github.com/neo4j/apoc/commit/73e7dae61303fba994b0675c43fbc9516ac6a972
> [4Bmcyc2U] Fix ignored testGeocodeGoogle (neo4j/apoc#239)

- core/src/test/java/apoc/refactor/rename/RenameTest.java
Cherry pick https://github.com/neo4j/apoc/commit/10e2fbcdd93e88c51fd16667b7c13bc9f7e054de
> [4Bmcyc2U] Try fixing flaky testDeadlockException for 4.3 (neo4j/apoc#238)

- core/src/test/java/apoc/meta/MetaEnterpriseFeaturesTest.java
Cherry-pick of test fix here https://github.com/neo4j/apoc/pull/252
> [4Bmcyc2U] Un-ignore and clean up working test.

- core/src/test/java/apoc/refactor/rename/RenameTest.java
Cherry pick https://github.com/neo4j/apoc/commit/10e2fbcdd93e88c51fd16667b7c13bc9f7e054de
> [4Bmcyc2U] Try fixing flaky testDeadlockException for 4.4 (neo4j/apoc#238)

- core/src/main/java/apoc/ApocConfig.java
- core/src/main/java/apoc/util/FileUtils.java
- core/src/main/java/apoc/util/Util.java
- core/src/test/java/apoc/load/XmlTest.java
- core/src/test/java/apoc/util/UtilIT.java
Also fix Ignored UtilIT
Cherry-pick of https://github.com/neo4j/apoc/pull/240
> [eOxJMLMv] Checks redirects for blocked IPs instead of just final location.

- full/src/main/java/apoc/load/LoadHtmlBrowser.java
- full/src/main/java/apoc/load/LoadHtmlConfig.java
- full/src/test/java/apoc/load/LoadHtmlTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/f654330c3bc50134e6ae8f319deba90dc74cdb37
> Fixes #2933: Add configurations for apoc.load.html via selenium browser (#2990)

- build.gradle
- docs/asciidoc/antora.yml
- docs/build.gradle
- extra-dependencies/build.gradle
- test-utils/src/main/java/apoc/util/TestContainerUtil.java
> [usYvttjz] Release 4.3.0.12

- build.gradle
- core/src/test/java/apoc/coll/CollTest.java
- docs/asciidoc/antora.yml
- docs/build.gradle
- extra-dependencies/build.gradle
- test-utils/src/main/java/apoc/util/TestContainerUtil.java
> [Xv3ZrpTp] Release 4.4.0.12

- docs/asciidoc/modules/ROOT/pages/database-integration/elasticsearch.adoc
- extended/src/test/java/apoc/es/ElasticSearchTest.java
- Improved docs with authentication url
- Added tests with authentication url
- Added test with `apocConfig()`
> [rQCxvZ5O] Improved docs and test with user-pass auth

- .github/workflows/traceability.yaml
- readme.adoc
cherry-picks: https://github.com/neo4j/apoc/pull/266
> [i19tvtq1] Add Trello Traceability GHA to CI

- core/src/main/java/apoc/result/IndexConstraintNodeInfo.java
- core/src/main/java/apoc/result/IndexConstraintRelationshipInfo.java
- core/src/main/java/apoc/schema/Schemas.java
- core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
- core/src/test/java/apoc/schema/SchemasTest.java
Cherry pick https://github.com/neo4j/apoc/commit/1751fe10f8b5ce99f1ba5410f61ffb41ef0f6936
> [Zl3h9sM8] apoc.schema.relationships return wrong output for relationship indexes

- core/src/main/java/apoc/trigger/Trigger.java
- core/src/main/java/apoc/trigger/TriggerHandlerNewProcedures.java
- core/src/main/java/apoc/trigger/TriggerInfo.java
- core/src/main/java/apoc/trigger/TriggerNewProcedures.java
- core/src/test/java/apoc/trigger/TriggerClusterRoutingTest.java
- core/src/test/java/apoc/trigger/TriggerEnterpriseFeaturesTest.java
- core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
- docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.add.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.pause.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.remove.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.removeAll.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.resume.adoc
Changes from https://github.com/neo4j/apoc/pull/250
- Added tests 
- Simplified implementation by adding `TriggerInfo.java`
Fixed adoc bug by adding `[]` at the end of the includes
> [gRNAet7B] Changes from neo4j/apoc#250

- docs/asciidoc/modules/ROOT/nav.adoc
- docs/asciidoc/modules/ROOT/pages/installation/index.adoc
- docs/asciidoc/modules/ROOT/partials/restricted.adoc
- readme.adoc
Cherry-pick of  https://github.com/neo4j/apoc/pull/281  and  https://github.com/neo4j/docs-apoc/pull/86
> [UDzPn3dS] Update docs and README for loading and unrestricting

- full/src/test/java/apoc/custom/CypherProceduresTest.java
> [NOID] Fix testWrongMode

- build.gradle
- docs/asciidoc/antora.yml
- docs/build.gradle
- extra-dependencies/build.gradle
- readme.adoc
> [NOID] Bump version to 5.5.0

- extended/build.gradle
- extended/src/main/java/apoc/metrics/Metrics.java
- extended/src/test/java/apoc/metrics/MetricsTest.java
- extra-dependencies/nlp/build.gradle
> [NOID] Cherry picks from 4.4 to 5.4

- extended/src/main/java/apoc/custom/CypherProcedures.java
- extended/src/main/java/apoc/custom/CypherProceduresHandler.java
- extended/src/test/java/apoc/custom/CypherProceduresTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/3dfd8ae5463cff37dcd35f2d55a94496d79f29b1
> [NOID] fixes #3349: Can not create custom procedure with void return type using apoc.custom.declareProcedure (#3356)

- core/src/main/java/apoc/trigger/TriggerHandlerNewProcedures.java
- core/src/main/java/apoc/trigger/TriggerNewProcedures.java
- core/src/test/java/apoc/trigger/TriggerClusterRoutingTest.java
- core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
- test-utils/src/main/java/apoc/util/TestContainerUtil.java
Cherry pick https://github.com/neo4j/apoc/commit/02d8e6ba1013ed0e85e4e90fe7c12f7c383ae052
> [gcL5e77c] Fix edge cases in trigger methods (neo4j/apoc#288)

- core/src/main/java/apoc/algo/Cover.java
cherry-pick: https://github.com/neo4j/apoc/pull/313
> [HQABUD5U] Improve coverNodes speed

- docs/asciidoc/modules/ROOT/pages/overview/apoc.meta/apoc.meta.data.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.meta/apoc.meta.data.of.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.meta/apoc.meta.graph.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.meta/apoc.meta.graph.of.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.meta/apoc.meta.schema.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.meta/apoc.meta.subGraph.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.meta.nodes.count.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.meta.samplingDesc.adoc
- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.meta.data.adoc
- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.meta.graph.adoc
- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.meta.nodeTypeProperties.adoc
- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.meta.nodes.count.adoc
- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.meta.relTypeProperties.adoc
cherry-pick: https://github.com/neo4j/docs-apoc/pull/104
> [04b6IYYB] Fix sampling documentation for apoc.meta.* procs

- core/src/test/java/apoc/util/s3/S3TestUtil.java
Cherry-pick https://github.com/neo4j/apoc/commit/f08caee9130a50005923469de4042cf21ec6c04c
> [0eSjZq6Q] Fix S3 failing flaky tests (neo4j/apoc#294)

- core/src/test/java/apoc/spatial/GeocodeTest.java
Cherry pick https://github.com/neo4j/apoc/commit/ba41be8f8555d71de5d3b7afb7d3a45c55551cb0
> [wvzcpHQH] Add SSFR check for apoc.spatial procedures (neo4j/apoc#305)

- .github/workflows/CI.yaml
- .gitmodules
- docs/asciidoc/modules/ROOT/pages/installation/index.adoc
- readme.adoc
Bump version:
- Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3397/commits/9601b735f29814de91c3c323153d8b3a43bbc670
Changed docs version:
- Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/b859284edd85dbc0daeefbedb39226df5be49695
> [NOID] Release 5.5.0

- core/src/main/java/apoc/spatial/Geocode.java
Cherry pick https://github.com/neo4j/apoc/commit/80b7db3beec5c689d0035d0baf7990dc6e1d8340
> [NOID] Fix wrong throttle config in Geocode.SupplierWithKey (#327)

- extended/build.gradle
- extended/src/main/java/apoc/load/LoadHtml.java
- extended/src/test/java/apoc/load/LoadHtmlTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/4f7668f28c66c538995f4e1b634caed1d1c0a1e4
> [NOID] Upgraded jsoup to v.1.15.3 to mitigate CVE-2022-36033 (#3305)

- docs/asciidoc/modules/ROOT/nav.adoc
- docs/asciidoc/modules/ROOT/pages/installation/index.adoc
- docs/asciidoc/modules/ROOT/partials/restricted.adoc
- readme.adoc
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/29cd0dce328b7ea79cecc823502cbe9cfa5b8811
> [iREBdGuF] Stop recommending loading/unrestricting all procedures (#3413)

- extended/build.gradle
- extended/src/test/java/apoc/load/LoadLdapTest.java
- extended/src/test/resources/ldap/example.ldif
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/50fae233710f095ebec6bd0e9b6cd33ed0bcd6c4
> [aNcPaEFK] Fix LoadLdapTest.testLoadLDAP (#3459)

- extended/src/test/java/apoc/export/ExportExtendedSecurityTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3457
> [GE2QhC9X] Fix path traversal vulnerability (CVE-2022-23532) (#3457)

- extended/build.gradle
- init.gradle
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/c51eb86aa0ca7fe259150f47416ee47adc92ca02
> [NOID] Ignore git submodule (#3418)

- core/src/main/java/apoc/trigger/TriggerNewProcedures.java
Cherry-pick https://github.com/neo4j/apoc/commit/0f0f3ed27de87d2ebadb040ba4a98ec2d63c95f9
> [mcub3FQf] Improve triggers error messages (neo4j/apoc#302)

- core/src/main/java/apoc/trigger/Trigger.java
- core/src/main/java/apoc/trigger/TriggerNewProcedures.java
- core/src/test/java/apoc/trigger/TriggerClusterRoutingTest.java
- core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
Cherry-pick https://github.com/neo4j/apoc/commit/9b808a787d9267834e5ec081bcf0b7c9267b4d85
> [Ci2sJ23z] apoc.trigger.show doesn't work in a system follower

- core/src/main/java/apoc/trigger/TriggerHandlerNewProcedures.java
- core/src/main/java/apoc/trigger/TriggerNewProcedures.java
Cherry-pick https://github.com/neo4j/apoc/commit/f8351cbf0763aa54a03bee762706a43227d40540
> [ROQ0fkdz] Reduce the number of transactions we use in triggers (neo4j/apoc#303)

- core/src/main/java/apoc/hashing/Fingerprinting.java
- core/src/test/java/apoc/hashing/FingerprintingTest.java
Cherry-pick https://github.com/neo4j/apoc/commit/6fc54d16e6e90bd712ec5dc02832bd03e78c7763
> [OnEGwZ5A] apoc.hashing.fingerprint can't deal with type byte[]

- core/src/main/java/apoc/create/Create.java
- core/src/test/java/apoc/create/CreateTest.java
Cherry-pick https://github.com/neo4j/apoc/commit/fff90a4d86631cf32a2530bb7911c90dd1353cdd
> [iTwFvqQ2] apoc.create.clonePathsToVirtual() returns more relationships than it should (neo4j/apoc#328)

- core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
- docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc
Cherry-pick https://github.com/neo4j/docs-apoc/commit/05ae1b6a6111eccb0ae2cb727915787f6936b77e
Cherry-pick https://github.com/neo4j/apoc/commit/514665bbb824f51e4493669a9ad514a748469651
> [yHvDctRN] Add tests and docs about $transactionId (neo4j/apoc#289)

- build.gradle
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/pages/installation/index.adoc
- docs/build.gradle
- extra-dependencies/build.gradle
- readme.adoc
> Bumps 5.7.0 version

- extended/src/main/java/apoc/es/ElasticSearch.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/14720fd34c332552811c668d102f57df1399f0cb
> Fix loadJsonStream compiler error in dev (#3494)

- .github/workflows/CI.yaml
- .gitmodules
> Init release 5.6.0

- .github/workflows/CI.yaml
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/fd84f62665757c00d608450a425f659b36e471dc
> [NOID] Updates JDK to use Temurin (#3487)

- core/src/main/java/apoc/trigger/TriggerHandler.java
- core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
Cherry-pick https://github.com/neo4j/apoc/commit/7c1023de0380c7e29f9a2961040f58a6bf28b652
> [H5vz3qhy] Prevent cascade trigger transactions (neo4j/apoc#346)

- docs/asciidoc/modules/ROOT/partials/usage/apoc.refactor.rename.label.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.refactor.rename.type.adoc
Cherry Picked: https://github.com/neo4j/docs-apoc/pull/118
> [EV6LG1ZP] Fix mixup of apoc.refactor.rename.label and apoc.refactor.rename.type

- docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.drop.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.dropAll.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.install.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.show.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.start.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.trigger/apoc.trigger.stop.adoc
- docs/asciidoc/modules/ROOT/partials/triggers/triggersAdmonitions.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.trigger.drop.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.trigger.dropAll.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.trigger.install.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.trigger.pause.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.trigger.removeAll.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.trigger.resume.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.trigger.show.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.trigger.start.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.trigger.stop.adoc
Cherry-pick https://github.com/neo4j/docs-apoc/commit/f0b962ef5ed0dfa239110c48377a11561ec29c7c
> [MKwC5lu0] Add more trigger usage examples (neo4j/docs-apoc#92)

- docs/asciidoc/modules/ROOT/partials/usage/allowed.configs.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.config.list.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.config.map.adoc
- full/src/main/java/apoc/config/Config.java
- full/src/test/java/apoc/config/ConfigTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/0124b5ff8bfbf7eff376bc8d8806a0c0fc387d6f
> [PL7XdSMV] apoc.config.list and apoc.config.map leak evars (#3400)

- .github/workflows/CI.yaml
- .gitmodules
- readme.adoc
Changed references to 5.7
Cherry-pick of https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/9601b735f29814de91c3c323153d8b3a43bbc670
> Release 5.7.0

- full/src/test/java/apoc/config/ConfigTest.java
- full/src/test/java/apoc/uuid/UUIDClusterRoutingTest.java
- test-startup/src/test/java/StartupTest.java
Because the CI is very flaky and we cannot merge anything at the moment
> [NOID] Ignores flaky tests until they are fixed

- core/src/main/java/apoc/export/cypher/ExportCypher.java
- core/src/test/java/apoc/export/cypher/ExportCypherTest.java
Cherry-pick https://github.com/neo4j/apoc/commit/d60a5a4029e8025f30ea00bfbb326ceab54a7506
> [ivaiMqVb] CALL apoc.export.cypher.schema(null, { stream: true }) returns nothing (neo4j/apoc#374)

- core/src/main/java/apoc/periodic/Periodic.java
- core/src/main/java/apoc/periodic/PeriodicUtils.java
- core/src/test/java/apoc/periodic/PeriodicTest.java
Cherry-pick https://github.com/neo4j/apoc/commit/c226380dc5d26787e7ca6d0a196cbbfecfa23728
> [gULAAkri] apoc.periodic.repeat doesn't always work (neo4j/apoc#388)

- core/src/main/java/apoc/hashing/Fingerprinting.java
Cherry-pick https://github.com/neo4j/apoc/commit/a78c07bc386faa0fee59c4aec62c262fcb2fb795
> [VyGD3IoX] apoc.hashing.fingerprint lossy conversion (neo4j/apoc#378)

- core/src/test/java/apoc/export/json/ExportJsonS3Test.java
- core/src/test/java/apoc/util/s3/S3TestUtil.java
Cherry-pick https://github.com/neo4j/apoc/commit/e3023e0f5454bc6fc91321f07497c00badced2f6
> [rePYjknU] Fix flaky testExportQueryNodesJsonCount (neo4j/apoc#406)

- build.gradle
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/pages/installation/index.adoc
- docs/build.gradle
- extra-dependencies/build.gradle
- readme.adoc
> Bump version 5.9.0 (#3456)

- core/src/main/java/org/neo4j/cypher/export/DatabaseSubGraph.java
- core/src/test/java/apoc/meta/MetaTest.java
When a label is not found the count will be `0`,
so that a wrong node will not be created [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/4.4/core/src/main/java/apoc/meta/Meta.java#L508) .
The bug is present only in 4.x
> [OfagjOnq] apoc.meta.subgraph returns wrong type when using includeLabels

- .github/workflows/CI.yaml
- .gitmodules
- docs/asciidoc/modules/ROOT/pages/installation/index.adoc
- readme.adoc
> [NOID] Release 5.8.0 (#3455)

- docs/asciidoc/modules/ROOT/nav.adoc
- docs/asciidoc/modules/ROOT/pages/ml/index.adoc
- docs/asciidoc/modules/ROOT/pages/ml/openai.adoc
- extended/src/main/java/apoc/ml/OpenAI.java
- extended/src/main/resources/extended.txt
- extended/src/test/java/apoc/ml/OpenAIIT.java
- extended/src/test/java/apoc/ml/OpenAITest.java
- extended/src/test/resources/chat/completions
- extended/src/test/resources/completions
- extended/src/test/resources/embeddings
- Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/edb4e6de5a3d585fb3431b8d1a3da403c30d1d4c
- Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/2e8e125c61e6a90859d58452f49ba68ba7c04d4f
- Updated `extended.txt`
> Add OpenAI (LLM) procedures (#3575)

- extended/src/main/resources/extended.txt
See https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/5057278608/jobs/9075835558?pr=3582#step:5:3736
> Updated extended.txt to fix checkCoreWithExtraDependenciesJars failure after Open AI procedures

- core/src/main/java/apoc/refactor/GraphRefactoring.java
- core/src/test/java/apoc/refactor/GraphRefactoringTest.java
Cherry-pick https://github.com/neo4j/apoc/commit/bf9988fec859895a46357f6a0a96c62bac764d1b
> [bZQoGhFu] apoc.refactor.mergeNodes is not working with uniqueness index (neo4j/apoc#361)

- core/src/main/java/apoc/ApocExtensionFactory.java
Cherry pick https://github.com/neo4j/apoc/commit/9ecb4c55d5cb605c5e597312e2d81b3e69042a5a
> [dLZ2xYwQ] Multiple CypherInitializer's per single DatabaseAvailabilityGuard (neo4j/apoc#413)

- docs/asciidoc/modules/ROOT/nav.adoc
- docs/asciidoc/modules/ROOT/pages/ml/index.adoc
- docs/asciidoc/modules/ROOT/pages/ml/vertexai.adoc
- extended/src/main/java/apoc/ml/VertexAI.java
- extended/src/main/resources/extended.txt
- extended/src/test/java/apoc/ml/VertexAIIT.java
- Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/17bace9c1437fbf14b48dda2cd02bbdc1f055adf
- Updated `extended.txt`
> Adding Vertex-AI Integration (#3601)

- extended/src/main/resources/extended.txt
> Updated exteded.txt with vertexai procs

- core/src/main/java/apoc/schema/Schemas.java
- core/src/test/java/apoc/schema/SchemasTest.java
Cherry pick https://github.com/neo4j/apoc/commit/724aedfa5afd2c3aa35873926be90051435560d1
> [wr4kMP3r] ArithmeticException calling apoc.schema.nodes (neo4j/apoc#364)

- core/src/main/java/apoc/atomic/Atomic.java
- core/src/test/java/apoc/atomic/AtomicTest.java
Cherry Picked: https://github.com/neo4j/apoc/pull/425
> [KUEoGBey] Sanitize text input and add quotes to allow special characters in Atomic procedures

- build.gradle
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/pages/installation/index.adoc
- docs/build.gradle
- extra-dependencies/build.gradle
- readme.adoc
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/e37455c7cea0bf914178945c600f3b0243eb0d25
> Bump version 5.10.0 (#3456)

- .github/actions/test-gradle-project/action.yaml
- LICENSES.txt
- NOTICE.txt
- licenses-3rdparties.gradle
Make sure the PR will fail for:
Spotless - unused imports
Newly added dependencies
> [VpC8nqNz] Fail build on spotless and licence failures

- full/src/main/java/apoc/ttl/TTLLifeCycle.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/9dbac9c0d742d5258a902c9b2d338c9ec86b6715
> [NOID] DETACH DELETE in TTLLifeCycle.java (#3608)

- extended/src/main/java/apoc/ttl/TTLLifeCycle.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/9dbac9c0d742d5258a902c9b2d338c9ec86b6715
> DETACH DELETE in TTLLifeCycle.java (#3608)

- core/src/test/java/apoc/export/ExportCoreSecurityTest.java
- core/src/test/java/apoc/export/ImportAndLoadCoreSecurityTest.java
- core/src/test/java/apoc/export/SecurityTestUtil.java
- core/src/test/java/apoc/export/arrow/ExportArrowSecurityTest.java
- core/src/test/java/apoc/load/LoadCoreSecurityTest.java
- core/src/test/java/apoc/load/LoadJsonTest.java
- core/src/test/java/apoc/load/XmlTest.java
- core/src/test/java/apoc/util/FileTestUtil.java
- full/src/test/java/apoc/load/LoadFullSecurityTest.java
- test-utils/src/main/java/apoc/util/SensitivePathGenerator.java
Cherry-pick https://github.com/neo4j/apoc/commit/e9e874ec53275d879e2619e7b145d20ba913c889
Waiting for https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3616
> [s7Ob7Zm7] Test that all load and import procedures respect security (neo4j/apoc#360) (neo4j/apoc#377)

- core-it/src/test/java/apoc/core/it/LoadCoreEnterpriseTest.java
- core/src/main/java/apoc/export/util/CountingInputStream.java
- core/src/main/java/apoc/export/util/LimitedSizeInputStream.java
- core/src/main/java/apoc/load/Xml.java
- core/src/main/java/apoc/util/CompressionAlgo.java
- core/src/main/java/apoc/util/StreamConnection.java
- core/src/main/java/apoc/util/Util.java
- core/src/main/java/apoc/util/s3/S3Aws.java
Cherry-pick https://github.com/neo4j/apoc/commit/c9ba4df820deb7e0fc50567eacfb6151b4b9f59c
> [P7cw3Wcj] Fix zip bomb attack (neo4j/apoc#398)

- build.gradle
Bump Neo4j version to latest released
> [5LCCVHk4] Bump Neo4j version 4.4.22

- core/src/test/java/apoc/schema/SchemasTest.java
Cherry picked: https://github.com/neo4j/apoc/pull/455
> [LePmOHly] Fix flakey index test

- full/src/test/java/apoc/export/ExportFullSecurityTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/ca090dc16a0478c011894d4a0825da8c92516c77
> [GE2QhC9X] Add path traversal vulnerability tests (#3457)

- docs/asciidoc/modules/ROOT/pages/installation/index.adoc
- docs/asciidoc/modules/ROOT/partials/docker.adoc
- docs/asciidoc/modules/ROOT/partials/neo4j-desktop.adoc
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- readme.adoc
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3665/commits/67ae791f51c077feb783a2a797a653bf44d9c3cd
> Update installation docs with docker and desktop, created partial and small fixes

- extended/src/test/java/apoc/ttl/TTLTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3664
> [ld3WXRsV] Fix APOC extended TTL tests

- docs/antora/package-lock.json
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3653/commits/5f3a5df8a48ee892885f18d975919e8ef3dbac08
> Bump semver from 5.7.1 to 5.7.2 in /docs/antora

- build.gradle
- extended/src/main/java/apoc/cypher/CypherExtended.java
- extended/src/test/java/apoc/cypher/CypherExtendedTest.java
- extended/src/test/resources/long-create.cypher
- extended/src/test/resources/range_in_transaction.cypher
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/4d97c9c3953e0b087cc6780c495baf025d4de35a
> [V8keNXu0] error details while using apoc.cypher.run* procedures (#3668)

- extended/src/test/java/apoc/cypher/CypherExtendedTest.java
- extended/src/test/resources/long-create.cypher
- extended/src/test/resources/range_in_transaction.cypher
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3687/commits/74eef6361c0c19adad3ac60483031b4759cf434c
> [NOID] lightened tests

- settings.gradle
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/9b9eb39cbdfe7964599189ceb26b53d60ca5bd32
> Exclude :core:shadowJar task from extended (#3597)

- full/src/main/java/apoc/periodic/PeriodicExtended.java
- full/src/main/resources/extended.txt
- full/src/test/java/apoc/periodic/PeriodicExtendedTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3211
> [hDJkPkOQ] Fixes neo4j/apoc#126: apoc.periodic.submit fails with schema operations (extended) (#3211) (#3508)

- full-it/src/test/java/apoc/full/it/SystemDbEnterpriseTest.java
- full/src/main/java/apoc/systemdb/SystemDb.java
- full/src/test/java/apoc/systemdb/SystemDbEnterpriseTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/e133dbb216b7f416df14ca147d89b0d86f3497ab
4.4 changes:
- changed dbms settings
- Removed `FileUtils.forceDelete()` because the folder is git ignored
> [LMyH0Fi7] apoc.systemdb.graph leaks passwords/hashes (#3414)

- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.log.debug.adoc
- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.log.error.adoc
- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.log.info.adoc
- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.log.warn.adoc
Cherry picked: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3702
> [NOID] apoc.log docs update

- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.log.debug.adoc
- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.log.error.adoc
- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.log.info.adoc
- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.log.warn.adoc
Cherry picked: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3704
> [NOID] Cherry pick logging doc updates (#3704)

- core/src/main/java/apoc/ApocConfig.java
- docs/asciidoc/modules/ROOT/nav.adoc
- docs/asciidoc/modules/ROOT/pages/ml/index.adoc
- docs/asciidoc/modules/ROOT/pages/ml/openai.adoc
- full/src/main/java/apoc/ml/OpenAI.java
- full/src/main/java/apoc/ml/Prompt.java
- full/src/main/resources/extended.txt
- full/src/test/java/apoc/ml/OpenAIIT.java
- full/src/test/java/apoc/ml/OpenAITest.java
- full/src/test/java/apoc/ml/PromptIT.java
- full/src/test/resources/chat/completions
- full/src/test/resources/completions
- full/src/test/resources/embeddings
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/76a62c7921be1b0e545c1aec4e444beda72639e3 - Add OpenAI (LLM) procedures
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/027de47f4c4069a47a6218da82c0ea14ad3076f8 - First LLM prompt for cypher, query and schema in APOC
> [NOID] Add OpenAI (LLM) procedures in 4.4

- core-it/src/test/java/apoc/core/it/LoadCoreEnterpriseTest.java
- core-it/src/test/java/apoc/core/it/StartupTest.java
- core/src/main/java/apoc/ApocConfig.java
- core/src/main/java/apoc/ApocSettings.java
- core/src/main/java/apoc/export/util/LimitedSizeInputStream.java
- core/src/test/java/apoc/ApocConfigTest.java
To allow for customers to tweak exactly how big the uncompressed files can be.
> [47wOlqLp] Adds option to customize decompression ratio

- core/src/test/java/apoc/ApocConfigCommandExpansionTest.java
- core/src/test/java/apoc/ApocConfigTest.java
- core/src/test/resources/apoc-config-command-expansion/apoc.conf
Cherry pick: https://github.com/neo4j/apoc/pull/466
> [NOID] Cherry pick ApocConfigCommandExpansionTest fixes

- core/src/test/java/apoc/ApocConfigTest.java
I didn't notice that my updates removed this test 🙈
> [NOID] Add back mistakenly removed test

- core/src/test/java/apoc/spatial/GeocodeTest.java
- core/src/test/resources/spatial.json
cherry picked:  https://github.com/neo4j/apoc/pull/476
> [q5Vf4pi2] Fix broken GeoCode tests

- .github/workflows/CI.yaml
- .gitmodules
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- extended/build.gradle
- readme.adoc
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/4927bf942d9a12747a1f7c11e3e637d744eb7214
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/cf5ea51186512053ee6fca4f64ddf15e9bf2c92d
> [NOID] Release 5.11.0

- build.gradle
Manual cherry-picked from here: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3655
> Removed -debian suffix from docker

- docs/asciidoc/modules/ROOT/pages/export/index.adoc
- docs/asciidoc/modules/ROOT/pages/export/parquet.adoc
- docs/asciidoc/modules/ROOT/pages/import/index.adoc
- docs/asciidoc/modules/ROOT/pages/import/parquet.adoc
- docs/asciidoc/modules/ROOT/partials/hadoop-dependencies.adoc
- extended/src/main/java/apoc/export/parquet/ImportParquet.java
- extended/src/main/java/apoc/load/LoadParquet.java
Added documentation for Parquet procedure: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3711
https://trello.com/c/YM9jwcK7/70-follow-up-parquet-procedures
> [YM9jwcK7] Follow up parquet procedures - Added documentation

- docs/asciidoc/modules/ROOT/pages/export/index.adoc
- docs/asciidoc/modules/ROOT/pages/export/parquet.adoc
- docs/asciidoc/modules/ROOT/pages/import/index.adoc
- docs/asciidoc/modules/ROOT/pages/import/parquet.adoc
- docs/asciidoc/modules/ROOT/partials/hadoop-dependencies.adoc
- extended/src/main/java/apoc/export/parquet/ImportParquet.java
- extended/src/main/java/apoc/load/LoadParquet.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/11793a1fe64b7f4ee6f0fe387657fe0c4a443420
> [YM9jwcK7] Follow up parquet procedures - Added documentation (#3736)

- docs/asciidoc/modules/ROOT/pages/database-integration/redis.adoc
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/2f9a3a13c5bbdb43b2b1107271573efa4de9c4b1
> Fixing typo on syntax (#3709)

- docs/asciidoc/modules/ROOT/pages/cypher-execution/cypher-based-procedures-functions.adoc
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/6f1733e648ad97f66b2ed3273b32bd96391bd510
> Fixes #3695: Improvement docs for Cypher Procedures on 5.11 (#3748)

- extended/src/main/java/apoc/load/LoadLdap.java
- extended/src/test/java/apoc/load/LoadLdapTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3727
> [qxkr2RlZ] apoc.load.ldap cant find config value due to missing

- full/src/main/java/apoc/load/LoadLdap.java
- full/src/test/java/apoc/load/LoadLdapTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/a7ac660596d1c1e586fd773009b88a25fd1aef7a
> [qxkr2RlZ] apoc.load.ldap cant find config value due to missing (#3727)

- extended/src/main/java/apoc/custom/CypherProcedures.java
- extended/src/main/java/apoc/custom/CypherProceduresHandler.java
- extended/src/test/java/apoc/custom/CypherProceduresStorageTest.java
- extended/src/test/java/apoc/custom/CypherProceduresTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/868c36f904b07bf0720df99d0723f2d522914633
> [XWc7tBAb] Custom procedures with overload fail after refresh (#3755)

- full/src/main/java/apoc/custom/CypherProceduresHandler.java
- full/src/test/java/apoc/custom/CypherProceduresTest.java
Fixes #3708
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/bd6f3d1108d73218098f9245628ec4824645a19d
> [NOID] Fixes #3708: Neo4j APOC custom function hangs when nothing is found (#3760)

- core/src/test/java/apoc/load/LoadJsonTest.java
- core/src/test/java/apoc/load/SimpleHttpHandler.java
- core/src/test/java/apoc/load/XmlTest.java
Cherry picked: https://github.com/neo4j/apoc/pull/477
> [YGQfavsP] Remove dependency on external websites in load tests

- build.gradle
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- docs/build.gradle
- extra-dependencies/build.gradle
- readme.adoc
> Bump version 5.13.0 (#3456) (#3536) (#3658)

- docs/antora/publish.yml
* Update playbooks for docs publish
* Attribute to display notes in selected versions
-
-
-
> Update playbooks for docs publish (#3758)

- build.gradle
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- docs/build.gradle
- extra-dependencies/build.gradle
- readme.adoc
> Change 5.11.1 to 5.11.0

- .github/workflows/CI.yaml
- .gitmodules
- build.gradle
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- extended/build.gradle
- readme.adoc
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/dfde578506aed233dac114006fa6287d8572ac91
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/490aaacc937bd5dd05c3d019dcf06a308704890d
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/b3fae2d733e852be76417483df6001316749315b
> Release 5.12.0

- LICENSES.txt
- NOTICE.txt
- build.gradle
- readme.adoc
> [NOID] Bump Neo version

- extended/src/main/java/apoc/custom/CypherProceduresHandler.java
- extended/src/test/java/apoc/custom/CypherProceduresTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/bd6f3d1108d73218098f9245628ec4824645a19d
> Fixes #3708: Neo4j APOC custom function hangs when nothing is found

- docs/asciidoc/modules/ROOT/partials/usage/apoc.refactor.normalizeAsBoolean.adoc
cherry-pick: https://github.com/neo4j/docs-apoc/pull/204/files
> [NiLGknLU] add boolean example to apoc.refactor.normalizeAsBoolean

- .github/workflows/CI.yaml
- .gitmodules
- build.gradle
- docs/antora/publish.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- readme.adoc
TODO - retrigger build
---
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/4927bf942d9a12747a1f7c11e3e637d744eb7214
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/cf5ea51186512053ee6fca4f64ddf15e9bf2c92d
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3795/commits/c48fc34043dd90087e20c98df258e8690a45f24e
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/490aaacc937bd5dd05c3d019dcf06a308704890d
> [NOID] Release 5.13.0

- build.gradle
- docs/asciidoc/modules/ROOT/pages/cypher-execution/cypher-based-procedures-functions.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.custom.list.adoc
- extended/src/main/antlr/apoc/custom/Signature.g4
- extended/src/main/java/apoc/custom/CypherProceduresHandler.java
- extended/src/main/java/apoc/custom/Signatures.java
- extended/src/main/java/apoc/get/GetProcedures.java
- extended/src/main/java/apoc/systemdb/metadata/ExportFunction.java
- extended/src/test/java/apoc/CoreExtendedTest.java
- extended/src/test/java/apoc/coll/CollExtendedTest.java
- extended/src/test/java/apoc/custom/CypherProceduresStorageTest.java
- extended/src/test/java/apoc/custom/CypherProceduresTest.java
- extended/src/test/java/apoc/systemdb/SystemDbTest.java
Similar to https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3795, without StartupExtendedTest ignored.
> Solve ci 5.13 errors

- .github/workflows/CI.yaml
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/bc690af6e663bc9b43a6d652d6be9991dffead8b
> Parallelize test if not in TeamCity (#3807)

- extended/src/main/resources/extended.txt
See https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/6641749608/job/18044969373#step:5:5055
> Fix StartupExtendedTest with bedrock procs

- extended/src/main/java/apoc/custom/CypherProceduresHandler.java
- extended/src/test/java/apoc/custom/CypherProceduresTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/c41d33b9bf4595bd4b1f8561539dbfef68764bf7
> Fixes #3708: Neo4j APOC custom function hangs when nothing is found (#3759)

- core/src/main/java/apoc/export/csv/CsvFormat.java
- core/src/test/java/apoc/export/csv/ExportCsvNeo4jAdminTest.java
cherry-picked: https://github.com/neo4j/apoc/pull/517
> [q3KTZ83O] Remove strange clean up method

- build.gradle
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- docs/build.gradle
- extra-dependencies/build.gradle
- readme.adoc
> Bump version 5.15.0 (#3456) (#3536) (#3726)

- extended/src/main/java/apoc/monitor/Ids.java
See here: https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/6799119784/job/18486711630#step:6:353.
Changed methods after signature changes in neo4j 5.15.0.
> Solve CI 5.15 compile error

- extended/src/main/java/apoc/uuid/UUIDHandlerNewProcedures.java
- extended/src/main/java/apoc/uuid/UuidHandler.java
- extended/src/test/java/apoc/uuid/UUIDTest.java
Fix bug in `apoc.uuid.*` procedures (similar to https://github.com/neo4j/apoc/pull/513).
cherry-pick: #3832
> Dev fix UUID bug

- LICENSES.txt
- NOTICE.txt
- core/src/main/java/apoc/coll/Coll.java
- core/src/main/java/apoc/convert/Convert.java
- core/src/test/java/apoc/coll/CollTest.java
Cherry-picked: https://github.com/neo4j/apoc/pull/538/files
> [gtjPFvMD] Fix coll support for lists coming from Nodes or Rels.

- core/src/main/java/apoc/export/csv/ExportCSV.java
- core/src/main/java/apoc/export/util/ExportConfig.java
- core/src/main/java/apoc/export/util/ExportFormat.java
- core/src/test/java/apoc/export/csv/ExportCsvTest.java
- docs/asciidoc/modules/ROOT/pages/overview/apoc.export/compression.adoc
Cherry picked: https://github.com/neo4j/apoc/pull/542
> [G9u7OAg9] Ignore check for optimizations if the format is CSV

- .github/workflows/CI.yaml
- .gitmodules
- build.gradle
- docs/antora/publish.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- extended/src/test/java/apoc/StartupExtendedTest.java
- extended/src/test/java/apoc/util/ExtendedTestContainerUtil.java
- extra-dependencies/build.gradle
- extra-dependencies/couchbase/build.gradle
- extra-dependencies/gcs/build.gradle
- extra-dependencies/hadoop/build.gradle
- extra-dependencies/mongodb/build.gradle
- extra-dependencies/nlp/build.gradle
- extra-dependencies/redis/build.gradle
- extra-dependencies/selenium/build.gradle
- readme.adoc
Cherry-pick of https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/4430171de366ae3e07d019f30e2f4311ddeb0976
* [NOID] Release 5.15.0 (#3803)
* Removed -debian suffix from docker (#3723)
* solve various jar conflict errors
* add commonExclusion
* try debug confligException
* remove extra-deps
* remove gson (present in hadoop) and changed wildCard extra-deps filter
* restore code
* update submodule (#3856)
> Release 5.15.0 (#3803) (#3844)

- docs/asciidoc/modules/ROOT/pages/ml/openai.adoc
- extended/src/main/java/apoc/ExtendedApocConfig.java
- extended/src/main/java/apoc/ml/OpenAI.java
- extended/src/main/java/apoc/ml/OpenAIRequestHandler.java
- extended/src/test/java/apoc/ml/OpenAIAzureIT.java
- extended/src/test/java/apoc/ml/OpenAIIT.java
- extended/src/test/java/apoc/ml/OpenAITest.java
- extended/src/test/java/apoc/ml/OpenAITestResultUtils.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/db102bd6c8054b1032fcd63b7f1e7a89fe28b5cf
> Fixes #3634: Updated ML procs for Azure OpenAI services (#3850)

- extended/build.gradle
- extended/src/main/java/apoc/export/parquet/ExportParquetFileStrategy.java
- extended/src/main/java/apoc/export/parquet/ExportParquetStrategy.java
- extended/src/main/java/apoc/export/parquet/ExportParquetStreamStrategy.java
- extended/src/main/java/apoc/export/parquet/ImportParquet.java
- extended/src/main/java/apoc/export/parquet/ParquetBufferedWriter.java
- extended/src/main/java/apoc/export/parquet/ParquetReadUtil.java
- extended/src/main/java/apoc/load/LoadParquet.java
- extended/src/test/java/apoc/export/parquet/ParquetTest.java
- extra-dependencies/hadoop/build.gradle
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/e79aae4f110cc2b640f7b806c66c2857c76c5b3e
> Fixes #3823: Reading Parquet from s3 (#3846)

- extended/build.gradle
Cherry-pick of https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/cf5ea51186512053ee6fca4f64ddf15e9bf2c92d
> Upgrade java driver 5.15.0

- build.gradle
- extended/build.gradle
- extended/src/main/java/apoc/export/parquet/ExportParquetFileStrategy.java
- extended/src/main/java/apoc/export/parquet/ExportParquetStrategy.java
- extended/src/main/java/apoc/export/parquet/ExportParquetStreamStrategy.java
- extended/src/main/java/apoc/export/parquet/ParquetBufferedWriter.java
- extended/src/main/java/apoc/export/parquet/ParquetReadUtil.java
- extended/src/test/java/apoc/export/parquet/ParquetTest.java
- extended/src/test/java/apoc/util/ExtendedTestContainerUtil.java
- extra-dependencies/hadoop/build.gradle
> Fixes #3823: Reading Parquet from s3

- extended/src/main/java/apoc/custom/CypherProceduresHandler.java
- extended/src/test/java/apoc/custom/CypherProceduresStorageTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/eda49ee076e1bea145a614b2a8a558b07300fa00
> [6R2yEhGU] No procedure with name xxxx registered for this database instance (#3800)

- docs/asciidoc/modules/ROOT/pages/ml/sagemaker.adoc
- extended/src/main/java/apoc/ml/aws/AWSConfig.java
- extended/src/main/java/apoc/ml/aws/AwsSignatureV4Generator.java
- extended/src/main/java/apoc/ml/aws/Bedrock.java
- extended/src/main/java/apoc/ml/aws/BedrockGetModelsConfig.java
- extended/src/main/java/apoc/ml/aws/BedrockInvokeConfig.java
- extended/src/main/java/apoc/ml/aws/BedrockInvokeResult.java
- extended/src/main/java/apoc/ml/aws/BedrockUtil.java
- extended/src/main/java/apoc/ml/aws/ModelItemResult.java
- extended/src/main/java/apoc/ml/aws/SageMaker.java
- extended/src/main/java/apoc/ml/aws/SageMakerConfig.java
- extended/src/main/resources/extended.txt
- extended/src/test/java/apoc/ml/aws/BedrockIT.java
- extended/src/test/java/apoc/ml/aws/BedrockTest.java
- extended/src/test/java/apoc/ml/aws/BedrockTestUtil.java
- extended/src/test/java/apoc/ml/sagemaker/SageMakerIT.java
- extended/src/test/java/apoc/ml/sagemaker/SageMakerTest.java
Fixes #3634: Add ML procs for AWS SageMaker Endpoints
> Fixes #3634: Add ML procs for AWS SageMaker Endpoints

- extended/src/main/java/apoc/ml/aws/Bedrock.java
- extended/src/main/java/apoc/ml/aws/SageMaker.java
Fix TC StartupExtendedTest errors
> Fix TC StartupExtendedTest errors

- docs/asciidoc/modules/ROOT/pages/config/index.adoc
- docs/asciidoc/modules/ROOT/pages/import/web-apis.adoc
Cherry-picks https://github.com/neo4j/docs-apoc/pull/193/
> [47wOlqLp] Adds documentation about decompression ratio

- docs/asciidoc/modules/ROOT/pages/export/index.adoc
- docs/asciidoc/modules/ROOT/pages/export/web-apis.adoc
- docs/asciidoc/modules/ROOT/pages/import/web-apis.adoc
Cherry-picks https://github.com/neo4j/docs-apoc/pull/188
> [NrNk9YvB] Reshapes import and export sections

- docs/asciidoc/modules/ROOT/pages/ml/bedrock.adoc
- extended/src/main/java/apoc/ml/bedrock/AwsSignatureV4Generator.java
- extended/src/main/java/apoc/ml/bedrock/Bedrock.java
- extended/src/main/java/apoc/ml/bedrock/BedrockInvokeConfig.java
- extended/src/test/java/apoc/ml/bedrock/BedrockIT.java
- extended/src/test/java/apoc/ml/bedrock/BedrockTestUtil.java
cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3867
> Make Bedrock chat body request compatible with OpenAI

- docs/asciidoc/modules/ROOT/pages/ml/sagemaker.adoc
- extended/src/main/java/apoc/ml/aws/AWSConfig.java
- extended/src/main/java/apoc/ml/aws/AwsSignatureV4Generator.java
- extended/src/main/java/apoc/ml/aws/Bedrock.java
- extended/src/main/java/apoc/ml/aws/BedrockGetModelsConfig.java
- extended/src/main/java/apoc/ml/aws/BedrockInvokeConfig.java
- extended/src/main/java/apoc/ml/aws/BedrockInvokeResult.java
- extended/src/main/java/apoc/ml/aws/BedrockUtil.java
- extended/src/main/java/apoc/ml/aws/ModelItemResult.java
- extended/src/main/java/apoc/ml/aws/SageMaker.java
- extended/src/main/java/apoc/ml/aws/SageMakerConfig.java
- extended/src/main/resources/extended.txt
- extended/src/test/java/apoc/ml/aws/BedrockIT.java
- extended/src/test/java/apoc/ml/aws/BedrockTest.java
- extended/src/test/java/apoc/ml/aws/BedrockTestUtil.java
- extended/src/test/java/apoc/ml/sagemaker/SageMakerIT.java
- extended/src/test/java/apoc/ml/sagemaker/SageMakerTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/64d9f776151ab3f278a503ee488fc900fcc17209
Cherry-pick  https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/83199902017ac9e89d699954a6f581147fa7e8b6
> Fixes #3634: Add ML procs for AWS SageMaker Endpoints (#3871)

- extended/src/test/java/apoc/nodes/NodesExtendedTest.java
Fixes #3367
Added test with [valueType](https://neo4j.com/docs/cypher-manual/current/functions/scalar/#functions-valueType),
to verify that the `apoc.path.rebind` function is not necessary, since rebinding a Path returns a Path and the data type is not lost, even if the `apoc.any.rebind` function returns `Object`.
It also works with neo4j 4.4, using the `apoc.meta.cypher.type`
> Fixes #3367: Test to check return type of apoc.any.rebind with a Path

- extended/src/test/java/apoc/nodes/NodesExtendedTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/6bb5ffe6391c08b2874aeecccf73a6123f16b546
> Fixes #3367: Test to check return type of apoc.any.rebind with a Path (#3841)

- extended/src/test/java/apoc/help/HelpExtendedTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/29b2ada86d576e0e9c3ccdaddb1c41c1ea08c942
> Fix HelpExtendedTest not to edit extended.txt when executed (#3896)

- docs/asciidoc/modules/ROOT/partials/mongodb-dependencies.adoc
- extended/build.gradle
- extended/src/main/java/apoc/mongodb/MongoDBColl.java
- extended/src/main/java/apoc/mongodb/MongoDBUtils.java
- extended/src/test/java/apoc/mongodb/MongoDBTest.java
- extended/src/test/java/apoc/mongodb/MongoDBVersion4Test.java
- extended/src/test/java/apoc/mongodb/MongoTest.java
- extended/src/test/java/apoc/mongodb/MongoTestBase.java
- extended/src/test/java/apoc/mongodb/MongoVersion4Test.java
- extra-dependencies/mongodb/build.gradle
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/bfbb9c27a1eaf99dd4b9e7c1068463fe4cfe6dd8
> Fixes #3203: apoc.mongo dependencies are outdated with current mongodb (#3897)

- docs/asciidoc/modules/ROOT/pages/ml/bedrock.adoc
- extended/src/main/java/apoc/ml/bedrock/AwsSignatureV4Generator.java
- extended/src/main/java/apoc/ml/bedrock/Bedrock.java
- extended/src/main/java/apoc/ml/bedrock/BedrockInvokeConfig.java
- extended/src/test/java/apoc/ml/bedrock/BedrockIT.java
- extended/src/test/java/apoc/ml/bedrock/BedrockTestUtil.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/c306b3cb112a51410eecf86a9a0e52e0674d55c3
> Make Bedrock chat body request compatible with OpenAI (#3866)

- extended/src/main/java/apoc/custom/CypherProceduresHandler.java
- extended/src/test/java/apoc/custom/CypherProceduresStorageTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/eda49ee076e1bea145a614b2a8a558b07300fa00
> [6R2yEhGU] No procedure with name xxxx registered for this database instance (#3800) (#3873)

- docs/asciidoc/modules/ROOT/pages/ml/sagemaker.adoc
- extended/src/main/java/apoc/ml/aws/AWSConfig.java
- extended/src/main/java/apoc/ml/aws/AwsSignatureV4Generator.java
- extended/src/main/java/apoc/ml/aws/Bedrock.java
- extended/src/main/java/apoc/ml/aws/BedrockGetModelsConfig.java
- extended/src/main/java/apoc/ml/aws/BedrockInvokeConfig.java
- extended/src/main/java/apoc/ml/aws/BedrockInvokeResult.java
- extended/src/main/java/apoc/ml/aws/BedrockUtil.java
- extended/src/main/java/apoc/ml/aws/ModelItemResult.java
- extended/src/main/java/apoc/ml/aws/SageMaker.java
- extended/src/main/java/apoc/ml/aws/SageMakerConfig.java
- extended/src/main/resources/extended.txt
- extended/src/test/java/apoc/ml/aws/BedrockIT.java
- extended/src/test/java/apoc/ml/aws/BedrockTest.java
- extended/src/test/java/apoc/ml/aws/BedrockTestUtil.java
- extended/src/test/java/apoc/ml/sagemaker/SageMakerIT.java
- extended/src/test/java/apoc/ml/sagemaker/SageMakerTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/9d3ebf8a5b1bd7c74955c0aba6aa423a04b4a4a1
> Fixes #3634: Add ML procs for AWS SageMaker Endpoints (#3871) (#3884)

- extended/build.gradle
Changed java driver version consistently with `$NEO4J_HOME/lib` version
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/0b43ecd595745e90b59a49ffab66bf8a904b3e60
> Changed java driver version

- docs/asciidoc/modules/ROOT/pages/ml/vertexai.adoc
Cherry-pick 0d6e6d20b8a5577db61283780d753a2d133ce82f
> Update vertexai.adoc (#3835)

- extended/src/main/java/apoc/ml/OpenAI.java
- extended/src/test/java/apoc/ml/OpenAIIT.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/a0a9deaa7719a67905cfe97637664cce77d91e84
> Replaced Open AI model (#3854)

- docs/asciidoc/modules/ROOT/pages/ml/index.adoc
- docs/asciidoc/modules/ROOT/pages/ml/watsonai.adoc
- extended/src/main/java/apoc/ExtendedApocConfig.java
- extended/src/main/java/apoc/ml/Watson.java
- extended/src/main/resources/extended.txt
- extended/src/test/java/apoc/ml/WatsonIT.java
- extended/src/test/java/apoc/ml/WatsonTest.java
- extended/src/test/resources/watson.json
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3901
> Fixes #3891: Add IBM Watson Foundation model integration (#3901)

- core/src/main/java/apoc/SystemPropertyKeys.java
- docs/asciidoc/modules/ROOT/pages/cypher-execution/cypher-based-procedures-functions.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.custom.declareFunction.adoc
- full/src/main/antlr/apoc/custom/Signature.g4
- full/src/main/java/apoc/custom/CypherProcedures.java
- full/src/main/java/apoc/custom/CypherProceduresHandler.java
- full/src/main/java/apoc/custom/Signatures.java
- full/src/test/java/apoc/custom/CypherProceduresStorageTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/0accff9f5647162a86bce728764dee7b1d865bf6
> [NOID] Fixes #2612: Added MAPRESULT type to custom functions (#3838)

- extended/src/main/java/apoc/ml/aws/Bedrock.java
- extended/src/main/java/apoc/ml/aws/SageMaker.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/83199902017ac9e89d699954a6f581147fa7e8b6
> Fix TC StartupExtendedTest errors (#3888)

- extended/src/test/java/apoc/StartupExtendedTest.java
- extra-dependencies/build.gradle
- extra-dependencies/couchbase/build.gradle
- extra-dependencies/gcs/build.gradle
- extra-dependencies/hadoop/build.gradle
- extra-dependencies/mongodb/build.gradle
- extra-dependencies/nlp/build.gradle
- extra-dependencies/redis/build.gradle
- extra-dependencies/selenium/build.gradle
Cherry-pick gradle stuff from here: https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/5cbc639346635f6b06d47d025fcb4ffdbd44c901
> Solved various jar conflict errors with neo4j 5.15+ (#3859)

- extended/src/main/java/apoc/cypher/CypherExtended.java
- extended/src/test/java/apoc/cypher/CypherEnterpriseExtendedTest.java
- extended/src/test/java/apoc/cypher/CypherExtendedTest.java
- extended/src/test/resources/parallel.cypher
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/e152208e092ac222bb805297f4f2f48db19a1971
> Fixes #3751: Failed to invoke procedure apoc.cypher.mapParallel2: Caused by:RuntimeException: Error polling, timeout (#3922)

- full/src/test/java/apoc/custom/CypherProceduresTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/a26f6800fc4a2dfee8772e4a8eebdaad2d4ff14a
> [NOID] Remove register BuiltInDbmsProcedures.class (#3660)

- docs/asciidoc/modules/ROOT/partials/html/runtime.adoc
- docs/asciidoc/modules/ROOT/partials/usage/config/apoc.load.html.adoc
- full-it/src/test/java/apoc/full/it/MissingExtraDependenciesTest.java
- full/src/main/java/apoc/bolt/BoltConnection.java
- full/src/main/java/apoc/couchbase/Couchbase.java
- full/src/main/java/apoc/couchbase/CouchbaseConnection.java
- full/src/main/java/apoc/data/email/ExtractEmail.java
- full/src/main/java/apoc/data/email/ExtractEmailHandler.java
- full/src/main/java/apoc/export/xls/ExportXls.java
- full/src/main/java/apoc/export/xls/ExportXlsHandler.java
- full/src/main/java/apoc/load/LoadHtml.java
- full/src/main/java/apoc/load/LoadXls.java
- full/src/main/java/apoc/load/LoadXlsHandler.java
- full/src/main/java/apoc/mongodb/Mongo.java
- full/src/main/java/apoc/mongodb/MongoDB.java
- full/src/main/java/apoc/mongodb/MongoDBColl.java
- full/src/main/java/apoc/mongodb/MongoDBUtils.java
- full/src/main/java/apoc/mongodb/MongoDbCollInterface.java
- full/src/main/java/apoc/redis/RedisConfig.java
- full/src/test/java/apoc/mongodb/MongoDBTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/0b6eb5794380b00bcadfb776a20fb6a1e75a72d7
> [NOID] Fixes #3831: Improve procedure errors in case of missing dependency (#3837)

- build.gradle
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- docs/build.gradle
- extra-dependencies/build.gradle
- readme.adoc
> Bump version 5.18.0 (#3456) (#3536)

- core/src/main/java/apoc/convert/Json.java
- core/src/test/java/apoc/convert/ConvertJsonTest.java
Cherry-pick: https://github.com/neo4j/apoc/pull/581
> [7nVhdJu3] apoc.convert.toTree keep all rels in tree fix

- full/src/test/java/apoc/help/HelpExtendedTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/29b2ada86d576e0e9c3ccdaddb1c41c1ea08c942
> [NOID] Fix HelpExtendedTest not to edit extended.txt when executed (#3896)

- extended/src/test/java/apoc/ml/VertexAITest.java
- extended/src/test/resources/vertex/chatCompletions.json
- extended/src/test/resources/vertex/completions.json
- extended/src/test/resources/vertex/embeddings.json
Fixes #3602
Added `VertexAI` unit tests, similar to `BedrockTest` and `OpenAITest`
> Fixes #3602: Add Vertex.ai Unit Tests

- .github/workflows/CI.yaml
- .gitmodules
- build.gradle
- docs/antora/publish.yml
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- docs/build.gradle
- extended/build.gradle
- extra-dependencies/build.gradle
- readme.adoc
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/5cbc639346635f6b06d47d025fcb4ffdbd44c901
> Release 5.17.1 (#3803) (#3844) (#3859)

- core/src/main/java/apoc/refactor/GraphRefactoring.java
- core/src/main/java/apoc/util/Util.java
- core/src/test/java/apoc/refactor/GraphRefactoringTest.java
Cherry-pick: https://github.com/neo4j/apoc/pull/605
> [oIVz2Y7V] apoc.refactor.cloneNodes does not need to be in its own transaction

- .github/actions/gradle-command-on-pr/action.yaml
- .github/workflows/generateLicenses-command.yml
Cherry-picks https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3991
> [NOID] Adjusts gradle command to always succeed in the license job

- build.gradle
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- docs/build.gradle
- extra-dependencies/build.gradle
- readme.adoc
> Bump version 5.19.0 (#3456) (#3536) (#3726)

- full/src/main/java/apoc/ExtendedApocGlobalComponents.java
- full/src/main/java/apoc/ttl/TTLLifeCycle.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/4d868fd3cd80da9817bd14c02b6b781ba6d37f87
> [NOID] Fixes #3777: Remove APOC Core procedures from TTLLifeCycle.java (#3957)

- full/src/main/java/apoc/cypher/CypherExtended.java
- full/src/test/java/apoc/cypher/CypherExtendedTest.java
- full/src/test/resources/parallel.cypher
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/e46bffbc4fed7b831f4e5b01cc92cfcd9112018b
> [NOID] Fixes #3751: Failed to invoke procedure apoc.cypher.mapParallel2: Caused by:RuntimeException: Error polling, timeout (#3922)

- full/src/main/java/apoc/custom/CypherProcedures.java
- full/src/test/java/apoc/VersionUpdateChecksTest.java
- full/src/test/java/apoc/custom/CypherProceduresTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/020672ecf9c9d26647aeabd39306fe5143f6ab28
> [NOID] Fixes #3072: apoc.custom.declareProcedure fails with java.lang.RuntimeException if provided mode is SCHEMA (#3954)

- extended/src/main/java/apoc/util/ExtendedUtil.java
- extended/src/test/java/apoc/util/ExtendedTestContainerUtil.java
Fixes #3963
Added retry mechanism
> Fixes #3963: Solve flaky cluster routing test

- .github/workflows/CI.yaml
- .gitmodules
- build.gradle
- docs/antora/publish.yml
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- docs/build.gradle
- extended/build.gradle
- extended/src/test/java/apoc/custom/CypherProceduresClusterRoutingTest.java
- extended/src/test/java/apoc/cypher/CypherEnterpriseExtendedTest.java
- extra-dependencies/build.gradle
- readme.adoc
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/d5e64470eb84aabf2461457ebe385cc38ba8b47a
> Release 5.18.0

- docs/antora/package-lock.json
- docs/antora/package.json
Antora bump suggested by dependatbot
> [NOID] Antora bump

- full/src/test/java/apoc/mongodb/MongoTestBase.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/8840fd9c731348ee0bef29aede9c2e6aa456f767
> [NOID] Fixes #3964: Solve flaky mongodb test (#4020)

- full/src/main/java/apoc/uuid/UuidHandler.java
- full/src/test/java/apoc/uuid/UUIDNewProceduresTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/0d79b97fb34fe6610cfa294d0f43e3e6f74a1f24
> [NOID] Fixes #3840: UUID handler throws warnings when deleting nodes (#4023)

- .github/workflows/CI.yaml
- .gitmodules
- build.gradle
- docs/antora/publish.yml
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- docs/build.gradle
- extended/build.gradle
- extra-dependencies/build.gradle
- readme.adoc
> Release 5.19.0 (#4013)

- build.gradle
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- docs/build.gradle
- extra-dependencies/build.gradle
- readme.adoc
> Bump version 5.21.0 (#3456) (#3536) (#3726) (#3995)

- LICENSES.txt
- NOTICE.txt
- build.gradle
- docs/asciidoc/antora.yml
- extra-dependencies/build.gradle
- gradle.properties
- readme.adoc
- Restructure gradle project.
- Bump version.
> [6AtySekS] Bump version

- build.gradle
- readme.adoc
Looks like Neo wasn't bumped with latest release
> [NOID] Bump Neo to next version

- build.gradle
Reverts neo4j-contrib/neo4j-apoc-procedures#4083
> Revert "Provisionally updated build.gradle docker versions to solve compile errors due to core 5.21 changes"

- core/src/main/java/apoc/export/cypher/ExportCypher.java
- core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java
Cherry-pick: https://github.com/neo4j/apoc/pull/623
> [WVuGDROz] Allow cypher.export.schema return using a stream

- .github/workflows/CI.yaml
- build.gradle
- docs/antora/publish.yml
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- docs/build.gradle
- extended/build.gradle
- extra-dependencies/build.gradle
- readme.adoc
> Release 5.20.0 (#3962) (#4051)

- .github/workflows/CI.yaml
- .gitmodules
- build.gradle
- docs/antora/publish.yml
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- docs/build.gradle
- extended/build.gradle
- extra-dependencies/build.gradle
- readme.adoc
> Bump 5.20.0

- extended/src/main/java/apoc/custom/CypherProceduresHandler.java
- extended/src/main/java/apoc/cypher/CypherExtended.java
- extended/src/main/java/apoc/export/arrow/ImportArrow.java
- extended/src/main/java/apoc/export/parquet/ExportParquet.java
- extended/src/main/java/apoc/export/parquet/ParquetReadUtil.java
- extended/src/main/java/apoc/load/LoadCsv.java
- extended/src/main/java/apoc/load/LoadDirectory.java
- extended/src/main/java/apoc/load/LoadHtml.java
- extended/src/test/java/apoc/export/parquet/ParquetTest.java
- extended/src/test/java/apoc/load/LoadCsvTest.java
- extended/src/test/java/apoc/util/ExtendedTestUtil.java
- extended/src/test/java/apoc/util/FileUtilsTest.java
Reverts neo4j-contrib/neo4j-apoc-procedures#4100
> Revert "Solve dev 5.21 compile errors"

- docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/chroma.adoc
- docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/milvus.adoc
- docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/pinecone.adoc
- docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/qdrant.adoc
- docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/weaviate.adoc
- extended-it/src/test/java/apoc/vectordb/ChromaDbTest.java
- extended-it/src/test/java/apoc/vectordb/MilvusTest.java
- extended-it/src/test/java/apoc/vectordb/QdrantTest.java
- extended-it/src/test/java/apoc/vectordb/WeaviateTest.java
- extended/src/test/java/apoc/vectordb/PineconeTest.java
- extended/src/test/java/apoc/vectordb/VectorDbTestUtil.java
Fixes #4091
- Updated docs
- Added unit tests
> Fixes #4091: Update RAG docs with vector db examples

- extended/build.gradle
- extra-dependencies/aws/build.gradle
- extra-dependencies/build.gradle
- extra-dependencies/yaml/build.gradle
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4094
> Solve 5.20 extra-dependencies conflict errors

- docs/asciidoc/modules/ROOT/nav.adoc
- docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/chroma.adoc
- docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/custom.adoc
- docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/index.adoc
- docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/milvus.adoc
- docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/pinecone.adoc
- docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/qdrant.adoc
- docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/weaviate.adoc
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/7da654be203da83baa4b364ee6070b0180b4792f
> Fixes for asciidoc files of vector db integration

- .github/workflows/CI.yaml
- .gitmodules
- build.gradle
- docs/antora/publish.yml
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- docs/build.gradle
- extended/build.gradle
- extra-dependencies/build.gradle
- readme.adoc
> Release 5.21.0 (#4013) (#4051)

- .gitignore
- .gitmodules
- extended-it/src/test/java/apoc/vectordb/ChromaDbTest.java
- extended-it/src/test/java/apoc/vectordb/QdrantTest.java
- extended/src/main/java/apoc/custom/CypherProceduresHandler.java
- extended/src/main/java/apoc/custom/CypherProceduresUtil.java
- extended/src/main/java/apoc/custom/Signatures.java
- extended/src/main/java/apoc/cypher/CypherExtended.java
- extended/src/main/java/apoc/export/arrow/ImportArrow.java
- extended/src/main/java/apoc/export/parquet/ExportParquet.java
- extended/src/main/java/apoc/export/parquet/ParquetReadUtil.java
- extended/src/main/java/apoc/load/LoadCsv.java
- extended/src/main/java/apoc/load/LoadDirectory.java
- extended/src/main/java/apoc/load/LoadHtml.java
- extended/src/test/java/apoc/export/parquet/ParquetTest.java
- extended/src/test/java/apoc/load/LoadCsvTest.java
- extended/src/test/java/apoc/systemdb/SystemDbTest.java
- extended/src/test/java/apoc/util/ExtendedTestUtil.java
- extended/src/test/java/apoc/util/FileUtilsTest.java
- gradle.properties
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/d0f424c1dec8aa2a0fd1fd530d8fd6620d411fde
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/3098d81cdd9f89a3234c513ce9b37f80d479de4e
> Solve dev 5.21 build errors

- docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/chroma.adoc
- docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/milvus.adoc
- docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/qdrant.adoc
- docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/weaviate.adoc
Fixes #4124
Added example results in adocs.
> Fixes #4124: Better document output of vector db procedures

- build.gradle
- docs/asciidoc/antora.yml
- extra-dependencies/build.gradle
- readme.adoc
> [NOID] Version Bump

- .gitmodules
- build.gradle
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- docs/build.gradle
- extra-dependencies/build.gradle
- readme.adoc
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/f351e8ddb00236ddcdad0728d8555511cce57386
> Bump version 5.22.0

- docs/asciidoc/modules/ROOT/pages/ml/openai.adoc
- docs/asciidoc/modules/ROOT/pages/ml/rag.adoc
- docs/asciidoc/modules/ROOT/pages/ml/vertexai.adoc
- extended/src/main/java/apoc/ml/OpenAI.java
- extended/src/test/java/apoc/ml/OpenAIIT.java
- extended/src/test/java/apoc/ml/PromptIT.java
- extended/src/test/java/apoc/ml/VertexAIIT.java
Fixes #4122
- added tests and docs with custom models `gemini-flash` in VertexAIIT
- added tests and docs with old model `gpt-3.5-turbo` in OpenAIIT and PromptIT
> Fixes #4122: Test if gemini-flash and gpt-35 work

- .github/workflows/CI.yaml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
> Release 5.22.0 

- .github/actions/test-gradle-project/action.yml
- .github/workflows/CI.yaml
- .gitmodules
- build.gradle
- docs/antora/publish.yml
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- docs/build.gradle
- extended/build.gradle
- extra-dependencies/build.gradle
- readme.adoc
- teamcity-repository.gradle
> Release 5.23.0 (#4013) (#4051)

- .github/workflows/CI.yaml
- docs/antora/publish.yml
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- docs/build.gradle
- extended/build.gradle
- extra-dependencies/build.gradle
- readme.adoc
> Release 5.24.0 (#3962)

- build.gradle
- docs/asciidoc/antora.yml
- extra-dependencies/build.gradle
- readme.adoc
> [VdgJs3OT] Bump version

- extended-it/src/test/java/apoc/couchbase/CouchbaseTestUtils.java
- extended-it/src/test/java/apoc/load/PostgresJdbcTest.java
- extended/src/test/java/apoc/export/csv/ExportCsvTest.java
- extended/src/test/java/apoc/export/parquet/ParquetHdfsTest.java
- extended/src/test/java/apoc/load/LoadHdfsTest.java
- extended/src/test/java/apoc/load/LoadLdapContainerTest.java
- extended/src/test/java/apoc/util/HdfsTestUtils.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/3ca397289ba8edd72c3b27b3e084d7d388a1a2c5
> Try again to solve remaining TeamCity errors (#4206)

- .github/workflows/CI.yaml
- build.gradle
- docs/antora/publish.yml
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- docs/build.gradle
- extended/build.gradle
- extra-dependencies/build.gradle
- readme.adoc
> Release 5.25.0 (#3962) (#4202)

- .gitmodules
> Update submodule to 5.25

- docs/asciidoc/modules/ROOT/pages/ml/openai.adoc
- full/src/main/resources/extended.txt
- full/src/test/java/apoc/ml/PromptIT.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/1081238c535519507455c2a41e552d662d688538
> [NOID] Fixes #4004: Given (a set of) queries return the schema + explanation of the subgraph (#4065)

- core/src/main/java/apoc/ApocConfig.java
- docs/asciidoc/modules/ROOT/pages/ml/openai.adoc
- full/src/main/java/apoc/ml/OpenAI.java
- full/src/main/java/apoc/ml/OpenAIRequestHandler.java
- full/src/test/java/apoc/ml/OpenAIAzureIT.java
- full/src/test/java/apoc/ml/OpenAITestResultUtils.java
Fixes #3634
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/db102bd6c8054b1032fcd63b7f1e7a89fe28b5cf
> [NOID] Fixes #3634: Updated ML procs for Azure OpenAI services (#3850)

- docs/asciidoc/modules/ROOT/partials/xls-dependencies.adoc
- extended/build.gradle
- extended/src/main/java/apoc/agg/Rollup.java
- extended/src/main/java/apoc/coll/CollExtended.java
- extended/src/main/java/apoc/dv/VirtualizedResource.java
- extended/src/main/java/apoc/export/xls/ExportXlsHandler.java
- extended/src/main/java/apoc/util/ExtendedListUtils.java
- extended/src/main/java/apoc/util/ExtendedMapUtils.java
- extended/src/main/java/apoc/uuid/UuidHandler.java
- extended/src/main/java/apoc/vectordb/ChromaDb.java
- extended/src/main/java/apoc/vectordb/VectorDb.java
- extended/src/main/java/apoc/vectordb/VectorDbUtil.java
- extra-dependencies/xls/build.gradle
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/fcbdae96110fbadee2561d1df7310aca3c7cd697
> Fixes #4108: Remove org.apache.commons.collections* imports (#4129)

- full-it/src/test/java/apoc/full/it/vectordb/ChromaDbTest.java
- full-it/src/test/java/apoc/full/it/vectordb/QdrantTest.java
Cherry pick changes to try to get these tests working in TC
> [NOID] Try a different host for QdrantDb and ChromaDb tests

- full-it/src/test/java/apoc/full/it/vectordb/WeaviateTest.java
- full/src/main/java/apoc/vectordb/VectorDb.java
- full/src/main/java/apoc/vectordb/VectorDbUtil.java
Fixes #4232
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/b7697f400b55c83e3319ce58a1767944e11f726c
> [NOID] Fixes #4232: The apoc.vectordb.configure(WEAVIATE', ..) procedure should append /v1 to url (#4248)

- .github/workflows/CI.yaml
- .gitmodules
- extended/src/main/java/apoc/ExtendedApocGlobalComponents.java
Cherry-pick: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4278
> Dev fix for procedure handlers

- .github/workflows/CI.yaml
- docs/antora/publish.yml
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- docs/build.gradle
- extended/build.gradle
- extra-dependencies/build.gradle
- readme.adoc
> Release 5.26.0 (#3962) (#4202) (#4214)

- extended-it/src/test/java/apoc/vectordb/WeaviateTest.java
- extended/src/main/java/apoc/vectordb/Weaviate.java
Fixes #4233
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/e70fcd6dacef33ed92cffc557b240ab0e49a1757
> Fixes #4233: Improve Weaviate error handling (#4239)

- docs/asciidoc/modules/ROOT/nav.adoc
- docs/asciidoc/modules/ROOT/pages/export/arrow.adoc
- docs/asciidoc/modules/ROOT/pages/export/index.adoc
- docs/asciidoc/modules/ROOT/pages/import/arrow.adoc
- docs/asciidoc/modules/ROOT/pages/import/index.adoc
- docs/asciidoc/modules/ROOT/pages/import/load-json.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.export/apoc.export.arrow.all.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.export/apoc.export.arrow.graph.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.export/apoc.export.arrow.query.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.export/apoc.export.arrow.stream.all.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.export/apoc.export.arrow.stream.graph.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.export/apoc.export.arrow.stream.query.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.import/apoc.import.arrow.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.load/apoc.load.arrow.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.load/apoc.load.arrow.stream.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.export.arrow.all.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.export.arrow.graph.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.export.arrow.query.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.export.arrow.stream.all.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.export.arrow.stream.graph.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.export.arrow.stream.query.adoc
- docs/asciidoc/modules/ROOT/partials/usage/apoc.load.jsonParams.adoc
- extended/src/main/java/apoc/export/arrow/ImportArrow.java
- extended/src/main/java/apoc/load/arrow/LoadArrowExtended.java
Fixes #4253
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/00d75d32d11e512397e3fe556e39f7c743f49dfa
> Fixes #4253: Missing apache arrow/jsonParams documentation (#4255)

- docs/asciidoc/modules/ROOT/pages/ml/openai.adoc
- extended/src/main/java/apoc/ml/MLUtil.java
- extended/src/main/java/apoc/ml/OpenAI.java
- extended/src/test/java/apoc/ml/MLTestUtil.java
- extended/src/test/java/apoc/ml/OpenAIIT.java
Fixes #4156
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/d6b31c3017656306f01060d038af7deda36e3134
> Fixes #4156: Improves handling of empty or blank input for openai procedures (#4228)

- extended-it/src/test/java/apoc/vectordb/WeaviateTest.java
- extended/src/main/java/apoc/vectordb/VectorDb.java
- extended/src/main/java/apoc/vectordb/VectorDbUtil.java
Fixes #4232
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/b7697f400b55c83e3319ce58a1767944e11f726c
> Fixes #4232: The apoc.vectordb.configure(WEAVIATE', ..) procedure should append /v1 to url (#4248)

- docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/pinecone.adoc
- extended/src/main/java/apoc/vectordb/Pinecone.java
- extended/src/main/java/apoc/vectordb/PineconeHandler.java
- extended/src/main/java/apoc/vectordb/VectorDbUtil.java
- extended/src/main/java/apoc/vectordb/VectorEmbeddingHandler.java
- extended/src/test/java/apoc/vectordb/PineconeTest.java
Fixes #4242
Cherry-pick b24d7746e41673d81fb698cc16a45a9793419817
> Fixes #4242: The Pinecone APOC implementation is misleading (#4250)

- extended/build.gradle
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/8223e27938431a19d8027e011d774e30a7e4301d
> Fix another unresolved imports with IntelliJ 2024.1+ (#4249)

- extended-it/src/test/java/apoc/monitor/StoreInfoProcedureEnterpriseTest.java
- extended/src/main/java/apoc/monitor/Store.java
Fixes #4197
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/8f4b277b87ad7c35d58bcdc713e8f71fb7111a96
> Fixes #4197: apoc.monitor.store fails for block stores (#4223)

- docs/asciidoc/modules/ROOT/pages/overview/apoc.dv/apoc.dv.queryAndLink.adoc
- docs/asciidoc/modules/ROOT/pages/virtual-resource/index.adoc
- extended-it/src/test/java/apoc/dv/DataVirtualizationCatalogTest.java
- extended-it/src/test/java/apoc/dv/DataVirtualizationCatalogTestUtil.java
- extended/src/main/java/apoc/dv/DataVirtualizationCatalog.java
Fixes #4157
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/4e2f977b6ab24d872442febb437058c9fc4729c3
> Fixes #4157: apoc.dv.queryAndLink how to specify direction (#4222)

- docs/asciidoc/modules/ROOT/pages/ml/openai.adoc
- extended/src/main/java/apoc/ml/OpenAI.java
- extended/src/main/java/apoc/util/ExtendedUtil.java
- extended/src/test/java/apoc/util/ExtendedUtilTest.java
Fixes #4153
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/5da811311cc086cc729c5221cb6e4e0d1ea5a5ee
> Fixes #4153: Handling OpenAI 429's gracefully (#4284)

- extended/src/main/java/apoc/ml/OpenAI.java
- extended/src/main/java/apoc/util/ExtendedMapUtils.java
Removed org.apache.commons.collections from OpenAI
Otherwise the following error could be thrown
```
java.lang.ClassNotFoundException: org.apache.commons.collections.MapUtils
```
> Removed org.apache.commons.collections from OpenAI

- extended-it/src/test/java/apoc/util/WeaviateTestUtil.java
- extended-it/src/test/java/apoc/vectordb/WeaviateEnterpriseTest.java
- extended-it/src/test/java/apoc/vectordb/WeaviateTest.java
- extended/src/main/java/apoc/ml/OpenAI.java
- extended/src/main/java/apoc/util/ExtendedMapUtils.java
- extended/src/main/java/apoc/vectordb/VectorDbUtil.java
- extended/src/test/java/apoc/vectordb/VectorDbTestUtil.java
Fixes #4245
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/db54aa4a5bdc26be8d511962a6853a60fb48b90b
> Fixes #4245: Add integration test to check that apache.commons.collections is not present anymore (#4279)

- extended/src/main/java/apoc/ml/OpenAI.java
- extended/src/main/java/apoc/util/ExtendedMapUtils.java
Reverts neo4j-contrib/neo4j-apoc-procedures#4304
> Revert "Removed org.apache.commons.collections from OpenAI"

- LICENSES.txt
- NOTICE.txt
- full/src/main/java/apoc/agg/MultiStats.java
Regenerate license via `./gradlew generateLicensesFiles`
> [NOID] test license

- extended-it/src/test/java/apoc/vectordb/QdrantTest.java
- extended/src/test/java/apoc/load/LoadCsvTest.java
- extended/src/test/java/apoc/ml/WatsonTest.java
- extended/src/test/java/apoc/util/ExtendedTestUtil.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/c686650295ff9de91d5f6de9ebf22eaa2299cebe
> Try solving TeamCity errors in 5.26 (#4220)

- LICENSES.txt
- NOTICE.txt
- build.gradle
- docs/asciidoc/antora.yml
- extra-dependencies/build.gradle
- readme.adoc
> [NOID] Neo4j 4.4.0.41, APOC 4.4.35

- docs/asciidoc/modules/ROOT/pages/overview/apoc.dv/apoc.dv.queryAndLink.adoc
- docs/asciidoc/modules/ROOT/pages/virtual-resource/index.adoc
- full/src/main/java/apoc/dv/DataVirtualizationCatalog.java
- full/src/test/java/apoc/dv/DataVirtualizationCatalogTest.java
- full/src/test/java/apoc/dv/DataVirtualizationCatalogTestUtil.java
Fixes #4157
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/4e2f977b6ab24d872442febb437058c9fc4729c3
> [NOID] Fixes #4157: apoc.dv.queryAndLink how to specify direction (#4222)

- docs/asciidoc/modules/ROOT/nav.adoc
- docs/asciidoc/modules/ROOT/pages/export/arrow.adoc
- docs/asciidoc/modules/ROOT/pages/export/index.adoc
- docs/asciidoc/modules/ROOT/pages/import/arrow.adoc
- docs/asciidoc/modules/ROOT/pages/import/index.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.export/apoc.export.arrow.all.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.export/apoc.export.arrow.graph.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.export/apoc.export.arrow.query.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.export/apoc.export.arrow.stream.all.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.export/apoc.export.arrow.stream.graph.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.export/apoc.export.arrow.stream.query.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.import/apoc.import.arrow.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.load/apoc.load.arrow.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.load/apoc.load.arrow.stream.adoc
Fixes #4253
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/00d75d32d11e512397e3fe556e39f7c743f49dfa
> [NOID] Fixes #4253: Missing apache arrow/jsonParams documentation (#4255)

- docs/asciidoc/modules/ROOT/pages/ml/openai.adoc
- full/src/main/java/apoc/ml/OpenAI.java
- full/src/main/java/apoc/util/ExtendedUtil.java
- full/src/test/java/apoc/util/ExtendedUtilTest.java
Fixes #4153
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/5da811311cc086cc729c5221cb6e4e0d1ea5a5ee
> [NOID] Fixes #4153: Handling OpenAI 429's gracefully (#4284)

- .github/actions/test-gradle-project/action.yaml
- .github/workflows/CI.yaml
CodeQL update
Note: This is failing on pulling the docker containers, I assume there is a pw issue or something, but the thing I changed is green :) and this shouldn't have any impact on the tests
> [NOID] Update codeql

- .github/workflows/CI.yaml
- .gitmodules
- docs/antora/publish.yml
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- docs/build.gradle
- extended/build.gradle
- extra-dependencies/build.gradle
> Release 2025.1.0 (#3962) (#4214) (#4285)

- .github/actions/test-gradle-project/action.yml
- .github/workflows/CI.yaml
- build.gradle
To solve the error https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/13198344396/job/36844534370#step:10:3
- Update upload artifact action to solve this error.
---
To solve the error https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/13182214745/job/36795587863#step:11:158
- Added the codeql change implemented [here in Core](https://github.com/neo4j/apoc/commit/e9e7f8f2a68e25812bf56a08d157fd032780e247)
- Added the NEO4J_VERSION_CI change implemented [here in Core](https://github.com/neo4j/apoc/commit/ceaee1b6dbdedb6a09a045fb51ba6a5d0ede9027)
- Added if clause, to assign it to `$neo4j_version_base` if is null or undefined
- Bump version to `2025.02.0`, consistent to Core
> Upgrade upload-artifact version

- extended-it/src/test/java/apoc/neo4j/docker/StartupExtendedTest.java
Fixes #4262
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/aa961c8f8962de413ccaacdd67ae4b2f66c4fc8f
> Fixes #4262: Add startup test for SLF4J (#4308)

- docs/asciidoc/modules/ROOT/pages/ml/genai.adoc
- extended/src/main/java/apoc/ml/Prompt.java
- extended/src/main/java/apoc/util/ExtendedUtil.java
- extended/src/test/java/apoc/ml/PromptIT.java
- extended/src/test/resources/northwind_dataset.cypher
- extended/src/test/resources/northwind_schema.cypher
Fixes #4000
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/e70fc2f9727ba3ba728401c0fb298cba4e4abaa1
> Fixes #4000: Add self-explanation to the model, include the verbal schema description to the flow (#4144)

- extended-it/src/test/java/apoc/neo4j/docker/MetricsTest.java
- extended/src/main/java/apoc/metrics/Metrics.java
Fixes #4355
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4357
> Fixes #4355: The apoc.metrics.get throws an URLAccessChecker error (#4357)

- .github/actions/setup-gradle-cache/action.yaml
- .github/workflows/CI.yaml
Fix CI - update cache version (#4349)
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/1be0f4a8e56f694a7fef1fe7441805d3b727ce3c
> Fix CI - update cache version (#4349)

- docs/asciidoc/modules/ROOT/pages/overview/apoc.create/apoc.create.virtual.fromNodeExtended.adoc
- docs/asciidoc/modules/ROOT/pages/virtual-nodes-and-relationships/index.adoc
- extended/src/main/java/apoc/create/CreateExtended.java
- extended/src/main/resources/extendedCypher25.txt
- extended/src/main/resources/extendedCypher5.txt
- extended/src/test/java/apoc/create/CreateExtendedTest.java
> Fixes #2181: extend apoc.create.virtual.fromNode(node,[propertyNames]) to add new virtual properties

- docs/asciidoc/modules/ROOT/pages/database-integration/load-jdbc.adoc
- extended/src/main/java/apoc/load/jdbc/Analytics.java
- extended/src/main/java/apoc/load/util/JdbcUtil.java
- extended/src/main/java/apoc/util/ExtendedUtil.java
- extended/src/test/java/apoc/load/jdbc/DuckDBJdbcPerformanceTest.java
- extended/src/test/java/apoc/load/jdbc/DuckDBJdbcTest.java
Fixes #4337
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/aa26ba2b9afb7e8be88dc8b14500d180ae9c0c87
> Fixes #4337: Improvements for apoc.agg.analytics (#4359)

- extended-it/src/test/java/apoc/mongodb/MongoTest.java
- extended-it/src/test/java/apoc/mongodb/MongoTestBase.java
Try fixing flaky MongoDb TeamCity tests 2025.01 (#4372)
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/2c82f3fc24468d49dea822d565a32d9fda6b4417
> Try fixing flaky MongoDb TeamCity tests 2025.01 (#4372)

- extended/src/test/kotlin/apoc/nlp/aws/AWSProceduresAPIWithDummyClientTest.kt
- extended/src/test/kotlin/apoc/nlp/azure/AzureProceduresAPIWithDummyClientTest.kt
- extended/src/test/kotlin/apoc/nlp/gcp/GCPProceduresAPIWithDummyClientTest.kt
Fixes https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/4378
> De-ignore *APIWithDummyClientTests

- .github/workflows/CI.yaml
- .gitmodules
- docs/antora/publish.yml
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- docs/build.gradle
- extended-it/src/test/java/apoc/s3/LoadS3MinioTest.java
- extended/build.gradle
- extra-dependencies/build.gradle
> Release 2025.03.0 (#4385)

- build.gradle
- extended/src/main/java/apoc/custom/CustomProcedureInfo.java
- readme.adoc
Bump Neo4j 2025.04.0
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4383
> Bump and fix Neo4j 2025.04.0 CI errors

- .github/workflows/CI.yaml
- .gitmodules
- docs/antora/publish.yml
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- docs/build.gradle
- extended-it/src/test/java/apoc/s3/LoadS3MinioTest.java
- extended/build.gradle
- extra-dependencies/build.gradle
> Release 2025.04.0

- docs/asciidoc/modules/ROOT/nav.adoc
- docs/asciidoc/modules/ROOT/pages/import/index.adoc
- docs/asciidoc/modules/ROOT/pages/import/load-partial.adoc
- extended-it/src/test/java/apoc/azure/LoadAzureStorageTest.java
- extended-it/src/test/java/apoc/gc/LoadGoogleCloudStorageTest.java
- extended-it/src/test/java/apoc/neo4j/docker/BoltTest.java
- extended-it/src/test/java/apoc/s3/LoadS3Test.java
- extended/src/main/java/apoc/load/partial/LoadPartial.java
- extended/src/main/java/apoc/load/partial/LoadPartialAws.java
- extended/src/main/java/apoc/load/partial/LoadPartialConfig.java
- extended/src/main/resources/extended.txt
- extended/src/test/java/apoc/export/ExportExtendedSecurityTest.java
- extended/src/test/java/apoc/load/LoadHdfsTest.java
- extended/src/test/java/apoc/load/partial/LoadPartialTest.java
- extended/src/test/java/apoc/ml/OpenAITest.java
Fixes #1796
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/14b7d0699d64ae49c85d043fb70864bf7771e7d9
> Fixes #1796: procedure/function to provide an URL + indexed String or json object (#4375)

- docs/asciidoc/modules/ROOT/pages/cypher-execution/cypher-based-procedures-functions.adoc
- docs/asciidoc/modules/ROOT/pages/database-integration/load-jdbc.adoc
- extended-it/src/test/java/apoc/neo4j/docker/BoltTest.java
- extended-it/src/test/java/apoc/s3/LoadS3MinioTest.java
- extended/src/main/java/apoc/custom/CypherNewProcedures.java
- extended/src/main/java/apoc/custom/CypherProcedures.java
- extended/src/main/java/apoc/custom/CypherProceduresHandler.java
- extended/src/main/java/apoc/custom/CypherProceduresUtil.java
- extended/src/main/java/apoc/load/jdbc/Analytics.java
- extended/src/main/java/apoc/load/util/JdbcUtil.java
- extended/src/main/java/apoc/util/ExtendedUtil.java
- extended/src/test/java/apoc/custom/CypherNewProceduresTest.java
- extended/src/test/java/apoc/load/jdbc/DuckDBJdbcPerformanceTest.java
- extended/src/test/java/apoc/load/jdbc/DuckDBJdbcTest.java
Fixes https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1431
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/d4315f2f762e5b7a528d4cf07caaa8b39f5d2630
> Fixes #1431: Disable custom procedure config (#4386)

- docs/asciidoc/modules/ROOT/pages/database-integration/load-jdbc.adoc
- extended-it/src/test/java/apoc/neo4j/docker/BoltTest.java
- extended-it/src/test/java/apoc/s3/LoadS3MinioTest.java
- extended/src/main/java/apoc/load/jdbc/Analytics.java
- extended/src/main/java/apoc/load/util/JdbcUtil.java
- extended/src/main/java/apoc/util/ExtendedUtil.java
- extended/src/test/java/apoc/load/jdbc/DuckDBJdbcPerformanceTest.java
- extended/src/test/java/apoc/load/jdbc/DuckDBJdbcTest.java
- extended/src/test/java/apoc/load/util/JdbcUtilTest.java
Fixes #4396
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/0a0b88ec2e36a51f618fea9240d337eae4cc483f
> Fixes #4396: The JdbcUtil.obfuscateJdbcUrl doens't work for Oracle JDBC URLs (#4397)

- docs/antora/preview.yml
- docs/antora/publish.yml
- docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/weaviate.adoc
- docs/asciidoc/modules/ROOT/pages/ml/vertexai.adoc
- docs/asciidoc/modules/ROOT/pages/overview/apoc.uuid/index.adoc
Created PR that encloses some PRs that is no longer valid because it is not on dev as a branch base
- cherry-pick and fix of https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3825
- cherry-pick of https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4105
- cherry-pick of https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4164
- cherry-pick of https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3822
> Docs fixes unused branches

- docs/antora/package-lock.json
- docs/antora/package.json
- https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4210/
- https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4195
- https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4189/
- https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4188/
- https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4104/
- https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4280
> [NOID] 4.4 cherry-picks of dependabots PRs

- build.gradle
- readme.adoc
> [NOID] Bump Neo 4.4

- docs/asciidoc/antora.yml
> Bump antora yml

- extended/src/main/java/apoc/bolt/BoltConnection.java
Fix BoltConnection with release 5.26.1
Same as https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4436 for 5.26 branch
> Fix BoltConnection with release 5.26.1

- .github/workflows/CI.yaml
- .gitmodules
- build.gradle
- docs/antora/publish.yml
- docs/asciidoc/antora.yml
- docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc
- docs/build.gradle
- extended/build.gradle
- extra-dependencies/build.gradle
- readme.adoc
> Release 2025.07.0 (#4385) (#4401)

- extended-it/src/test/java/apoc/neo4j/docker/CustomNewProcedureMultiDbTest.java
- extended/src/main/java/apoc/custom/CypherProceduresHandler.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/c67ccaa0a2248905d2b0bd8c5ba7f3e0315c702e
> Fixes #4382: apoc custom function working in a different database than the one it was installed (#4392)
