neo4j-contrib/neo4j-apoc-procedures

databases.xml, src/main/java/apoc/load/Xml.java, src/test/java/apoc/util/XmlTest.java
This is to deal with the case when the text of an element contains the ampersand character.
Without this option when the parser finds and ampersand, it splits the text content into multiple processing events.
=> set isCoalescing property on XMLInputFactory in load.xml proc

src/main/java/apoc/help/Help.java, src/main/java/apoc/help/HelpScanner.java
**Use the class's own ClassLoader to find the apoc jar file**
>When using thread's context class loader, it is not guaranteed to find the apoc jar. When using the class's own class loader, it is guaranteed, since this class comes from apoc jar itself.
>This ensures the help system always works.
**Enhance help to search whole procedure name, and be case insensitive**
>The original search was too restrictive as it only checked the beginning and end of the string, and moreover it was case sensitive. This makes the search more lenient by allowing one to search anywhere within the procedure name, and also ignores the case of the search terms.
>This gives more relevant results, such as searching for all procedures related to "meta" or getting information about "apoc.meta.subGraph" when …
=> Fix the Help System

src/main/java/apoc/algo/pagerank/NodeCounter.java
runtime=compiled option was removed in Neo4j 3.0.3 and using
this results in a Cypher syntax error
=> Remove runtime=compiled in NodeCounter Cypher statement

src/main/java/apoc/text/Strings.java, src/test/java/apoc/text/StringCleanTest.java, src/test/java/apoc/text/StringsTest.java
=> neo4j-apoc-procedures-78 `apoc.text.clean` should not clean umlauts

src/test/java/apoc/export/ExportTest.java
=> Replaced hard-coded EoL characters (unix only) with lineSeparator() call

src/main/java/apoc/schema/Properties.java, src/main/java/org/neo4j/kernel/api/impl/schema/reader/SortedIndexReader.java, src/test/java/apoc/schema/DistinctPropertiesTest.java
Leverages lucene index to get the indexed terms, as a replacement for queries such as:
`MATCH (c:Customer) RETURN DISTINCT c.ethnicity;`
=> adding schema.properties.distinct

src/main/java/apoc/algo/PageRank.java, src/main/java/apoc/algo/pagerank/PageRankArrayStorageParallelCypher.java, src/test/java/apoc/algo/PageRankTest.java
We are now stored the chunk starting index and using this. Computation time has really by this.
We are now not assuming that the relationships should be sorted on the basis of source index.
Future work:
- Executing the second cypher query in parallel to the first one making sure that the first one is processed completely before we begin processing the second one.
=> Pagerank optimizations for computation time.

build.gradle, src/main/java/apoc/warmup/Warmup.java, src/test/java/apoc/warmup/WarmupTest.java
As reported in #131, instead of the node (or relationship) count, the maximum id needs to be used to try and load all pages: if some data has been deleted, the id space will be sparsed instead of sequential, and the count less than the actual maximum id.
I've also set the locale for the tests in the Gradle configuration, as some tests would fail on my machine due to number formats being different that the asserted ones using the French locale.
=> Use their max ids to warm up all the nodes/rels

src/main/java/apoc/Pools.java, src/main/java/apoc/algo/Algorithm.java, src/main/java/apoc/algo/Centrality.java, src/main/java/apoc/algo/PageRank.java, src/main/java/apoc/algo/algorithms/AlgoUtils.java, src/main/java/apoc/algo/algorithms/Algorithm.java, src/main/java/apoc/algo/algorithms/AlgorithmInterface.java, src/main/java/apoc/algo/algorithms/BetweennessCentrality.java, src/main/java/apoc/algo/pagerank/PageRank.java, src/main/java/apoc/algo/pagerank/PageRankAlgorithm.java, src/main/java/apoc/algo/pagerank/PageRankArrayStorageParallelCypher.java, src/main/java/apoc/algo/pagerank/PageRankUtils.java, src/test/java/apoc/algo/CentralityTest.java
This pull requests add unweighted betweenness centrality.
Similar to  pagerank, we take nodeCypher and relCypher and store them in local Ds.
Using the stored locations, we calculate the betweenness centrality in parallel. Computation and memory perf are good as compared to iGraph. Example, for a graph that took ~one day in igraph,we were able to do that in approximately 75 minutes.
I've used double array for precision to store the results.
I think memory can be improved some more.
=> Adding Unweighted Betweenness Centrality

docs/periodic.adoc
Updated apoc.periodic.iterate example. Fixed the example as there was a small bug in it. 
In the second statement need to treat `p` as a parameter so had to add the following. 
`with {p} as p ...`. 
Same thing for the other example as well.  
I have tested this and it works.
=> Updated apoc.periodic.iterate example.

src/main/java/apoc/index/FreeTextSearch.java, src/main/java/apoc/index/analyzer/DynamicChainAnalyzer.java, src/test/java/apoc/index/FreeTextSearchTest.java
e.g.
`CALL apoc.index.addAllNodes('name',{ Supplier: ["companyName", "description","address"], Product:  ["productName","address"] }, {to_lower_case: false, analyzer: "org.apache.lucene.analysis.core.WhitespaceAnalyzer", autoUpdate: true, queue: "asciifolding" } )`
Next steps: Add to trigger if autoUpdate is true, @sarmbruster had some ideas about this queue stuff.
=> Additional option parameters for apoc.index.addAllNodes

docs/index.html, docs/loadxml.adoc, src/main/java/apoc/load/Xml.java, src/test/java/apoc/load/XmlTest.java, src/test/resources/mixedcontent.xml
* deal gracefully with xml mixed content
* refactoring
=> fixes #256

docs/datetime.adoc, docs/overview.adoc, src/main/java/apoc/date/Date.java, src/test/java/apoc/date/DateTest.java
This fulfills the feature request in #289.
=> Added apoc.date.convert() and apoc.date.add()

docs/expand.adoc, docs/overview.adoc, src/main/java/apoc/algo/Cover.java, src/main/java/apoc/path/PathExplorer.java, src/test/java/apoc/path/SubgraphTest.java
Also added a static Cover.cover() method for internal usage, and updated path expander documentation.
This replaces PR #279, switching to base on APOC 3.1 branch.
This fulfills feature requests #273 #274 and #275.
=> Added new apoc.path procedures: subgraphNodes(), subgraphAll(), and spanningTree()

docs/overview.adoc, src/main/java/apoc/coll/Coll.java, src/test/java/apoc/coll/CollTest.java
This fulfills feature request #298
=> Added new functions to apoc.coll - containsDuplicates(), duplicates(), duplicatesWithCount(), and occurrences()

docs/expand.adoc, docs/overview.adoc, src/main/java/apoc/path/PathExplorer.java, src/test/java/apoc/path/ExpandPathTest.java
(and all procedures using the config map). Default is false for versions < 3.2.x.x.
=> Added 'filterStartNode' config parameter to expandConfig()

docs/expand.adoc, docs/overview.adoc, src/main/java/apoc/path/PathExplorer.java, src/test/java/apoc/path/ExpandPathTest.java
Also cleaned up and clarified docuementation regarding label filters (only one operation allowed) and the termination filter behavior.
This fulfills feature request #324
=> Add limit config parameter to expand path config

docs/expand.adoc, docs/overview.adoc, src/main/java/apoc/path/PathExplorer.java, src/test/java/apoc/path/ExpandPathTest.java
The new operator, `>`, works just like the termination operator `/` in that labels in the filter will be used as end nodes in the expansion, except traversal is allowed past these end nodes.
The new `limit` config parameter applies when using this filter.
=> Add end node operator to path expander label filter

docs/overview.adoc, src/main/java/apoc/coll/Coll.java, src/test/java/apoc/coll/CollTest.java
Also tightened null and empty list handling on newer collection functions.
This fulfills feature request #322
=> Add apoc.coll.reverse() 

src/main/java/apoc/data/Extract.java, src/test/java/apoc/data/ExtractTest.java
Fixes bug #250, but may alter behavior when run on URLs with an @ in the query string which shouldn't be picked up as the domain (if the domain part of an embedded email address, for example, is the last part of the query string, or immediately precedes a split delimiter)
=> Fixed apoc.data.domain() when there are .'s before the @ symbol

docs/expand.adoc, docs/overview.adoc, src/main/java/apoc/path/PathExplorer.java, src/test/java/apoc/path/ExpandPathTest.java
This implements proposed order 1 operator precedence from #317, including the adjustment on evaluation for the end node filter which first checks if the a label is in the whitelist before an INCLUDE_AND_CONTINUE, to avoid including paths to further end nodes which inadvertently include a node that violates the whitelist.
See included test cases for examples of operator precedence.
Please don't approve pull request yet, documentation is not yet included.
Documentation will come in a later commit, as I'd like to get some feedback and confirmation on the implementation first.
=> Allow all labelFilter operations in path expander procedures

docs/elasticsearch.adoc, src/test/java/apoc/es/ElasticSearchTest.java
use parameters so that queries are easier to read fixes #345
=> use parameters so that queries are easier to read fixes #345

src/main/java/apoc/algo/LabelPropagation.java, src/main/java/apoc/algo/Pregel.java, src/main/java/apoc/algo/algorithms/AlgoUtils.java, src/main/java/apoc/algo/pagerank/BatchRunnable.java, src/main/java/apoc/util/Util.java, src/main/java/apoc/warmup/Warmup.java
In Utils class is now available a method to check if a transaction is terminated or not.
The following classes were fixed according to this new method:
- Warmup
- Pregel 
- LabelPropagation
- AlgoUtils
- BatchRunnable
All the methods that expect a return value are provided with a default one
We should check all the other packages in order to normalize the transaction checking with only one method
=> Util method for transaction termination checking (algo and warmup) fixes #211

docs/overview.adoc, src/main/java/apoc/refactor/rename/Rename.java, src/test/java/apoc/refactor/rename/RenameTest.java
Indexes and constraints are managed, legacy indexes are not
=> Fixes #302 - procedure to rename property, rename label, rename reltype

src/main/java/apoc/path/PathExplorer.java, src/test/java/apoc/path/ExpandPathTest.java
=> Prevent path expander termination filter from filtering below minLevel

src/main/java/apoc/export/cypher/ExportCypher.java, src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java, src/main/java/apoc/export/util/ExportConfig.java, src/test/java/apoc/export/cypher/ExportCypherTest.java
Given a full path file name like /tmp/myexport.cypher this method will create:
1. /tmp/myexport.schema.cypher
2. /tmp/myexport.nodes.cypher
3. /tmp/myexport.relationships.cypher
We need to consider to normalize the export like the import. We can pass an URI that will be normalized to an export directory.
=> export now creates 3 different files fixes #270

src/main/java/apoc/date/Date.java, src/test/java/apoc/date/DateTest.java
Fulfills change request #392.
If there's a good reason for the restriction that I've overlooked, please reject the PR.
=> Allowed negative time parameter to apoc.date.format()

docs/overview.adoc
@jexp `silent` and `quotes` params are never used
=> fixes #252 - docs should explain export config

docs/datetime.adoc, docs/extract.adoc, docs/functions.adoc, docs/number.adoc, docs/overview.adoc, docs/spatial.adoc
We don't found some procedures/functions, so we deleted them from documentation.
apoc.number.format.lang
apoc.number.format.pattern
apoc.number.format.pattern.lang
apoc.number.parseInt.pattern
apoc.number.parseInt.lang
apoc.number.parseInt.pattern.lang
apoc.number.parseFloat.pattern
apoc.number.parseFloat.lang
apoc.number.parseFloat.pattern.lang
apoc.date.formatDefault
apoc.date.parseDefault
apoc.date.formatTimeZone
apoc.date.fieldsFormatted
apoc.date.fieldsDefault
=> fixes #391 - Update documentation for procedures that have converted to functions

src/main/java/apoc/index/FreeTextSearch.java, src/main/java/apoc/index/FulltextIndex.java, src/main/java/apoc/index/IndexUpdateTransactionEventHandler.java, src/main/java/org/neo4j/kernel/KernelApi.java, src/test/java/apoc/util/UtilTest.java
`apoc.index.forRelationships` and `apoc.index.forNodes` are gets or create so we cannot transform it into read only operations. We can split it into two different procedure, get and create or leave it like this.
Using the method `relationshipLegacyIndexQuery` of `ReadOperation` :
`relationshipLegacyIndexQuery(indexName, query, startingNode, endingNode)`
if we pass `null` on the `endNode` parameter (that we transform in **-1** to ignore the parameter), we have an unexpected behavior. For example if we test `apoc.index.out` (see `testOut)` we have the same result as the incoming (`apoc.index.in`).
We have this problem only if we pass **-1** as parameter, for every other number it works.  If we pass **-1**  on startingNode it works. It seems a bug
=> Fixes #334 - make sure that manual index operations are read-only

src/main/java/apoc/trigger/Trigger.java
Added suggested changes, we have opened an issue #433 to handle the update on  `phase: after`, when the transaction is already been committed. Now we add some comments in the issue.
=> Fixes #395 - Apoc.trigger.propertiesByKey adding a dynamic label based on newValue vs oldValue does not work

src/main/java/apoc/couchbase/Couchbase.java, src/main/java/apoc/load/Jdbc.java, src/main/java/apoc/mongodb/MongoDB.java, src/main/java/apoc/util/MissingDependencyException.java, src/test/java/apoc/couchbase/CouchbaseTest.java
@jexp for jdbc we have already an error who specifies that driver is missing.
If you want, we can create a map that specifies the drive to be inserted into the plugin folder (Oracle, Derby...).
=> fixes #430 - Better error messages when missing drivers

src/main/java/apoc/periodic/Periodic.java
The goal here is simple: to be able to YIELD failedBatches instead of having code w/ a typo.
=> #469 - fixing type in RundownResult that impact YIELD reliance

src/main/java/apoc/refactor/GraphRefactoring.java, src/test/java/apoc/refactor/GraphRefactoringTest.java
When the source node has ingoing relationships, the merged node should have them as ingoing relationhips as well.
=> Fixing nodes merge only create outgoing relationships

docs/overview.adoc, src/main/java/apoc/meta/Meta.java, src/test/java/apoc/meta/MetaTest.java
to introduce this new apoc, we reuse the existing `MetaData` container plus `MetaStats`  and we just transform it into the agreed map with a couple of private methods.
=> fixes #384 - add a apoc.meta.schema procedure

docs/overview.adoc, src/main/java/apoc/convert/Json.java, src/main/java/apoc/map/Maps.java, src/test/java/apoc/convert/ConvertJsonTest.java, src/test/java/apoc/map/MapsTest.java
Added apoc.convert.toSortedJsonMap(), and apoc.map.sortedProperties(), which return map representations (with lists, in the case of apoc.map.sortedProperties()) with properties sorted alphabetically, with optional case sensitivity.
=> Sorted map properties

build.gradle, docs/fulltext.adoc, docs/jmh.adoc, src/jmh/java/apoc/AsyncIndexingGraphDatabaseState.java, src/jmh/java/apoc/GraphDatabaseState.java, src/jmh/java/apoc/IndexTrackingGraphDatabaseState.java, src/jmh/java/apoc/IndexUpdateBenchmarks.java, src/jmh/java/apoc/SyncIndexingGraphDatabaseState.java, src/main/java/apoc/index/IndexUpdateTransactionEventHandler.java
I've added JMH library to run micro benchmarks. Note that JMH is not enabled by default, you need to run `./gradlew jmh` for this.
Additionally this PR adds more config options for index population. 
Related to #329.
This PR should be cherry-picked to 3.2 branch as well.
=> add jmh for performance testing and improvements for background index population

src/main/java/apoc/merge/Merge.java, src/main/java/apoc/util/Util.java, src/test/java/apoc/merge/MergeTest.java, src/test/java/apoc/util/UtilTest.java
We already have `apoc.create.node|relationship` to deal with dynamic relationship types or labels. These two new procedures do the very same for `merge`. In the implementation I'm assembling a Cypher `merge` statement.
This PR should be cherry-picked to 3.2 branch as well.
=> adding apoc.merge.node/relationship

src/main/java/apoc/index/FreeTextSearch.java, src/test/java/apoc/index/FreeTextSearchTest.java
adding an optional parameter to apoc.index.search to control max number of results. Defaults to 100 for backwards compatibility. -1 doesn't limit and returns all the results.
=> fixes #512

src/main/java/apoc/convert/Convert.java, src/test/java/apoc/convert/ConvertTest.java
When passing in a Node or Relationship, a map containing its properties is returned.
=> improving apoc.convert.toMap to support Node/Relationship

docs/text.adoc, src/main/java/apoc/text/Strings.java, src/test/java/apoc/text/StringsTest.java
I've Implemented the apoc.text.split function from the https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/502 issue. Is the null handling as expected or should it return an empty list instead of null?
=> add apoc.text.split function that splits a string using a regexp (#502)

build.gradle, docs/overview.adoc, src/main/java/apoc/mongodb/MongoDB.java, src/main/java/apoc/mongodb/MongoDBColl.java, src/main/java/apoc/trigger/Trigger.java, src/test/java/apoc/mongodb/MongoDBTest.java
For all procedures that are related to document retrieval from MongoDB there is a new (boolean) parameter enabling/disabling automatic conversion in order to avoid exception for non-packable values
=> Compatible values flag for non-packable values

build.gradle, docs/loadldap.adoc, src/main/java/apoc/load/LDAPResult.java, src/main/java/apoc/load/LoadLdap.java, src/test/java/apoc/load/LoadLdapTest.java
when you want to use this on neo4j server you have to put an jldap.jar in the plugins folder. You can get that via this url : https://mvnrepository.com/artifact/com.novell.ldap/jldap/2009-10-07
=> added apoc.load.ldap

src/main/java/apoc/index/SchemaIndex.java, src/main/java/apoc/meta/Meta.java, src/main/java/apoc/nodes/Nodes.java
Wrapping `KernelStatement stmt = (KernelStatement) tx.acquireStatement()` in a try() clause.
All the changes are related to ReadOperations.
=> KernelStatement in try() clause fixes #532

docs/overview.adoc, docs/periodic.adoc, src/main/java/apoc/Pools.java
Now it's possible to set up the number of threads for the SCHEDULED pool.
The configuration property is `apoc.jobs.scheduled.num_threads`
=> Configurable pool size for Pools.SCHEDULED

src/main/java/apoc/nodes/Grouping.java, src/test/java/apoc/nodes/GroupingTest.java
* also introduces key:null properties for virtual nodes if the property is not present at the group members
=> Fixes #584 - Allow asterisk as node label filter

src/main/java/apoc/index/SchemaIndex.java, src/main/java/apoc/meta/Meta.java, src/main/java/apoc/nodes/Nodes.java
Neo4j has become more strict about making sure that statements are closed by procedures using them. If this does not happen, chaining multiple procedure calls can fail. Please forward merge this into 3.3, and possibly have a look at 3.1 as well.
=> Close all statements using try-with-resources

src/main/java/apoc/index/SchemaIndex.java, src/test/java/apoc/index/SchemaIndexTest.java
This PR should fix #639 and #640 
I removed the `finally` block that was closing the transaction to fix #639.
For #640, when `labelName.isEmpty()` all indexes are searched (rather than none). This exposed another bug, which is that we would count distinct terms on all indexes for the label, whether or not they contained the key under consideration. So there are two small changes to the logic in `@Procedure("apoc.schema.properties.distinctCount")`
I added test cases to check the behavior with:
1. Labels with more than one index
2. labelName.isEmpty()
3. keyName.isEmpty()
4. both (2) and (3)
In doing so I noticed that only `string` Lucene terms work with these distinct property APOC methods. I'm not sure how to fix that so I just created issue #641 and commented out the test lines that were …
=> Support null labels, multiple labels in apoc.schema.properties.distinctCount

docs/overview.adoc, src/main/java/apoc/coll/Coll.java, src/test/java/apoc/coll/CollTest.java
Given a list, returns all combinations of list elements of combination sizes between minSelect and maxSelect inclusive (if omitted, maxSelect defaults to minSelect)
Fulfills request #310
=> Added apoc.coll.combinations()

src/main/java/apoc/result/AssertSchemaResult.java, src/main/java/apoc/schema/Schemas.java, src/test/java/apoc/schema/SchemasTest.java
So as not to change the output, I create multiple `AssertSchemaResult` instances per key in a compound index. This should get into 3.2 and 3.3 branches.
=> Fixes #681 - Compound index dropping using apoc.schema.assert fails

docs/expand.adoc, docs/overview.adoc, src/main/java/apoc/path/LabelMatcher.java, src/main/java/apoc/path/LabelMatcherGroup.java, src/main/java/apoc/path/PathExplorer.java, src/main/java/apoc/path/RelationshipSequenceExpander.java, src/test/java/apoc/path/ExpandPathTest.java, src/test/java/apoc/path/LabelSequenceTest.java, src/test/java/apoc/path/RelSequenceTest.java, src/test/java/apoc/path/SequenceTest.java
Added `labelSequence` to path expander config parameters, allowing label filters to define a repeating sequence of nodes to expand.
Further commits also include `relationshipSequence`, and `sequence` (when both are needed)
Addresses #691.
=> Added sequences to path expander procedures

src/main/java/apoc/date/Date.java, src/test/java/apoc/date/DateTest.java
- date.format(null) returns null, instead of throw
- add ISO8601 convenience format function, ISO8601 is commonly used, eg in Neo4j OGM, API endpoints, etc.
=> Fixes #747: date.format(null) returns null, also add ISO8601 convenience format

src/main/java/apoc/coll/Coll.java, src/test/java/apoc/coll/CollTest.java
apoc.coll.combinations was missing in the code of version 3.3 while being in the docs.
Code was added in version 3.2 but only partially merged into 3.3
This code is based on the original from contributor InverseFalcon
=> Add missing apoc.coll.combinations() to 3.3

src/main/java/apoc/path/RelationshipSequenceExpander.java, src/main/java/apoc/schema/Schemas.java
Fixes #765. Get rid of usage of commons-collections in apoc. Commons-collections is a transitive dependency in enterprise, but not in community. In order to prevent version glitches it's better to not depend on it at all.
=> fixes #765 Missing Iterator Utils in apoc .jar file

src/main/java/apoc/cypher/Cypher.java, src/test/java/apoc/cypher/CypherTest.java, src/test/resources/parameterized.cypher
Parameters are passed by adding a `parameters: {...}` entry to the config parameter of the `runFile` procedure.
=> Allow passing parameters to `apoc.cypher.runFile`

docs/temporal.adoc, src/main/java/apoc/temporal/TemporalProcedures.java, src/test/java/apoc/temporal/TemporalProceduresTest.java
These functions can be used to format temporal values using a valid `DateTimeFormatter` pattern.
```
apoc.temporal.format( date(), 'YYYY-MM-dd')
apoc.temporal.format( datetime(), 'YYYY-MM-dd HH:mm:ss.SSSSZ')
apoc.temporal.format( localtime(), 'HH:mm:ss.SSSS')
apoc.temporal.format( localtime(), 'HH:mm:ss.SSSS')
apoc.temporal.format( duration.between( datetime.transaction(), datetime.realtime() ) , 'HH:mm:ss.SSSS')
```
=> Added temporal subpackage for formatting temporal values

docs/loadxml.adoc, src/main/java/apoc/load/Xml.java
Gives the ability to provide a map of HTTP headers on the config property for HTTP requests.
```
WITH { `X-API-KEY`: 'abc123' } as headers,
WITH "https://myapi.com/api/v1/" AS url
CALL apoc.load.xml(url, '', { headers: headers }) YIELD value
UNWIND keys(value) AS key
RETURN key, apoc.meta.type(value[key]);
```
=> Read headers from config object

docs/diff.adoc, docs/index.adoc, src/main/java/apoc/diff/Diff.java, src/test/java/apoc/diff/DiffTest.java
The new procedure `apoc.diff.nodes` returns an overview of all node property differences of two nodes given by their nodeIds. The new functionality is documented in a new `*.adoc`-file (with usage and example Cypher) and covered by a unit test.
=> Add apoc.diff user function

src/main/java/apoc/result/IndexConstraintNodeInfo.java, src/main/java/apoc/schema/Schemas.java, src/test/java/apoc/schema/SchemasTest.java
@jexp this is the new response. Constraints are reported by the attribute *type* with value *UNIQUENESS*
=> fixes #510 - add index selectivity to apoc.meta.data apoc.meta.schema  and the apoc.index procedures

src/main/java/apoc/trigger/Trigger.java
Fixes #856. Added optional parameter to procedure 'apoc.trigger.add' that allows configuration to be passed in.
=> Fixes #856 - Added optional parameter to procedure 'apoc.trigger.add' for configuration. (Branch 3.4) 

src/main/java/apoc/periodic/Periodic.java, src/test/java/apoc/periodic/PeriodicTest.java
Added optional 4th parameter to procedure 'apoc.periodic.repeat' that allows for configuration to be passed in.
Added test for apoc.periodic.repeat that makes sure parameters passed in work as expected. Named testRepeatParams(). This PR is for branch 3.4.
=> Fixes #852 - Added optional 4th parameter to procedure 'apoc.periodic.repeat'. (Branch 3.4)

src/main/java/apoc/trigger/Trigger.java, src/test/java/apoc/trigger/TriggerDisabledTest.java
Added runtime exception if an `apoc.trigger.*` procedure is called but `apoc.trigger.enabled=true` has not been set in the neo4j.conf file.
This PR includes a separate test file 'TriggerDisabledTest.java' for fix of #845. Testing the disabled triggers needs to be in a different test file from 'TriggerTest.java' since trigger classes and methods are static and 'TriggerTest.java' instantiates a class that enables triggers.
**Technicals:**
This works due to the `start()` method located in the static LifeCycle class in 'Trigger.java'. If `apoc.trigger.enabled=true` is set in the neo4j.conf then the `properties` data member will be set from line 321 `triggerHandler = new Trigger.TriggerHandler(db,log);`. If `apoc.trigger.enabled=false` or it is not set in the neo4j.conf then line 321 will …
=> Fixes #845 - Message fix for Triggers when 'apoc.trigger.enabled=true' is not set in neo4j.conf 

docs/elasticsearch.adoc, src/main/java/apoc/es/ElasticSearch.java
Corrected Elasticsearch methods to match their documentation. Plus added a fix to the documentation.
=> Fixes - #862 Elasticsearch Integration fix

build.gradle, docs/overview.adoc, src/main/java/apoc/text/Phonetic.java, src/main/java/apoc/text/Strings.java, src/test/java/apoc/text/PhoneticTest.java, src/test/java/apoc/text/StringsTest.java
Adds text similarity/distance methods and double metaphone text encoding.
Added Levenshtein Distance and Similarity code and test.
Added Hamming Distance code and test.
Added Jaro-Winkler Distance code and test.
Added Double Metaphone text encoding and test.
Added Apache commons-text dependency.
=> Fixes #864 - Adds text similarity/distance methods and double metaphone text encoder.

docs/loadcsv.adoc
Documentation sketch for PR #581, based on the 3.4 branch.
Potential things to discuss in the docs:
=> Initial documentation for 'apoc.import.csv'

docs/overview.adoc, docs/spatial.adoc, src/main/java/apoc/spatial/Geocode.java, src/test/java/apoc/spatial/GeocodeTest.java, src/test/java/apoc/spatial/SpatialTest.java, src/test/resources/geoSpatial.conf, src/test/resources/spatial.json
- added a new method `reverseGeocode(Double latitude, Double longitude)`
- reviewed all the variables and methods changing "inverseGeocode" with "reverseGeocode"
- documentation updated
- added a new property for reverse geocoding when using a custom GeoProvider
- tests for the custom GeoProvider assert the existence of a key otherwise they don't run anything
=> Issue 234 - Support reverse geocoding in apoc.spatial

build.gradle, src/main/java/apoc/export/csv/CsvEntityLoader.java, src/main/java/apoc/export/csv/CsvFormat.java, src/main/java/apoc/load/LoadCsv.java
Previous dependency was net.sf.opencsv:opencsv:2.3 (transitively from org.neo4j:neo4j-cypher),
new one is com.opencsv:opencsv:4.2
This change is aligned with https://github.com/neo4j/neo4j/pull/12009.
=> Update opencsv dependency

src/main/java/apoc/trigger/Trigger.java, src/test/java/apoc/trigger/TriggerDisabledTest.java
At present, if apoc.trigger.enabled is not set, or set to false, and a user calls any of the APOC trigger procedures, they get a stacktrace and a NullPointerException.
This PR just sets a flag and checks prior to executing any trigger related function whether triggers are enabled.  If they are not, a RuntimeException is thrown that gives a meaningful message the user can act on.
Submitting this PR because I've run into it twice recently, it confused me both times.  Internal neo4j slack #apoc channel had two other users who got caught by same confusion, raising questions.
=> Inform users what's wrong when triggers are not enabled

src/main/java/apoc/load/Xml.java, src/test/java/apoc/load/XmlTest.java, src/test/resources/xml/xxe.xml
Doc types are now disabled in order to prevent almost all XML entity attacks.
=> Fixes #931

src/test/java/apoc/load/LoadS3Test.java
LoadS3Test fails due to an incompatibility of the md5 validation between Minio and the S3 client.
In the tests, we disable the md5 validation.
=> Fixes #959

docs/overview.adoc, docs/text.adoc, src/main/java/apoc/text/Strings.java, src/test/java/apoc/text/StringsTest.java
Fixes #985 
Provide Locale as option in apoc.text.format
- added new optional param _language_ , with default value _en_
=> fixes #985 - Provide Locale as option in apoc.text.format

src/main/java/apoc/mongodb/MongoDB.java, src/main/java/apoc/mongodb/MongoDBColl.java
Start a MongoDB with docker:
```
docker run --name apoc-mongo  mongo -p 27017:27017
docker exec -it apoc-mongo bash
>mongo
```
To check the number of opened connection you can use the command (inside the mongo shell)
`db.serverStatus().connections`
Check the number of connection using the current API for mongodb
```
CALL apoc.mongodb.get('localhost:27017','myDb','myColl',{x:1}) yield value return value
CALL apoc.mongodb.count('localhost:27017','myDb','myColl',{x:1}) yield value
CALL apoc.mongodb.first('localhost:27017','myDb','myColl',{x:1}) yield value
CALL apoc.mongodb.find('localhost:27017','myDb','myColl',{x:1},null,null) yield value
CALL apoc.mongodb.insert('localhost:27017','myDb','myColl',[{y:1}])
CALL apoc.mongodb.update('localhost:27017','myDb','myColl',{y:1}, …
```
=> fixes #830 - Help me with apoc (mongodb)

docs/loadjdbc.adoc, src/main/java/apoc/load/Jdbc.java, src/main/java/apoc/load/util/LoadJdbcConfig.java, src/test/java/apoc/load/JdbcTest.java
Fixes #994 
Provide a configuration parameter map with user/pass for JDBC
- added a new config parameter _credentials_ in which user can write user and password 
`{credentials:{user:"",password:""}}`
=> fixes #994 - Provide a configuration parameter map with user/pass for JDBC

docs/overview.adoc, src/main/java/apoc/convert/Convert.java, src/main/java/apoc/meta/Meta.java, src/test/java/apoc/meta/MetaTest.java
Fixes #981
apoc.meta.type should give consistent type info
- Add new function `apoc.meta.v2.type(value)`, `apoc.meta.v2.isType`, `apoc.meta.v2.types`
- New types (`INTEGER,FLOAT,STRING,BOOLEAN,RELATIONSHIP,NODE,PATH,NULL,MAP,LIST,POINT,DATE,DATE_TIME,LOCAL_TIME,LOCAL_DATE_TIME,TIME,DURATION`)
- Deprecated `apoc.meta.type(value)`, `apoc.meta.isType`, `apoc.meta.types`
=> fixes #981 - apoc.meta.type should give consistent type info

src/main/java/apoc/export/json/JsonFormat.java, src/test/java/apoc/gephi/GephiTest.java, src/test/java/apoc/util/TestUtil.java
Fixes #1016
- Change the way that `GephiTest` resolve a running Gephi instance the old way could return a false positive if there is a running service at port `8080`
- Correct the path separator of the Enterprise Edition instance
- fixed the LIST management in the json export with a `Meta.Types.LIST` after the #1000
=> fixes #1016: Travis build failures

src/main/java/apoc/export/csv/CsvFormat.java, src/main/java/apoc/export/util/ExportConfig.java, src/test/java/apoc/export/csv/ExportCsvTest.java
`apoc.export.csv.query` do not surround every exported field
Fixes #1005
- In case the configuration for the export contains the pair `"quotes": true`, in the constructor of the  `CSVWriter` are specified `quotechar` and `escapechar` as `'\0'`:
- the first avoids to migrate the call of `public void writeNext(String[] nextLine)` to `public void writeNext(String[] nextLine, boolean applyQuotesToAll)`
- the second is used to avoid to append an extra `"`, since the default escape character is `"` (see `protected boolean stringContainsSpecialCharacters(String line)`  in `class CSVWriter` )
- In the` ExportConfig` the default value of "quotes" configuration is `true`. 
- The export of the result of the query
```
"CREATE (f:User1:User …
```
=> fixes #1005

src/main/java/apoc/export/graphml/ExportGraphML.java, src/test/java/apoc/export/graphml/ExportGraphMLTest.java
fixes #775
apoc.export.graphml.all requires apoc.import.file.enabled needs to be enabled rather than apoc.export.file.enabled.
- Import required only the `apoc.import.file.enabled`
- Export required only the `apoc.export.file.enabled`
=> fixes #775 - apoc.export.graphml.all requires apoc.import.file.enabled needs to be enabled rather than apoc.export.file.enabled.

src/main/java/apoc/export/graphml/XmlGraphMLReader.java, src/test/java/apoc/export/graphml/ExportGraphMLTest.java
Fixes #721
GraphML import and labels
- Now the import, with `readLabels:true`, read the type of relationship write as:
- <edge id="1" source="2" target="3"> <data key="labels">:EDGE_LABEL</data> </edge>
- <edge id="1" source="2" target="3"> <data key="labels">EDGE_LABEL</data> </edge>
=> fixes #721 - GraphML import and labels

src/main/java/apoc/export/graphml/XmlGraphMLReader.java, src/test/java/apoc/export/graphml/ExportGraphMLTest.java
fixes #548
apoc.import.graphml ignores Node properties with empty String
- Now properties with space are imported
=> fixes #548 - apoc.import.graphml ignores Node properties with empty String

readme.adoc
The relative link doesn't work on the user guide nor the readme on GH itself.
=> Fix link to issue page.

docs/overview.adoc, docs/schema.adoc, src/main/java/apoc/schema/SchemaConfig.java, src/main/java/apoc/schema/Schemas.java, src/test/java/apoc/schema/SchemasTest.java
Fixes #991
Add ability to provide label to schema functions for filtered results
- Now it can be possible to find all the nodes contraints/Indexes by label e.g (CALL apoc.schema.nodes(labelName) yield properties)
=> fixes #991 - Add ability to provide label to schema functions for filtered results

src/main/java/apoc/export/csv/CsvFormat.java, src/main/java/apoc/export/util/ExportConfig.java, src/test/java/apoc/export/csv/ExportCsvTest.java
Complement of the Fixes #1005
- Fixes in #1005 did not applied for export all graph, quotes rules should be now valid for all types of csv export
- counter of the exported relationships has been fixed
=> Add missing cases in #1005

src/main/java/apoc/load/Jdbc.java, src/test/java/apoc/load/JdbcTest.java
Fixes #1039 
update to version 3.5.0.1, apoc.load.jdbc select timestamp column which value is NULL raise Exception
- add null value check
=> fixes #1039 - update to version 3.5.0.1, apoc.load.jdbc select timestamp column which value is NULL raise Exception

docs/overview.adoc, src/main/java/apoc/export/csv/CsvFormat.java, src/main/java/apoc/export/graphml/XmlGraphMLWriter.java, src/main/java/apoc/export/util/ExportConfig.java, src/main/java/apoc/export/util/ExportFormat.java, src/main/java/apoc/export/util/FormatUtils.java, src/main/java/apoc/export/util/MetaInformation.java, src/main/java/apoc/gephi/GephiFormatUtils.java, src/test/java/apoc/export/graphml/ExportGraphMLTest.java, src/test/java/apoc/load/LoadCsvTest.java, src/test/java/apoc/util/TestUtil.java
fixes #478 #466
- #478 Export graphml missing labels of Nodes and Edges
- #466 APOC GraphML attributes not loadable by Gephi
- All attributes/key are exported and generated
- By deafult key are generated, for types use `useTypes:true`
=> fixes #478 - Export graphml missing labels of Nodes and Edges

docs/refactor.adoc, src/main/java/apoc/refactor/GraphRefactoring.java, src/main/java/apoc/refactor/util/RefactorConfig.java, src/test/java/apoc/refactor/GraphRefactoringTest.java
Fixes #1047 
apoc.refactor.mergeNodes don't overwrite properties of relationships
- now properties of merged relationships in mergeNodes are managed like properties nodes with config parameter `properties`
- if `properties` isn't set, properties of merged relationships are combined
=> fixes #1047 - apoc.refactor.mergeNodes don't overwrite properties of relationships

docs/periodic.adoc, src/main/java/apoc/periodic/Periodic.java, src/test/java/apoc/periodic/PeriodicTest.java
This - of course - is a somewhat breaking changes. Usages that do not have a `limit` will get an exception.
=> fix #1071 apoc.periodic.commit should check for `limit`

docs/overview.adoc, src/main/java/apoc/coll/Coll.java, src/test/java/apoc/coll/CollTest.java
Fixes #1044 
Drop Duplicate Neighbors
- new procedure which drop duplicate neighbors in a list of elements (node, relationships, numbers, strings ..)
=> fixes #1044 - Drop Duplicate Neighbors

src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java, src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java, src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java, src/main/java/apoc/export/cypher/formatter/CreateCypherFormatter.java, src/main/java/apoc/export/cypher/formatter/CypherFormatter.java, src/main/java/apoc/export/cypher/formatter/CypherFormatterUtils.java, src/main/java/apoc/export/cypher/formatter/UpdateAllCypherFormatter.java, src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java, src/test/java/apoc/export/cypher/ExportCypherTest.java
Fixes #1049 
apoc.export.cypher.all fails when a compound constraint exists
- compound constraind are now managed
=> fixes #1049 - apoc.export.cypher.all fails when a compound constraint exists

build.gradle, src/test/java/apoc/nodes/NodesTest.java, src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java, src/test/java/apoc/schema/SchemasTest.java, src/test/java/apoc/util/TestContainerUtil.java, src/test/java/apoc/util/TestUtil.java
Fixes #1079 
This PR focuses on a resolution of the issue above "Run Ignored Enterprise Tests with TestContainers instead"
The enterprise tests are now managed with Testcontainers as requested, the project will be build into a directory used by Testcontainers as external volume. Every call to the Docker is made by the Neo4j Java Driver.
- Added the test container support 
- created the `TestContainersUtil` class in order to support the enterprise test lifecycle
- moved the enterprises test of `SchemaTest` to the new class `SchemasEnterpriseFeaturesTest`
- removed the `@Ignore` inside the class `NodesTest` the now work properly.
If we plan to rebase the 3.5 with the 3.4 updates I'll provide a new PR with the management of the …
=> fixes #1079: Run Ignored Enterprise Tests with TestContainers instead

docs/overview.adoc, src/main/java/apoc/convert/ConvertConfig.java, src/main/java/apoc/convert/Json.java, src/test/java/apoc/convert/ConvertJsonTest.java
Fixes #1040
apoc.convert.toTree config option to include/exclude certain properties
- Add config to include/exclude certain properties by label/type
=> fixes #1040 - apoc.convert.toTree config option to include/exclude certain properties

docs/overview.adoc, src/main/java/apoc/meta/Meta.java, src/main/java/apoc/meta/MetaConfig.java, src/test/java/apoc/meta/MetaTest.java
Fixes #899 
make apoc.meta.* sample at batches
- add `sample` config on apoc.meta procedures for sample the dataset
=> fixes #899 - make apoc.meta.* sample at batches

build.gradle, src/test/java/apoc/export/graphml/ExportGraphMLTest.java
Fixes #1100
Instead of change the Code I used the `XmlUnit` library in order to identify the elements `byNameAndAllAttributes`
- Used the `XmlUnit` library in order to test the XML comparison
=> fixes #1100: graphml export: sort property keys for consistency

src/main/java/apoc/ApocConfiguration.java, src/main/java/apoc/load/LoadCsv.java, src/main/java/apoc/log/Neo4jLogStream.java, src/main/java/apoc/meta/Meta.java, src/main/java/apoc/metrics/Metrics.java, src/main/java/apoc/util/FileUtils.java
- Changes metrics to return a timestamp and map of values instead of breaking those values out.  This accomodates a range of different schemas in different metric files across Neo4j versions.  In particular, there were a lot of metric schema changes between 3.4 and 3.5 which makes supporting the individual file format of particular metrics not a terribly feasible option
=> Revise Metrics and Log Streaming Approach

docs/asciidoc/_export_import.adoc, src/main/java/apoc/export/csv/CsvFormat.java, src/main/java/apoc/export/csv/ExportCSV.java, src/main/java/apoc/export/cypher/ExportCypher.java, src/main/java/apoc/export/cypher/ExportFileManager.java, src/main/java/apoc/export/cypher/FileManagerFactory.java, src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java, src/main/java/apoc/export/graphml/XmlGraphMLFormat.java, src/main/java/apoc/export/json/ExportJson.java, src/main/java/apoc/export/json/JsonFormat.java, src/main/java/apoc/export/util/BulkImportUtil.java, src/main/java/apoc/export/util/ExportConfig.java, src/main/java/apoc/export/util/Format.java, src/main/java/apoc/export/util/Neo4jAdminImportUtil.java, src/main/java/apoc/util/Util.java, src/test/java/apoc/export/csv/ExportCsvTest.java
Fixes #928
Round-trip for apoc.export.csv.all
- Add the the config to export the csv for the adminImportTool
=> fixes #928 - Round-trip for apoc.export.csv.all

docs/asciidoc/big-graph-from-cypher.adoc, docs/asciidoc/exportCypher.adoc, docs/script/performanceCypherTest.sh, src/main/java/apoc/export/cypher/ExportCypher.java, src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java, src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java, src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java, src/main/java/apoc/export/cypher/formatter/CreateCypherFormatter.java, src/main/java/apoc/export/cypher/formatter/CypherFormatter.java, src/main/java/apoc/export/cypher/formatter/CypherFormatterUtils.java, src/main/java/apoc/export/cypher/formatter/UpdateAllCypherFormatter.java, src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java, src/main/java/apoc/export/util/ExportConfig.java, src/main/java/apoc/export/util/FormatUtils.java, src/test/java/apoc/export/cypher/ExportCypherTest.java
Fixes #998
- Add a mode to export.cypher that batches updates
- Add new config `useOptimizations` (true or false), that create a file with batch update
- By default the method export the data with `useOptimizations` false
=> fixes #998 - Add a mode to export.cypher that batches updates

docs/asciidoc/_indexes.adoc
Fixes #1137 
Moves deprecation warning to correct headline to clarify, which namespace specifically will be deprecated and removed in the future.
properly scope and move the deprecation warning.
=> Move deprecation warning to correct headline

src/main/java/apoc/util/Util.java, src/test/java/apoc/load/LoadCsvTest.java, src/test/java/apoc/util/UtilIT.java
Fixes #1140 
In case of the HTTP response code is 3XX and the `Location` header provides a different protocol we throw an Exception with the value of the `Location` in the message
- changed the `Util#isRedirect` method in order to implement that logic
- provided a simple test for `CALL apoc.load.csv({url})` in order to highlight the new behaviour
- added the `UtilIT` class that tests the method `Util#openInputStream` for two call, one that has as redirect location `http://www.google.com` and the other one has `file:/etc/passwd`
=> fixes #1140: Prevent unsafe redirect

docs/asciidoc/periodic.adoc, src/main/java/apoc/periodic/Periodic.java, src/test/java/apoc/periodic/PeriodicTest.java
adding a new optional parameter to apoc.periodic.iterate.
If `includeFailedBatches:true` is set, the data of all failed batches is included in the result being passed back to the caller. 
Since it defaults to false I don't expect any compatibility issues.
=> fix #1055 adding includeFailedBatches for apoc.periodic.iterate

docs/asciidoc/_export_import.adoc, docs/asciidoc/config.adoc, src/main/java/apoc/ApocConfiguration.java, src/test/java/apoc/cypher/CypherTest.java, src/test/java/apoc/export/csv/ImportCsvLdbcTest.java, src/test/java/apoc/export/csv/ImportCsvTest.java, src/test/java/apoc/export/graphml/ExportGraphMLTest.java, src/test/java/apoc/load/LoadJsonTest.java, src/test/java/apoc/load/LoadS3Test.java, src/test/java/apoc/load/XmlTest.java, src/test/java/apoc/load/relative/LoadRelativePathTest.java, src/test/java/apoc/util/FileUtilsTest.java
Fixes #1142
Switch import directory mode to honor neo4j import directory setting
- created a `DEFAULTS` map into `ApocConfiguration.java` which contains the <k,v> pairs of default configuration values
- improved the documentation
- fixed broken tests configuring `apoc.import.file.use_neo4j_config=false` into them.
=> fixes #1142: switch import directory mode to honor neo4j import directory setting

src/main/java/apoc/meta/Meta.java
Fixes #1127 
The bug was caused by the method `Meta#getSampleForLabelCount` that sometimes returns 0, that value is then used in a `%` operation causing the `ArithmeticException`
- in case `ThreadLocalRandom.current().nextLong` returns 0 (zero) we change that value to -1 (with the same strategy adopted for the if `min >= max`)
=> fixes #1127

docs/asciidoc/_utilities.adoc, docs/asciidoc/log.adoc, src/main/java/apoc/log/Logging.java, src/main/java/apoc/util/SimpleRateLimiter.java, src/test/java/apoc/log/LoggingTest.java, src/test/java/apoc/util/SimpleRateLimiterTest.java
Fixes #1141
add config option to "garble" log messages
* Added three properties:
* `apoc.user.log.type` | enum[none, safe, raw] (default value `safe`) | type of logging:
* `node`: disable the procedures
* `safe`: replace all `.` and whitespace (space and tab) with underscore and lowercase all characters
* `raw`: left the messages as-is
* `apoc.user.log.window.ops` | int (default value `10`) | num of logs permitted in a time-window, exceeded this quota every log message will be skip
* `apoc.user.log.window.time` | long (default value `10000`) | the length (in milliseconds) of the time-window (default 10 seconds)
* Added documentation
* Added tests
=> fixes #1141: add config option to "garble" log messages

docs/asciidoc/custom.adoc, src/main/java/apoc/custom/CypherProcedures.java, src/test/java/apoc/custom/CypherProceduresTest.java
Fixes #1073
Add "description" to custom procedures/functions.
- Added the `description` field as the last field in `apoc.custom.asProcedure` and `apoc.custom. asFunction`
- Added test
=> fixes #1073: Add "description" to custom procedures/functions

src/main/java/apoc/export/csv/CsvFormat.java, src/test/java/apoc/export/csv/ExportCsvNeo4jAdmin.java, src/test/java/apoc/export/csv/ExportCsvTest.java
Fixes #1173
Fix ExportCsv ordering tests
- Provided a natural sorting for the headers in order to have a deterministic, test prone, result
- Moved tests of Neo4j Admin Import to a separate class in order to simplify the dataset management
- Clean some code test
=> fixes #1173: Fix ExportCsv ordering tests

docs/asciidoc/_export_import.adoc, src/main/java/apoc/ApocConfiguration.java, src/main/java/apoc/util/FileUtils.java, src/test/java/apoc/export/csv/ExportCsvNeo4jAdminTest.java, src/test/java/apoc/export/csv/ExportCsvTest.java, src/test/java/apoc/export/csv/ExportXlsTest.java, src/test/java/apoc/export/cypher/ExportCypherEnterpriseFeaturesTest.java, src/test/java/apoc/export/cypher/ExportCypherTest.java, src/test/java/apoc/export/json/ExportJsonTest.java
Fixes #1178 
Make the `dbms.directories.import` dir root dir for exports 
- changed the behaviour of `FileUtils#getOutputStream` method in order to manage the property `apoc.import.file.use_neo4j_config`, in case it's `true` it takes the value `dbms.directories.import` as root dir
- fixed all the test
=> fixes #1178: Make the `dbms.directories.import` dir root dir for exports

src/main/java/apoc/date/Date.java, src/main/java/apoc/util/DateFormatUtil.java, src/test/java/apoc/date/DateTest.java
Fixes #1203
Adds support for the date format `RFC_1123_DATE_TIME`.
Adds a method to convert a String of one date format into a String of another date format.
The function header has an input, a string currentFormat, and a string convertToFormat parameter. 
``` 
apoc.date.convertFormat('Tue, 14 May 2019 14:52:06 -0400', 'rfc_1123_date_time', 'iso_date_time')
```
=> fixes #1203 - Added RFC date support and date string converter function 

src/main/java/apoc/load/Jdbc.java, src/main/java/apoc/load/util/JdbcUtil.java, src/test/java/apoc/load/JdbcTest.java
Fixes #1206 
Allow for SQL called by apoc.load.jdbc to be aliased under the conf file in the same way as connection strings currently are.
- Moved logic for `executeQuery`'s query generation to new method `JdbcUtil.getSqlOrKey()`, using existing `Util.loadUrlByConfigFile()` to access conf value.
- Created two new unit tests for use of aliased sql statements.
- Existing unit tests were unaffected.
=> fixes #1206 alias sql statements in conf for apoc.load.jdbc

build.gradle, docs/asciidoc/_export_import.adoc, src/main/java/apoc/export/csv/CsvFormat.java, src/test/java/apoc/export/csv/CsvTestUtil.java, src/test/java/apoc/export/csv/ExportCsvIT.java, src/test/java/apoc/export/csv/ExportCsvTest.java
Fixes #1188 
Removed sorting for `apoc.export.csv.query` and added for `apoc.export.csv.all/data/graph`
- Added sorting in exporting a subgraph. As described here:
https://github.com/conker84/neo4j-apoc-procedures/blob/fb316cce65daab4198a1d348fa9f39f08138f849/src/main/java/apoc/export/csv/CsvFormat.java#L245-L261
In particular, now we have this general structure for the headers:
`_id,_labels,<list_nodes_properties_naturally_sorted>,_start,_end,_type,<list_rel_properties_naturally_sorted>`
So for instance:
`_id,_labels,age,city,kids,male,name,street,_start,_end,_type,bar,foo`
- Fixed tests related to `apoc.export.csv.query`
=> fixes #1188: headers incorrect order after apoc csv export in enterprise edition 3.5.4, 3.5.5

src/main/java/apoc/load/LoadCsv.java, src/main/java/apoc/load/util/LoadCsvConfig.java
Fixes #1194
Adds ignoreQuotations to the apoc.load.csv configuration. This will allow the load csv operation to treat quote characters as regular characters, preventing issues if a quote is unclosed. When the row is loaded quote characters are NOT included. You can include quote characters by placing an escape character in front of them.
=> fixes #1194 - Adds ignoreQuotations configuration to apoc.load.csv - Branch 3.4

src/main/java/apoc/mongodb/MongoDB.java, src/main/java/apoc/mongodb/MongoDBColl.java
In apoc/mongodb/MongoDB.java ...
```
try (Coll coll = getMongoColl(hostOrKey, db, collection, compatibleValues)) {
return coll.all(query, skip, limit).map(MapResult::new); // .onClose(coll::safeClose);
} catch (Exception e) {
log.error("...");
throw new RuntimeException(e);
}
```
When leaving the try block the `coll` goes out of scope and its `close()` is called.
apoc.mongodb.MongoDBColl
```
@Override
public void close() throws IOException { 
mongoClient.close();
}
```
However, the returned stream (let's call it `res_stream`) needs for 
the mongo connection associated with `coll`  to remain open.
The closing of `res_stream` is handled by the .onClose() stream modifier
apoc.mongodb.MongoDBColl
```
private Stream<Map<String, Object>> asStream(FindIterable<Document> result) { …
```
=> #1177 keep the mongodb connection open until stream is closed

build.gradle, docs/asciidoc/custom.adoc, src/main/java/apoc/custom/CypherProcedures.java, src/test/java/apoc/custom/CypherProceduresClusterTest.java, src/test/java/apoc/custom/CypherProceduresTest.java, src/test/java/apoc/export/cypher/ExportCypherEnterpriseFeaturesTest.java, src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java, src/test/java/apoc/util/Neo4jContainerExtension.java, src/test/java/apoc/util/TestContainerUtil.java, src/test/java/apoc/util/TestcontainersCausalCluster.java
Fixes #1072
Make sure custom procedures are also recreated on other cluster members
- added "lastUpdate" to the procedure/function structure
- added timer that checks every `x` (default 60000) milliseconds if the graph property got updated and register the updated procedure/function version
- added integration test in Causal Cluster environment (3 core + 1 read replica)
=> fixes #1072: Make sure custom procedures are also recreated on other cluster members

docs/asciidoc/cypher.adoc, src/test/java/apoc/cypher/CypherTest.java
Fixes #1189 
Adds unit test and documentation for `apoc.cypher.doIt`.
=> fixes #1189 - Adds unit test & docs for apoc.cypher.doIt

build.gradle
Fixes #1187 
The tests of `apoc.schema.nodes` were all green; only when deployed the error pops up.
I tested with a running instance of neo4j 3.5.3 but with the error is still there, with this bump it starts working from v 3.5.4
- bump Neo4j version to `3.5.7` (the latest)
=> fixes #1187: 3.5.x apoc.schema.nodes fails

docs/asciidoc/aggregation.adoc, src/main/java/apoc/agg/MaxAndMinItems.java, src/test/java/apoc/agg/MaxAndMinItemsAggregationTest.java
Implements #1229 
Adds aggregation functions for collecting items associated with a minimal or maximal value.
Adds aggregation functions for collecting items associated with a minimal or maximal value. Includes the ability to optionally limit the results per value.
=> Added apoc.agg.maxItems() and apoc.agg.minItems()

docs/asciidoc/exportCypher.adoc, src/main/java/apoc/export/util/ExportConfig.java, src/test/java/apoc/export/cypher/ExportCypherTest.java
Fixes #1219
Changed the default format as suggested into the issue (new default is `cypher-shell`) and updated the related documentation
- changed default export type to `cypher-shell`
=> fixes #1219: change dbms.export.cypher.query default format, or document

src/test/java/apoc/agg/StatisticsTest.java
a previous commit changes the behaviour of apoc.agg.statistics causing a unit test to fail. This PR contains a fix for the test itself.
However I'm not sure if we should preferrably fix the code itself to satisfy the exiting test.
Wdyt @jexp?
=> fixes test for apoc.agg.statistics

build.gradle
Upgraded com.jayway.jsonpath:json-path from version 2.2.0 to 2.4.0 as the older version comes with a dependency to net.minidev:accessors-smart (version 1.1) which contains a shaded but outdated version of ASM, see https://github.com/netplex/json-smart-v2/pull/35. 
(caused troubles using Neo4j/APOC embedded in jQAssistant)
=> Upgraded com.jayway.jsonpath:json-path from version 2.2.0 to 2.4.0

docs/asciidoc/functions.adoc, docs/asciidoc/import/loadxml.adoc, src/main/java/apoc/load/Xml.java, src/test/java/apoc/load/LoadS3Test.java, src/test/java/apoc/load/XmlTest.java
Fixes #1211
In this PR is provided only the `apoc.xml.parse` function.
- moved tests to string comparison into objects because I had problems with property order
- implemented the `apoc.xml.parse` function
=>  fixes #1211: Create a function apoc.xml.parse and apoc.xml.format

docs/asciidoc/virtual/virtual-graph.adoc, src/main/java/apoc/graph/Graphs.java, src/main/java/apoc/graph/document/builder/DocumentToGraph.java, src/main/java/apoc/graph/document/builder/LabelBuilder.java, src/main/java/apoc/graph/util/GraphsConfig.java, src/test/java/apoc/graph/GraphsTest.java
Fixes #1243 
Added new config params in order to manage auto-generated ids and the default label
=> fixes #1243: Improving apoc.graph.fromDocument: manage missing id and label

docs/asciidoc/big-graph-from-cypher.adoc, src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java, src/main/java/apoc/export/util/ExportConfig.java, src/test/java/apoc/export/cypher/ExportCypherTest.java
Fixes #1209
This should fix the bug of `extraneous comma within an unwind statement`
- Moved the filtered properties outside the method
=> fixes #1209: apoc.export.cypher.query writes out invalid cypher

docs/asciidoc/virtual/virtual-graph.adoc, src/main/java/apoc/graph/document/builder/DocumentToGraph.java, src/main/java/apoc/graph/document/builder/LabelBuilder.java, src/main/java/apoc/graph/util/GraphsConfig.java, src/main/java/apoc/util/Util.java, src/test/java/apoc/graph/GraphsTest.java
Fixes #1245
Add support to store value object via `valueObjects` map. The properties of the value objects will be flattened with this general rule:
A json like this:
```json
{
"id": 1,
"type": "Person",
"name": "Andrea",
"sizes": {
"weight": {
"value": 70,
"um": "Kg"
},
"height": {
"value": 174,
"um": "cm"
}
}
}
```
Will be flattened as follows:
```json
{
"id": 1,
"type": "Person",
"name": "Andrea",
"sizes.weight.value": 70,
"sizes.weight.um": "Kg",
"sizes.height.value": 174,
"sizes.height.um": "cm"
}
```
- added the support via the property configuration `valueObjects`
=>  fixes #1245: Improving apoc.graph.fromDocument: storing value objects

src/main/java/apoc/coll/Coll.java, src/test/java/apoc/coll/CollTest.java
Fixes #1159 
Adds apoc.coll.extract function and unit tests.
Can only extract from collections of Maps, Nodes, and Relationships. If one of the objects in the collection is missing the property then a null value is used.
=> fixes #1159 - Adds apoc.coll.extract function and unit tests.

docs/asciidoc/path-finding/expand-spanning-tree.adoc, docs/asciidoc/path-finding/expand-subgraph.adoc, docs/asciidoc/path-finding/expand.adoc, src/main/java/apoc/path/PathExplorer.java, src/test/java/apoc/path/SubgraphTest.java
Fixes #1293 
Allows `minLevel` to be used in subgraphNodes(), subgraphAll(), and spanningTree() for values of 0 or 1.
Previously attempts to set this config property triggered an error, since consequences of using minLevel with these NODE_GLOBAL uniqueness procs isn't intuitive and can lead to some unexpected results. minLevel of 1 however only skips the starting node and doesn't do anything surprising, so this now allows it.
Allow minLevel values of 0 and 1 for these procs.
=> Allow minLevel of 1 in subgraphNodes(), subgraphAll(), and spanningTree()

docs/asciidoc/utilities/text.adoc
=> Typo in naming for base64Url(De/En)code

docs/asciidoc/database-integration/mongodb.adoc, src/main/java/apoc/mongodb/MongoDB.java, src/main/java/apoc/mongodb/MongoDBColl.java, src/test/java/apoc/mongodb/MongoDBTest.java
Fixes #1288
The Mongo ObjectId is now managed as String.
- ObjectId managed as String
- added a new property `extractReferences` that recursively extract documents if finds `ObjectId` fields into a document (except for the `_id` field)
- added support for new neo4j datatypes
- added a round-trip test with `apoc.graph.fromDocument` in order to better test the `compatibleValues` with the new data-types
=> fixes #1288: Mongo connector chokes on ObjectId.

docs/asciidoc/graph-updates/data-creation.adoc, src/main/java/apoc/create/Create.java
Fixes #1304
The removeRelProperties expect 2 parameters, but 3 are described in the doc
(this is another try at #1310, hopefully on the right files/branch this time!)
- removed the values parameter from the removeRelProperties description
- changed the description of the *Properties procedure to apply the plural form there too
=> fix #1304 removeRelProperties expects only 2 params

src/main/java/apoc/custom/CypherProcedures.java, src/main/java/apoc/index/IndexUpdateTransactionEventHandler.java, src/main/java/apoc/periodic/Periodic.java, src/main/java/apoc/ttl/TTLLifeCycle.java, src/main/java/apoc/util/Util.java, src/test/java/apoc/periodic/PeriodicTest.java
PR ensures that we use `Future.cancel(false)` instead if `Future.cancel(true)` consistently in APOC's codebase.
The new test succeeds with this change applied, but fails in a sporadic way (~ 4 out of 5 attempts) when `Future.cancel(true)` is used. I was not able to make the test consistently failing.
Of course the PR is about to fix #1314
=> fixes #1314: ensure Future.cancel(false) is used everywhere

src/main/java/apoc/periodic/Periodic.java, src/main/java/apoc/util/Util.java, src/test/java/apoc/coll/CollTest.java, src/test/java/apoc/periodic/PeriodicTest.java
Fixes #1268
Added query validation in each `apoc.periodic.*` procedure
- Added the validation in each procedure
- Added test for each procedure/arguments
=> fixes #1268: apoc.periodic.repeat doesn't provide any feedback when query is bad

src/main/java/apoc/mongodb/MongoDBColl.java, src/test/java/apoc/mongodb/MongoDBTest.java
Fixes #1331
Changed the call `Collectors.toMap` with a new one that manages null values.
=> fixes #1331: Mongo procedure throws NullPointerException if a field is null

src/main/java/apoc/graph/util/GraphsConfig.java, src/test/java/apoc/graph/GraphsTest.java
Fixes #1333
Fixes the bug
- Added the mappings fields into the properties whitelist
=> fixes #1333: apoc.graph.fromDocument should consider mappings field into document whitelist

docs/asciidoc/cypher-execution/custom.adoc, src/main/java/apoc/custom/CypherProcedures.java, src/test/java/apoc/custom/CypherProceduresClusterTest.java, src/test/java/apoc/custom/CypherProceduresTest.java
Fixes #1317
Added procedure `apoc.custom.remove` which allows removing custom procedures/functions
- Added the `apoc.custom.remove` procedure 
- managed the custom procedure remove into a cluster environment, by adding a new property `removed` into the `apoc.custom` graph property to track the removed procedures
- updated documentation
=> fixes #1317: Add apoc.custom.delete/remove

docs/asciidoc/utilities/collection.adoc, src/main/java/apoc/coll/Coll.java, src/test/java/apoc/coll/CollTest.java
Fixes https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1339
Added apoc.coll.fill function
Proposed Changes
apoc.coll.fill(item, count) function returns a list with the "count" number of items
Example
return apoc.coll.fill('ab', 2)
returns ['ab', 'ab']
=> Add apoc.coll.fill function

docs/asciidoc/export/exportJson.adoc, docs/asciidoc/export/graphml.adoc, src/main/java/apoc/export/csv/ExportCSV.java, src/main/java/apoc/export/cypher/ExportCypher.java, src/main/java/apoc/export/cypher/FileManagerFactory.java, src/main/java/apoc/export/graphml/ExportGraphML.java, src/main/java/apoc/export/graphml/XmlGraphMLWriter.java, src/main/java/apoc/export/json/ExportJson.java, src/main/java/apoc/export/json/JsonFormat.java, src/main/java/apoc/export/util/ExportUtils.java, src/test/java/apoc/export/graphml/ExportGraphMLTest.java, src/test/java/apoc/export/json/ExportJsonTest.java
Fixes #1276
Add streaming support to export JSON and GraphML
- Added stream support to JSON
- Added stream support to GraphML
=> fixes #1276: Add streaming support to export JSON and GraphML

src/main/java/apoc/cypher/Cypher.java, src/test/java/apoc/cypher/CypherTest.java, src/test/resources/empty.cypher
Fixes #1262
Fixed the bug
- Added a recursion into the `removeShellControlCommands` method
- Added test
=> fixes #1262: apoc.cypher.runFile fails when there is a empty transaction

docs/asciidoc/utilities/map.adoc, docs/guide.html, docs/index.html, src/main/java/apoc/map/Maps.java, src/test/java/apoc/map/MapsTest.java
Fixes #1270 
add optional recursive-parameter to map.removeKeys
- added the "recursive" optional parameter with default set to false to the map.removeKey and map.removeKeys procedures (similar to what is done for coll.flatten)
=> fixes #1270 add optional recursive-parameter to map.removeKeys

src/main/java/apoc/Pools.java, src/main/java/apoc/refactor/GraphRefactoring.java, src/test/java/apoc/refactor/GraphRefactoringTest.java
Fixes #826
Fixed the bug
- Split the categorization into two phases
- First, we create the categorization nodes
- Second, we create the connection between the categorization nodes and "old" nodes
=> fixes #826: apoc.refactor.categorize duplicated categorization nodes

src/main/java/apoc/date/Date.java, src/test/java/apoc/date/DateTest.java
Fixes #1298
A companion to apoc.date.parse which returns a datetime rather than a Long.
- new class apoc.datetime.DateTime
- new method apoc.datetime.DateTime.parse which takes date/time string, format, and timezone (with defaults)
- returns a ZonedDateTime
This preview PR just added the method into apoc.date.Date with a different function signature which will be moved to DateTime class and adding tests if this approach is acceptable.
It wasn't quite clear in the issue description what type of DateTime it should return. I'm not yet very familiar with Neo4j and couldn't see any other DateTime types to go by.
Also the implementation assumes Java8 or later.
=> apoc.datetime.parse like apoc.date.parse but returns a datetime

src/main/java/apoc/periodic/Periodic.java, src/main/java/apoc/util/Util.java
**This is the cherry-picked commit of #1402**
Related to: https://neotechnology.zendesk.com/agent/tickets/8171
Fixed the bug and improved the logging mechanism.
- Improved the logging mechanism for `Util#inTxFuture`
- managed a possible `NullPointerException` scenario for `Periodic#getMessages`
=> fixes #1367: Improve logging when there is NullPointerException with  apoc.periodic.iterate/apoc.load.csv (3.4)

src/main/java/apoc/periodic/Periodic.java, src/main/java/apoc/util/Util.java
Fixes #1367
Related to: https://neotechnology.zendesk.com/agent/tickets/8171
Fixed the bug and improved the logging mechanism.
- Improved the logging mechanism for `Util#inTxFuture`
- managed a possible `NullPointerException` scenario for `Periodic#getMessages`
=> fixes #1367: Improve logging when there is NullPointerException with apoc.periodic.iterate/apoc.load.csv

docs/asciidoc/introspection/meta.adoc, src/main/java/apoc/meta/Meta.java, src/main/java/apoc/meta/MetaConfig.java, src/main/java/apoc/meta/Tables4LabelsProfile.java, src/main/java/apoc/meta/tablesforlabels/OrderedLabels.java, src/main/java/apoc/meta/tablesforlabels/PropertyContainerProfile.java, src/main/java/apoc/meta/tablesforlabels/PropertyTracker.java, src/test/java/apoc/meta/MetaEnterpriseFeaturesTest.java, src/test/java/apoc/meta/MetaTest.java
Fixes #1388 (for 4.x)
Full list of features:
1. **Tables4Labels**. Base functionality to replace nodeTypeProperties() and relTypeProperties() with sampling versions.
2. **Relationships4Labels**. Adds two columns to relTypeProperties() to show source and target labels for each relationship that has a valid property.
3. **Mandatory handling functionality change**. Forces "mandatory" flag to true only if a constraint exists for this property (only works for Enterprise Edition as constraints are a licensed function of Neo4J).
4. **Allow inclusion/exclusion of nodes by relationships**. When calling nodeTypeProperties(), include/exclude a node if it has a specifically has/doesn't have a relationship type associated).
Work-in-progress PR. Still requires:
- Complete unit tests (some are complete, …
=> Tables4Labels - 4.x

src/main/java/apoc/meta/Meta.java, src/main/java/apoc/meta/tablesforlabels/PropertyContainerProfile.java
Fixes #1414 
Changed constraint tracking to store strings instead of constraintdefinition objects.
Updated constraint tracking to track strings derived from constraintdefinitions gathered while the transaction is definitely open. Once stored as Map<String, List<String>>, transactions are no longer an issue when setting mandatory flag on the output.
=> Fixed bug with constraint checking after transaction has closed

docs/asciidoc/database-integration/bolt.adoc, docs/asciidoc/utilities/diff.adoc, src/main/java/apoc/bolt/Bolt.java, src/main/java/apoc/bolt/BoltConfig.java, src/main/java/apoc/diff/Diff.java, src/main/java/apoc/diff/DiffConfig.java, src/main/java/apoc/diff/SourceDestConfig.java, src/main/java/apoc/export/util/MapSubGraph.java, src/main/java/apoc/export/util/NodesAndRelsSubGraph.java, src/test/java/apoc/bolt/BoltTest.java, src/test/java/apoc/diff/DiffTest.java, src/test/java/apoc/util/Neo4jContainerExtension.java, src/test/resources/init_neo4j_diff.cypher
Fixes #1064
This procedure implements the changes in the related issue, with small changes in the requirement about the relationship comparison.
The `apoc.diff.graphs` compares two graphs and returns the differences in term of:
* same node count
* same count per label
* same relationship counter
* same count per rel-type
For each node in the `source` graph with a certain label, find the same node (in the `dest` graph) by keys or internal id in the other graph and if found:
* compare all labels
* compare all properties
For each relationship in the `source` graph, we'll get the two nodes of the relationship and look into the the `dest`
graph if there is a relationship with the same properties and the same start/end node.
In order to allow to use this procedure with the `apoc.bolt.*` I had …
=> fixes #1064: Add procedure to compare graphs

src/main/java/apoc/ApocConfig.java, src/test/java/apoc/ApocConfigTest.java
Fixes #1424
- changed parsing of the neo4j.conf dir
- added test
=> fixes #1424: ApocConfig does not load neo4j.conf properly if dir contains whitespace

src/main/java/apoc/neighbors/Neighbors.java, src/test/java/apoc/neighbors/NeighborsTest.java
Fixes #1437
- remove the true source node
- fixed the NPE exception in case you provide `>` as pattern, now it manges all the outgoing relationships
- improved tests in order to understand the content of the returned nodes are correct
=> fixes #1437: Fix node retival in apoc.neighbors.*

src/main/java/apoc/uuid/Uuid.java, src/test/java/apoc/uuid/UUIDTest.java
The procedure now yeilds batchComputationResult in line with what is
documented.
Fixes #1447
apoc.uuid.install yeild batchComputationResult
- Uuid install method returning UuidInstallInfo
- New unit test
=> apoc.uuid.install yeild batchComputationResult

docs/asciidoc/graph-updates/ttl.adoc, docs/asciidoc/temporal/datetime.adoc, src/main/java/apoc/date/Date.java, src/main/java/apoc/ttl/TTLLifeCycle.java
Fixes #1419, #1417 
1419: Remove apoc.date.field and apoc.date.fields procedures that are no longer needed with the built-in native date/temporal support in Neo4j.
- Add info on @UserFunction/@Procedure annotation to note replacement syntax
- Add @Deprecated annotation to procedures
1417: Move apoc.date.expire* to apoc.ttl.* naming and redirect/deprecate apoc.date.expire and apoc.date.expireIn.
- Date section:
- Add info on @UserFunction/@Procedure annotation to note replacement syntax
- Add @Deprecated annotation to procedures
- TTL section:
- Move 2 apoc.date.expire* procedures to this section
- Add documentation for these procedures
=> Start phase-out process for apoc.date.field*

CONTRIBUTING.adoc
Based on a discussion with @jexp please take a look if this "early cherry-pick" policy makes sense.
So far we did cherry-picking prior to a  release which is more painful compared to immediate cherry-picking when you still have the details in your mind. 
Feel free to comment, e.g. @mneedham @jexp and others as well.
=> document branching policy

build.gradle
@sarmbruster Trying to figure out how to publish the fat jar to Maven. Not sure if this is the right way?
```
$ ./gradlew publish
> Task :publishShadowPublicationToPipelineRepository
Multiple publications with coordinates 'org.neo4j.procedure:apoc:4.0.0.5' are published to repository 'pipeline'. The publications will overwrite each other!
BUILD SUCCESSFUL in 18s
13 actionable tasks: 11 executed, 2 up-to-date
```
Is the warning a problem or can we safely ignore it?
```
$ ls -alh build/repo/org/neo4j/procedure/apoc/4.0.0.5/
total 21M
drwxr-xr-x 2 markhneedham markhneedham 4.0K Apr  1 09:23 .
drwxr-xr-x 3 markhneedham markhneedham 4.0K Apr  1 09:22 ..
-rw-r--r-- 1 markhneedham markhneedham  18M Apr  1 09:35 apoc-4.0.0.5-all.jar
-rw-r--r-- 1 markhneedham markhneedham   32 Apr  1 09:35 …
```
=> adding the fatjar to maven artifacts

docs/asciidoc/config.adoc
Documents the `apoc.http.timeout.connect` and `apoc.http.timeout.read` settings.
Fixes #779
Adds documentation for the two `http.timeout` settings in the config.
- Add documentation
=> Adds documentation for the `http.timeout` config settings.

docs/asciidoc/import/loadjson.adoc, src/main/java/apoc/export/json/ImportJson.java, src/main/java/apoc/export/json/ImportJsonConfig.java, src/main/java/apoc/export/json/JsonImporter.java, src/test/java/apoc/export/json/ImportJsonTest.java
Fixes #1257 
Imported json files produced with `apoc.export.json.all`
- created `apoc.import.json.all`
- added tests
- updated documentation
=> fixes #1257: apoc.load.json file roundtrip from apoc.export.json.all

src/main/java/apoc/load/Jdbc.java, src/test/java/apoc/load/JdbcTest.java
Fixes #1458
Fixed the bug
- Changed procedure modes so they will work so with `apoc.iterate`
=> fixes #1458: apoc.load.jdbcUpdate doesn't work with apoc.periodic.iterate

src/main/java/apoc/coll/Coll.java, src/test/java/apoc/coll/CollTest.java
Fixes #1463
- apoc.coll.min and max doing a reduce db call
- Added unit test for max date/datetime
Note 1: I ran some performance test with jmh and could not see any significant impact
Note 2: There is a ton of other places where we can discuss if apoc is implementing "cypher like" operator logic.
=> apoc.coll.min and max comparsion operator logic like cypher

src/main/java/apoc/export/csv/CsvLoaderConstants.java, src/test/java/apoc/export/csv/ImportCsvTest.java
Fixes #1412
Allow dashes in id spaces in CSV headers.
Change the regex for matching id spaces from `\w+` to `[-a-zA-Z_0-9]+`.
=> Allow dashes in id spaces in CSV headers

src/main/java/apoc/cypher/Cypher.java, src/main/java/apoc/export/cypher/ExportCypher.java, src/main/java/apoc/export/util/ExportUtils.java, src/main/java/apoc/index/SchemaIndex.java, src/main/java/apoc/util/QueueBasedSpliterator.java, src/main/java/apoc/util/QueueUtil.java, src/main/java/apoc/util/Util.java, src/test/java/apoc/cypher/CypherTest.java, src/test/resources/enrollment-incremental.cypher
We did use the default thread pool for the thread sending eventually the tombstone object to a queue. If used in a nested way this could lead to a situation when default pool is full that the tombstone sending thread waits for the queue. Queue consumer waits as well -> deadlock situation.
By using a new thread instead we ensure that the tombstone is always sent correctly. Also QueueBasedSpliterator has been refactor and uses `take` instead of `poll`.
=> fix deadlock situation in concurrent executions

src/main/java/apoc/trigger/Trigger.java, src/test/java/apoc/trigger/TriggerTest.java
The kernel event handling creates a big expensive transaction snapshot
for every transaction if there are registered event handlers.
To avoid paying that overhead, unregister from the kernel if there
are no triggers.
This works as a complement to the config option, so you can deploy
large groups of databases with the config enabled but only pay the
overhead on those databases that use trigger.
This is backporting the respective commit from 4.0 branch.
-
-
-
=> Only register with kernel if there are triggers

build.gradle, docs/build.gradle, src/main/java/apoc/coll/Coll.java, src/test/java/apoc/coll/CollTest.java, src/test/java/apoc/meta/CollEnterpriseTest.java
Pipelined and expressionEngine=compiled fail in 4.0.3 for apoc.coll.min/max
This (temporarily) fixes the runtime to `slotted`
=> Fix apoc.coll.min/max limit to slotted runtime

docs/asciidoc/nlp/aws.adoc
The AWS sentiment docs have the wrong procedure in the parenthesis
=> Fix AWS sentiment docs

src/main/java/apoc/export/xls/ExportXls.java, src/main/java/apoc/export/xls/XlsExportConfig.java, src/test/java/apoc/export/csv/ExportXlsTest.java
Fixes #1488 and #1489
For #1488 
- I added a new config param `prefixSheetWithEntityType` that prefix the sheet with the entity type `Node-` / `Rel-`
For #1489 
- I added a new config param `joinLabels` that joint labels for the sheet name (ie `:User:Customer`, become `User,Customer`)
=> fixes #1488 and #1489: Export XLS improvements

src/main/java/apoc/result/VirtualGraph.java, src/test/java/apoc/graph/GraphsTest.java
Fixes #1436
The `VirtualGraph` doesn't manage duplicate entities.
- Transformed `nodes` and `relationships` field of `VirtualGraph` into `Sets`
- Added test case
=> fixes #1436: duplicate nodes in apoc.export.csv.graph from a apoc.create.graph

src/main/java/apoc/load/LoadCsv.java, src/main/java/apoc/load/util/LoadCsvConfig.java, src/main/java/apoc/util/Util.java, src/test/java/apoc/load/LoadCsvTest.java
Fixes #1505
The `skip + limit` exceeds `Long.MAX_VALUE` in case no limit is provided (because the limit default is `Long.MAX_VALUE`)
- Added a check in case `skip + limit > Long.MAX_VALUE`
- Added test case
=> fixes #1505: apoc.load.csv does not skip properly

docs/asciidoc/utilities/static-values.adoc
Static values are no longer stored in the Neo4j configuration file but in the APOC configuration file.
=> static values docs update

src/main/java/apoc/cypher/Cypher.java, src/test/java/apoc/cypher/CypherEnterpriseTest.java
Fixes #1163
- Added `TerminationGuard` right before the query execution
- Added `CypherEnterpriseTest` in order to test it
=> fixes #1163: apoc.cypher.parallel() procedures need tx termination guards

src/test/java/apoc/couchbase/CouchbaseTestUtils.java, src/test/java/apoc/export/cypher/ExportCypherEnterpriseFeaturesTest.java, src/test/java/apoc/load/LoadCsvTest.java, src/test/java/apoc/util/TestContainerUtil.java, src/test/java/apoc/util/UtilIT.java
- Added reference to container IP address instead of `localhost`
- improved logging while we fail to assign the host user to the container
=> fix docker tests on Team City

src/main/java/apoc/load/Jdbc.java, src/main/java/apoc/load/util/LoadJdbcConfig.java, src/test/java/apoc/load/JdbcTest.java
Fixes #1522
make fetchSize configureable for apoc.load.jdbc
- added `fetchSize` and `autoCommit` as configuration params
=> fixes #1522: make fetchSize configureable for apoc.load.jdbc

src/main/java/apoc/periodic/Periodic.java, src/main/java/apoc/util/Util.java
Fix issue with `apoc.periodic.iterate` keeping full intermediate result in memory until the procedure completed. 
Ensure periodic.iterate data is released once the computation completes by using custom classes to capture the data needed for batch processing, and explicitly releasing these on batch completion.
=> Ensure periodic.iterate data is released once the computation completes

src/main/java/apoc/load/Jdbc.java
as it always returns data it should never be optimized away
left loadJdbcUpdate as DBMS to avoid that there, although WRITE might be more correct there.
=> Change load.jdbc back to mode=READ

docs/asciidoc/config.adoc, src/main/java/apoc/ApocConfig.java, src/main/java/apoc/Pools.java
Fixes #1537
- made it configurable via `apoc.jobs.queue.size` property
- reduced the default to threads * 5
=> fixes #1537: Make Pools queue size configurable

src/main/java/apoc/refactor/GraphRefactoring.java, src/test/java/apoc/refactor/CloneSubgraphTest.java
apoc.refactor.cloneSubgraph skipProperties does not observe skipping relationship properties
Fixes #1534
This change enforces skipping of properties on both nodes and relationships
- Not copying skippedProperties on relationships in apoc.refactor.cloneSubgraph  
- Addition of ids to relationships in test case
- Extension of pre-exisitng test to ensure skiped id property is also not copied for relationships
Note: My need for applying this behaviour was driven by the need to use cloneSubgraph on a database with UUIDs on nodes and relationships where skipping of all uuids is essential to allow the clone operation to succeed.
=> #1534 apoc.refactor.cloneSubgraph skipProperties does not observe skipping relationship properties

docs/asciidoc/utilities/hashing.adoc, src/main/java/apoc/hashing/Fingerprinting.java, src/main/java/apoc/hashing/FingerprintingConfig.java, src/test/java/apoc/hashing/FingerprintingTest.java
Followup for fingerprinting:
- added 4 new properties:
- `allNodesAllowList/allNodesDisallowList` for properties common to all Nodes
- `allRelsAllowList/allRelsDisallowList` for properties common to all Relationships
- Fixed a bug in case the `keys` to include in the fingerprint is empty.
- added fingerprint for type `Path`
=> follow-up fingerprint

docs/asciidoc/utilities/collection.adoc, src/main/java/apoc/coll/Coll.java, src/test/java/apoc/coll/CollTest.java
Fixes #1546
Created the new procedure that sorts lists of strings
- created `apoc.coll.sortText`
- added text
- updated documentation
=> fixes #1546: Sorting for international strings

src/main/java/apoc/text/Strings.java, src/test/java/apoc/text/StringsTest.java
Fixes #1493
`A-Z` and `\W` get all non-ASCII chars
- replaced  `A-Z` and `\W` with `\p{L}`
- improved tests
=> fixes #1493: wrong encoding / processing of accentuated characters (diacritics)

docs/asciidoc/utilities/hashing.adoc, src/main/java/apoc/hashing/Fingerprinting.java, src/main/java/apoc/hashing/FingerprintingConfig.java, src/main/java/apoc/util/Util.java, src/test/java/apoc/hashing/FingerprintingTest.java
Added fingerprinting strategy. Now we have two values:
* `EAGER` is as it behaves the old procedure, it evaluates every graph entity.
* `LAZY` is the new one and processed the data only if the graph entity is present into the configuration in `allow` or `disallow` lists
Now we support both allow and disallow configurations, but the user cannot define allow&disallow for the same graph entity
- Added the strategies
- Improved the configuration management
- Updated tests
=> added fingerprint strategy

docs/asciidoc/job-management/trigger.adoc
Replaced deprecated `{}` parameter syntax with `$`  syntax in triggers examples
=> removed deprecated parameters syntax in triggers examples

src/main/java/apoc/periodic/Periodic.java, src/main/java/apoc/trigger/Trigger.java, src/main/java/apoc/util/Util.java, src/test/java/apoc/trigger/TriggerTest.java
Fixes #1556
Added the validation in `add` method
- added validation
=> fixes #1556: request trigger not be saved if syntactically incorrect

build.gradle, src/main/java/apoc/custom/CypherProceduresHandler.java, src/main/java/apoc/custom/Signatures.java
Fixes #1584 
In Neo4j 4.0.5 `org.neo4j.internal.kernel.api.procs.ProcedureSignature` changed the signature adding a boolean at the end and without leaving the old signature in order to maintain the backwards compatibility with version prior to 4.0.5 we use the reflection to create a new instance of the class.
=> fixes #1584: apoc.custom.asProcedure() doesn't work when there is input parameters

src/main/java/apoc/load/Jdbc.java
This fixes potential out of heap issues when using `apoc.load.jdbc()` when used in the outer driving query with `apoc.periodic.iterate()`, and mirrors the change that was applied to the 4.0 branch.
https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/1531
Changes `apoc.load.jdbc()` to READ mode instead of WRITE.
=> Changed apoc.load.jdbc() to READ mode instead of WRITE for 3.5.

core/src/main/java/apoc/CoreApocGlobalComponents.java, core/src/main/java/apoc/index/SchemaIndex.java, core/src/test/java/apoc/trigger/TriggerTest.java, full/src/main/java/apoc/ExtendedRegisterComponentFactory.java, full/src/main/java/apoc/custom/CypherProceduresHandler.java, full/src/main/java/apoc/custom/Signatures.java, full/src/test/java/apoc/cypher/CypherExtendedTest.java, full/src/test/java/apoc/uuid/UUIDTest.java
Fixes
- fixed wrong parameter syntax in Trigger Test
- new TriggerHandler parameters
- full/src/main/java/apoc/ExtendedRegisterComponentFactory.java was missing from the code
- Procedure API has now a "category", set it to "apoc.custom"
- SchemaIndex cursor was missing memory tracker
- 
These tests still fail, perhaps something in the parallel periodic commit in the "UUID.install(addExisting)"
UUIDTest. testAddToExistingNodes
UUIDTest. testAddToExistingNodesBatchResult
UUIDTest. testUUIDListAddToExistingNodes
=> Attempt to fix the 4.2-drop04 build

core/src/main/java/apoc/ApocConfig.java, core/src/main/java/apoc/ApocExtensionFactory.java, core/src/main/java/apoc/ApocSettings.java, core/src/main/java/apoc/CoreApocGlobalComponents.java, core/src/main/java/apoc/cypher/CypherInitializer.java, core/src/main/java/apoc/util/Util.java, core/src/test/java/apoc/cypher/CypherInitializerTest.java, core/src/test/java/apoc/test/EnvSettingRule.java, core/src/test/java/apoc/test/annotations/Env.java, core/src/test/java/apoc/test/annotations/EnvSetting.java, docs/asciidoc/modules/ROOT/pages/operational/init-script.adoc, full/src/main/java/apoc/ExtendedApocGlobalComponents.java
Adding support for db specific cypher initializers.
Side note: also added a custom TestRule that allows for test-method specific env settings via annotations.
Please cherry pick this one for 4.2 as well.
=> db specific initializers

core/src/main/java/apoc/export/util/FormatUtils.java, core/src/test/java/apoc/export/cypher/ExportCypherTest.java
Fixes #1671
Remove number formatting leaving the original representation for Cypher export
- Added test
=> fixes #1671: apoc.export.cypher.all() causes integer is too large error

docs/asciidoc/modules/ROOT/pages/database-integration/bolt-neo4j.adoc, src/main/java/apoc/bolt/Bolt.java, src/main/java/apoc/bolt/BoltConfig.java, src/test/java/apoc/bolt/BoltTest.java
Fixes #1336
- `apoc.bolt.load.fromLocal($url, $localStatement, $remoteStatement, $config)`: which allow to execute a statement into `local` Neo4j instance with the `localStatement` variable and use the result of the execution in order use them in combination with the `remoteStatement` in the `remote` Neo4j instance. **The procedure can be useful when the user needs to call `apoc.bolt.load` more than once (maybe in an unwind) because on each call we create a new Driver (& Session) instance that can slow down the performances, while into the `fromLocal` procedure we create them once**
Please look at the related tests `testLoadFromLocal` and `testLoadFromLocalStream` into the `BoltTest` class
It the `config` contains `streamStatements` as true, the procedure assumes that the output of the …
=> fixes #1336: Create apoc.export.cypher format and outputs optimised for passing to apoc.bolt.execute

src/main/java/apoc/custom/CypherProcedures.java, src/test/java/apoc/custom/CypherProceduresStorageTest.java
This handles loading a stored APOC custom state where
a function or procedure had an Optional.empty() description.
Jackson serialized those to {"present::false}, which then broke
Apocs assumptions about the schema here.
This makes it so we handle any in-the-wild incarnations of this,
and modifies our write path to always ensure the value is a string
When APOC serializes custom function/procedure state, it does this:
```
Map<String, Object> data = map("statement", statement, "mode", signature.mode().toString(), "signature", signature.toString(), "description", signature.description());
```
Which assumes `signature.description()` won't be …
=> Handle Optional.empty() function descriptions

src/main/java/apoc/custom/CypherProceduresHandler.java, src/main/java/apoc/util/Util.java, src/test/java/apoc/custom/CypherProceduresTest.java
Fixes #1555 and #1558 
Fixes the issue and enables repairs for affected users
- Fix typo in `Util.mergeNode` (cause of the issues)
- Let `apoc.custom.removeProcedure` and `apoc.custom.removeFunction` handle existence of multiple records of procedure/function with same name
=> Fixes #1555 and #1558 

full/src/main/java/apoc/ttl/TTLLifeCycle.java
The previus way of always trying to create the TTL index
created unneccessary errors in the logs.
Fixes #1587
Using apoc schema assert to ensure TTL index is present
- CREATE INDEX ON :TTL(ttl) replaced with call apoc.schema.assert({ TTL: ['ttl'] }, null, false) to prevent error being logged on startup
=> Using apoc schema assert to ensure TTL index is present

core/src/main/java/apoc/coll/Coll.java, core/src/test/java/apoc/coll/CollTest.java, docs/asciidoc/modules/ROOT/pages/data-structures/collection-list-functions.adoc
Fixes #1661
Added `apoc.coll.pairWithOffset` procedure and function
- Added the procedure
- Added the function
- Added test
- Updated docs
=> fixes #1661: Add lead/lag function for collections

docs/asciidoc/modules/ROOT/pages/graph-querying/expand-subgraph.adoc
Looks like there is a typo in the documentation.
Looking in the actual code, the "List" in "blackListNodes" should have a lower-case "L". That is, it should be "blacklistNodes" Same case for whitelistNodes
- Config parameters `whiteListNodes` should be `whitelistNodes`
- Config parameters `blackListNodes` should be `blacklistNodes`
Check this [section in documentation](https://neo4j.com/labs/apoc/4.1/graph-querying/expand-subgraph/#expand-subgraph-config)
=> Document Typo apoc.path.subgraph - Config parameters

docs/asciidoc/modules/ROOT/pages/graph-updates/graph-refactoring/merge-nodes.adoc, src/main/java/apoc/refactor/util/PropertiesManager.java, src/main/java/apoc/refactor/util/RefactorConfig.java, src/test/java/apoc/refactor/GraphRefactoringTest.java
Fixes #1572
Added config property in order to prevent the behaviour
- added `preventArrayTypeChange` with default false, so the current behaviour is mantained
- added tests
- updated docs
=> fixes #1572: mergeNodes with combine change array type

core/src/main/java/apoc/util/google/cloud/GCStorageURLConnection.java, docs/asciidoc/modules/ROOT/pages/import/web-apis.adoc
This PR adds the ability to leverage passive authentication if Neo4j is running in Google Cloud, like in the case of running in GCE on a VM host or as a container instance. This simplifies and improves APOC's Google Cloud Storage support by:
- not requiring users to generate private key files for authenticating as a service account, which is generally [frowned upon](https://medium.com/@jryancanty/stop-downloading-google-cloud-service-account-keys-1811d44a97d9) because they do not expire and are hard to track.
- fixes a fundamental logic error causing NullPointerExceptions preventing accessing Google Storage objects (due to calling `getHost()` and not `getAuthority()` on the `URI` instance)
- updates the docs accordingly for the new `authenticationType` options (`NONE`, `PRIVATE_KEY`, …
=> Support passive environmental service account authentication in Google Cloud

core/src/main/java/apoc/util/Util.java, full/src/main/java/apoc/cypher/CypherExtended.java
Fixes #1695
Changed the `runFiles` internals in order to close `Reader` and `Scanner` when the stream ends
- fixed the bug
=> fixes #1695: Apoc.cypher.runFile not closing file handle

core/src/main/java/apoc/util/Util.java, core/src/test/java/apoc/export/cypher/ExportCypherTest.java, core/src/test/java/apoc/util/UtilQuoteTest.java
Fixes #1705 
Checking the [documentation for Cypher](https://neo4j.com/docs/cypher-manual/current/syntax/naming/) the `$` character seems to be forbidden at the start of a Neo4j identifier as opposed to a Java identifier. This causes the issue from #1705.
1. Check in `Util.quote` whether the passed identifier starts with a `$` character and then quote it, even if it is a valid Java identifier
2. Add test cases for the identifier `$lock` and others mentioned in the [documentation for Cypher](https://neo4j.com/docs/cypher-manual/current/syntax/naming/)
3. Ensure that quotes are not applied in cases which previously where not quoted and which do work without quotes. This helps to avoid many test failures e.g. in [`ExportCypherTest`](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/ …
=> fixes #1705: Quote identifiers starting with a dollar character

core/src/main/java/apoc/ApocConfig.java, docs/asciidoc/modules/ROOT/pages/config/index.adoc, docs/asciidoc/modules/ROOT/pages/graph-updates/uuid.adoc, full/src/main/java/apoc/uuid/UuidHandler.java, full/src/test/java/apoc/uuid/UUIDMultiDbTest.java
Added `apoc.uuid.enabled.db_name=false/true` key to `apoc.conf`.
- With `apoc.uuid.enabled=false` and `apoc.uuid.enabled.<db_name>=true`, 
UUID is disabled for all databases except for database with name `db_name`.
- With `apoc.uuid.enabled=true` and `apoc.uuid.enabled.<db_name>=false`, 
UUID is enabled for all databases except for database with name `db_name`.
=> Added apoc.uuid.enabled.db_name=false/true key to apoc.conf

docs/asciidoc/modules/ROOT/pages/graph-updates/graph-refactoring/rename-label-type-property.adoc, src/main/java/apoc/refactor/rename/Rename.java, src/test/java/apoc/refactor/rename/RenameTest.java
Fixes #1387
Improved returned fields and added configuration params.
As the procedures under the hood leverage `apoc.periodic.iterate` I added configuration params in order to allow fine-tuning on this procedure
- Added config params 
- Improved returned messages
- Updated documentation
=> fixes #1387: Failed batches with no error msg from apoc.refactor.rename.type

core/src/main/java/apoc/export/cypher/ExportFileManager.java, core/src/main/java/apoc/export/cypher/FileManagerFactory.java, core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java, core/src/main/java/apoc/util/FileUtils.java, core/src/main/java/apoc/util/s3/S3Aws.java, core/src/main/java/apoc/util/s3/S3OutputStream.java, core/src/main/java/apoc/util/s3/S3Params.java, core/src/main/java/apoc/util/s3/S3ParamsExtractor.java, core/src/main/java/apoc/util/s3/S3UploadUtils.java, core/src/test/java/apoc/export/ExportS3PerformanceTest.java, core/src/test/java/apoc/export/csv/ExportCsvS3Test.java, core/src/test/java/apoc/export/cypher/ExportCypherS3Test.java, core/src/test/java/apoc/export/graphml/ExportGraphMLS3Test.java, core/src/test/java/apoc/export/json/ExportJsonS3Test.java, core/src/test/java/apoc/util/s3/S3TestUtil.java, docs/asciidoc/modules/ROOT/pages/export/csv.adoc, docs/asciidoc/modules/ROOT/pages/export/cypher.adoc, docs/asciidoc/modules/ROOT/pages/export/graphml.adoc, docs/asciidoc/modules/ROOT/pages/export/json.adoc, docs/asciidoc/modules/ROOT/pages/import/web-apis.adoc, docs/asciidoc/modules/ROOT/partials/enableS3Export.adoc
Adds support for S3 as an export destination
Adds the ability to use an S3 location as an export destination for csv, graphml, json, and cypher script.
Includes test coverage.
https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1689
=> Fixes #1689

docs/asciidoc/modules/ROOT/pages/export/csv.adoc, docs/asciidoc/modules/ROOT/pages/export/cypher.adoc, docs/asciidoc/modules/ROOT/pages/export/graphml.adoc, docs/asciidoc/modules/ROOT/pages/export/json.adoc, docs/asciidoc/modules/ROOT/pages/import/web-apis.adoc, docs/asciidoc/modules/ROOT/partials/enableS3Export.adoc, src/main/java/apoc/export/cypher/ExportFileManager.java, src/main/java/apoc/export/cypher/FileManagerFactory.java, src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java, src/main/java/apoc/util/FileUtils.java, src/main/java/apoc/util/s3/S3Aws.java, src/main/java/apoc/util/s3/S3OutputStream.java, src/main/java/apoc/util/s3/S3Params.java, src/main/java/apoc/util/s3/S3ParamsExtractor.java, src/main/java/apoc/util/s3/S3UploadUtils.java, src/test/java/apoc/export/ExportS3PerformanceTest.java, src/test/java/apoc/export/csv/ExportCsvS3Test.java, src/test/java/apoc/export/cypher/ExportCypherS3Test.java, src/test/java/apoc/export/graphml/ExportGraphMLS3Test.java, src/test/java/apoc/export/json/ExportJsonS3Test.java, src/test/java/apoc/util/s3/S3TestUtil.java
Adds support for S3 as an export destination
Adds the ability to use an S3 location as an export destination for csv, graphml, json, and cypher script.
Includes test coverage.
https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1689
=> Fixes #1689: Adds support for S3 as an export destination

core/src/main/java/apoc/ApocConfig.java, core/src/main/java/apoc/ApocExtensionFactory.java, core/src/main/java/apoc/TTLConfig.java, core/src/main/java/apoc/TTLConfigExtensionFactory.java, core/src/test/java/apoc/TTLConfigTest.java, full/src/main/java/apoc/ExtendedApocGlobalComponents.java, full/src/main/java/apoc/ttl/TTL.java, full/src/main/java/apoc/ttl/TTLLifeCycle.java, full/src/test/java/apoc/date/TTLTest.java, full/src/test/java/apoc/ttl/TTLMultiDbTest.java
The current tests in TTLMultiDbTest are super flaky. I think a better way to test this functionality is to check that the config used for scheduling is correct.
So I've pulled out the config and created a function that exposes the config for the current database. This makes the tests more deterministic, which will stop them failing almost every build!
=> Trying to simplify TTL tests by testing the config on its own

core/src/main/java/apoc/util/Util.java, full/src/main/java/apoc/custom/CypherProceduresHandler.java, full/src/test/java/apoc/custom/CypherProceduresTest.java
Fixes #1555 
The pr #1559 has fixed this issue, however this pr was merged in `4.0` but the bug is still present in `4.1` branch.
=> Fixes #1555: apoc.custom.asProcedure doesn't overwrite existing procedure by same name

core/src/main/java/apoc/SystemPropertyKeys.java, full/src/main/java/apoc/custom/CypherProceduresHandler.java, full/src/test/java/apoc/custom/CypherProceduresStorageTest.java
Fixes #1448 
- added "prefix" property to `SystemPropertyKeys.java` to save custom procedures and functions with dot in name
- added tests save procedure and function with dot in name
=> Fixes #1448: apoc.custom.asProcedure is broken for procedure names with '.' in them.

docs/asciidoc/modules/ROOT/partials/usage/apoc.date.format.adoc
Uppercase Y is week-year, lowercase y is what you want.
-
-
-
=> Replaced the incorrect uppercase Y with y in the date formats

core/src/main/java/apoc/trigger/TriggerHandler.java
Fixes #1736 
These are ultimately converted to a Collection
when the Cypher query is executed anyway, so no
real performance advantage to the old way
- Eagerly convert TxData iterables to lists. This gets access to the transaction bound lazy iterables out of the way earlier, to prevent issues when the query is executed.
=> Eagerly convert TxData iterables to lists

core/src/main/java/apoc/export/graphml/XmlGraphMLReader.java, core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
Fixes #1686
- Added condition in `getRelationshipType` method in `XmlGraphReader.java` to entry in `return getRelationshipType(reader)` if an element is not a StartElement or contains key label
- Added test to import file with `defaultRelationshipType `
=> Fixes #1686: graphml import doesn't create the default relationship-type anymore

core/src/main/java/apoc/CoreApocGlobalComponents.java, core/src/main/java/apoc/trigger/TriggerHandler.java, core/src/test/java/apoc/trigger/TriggerTest.java, docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc
Fixes #1731 
Just cherry picked the commit from https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/1573 and resolved the conflicts
- Cherry pick the commit from https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/1573
=> Cherry-pick add a new after-async or async phase to triggers

core/build.gradle
Updated apoc core dependency from commons-configuration2 2.5 to 2.7. 
Elsewhere in the code (and in earlier versions of apoc) 2.7 is used but it seems like updating core was missed for 4.3.
=> bumped commons-configuration2 dependency to version 2.7

docs/asciidoc/modules/ROOT/pages/import/import-csv.adoc
Fixes #1762
Update links to Import CSV in APOC docs to fix 404.
- Adjusted top link `Neo4j import tool’s header format` to [this URL](https://neo4j.com/docs/operations-manual/current/tools/neo4j-admin-import/#import-tool-header-format)
- Adjust bottom link `import tool’s syntax` to the same URL
=> Fix broken links for import CSV formats

build.gradle, docs/asciidoc/antora.yml, full/build.gradle, readme.adoc, test-utils/build.gradle, test-utils/src/main/java/apoc/util/TestContainerUtil.java
Fixes #1758
Version for neo4j-java-driver has been bumped to 4.2.0. Neo4j version has been updated to 4.2.2, too as requested in #1759.
Note: This is the same topic as #1759 which I accidentally closed. I also incorporated the requested changes from #1759 and polished the readme.
=> Fix #1758 by updating neo4j-java-driver and Neo4j versions.

core/src/main/java/apoc/generate/relationship/ErdosRenyiRelationshipGenerator.java
that could cause IndexOutOfBoundExceptions for some values of numberOfNodes over 46341
Fixes #1747
ErdosRenyi generator - fixed integer multiplication overflow
Convert to long before multiplying the int values
=> ErdosRenyi generator - fixed integer multiplication overflow

docs/asciidoc/modules/ROOT/pages/import/import-csv.adoc
Fixes #1785
Improved documentation of `apoc.csv.import`
- fix typo
- clarify the difference between the load/import CSV procedures
=> Fix typo, clarify the difference between the load/import CSV procedures

core/src/main/java/apoc/merge/Merge.java, core/src/test/java/apoc/merge/MergeTest.java
Fixes neo4j-contrib/neo4j-apoc-procedures#1783
Removed double escaping of keys in identPropsString
- Removed double escaping of keys in identPropsString (already done once by Util.quote)
- Created test case
=> Fixes #1783: Removed double escape of identProps in apoc.merge

core/src/main/java/apoc/meta/Meta.java, core/src/test/java/apoc/meta/MetaTest.java
Fixes #1810
- added `entityData.isEmpty()` condition in `collectRelationshipsMetaData()` method, that is, when a node hasn't properties
=> Fixes #1810: CALL apoc.meta.schema returns wrong type with a node without properties

full/src/main/kotlin/apoc/nlp/azure/azure/RealAzureClient.kt
Fixes #1808
The `Content-Type=text/json` does not work anymore. Switched to `application/json` 
- Fixed the problem
=> fixes #1808: APOC NLP functions for Azure cognitive services - Failed - returned HTTP response code: 400

core/src/main/java/apoc/export/csv/CsvEntityLoader.java, core/src/main/java/apoc/export/csv/ImportCsv.java, core/src/test/java/apoc/export/csv/ImportCsvTest.java
Fixes #1803
- improved `nodeCsvId` assignment when `idField` is not present
- added `log.warn()` if `idField` is not present
=> Fixes #1803: `apoc.import.csv` Caused by: java.util.NoSuchElementException: No value present

core/src/main/java/apoc/util/Util.java, core/src/test/java/apoc/diff/DiffTest.java
Fixes #1809
The rebind function needs to disambiguate Virtual graph entities from the real ones.
- fixed the bug
- added tests
=> fixes #1809: Problems with apoc.diff.nodes and Neo4j 4.2

core/src/main/java/apoc/periodic/BatchAndTotalCollector.java, core/src/main/java/apoc/periodic/BatchAndTotalResult.java, core/src/main/java/apoc/periodic/Periodic.java, core/src/main/java/apoc/periodic/PeriodicUtils.java, core/src/test/java/apoc/periodic/PeriodicTest.java, docs/asciidoc/modules/ROOT/pages/overview/apoc.periodic/apoc.periodic.iterate.adoc, docs/asciidoc/modules/ROOT/pages/overview/apoc.periodic/apoc.periodic.rock_n_roll.adoc, full/src/main/java/apoc/periodic/PeriodicExtended.java, full/src/test/java/apoc/periodic/PeriodicExtendedTest.java
This PR has a few pieces to it:
- cherry-picks my previous PR (#1769) to the 4.2 branch
- adds a guard for #1805 to prevent execution with non-sensical concurrency or batch sizes (i.e. < 1)
- tracks the `QueryStatistics` for each consuming transaction and adds parts of it as a new yielded field `updateStatistics`
Some things to note:
- this PR refactors and centralizes some of the batch transaction handling since it was shared with the (deprecated) `apoc.periodic.rock_n_roll` procedure, fixing the same issue that lead to #1769
- schema changes are _not_ include in the statistics as there's no easy way currently to perform them as part of `apoc.periodic.iterate` and `apoc.schema.assert` doesn't properly report them
=> Provide update statistics for apoc.periodic.iterate (issue #1815)

docs/asciidoc/modules/ROOT/partials/usage/apoc.load.html.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.load.html.adoc, full/src/main/java/apoc/load/LoadHtml.java, full/src/test/java/apoc/load/LoadHtmlTest.java, full/src/test/resources/wikipedia.html
Fixes #1793
- added `failsSilently: true/false` config (default `false`). With `true`, will be returned the list of the values, except for values not correctly parsed. In case of errors, will be printed a `log.warn`
- improved the error returned, with `UnsupportedEncodingException`, `FileNotFoundException` and, in case of incorrect parse, with a message containing the incorrect tag
=> Fixes #1793: apoc.load.html procedure fail silently

core/src/main/java/apoc/schema/Schemas.java, core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
Fixes #1657
- Added method `checkIfConstraintNotExists` in `Schemas.java` to remove/kept/create a node key constraint, like unique constraints
=> Fixes #1657: apoc.schema.assert nodekey throws EquivalentSchemaRuleAlreadyExistsException

full/src/main/java/apoc/monitor/Kernel.java
Database read-only property is now dynamic and controlled by set of dynamic settings.
This PR adapts `apoc.monitor.kernel` procedure to use a new API instead of the old one that is gone now.
=> Use newly introduced DatabaseReadOnlyChecker to check if database is read only

docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.schema.node.constraintExists.adoc, docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.schema.node.indexExists.adoc, docs/asciidoc/modules/ROOT/examples/generated-documentation/apoc.schema.relationship.constraintExists.adoc
Fixes errors from the documentation build identified by the linting process.
```
Unresolved xrefs (grouped by origin):
repo: https://github.com/neo4j-contrib/neo4j-apoc-procedures | branch: 4.1 | component: apoc | version: 4.1
path: docs/asciidoc/modules/ROOT/pages/indexes/schema-index-operations.adoc | xref: :overview/apoc.schema.node/apoc.schema.node.constraintExists.adoc
path: docs/asciidoc/modules/ROOT/pages/indexes/schema-index-operations.adoc | xref: :overview/apoc.schema.relationship/apoc.schema.relationship.constraintExists.adoc
path: docs/asciidoc/modules/ROOT/pages/indexes/schema-index-operations.adoc | xref: :overview/apoc.schema.node/apoc.schema.node.indexExists.adoc
```
=> Fixed xref errors

docs/asciidoc/modules/ROOT/pages/graph-updates/ttl.adoc
- Updated examples to use updated procedure names
- Updated expireIn example to time to match description
- Updated expireIn example to use the DIRECTED relationship as if both examples are followed then the second would not work as PRODUCED had already been removed by TTL process
=> Corrected TTL procedure signatures in examples

core/src/main/java/apoc/convert/Json.java, core/src/test/java/apoc/convert/ConvertJsonTest.java
Fixes #1685
Now the paths are sorted by length in decreasing order, 
so the longest paths are retrieved first.
=> Fixes #1685: apoc.convert.toTree() returns incorrect results in 4.1.x.x

core/build.gradle
Fixes #1860
Forcing `json-smart` to the last version `2.4.5`
=> fixes #1860: Upgrade json-smart to avoid security issue

core/src/main/java/apoc/nodes/Nodes.java, core/src/main/java/apoc/refactor/GraphRefactoring.java, core/src/main/java/apoc/refactor/util/RefactorConfig.java, core/src/main/java/apoc/refactor/util/RefactorUtil.java, core/src/main/java/apoc/util/Util.java, core/src/test/java/apoc/refactor/GraphRefactoringTest.java, docs/asciidoc/modules/ROOT/pages/graph-updates/graph-refactoring/merge-nodes.adoc
Fixes #1765
- added `config.isSelfRel()` in `RefactorUtil.java`
- added `config.putIfAbsent("selfRel", false);` in `Nodes.java` to reuse `selfRel` configuration
=> Fixes #1765: apoc.refactor.mergeNodes option to not create self-relationships

core/src/main/java/apoc/math/Maths.java, docs/asciidoc/modules/ROOT/partials/usage/apoc.math.round.adoc
Neo4j's built-in round() function has the same signature since 4.2
=> Deprecate the apoc round function

.github/workflows/auto-cherry-pick.yml
Added auto cherry-picking action: branch 4.1.
In order to merge this, we need to have the branches as much as possible aligned, so it depends on #1830 and the next one that we need to have for branch `4.3`
An example of auto PR created with this action is available here:
https://github.com/conker84/neo4j-apoc-procedures/pull/12
=> Added auto cherry-picking action: branch 4.1

build.gradle
Fixes #1874
Same as #1862 for branch `3.5`
=> fixes #1874: Upgrade json-smart to avoid security issue for Neo4j APOC 3.5 version

core/build.gradle
Fixes #1880
Due to transitive dependency issue, Google Guava is not included into the package anymore so we need to include it manually
=> fixes #1880: 4.1.0.7 / 4.2.0.3 has no apoc.coll package

full/src/main/java/apoc/custom/CypherProceduresHandler.java, full/src/test/java/apoc/custom/CypherProceduresStorageTest.java
Fixes #1744
Fixes #1871
- Added test emulating the issue 1744
- Changed `registeredProcedureSignatures` and `registeredUserFunctionSignatures ` from immutable to mutable Sets
- Simplified logic removing de-register on restoreProcedure and replacing with `registeredProcedureSignatures.remove(signature);` in `registerProcedure()` and `registeredUserFunctionSignatures.remove(signature);` in `registerFunction()`
=> Fixes #1744: Stored procedure error on neo4j restart

core/src/main/java/apoc/ApocConfig.java, core/src/main/java/apoc/util/FileUtils.java, full/src/main/java/apoc/metrics/Metrics.java, full/src/test/java/apoc/metrics/MetricsTest.java
Fixes #1829
Fixes #1544
- Removed `apoc.` prefix in `Metrics.java`
- Added missing dir settings in `ApocConfig.java`
- Changed `unsupported.dbms.directories.neo4j_home` to `dbms.directories.neo4j_home` and commented `dbms.directories.certificates` (not present in neo4j 4.x) in `FileUtils.java`
- Added test to `apoc.metrics.storage` for each `Directory configuration` and with `apoc.metrics.storage(null)`
=> Fixes #1829: Bug in CALL apoc.metrics.storage('dbms.directories.data') due to APOC configuration check

full/src/main/java/apoc/load/LoadDirectory.java
With an updated set of dependencies in the latest version, we have LoadDirectories tests that are failing. This PR updates filters for tests to pass, but not entirely sure if thats the right fix for that.
=> Update load directory filters to match only files

build.gradle, core/src/main/java/apoc/meta/Meta.java, core/src/main/java/apoc/meta/Tables4LabelsProfile.java, core/src/test/java/apoc/meta/MetaTest.java
Fixes #1903
Cleanup apoc.meta.nodeTypeProperties() and apoc.meta.relTypeProperties()
- Make APOC compile on windows
- Code cleanup
=> Cleanup schema sampling procs

core/src/main/java/apoc/util/FileUtils.java, core/src/test/java/apoc/log/Neo4jLogStreamTest.java
Fixes #1749
- Added `Neo4jLogStreamTest`
=> Fixes #1749: In version 4 of the database there is property dbms.directories.neo4j_home without unsupported. prefix

core/src/main/java/org/neo4j/cypher/export/DatabaseSubGraph.java, core/src/test/java/apoc/meta/MetaTest.java
=> Fixes #1952: apoc.meta.stats for 4.1.0.8 fails whereas 4.1.0.3 succeeds when a rel is back ticked

core/src/main/java/apoc/periodic/Periodic.java, core/src/test/java/apoc/periodic/PeriodicTest.java
Extend `apoc.periodic.submit` to accept parameters.
At present, this proc runs a query in a background job, but can only accept raw string Cypher queries.  It is not possible to pass parameters to these background jobs.  All other forms of the procedure require work-arounds, and may for example loop or execute more than once, which is not desired.
This change should be very safe, in that it adds a third (optional) argument to apoc.periodic.submit.  The default is an empty map, so it should be 100% backwards compatible and not affect any existing query patterns.
This is important for using GDS in certain environments, such as with Aura.  In Neo4j, [transactions are tightly coupled to connections](https://trello.com/c/vOV9NLAv/722-connection-transaction-coupling) (internal link only).  This …
=> extend apoc.periodic.submit to accept parameters

core/src/main/java/apoc/SystemPropertyKeys.java, core/src/main/java/apoc/uuid/UuidConfig.java, docs/asciidoc/modules/ROOT/partials/usage/apoc.uuid.install.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.uuid.install.adoc, full/src/main/java/apoc/uuid/Uuid.java, full/src/main/java/apoc/uuid/UuidHandler.java, full/src/test/java/apoc/uuid/UUIDTest.java
Fixes #1901
- Changed `Mode.DBMS` to `Mode.WRITE` to fix the `addToExistingNodes` bug
- Changed `txData.createdNodes()` to `txData.assignedLabels();` to handle uuid with `SET n:LabelName` in `UUIDHandler.java`
=> Fixes #1901: apoc.uuid.install addToExistingNodes does not work

core/src/main/java/apoc/text/SorensenDiceCoefficient.java, core/src/test/java/apoc/text/SorensenDiceCoefficientTest.java
Fixes #1959
Change the Sorensen-Dice coefficient algorithm to consume bigrams as it matches them.
- Implement Comparable on Bigram so we can take advantage of built-in sorting
- Sort the two lists of bigrams
- Consume bigrams as they are matched so we don't cause a cartesian join of matching bigrams
=> Fixes #1959: Score repeated bigrams correctly in apoc.text.sorensenDiceSimilarity

core/src/main/java/apoc/util/Util.java
SecurityContext.allowExecuteAdminProcedure is changing in 4.4 to provide more information than just true / false. 
- Update to reflect this change to the interface . 
- I haven't done so, but it would be possible to use this to provide a better error message if this is desirable.
=> SecurityContext.allowExecuteAdminProcedure is changing in 4.4

core/src/main/java/apoc/util/FileUtils.java, full/src/main/java/apoc/load/LoadDirectory.java, full/src/test/java/apoc/load/LoadDirectoryTest.java
Fixes #1911
- Changed `Paths.get(URI.create(urlDir).getPath());` to `Paths.get(URI.create(urlDir));` in `FileUtils.java`
to avoid `"java c:/ InvalidPathException: Illegal char"` on Windows path
- Changed `encodePath(getDirImport())` to `encodePath(pathImport.toUri().toString())` in `LoadDirectory.java`
to avoid `"java.nio.file.FileSystemNotFoundException: Provider "C" not installed"` on Windows path when an empty string is passed
=> Fixes #1911: apoc.load.directory path to directory not read correctly

full/src/main/java/apoc/monitor/Store.java
Depending on internal layout. Now does cast, will have to be updated when databases of different format than record are available
=> Fix compilation error in apoc.monitor.store()

docs/asciidoc/modules/ROOT/partials/usage/apoc.convert.toTree.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.convert.toTree.adoc
Fixes #1269
- Added "exclude" example and config 
Other stuff are in https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/1290882935629dc91160097aec5936d0138c873b
=> Fixes #1269: Document apoc.convert.toTree

core/src/main/java/apoc/export/csv/CsvFormat.java, core/src/main/java/apoc/export/csv/ExportCSV.java, core/src/main/java/apoc/export/util/ExportConfig.java, core/src/main/java/apoc/export/util/MetaInformation.java, core/src/main/java/apoc/meta/tablesforlabels/PropertyTracker.java, core/src/test/java/apoc/export/csv/ExportCsvTest.java, docs/asciidoc/modules/ROOT/partials/usage/apoc.export.csv.all.adoc
Fixes #536
- Added `sampling` config (default: false). When it's `true`, we use under the hood
the `apoc.meta.nodeTypeProperties` and the `apoc.meta.relTypeProperties` procedure to get the property types
- Fixed wrong test `testExportInvalidQuoteValue`
=> Fixes #536: make export.csv configurable if it computes property types upfront

core/src/main/java/apoc/date/Date.java, core/src/test/java/apoc/date/DateTest.java
=> Fixes #1510: apoc.date.parse gives error when Date is NULL or empty string

core/src/main/java/apoc/meta/Meta.java, core/src/test/java/apoc/meta/MetaTest.java, docs/asciidoc/modules/ROOT/partials/usage/apoc.meta.data.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.meta.schema.adoc
Fixes #1861
Added suffix " (RELATIONSHIP)" only in case of duplicate `labelName/typeRel`
=> Fixes #1861: the procedure of apoc.meta.schema() get wrong result

core/build.gradle, core/src/main/java/apoc/export/csv/CsvFormat.java, core/src/main/java/apoc/export/graphml/XmlGraphMLReader.java, core/src/main/java/apoc/load/util/LoadJdbcConfig.java, core/src/main/java/apoc/number/exact/Exact.java, core/src/main/java/apoc/util/FileUtils.java, core/src/main/java/apoc/util/Util.java, core/src/main/java/apoc/util/google/cloud/GCStorageURLConnection.java, core/src/test/java/apoc/path/SubgraphTest.java, full/src/main/java/apoc/load/LoadDirectory.java, full/src/test/java/apoc/export/csv/ExportCsvTest.java, full/src/test/java/apoc/load/LoadHdfsTest.java, full/src/test/java/apoc/load/relative/LoadRelativePathTest.java, full/src/test/java/apoc/util/HdfsTestUtils.java, test-utils/build.gradle
Fixes `Security vulnerability with Neo4j enterprise 4.2.7` trello card
https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=CVE-2018-10237
`Unbounded memory allocation in Google Guava 11.0 through 24.x before 24.1.1`
=> fixed guava cve

docs/asciidoc/modules/ROOT/pages/import/load-csv.adoc, docs/asciidoc/modules/ROOT/pages/import/load-json.adoc, docs/asciidoc/modules/ROOT/pages/import/xml.adoc
Fixes #1149
This feature exists, but poorly documented 
- Added `failOnError` in `apoc.load.csv` doc
- Added examples for `failOnError` procedures to handle with incorrect url / file
=> Fixes #1149: request apoc.load.json not hard fail if url results in 404

core/src/main/java/apoc/number/Numbers.java, core/src/test/java/apoc/number/NumbersTest.java
=> Fixes #2050: apoc.number.parseFloat throws NullPointerException with null argument

full/src/main/java/apoc/cypher/CypherExtended.java, full/src/test/java/apoc/cypher/CypherExtendedTest.java
=> Fixes #2034: The procedure apoc.cypher.mapParallel2 sometime fails with Unable to complete transaction error

core/src/main/java/apoc/export/csv/CsvEntityLoader.java, core/src/main/java/apoc/export/csv/CsvLoaderConfig.java, core/src/main/java/apoc/export/csv/CsvPropertyConverter.java, core/src/test/java/apoc/export/csv/ImportCsvTest.java, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.import.csv.adoc
Fixes #2074
- Ignore null properties during the import
- Added `ignoreBlankString` config
In addition to the fix, I've added in this pr the handling of `INT[]` and `FLOAT[]` (before they failed due to `Cast Exeption`)
=> Fixes #2074: apoc.import.csv failed for NULL values when using INT datatype with error [null] is not a supported property value

docs/asciidoc/modules/ROOT/nav.adoc, docs/asciidoc/modules/ROOT/pages/transaction/index.adoc
Fixes #1691
To extract these, 
I found the classes that call `Transaction.java` class through a `beginTx()`
and from these I obtained the procedures / functions from which they were used.
=> Fixes #1691: Document (and list) which APOC procs start their own transaction

core/src/main/java/apoc/meta/Meta.java, core/src/test/java/apoc/meta/MetaTest.java, docs/asciidoc/modules/ROOT/partials/usage/apoc.meta.stats.adoc
Fixes #1910
The problem is that `TokenRead.labelCount()` and `TokenRead.relationshipTypeCount()` returns all labels/relTypes (even those deleted).
For consistency with the other results, we should return only labels/relTypes in use.
=> Fixes #1910: apoc.meta.stats return false relationship count when having multi-labeled nodes

core/src/main/java/apoc/periodic/Periodic.java, core/src/test/java/apoc/periodic/PeriodicTest.java, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.periodic.iterate.adoc
Fixes #1238
- Added config planner (If not `DEFAULT` prepend to the `statement` parameter a `cypher planner=[VALUE_OF_CONFIG]` (or `planner=[VALUE_OF_CONFIG]` if the statement already has the `cypher ` options))
Fixed bug in slottedRuntime parser (query with cypher, for example `match (n:cypher) return n`, test case in `PeriodicTest.java` on line 125)
=> Fixes #1238: Update Apoc Periodic to allow for Cypher Planner Switch

core/src/main/java/apoc/ApocConfig.java, core/src/main/java/apoc/export/csv/ExportCSV.java, core/src/main/java/apoc/export/cypher/ExportCypher.java, core/src/main/java/apoc/export/cypher/FileManagerFactory.java, core/src/main/java/apoc/export/graphml/ExportGraphML.java, core/src/main/java/apoc/export/json/ExportJson.java, core/src/test/java/apoc/export/ExportCoreSecurityTest.java, core/src/test/java/apoc/log/Neo4jLogStreamTest.java, full/src/main/java/apoc/export/xls/ExportXls.java, full/src/test/java/apoc/export/ExportFullSecurityTest.java
Fixes #2200
This PR restrict the cases when procedures are allowed to write data into the file system
- Added tests
=> fixes #2200: apoc.export allows writes anywhere in the host filesystem

docs/asciidoc/modules/ROOT/pages/database-integration/redis.adoc, extra-dependencies/redis/build.gradle
=> Fixes #2218: combination of Neo4j 4.3.3 and Redis dependencies causes Neo4j to crash on start (Linux only)

core/build.gradle
Fixes #2215
Forced `org.apache.commons:commons-lang3` version.
=> Fixes #2215: Unable to bring database up in Neo4j 4.3.2 using the `expand-commands' with APOC jar in the plugins directory

full/build.gradle, full/src/main/java/apoc/load/LoadHtml.java
=> Update jsoup to 1.14.2

core/src/main/java/apoc/ApocConfig.java, core/src/main/java/apoc/export/csv/CsvEntityLoader.java, core/src/main/java/apoc/export/csv/CsvHeaderField.java, core/src/main/java/apoc/export/csv/CsvLoaderConstants.java, core/src/main/java/apoc/export/csv/CsvPropertyConverter.java, core/src/main/java/apoc/export/json/JsonImporter.java, core/src/main/java/apoc/load/Mapping.java, core/src/main/java/apoc/load/Xml.java, core/src/main/java/apoc/meta/Meta.java, core/src/main/java/apoc/util/Util.java, core/src/test/java/apoc/export/csv/CsvHeaderFieldTests.java, core/src/test/java/apoc/export/csv/ImportCsvTest.java, core/src/test/java/apoc/export/json/ImportJsonTest.java, docs/asciidoc/modules/ROOT/pages/import/import-csv.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.import.csv.adoc
Fixes #1471
- Added mapping for `point` and `time` types
- The csv can have a column header like propName:time{timezone:+02:00} handled like https://neo4j.com/docs/operations-manual/current/tools/neo4j-admin-import/#import-tool-header-format-properties
- Fixed `JsonImporter.toPoint()` bug (x and y inverted)
- Added `toUpperCase() `in `CsvPropertyConverter.java` to handle array fields with lower case
=> Fixes #1471: Support spatial and temporal datatypes in CSV import (e.g. point, datetime)

docs/asciidoc/modules/ROOT/partials/usage/apoc.meta.schema.adoc
Fixes #2225
Only `sample` config. Other `MetaConfig` are not used.
=> Fixes #2225: Missing documentation for the input parameter of apoc.meta.schema

core/src/main/java/apoc/load/util/LoadCsvConfig.java, core/src/main/java/apoc/util/Util.java, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.load.csv.adoc, full/src/main/java/apoc/load/LoadCsv.java, full/src/test/java/apoc/load/LoadCsvTest.java, full/src/test/resources/test-escape.csv
Fixes #1376
Added `escapeChar` config
=> Fixes #1376: apoc.load.csv cannot parse files with backslash character in the data

core/src/main/java/apoc/export/cypher/ExportCypher.java, core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java, core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java, core/src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java, core/src/main/java/apoc/export/cypher/formatter/CypherFormatter.java, core/src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java, core/src/main/java/apoc/export/util/ExportConfig.java, core/src/test/java/apoc/export/cypher/ExportCypherTest.java, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.export.cypher.all.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.export.cypher.data.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.export.cypher.query.adoc
Fixes neo4j-contrib#2037
Fixes neo4j-contrib#2073
Changed index creation with new syntax
=> Fixes #2037: apoc.export.cypher.all to generate constraints with IF NOT EXISTS

core/src/main/java/apoc/export/util/NodesAndRelsSubGraph.java, core/src/main/java/apoc/meta/Meta.java, core/src/main/java/apoc/result/IndexConstraintRelationshipInfo.java, core/src/main/java/apoc/schema/Schemas.java, core/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java, core/src/main/java/org/neo4j/cypher/export/DatabaseSubGraph.java, core/src/main/java/org/neo4j/cypher/export/SubGraph.java, core/src/test/java/apoc/meta/MetaTest.java, core/src/test/java/apoc/schema/SchemasTest.java
Fixes #2015
- Implemented `getIndexes(RelationshipType type)` in `SubGraph.java`
- Added `relIndexes` in `Meta.java`
- Added lookup index handling
=> Fixes #2015: Various bugs with Neo4j 4.3 indexes

core/src/main/java/apoc/util/kernel/MultiThreadedGlobalGraphOperations.java, core/src/test/java/apoc/util/kernel/MultiThreadedGlobalGraphOperationsTest.java
Storage engine agnostic MultiThreadedGlobalGraphOperations implementation
- MultiThreadedGlobalGraphOperations was accessing record storage specific classes and methods, which won't work with other storage engines going forward. Changed it to use the cursor scan concept and tries to keep the same multi-threaded functionality of it.
=> MultiThreadedGlobalGraphOperations is storage-agnostic

core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java, core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java, full/src/test/resources/signatures.csv
Revert because SHOW INDEXES has higher access mode requirements than db.indexes. Will find another way.
=> Revert "Replace usage of removed db.indexes() with SHOW INDEXES"

docs/asciidoc/modules/ROOT/nav.adoc, docs/asciidoc/modules/ROOT/pages/general-considerations/index.adoc
=> Fixes #2295: Add documentation to indicate that the procedures are not detected by MemoryTracker

full/src/main/java/apoc/uuid/UuidHandler.java
Fixes #2211
Correct the properties that make the uuid handler restoreable after server (re)start.
- In the `add`-Methode inside the `UuidHandler.java` also save the missing `addToSetLabels` property.
=> fix uuid restore on restart (#2211)

core/src/test/java/apoc/spatial/SpatialTest.java, docs/asciidoc/modules/ROOT/pages/misc/spatial.adoc, docs/guide.html, docs/index.html
The `distance` function has been moved to `point.distance` in 5.0. This changes all usages to reflect the change.
=> distance has been replaced with point.distance

core/src/main/java/apoc/export/util/PointSerializer.java
`CoordinateReferenceSystem` is not listed as `@PublicAPI`. This usage was found in an internal Neo4j failing build.
A pending internal PR is changing some constant names to fit with internal naming conventions. Rather than fix it to use the new (still internal) name; this change explicitly checks for the string, minimising direct use, and assumptions, of internals.
=> Remove usage of CoordinateReferenceSystem

core/src/main/java/apoc/hashing/Fingerprinting.java, core/src/test/java/apoc/hashing/FingerprintingTest.java
=> Fixes #2253: apoc.hashing.fingerprintGraph fails if there are equals nodes

build.gradle
module-info.class is not compatible with JDK 1.8
=> Exclude module-info.class from fat jar on 3.5

build.gradle, src/main/java/apoc/util/FileUtils.java
Update packages to fix CVEs
Also, removed unnecessaries `org.apache.commons.httpclient.URIException` and `encodeExceptQM` method.
=> Update packages to fix CVEs

core/src/main/java/apoc/result/VirtualNode.java, core/src/main/java/apoc/result/WrappedNode.java
Public API for org.neo4j.graphdb.Node will be changing for getRelationships calls so that ResourceIterable is returned rather than just Iterable. This is to expose the fact that these calls may leak resources so care should be taken to close them properly.
This change is to ensure that builds do not fail when that API change lands due to compilation failures in APOC
=> Refactor Node implementations to return ResourceIterable pending change in core API Node interface

docs/asciidoc/modules/ROOT/pages/import/xls.adoc, extra-dependencies/xls/build.gradle, full/build.gradle, full/src/main/java/apoc/load/LoadXls.java, full/src/test/java/apoc/export/csv/ExportXlsTest.java, full/src/test/java/apoc/load/LoadFullSecurityTest.java
Fixes #2347
From [documentation](https://poi.apache.org/components/):
```
poi-ooxml requires poi-ooxml-lite. 
This is a substantially smaller version of the poi-ooxml-full jar (ooxml-schemas-1.4.jar for POI 4.0.0, ooxml-schemas-1.3.jar for POI 3.14 or to POI 3.17, ooxml-schemas-1.1.jar for POI 3.7 up to POI 3.13, ooxml-schemas-1.0.jar for POI 3.5 and 3.6). The larger ooxml-schemas jar is normally only required for development. 
Similarly, the ooxml-security jar, which contains all of the classes relating to encryption and signing, is normally only required for development. A subset of its contents are in poi-ooxml-schemas. 
This JAR is ooxml-security-1.1.jar for POI 3.14 onwards and ooxml-security-1.0.jar prior to that.
```
So, I added `poi-ooxml-lite` and removed `poi-ooxml-schemas` …
=> Fixes #2347: Update POI versions

core/src/main/java/apoc/export/cypher/ExportCypher.java, core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java, core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java, core/src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java, core/src/main/java/apoc/export/cypher/formatter/CypherFormatter.java, core/src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java, core/src/main/java/apoc/export/util/ExportConfig.java, core/src/test/java/apoc/export/cypher/ExportCypherTest.java, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.export.cypher.all.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.export.cypher.data.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.export.cypher.query.adoc
Fixes #2037
Cherry-pick: `7a99cad24f869db67d436a0896f4e2c611e27268`
=> Fixes #2037: apoc.export.cypher.all to generate constraints with IF NOT EXISTS (4.4)

core/src/main/java/apoc/export/util/CountingInputStream.java, full/src/test/java/apoc/load/LoadCsvTest.java, full/src/test/resources/taxonomy.csv
Fixes #1674
Wrapped `InputStream` into `BOMInputStream`.
---
I tried to overwrite BOM with null charachter `\ 0`, but it does not work, because the null character is different from "empty character ".
Also, I tried to assign the `cbuf` array with another cleaned and then re-read the portion,
but it doesn't work as well, because the `BufferedReader` under the hood takes the starting array with the BOM (`cb`) and replaces the other cleaned array -> `System.arraycopy(cb, nextChar, cbuf, off, n); `.
Because of this, I opted for the `BOMInputStream`.
=> Fixes #1674: Manage utf8 file with BOM properly

full/src/test/java/apoc/systemdb/SystemDbTest.java
The initial content of the system database has changed, updating tests to reflect this
`SHOW DATABASES` have added columns to the output
=> Update expected systemdb content

core/src/main/java/apoc/RegisterComponentFactory.java, core/src/test/java/apoc/ApocConfigTest.java, core/src/test/java/org/neo4j/test/rule/ImpermanentDbmsRule.java, test-utils/src/main/java/org/neo4j/test/rule/ImpermanentDbmsRule.java
A few methods have moved to the InternalLogProvider and this will fix all related compilation errors.
=> Update Neo4j Logging API usage

full/src/main/java/apoc/couchbase/CouchbaseManager.java
Use StringUtils from apache instead of parboiled.
- Neo4j is removing the parboiled parser, so APOC can no longer depend on parboiled StringUtils.
=> Use StringUtils from apache instead of parboiled.

core/src/main/java/apoc/warmup/Warmup.java, core/src/test/java/apoc/warmup/WarmupTest.java
Also changing tests of the procedure not to assert
the exact number of loaded pages as this is extremely
kernel-internals specific
=> Deprecating apoc.warmup.run procedure

docs/asciidoc/modules/ROOT/pages/misc/text-functions.adoc
Trello issue https://trello.com/c/LBMbuerB/930-https-neo4jcom-labs-apoc-44-misc-text-functions-is-syntactically-incorect
Fix adoc text functions. 
`=` sign trim the string. Added `+` sign between urls.
Also, added `+` in `apoc.text.format` and `apoc.text.random`, because `]` sign stops url string prematurely
=> Fix adoc text functions

core/src/main/java/apoc/result/VirtualNode.java, core/src/main/java/apoc/result/VirtualRelationship.java, core/src/main/java/apoc/result/WrappedNode.java
Core API Node/Relationships will soon get `String getElementId()` methods. This commit implements those methods in:
- VirtualNode
- VirtualRelationship
- WrappedNode
- WrappedRelationship
in order to make things compile. Element IDs as a whole are not yet completely plugged in and functioning tho.
=> Placeholder implementations for Entity#getElementId() for compilation

core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
Fixes a failing test due to too new index syntax.
=> Use 4.2 index syntax

build.gradle
Moved source of truth for Neo4j releases to repo1.maven.org
=> Moved source of truth for Neo4j releases to repo1.maven.org

docs/asciidoc/modules/ROOT/pages/import/web-apis.adoc
Fixes #2424
The com.amazonaws:aws-java-sdk-core:1.11.250 dependency in particular, which dates back to 2017, was riddled with vulnerabilities.
Use the following dependencies:
- com.amazonaws:aws-java-sdk-core:1.12.136 (CVE's are test dependencies, not compile)
- com.amazonaws:aws-java-sdk-s3:1.12.136 (no CVE's)
- org.apache.httpcomponents:httpclient:4.5.13 (CVE's are test dependencies, not compile)
- org.apache.httpcomponents:httpcore:4.4.15 (CVE's are test dependencies, not compile)
- joda-time:joda-time:2.10.13 (no CVE's)
-
-
-
=> Update S3 dependency versions in docs to eliminate CVEs

core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java, core/src/test/java/apoc/export/cypher/ExportCypherTest.java
Fixes #2336 (≥ 4.3)
New syntax. This also fixes the bug.
It's not possible to create test for the fulltext relationship due to `https://github.com/neo4j/neo4j/issues/12304`
=> Fixes #2336: Error when restoring a backup with cypher-shell (≥ 4.3)

.github/workflows/CI.yaml, build.gradle, teamcity-repository.gradle, test-utils/src/main/java/apoc/util/TestContainerUtil.java
Uses TeamCity as artifactory. Only PRs from branches internal to the repo (that means only members of neo4j) will have a green CI, due to them having access to the secrets. If we receive a PR from a fork against dev, the CI will be red.
Note the CI of this same PR is already being run with neo4j 5.0.0 SNAPSHOT.
So we can develop in this repo with confidence we are not breaking things against the latest version of the database.
=> Uses TeamCity as artifactory

core/src/main/java/apoc/result/VirtualNode.java, core/src/test/java/apoc/create/CreateTest.java, docs/asciidoc/modules/ROOT/pages/virtual/virtual-nodes-rels.adoc, full/src/test/kotlin/apoc/nlp/NodeMatcher.kt, full/src/test/kotlin/apoc/nlp/NplUtils.kt, full/src/test/kotlin/apoc/nlp/aws/AWSProceduresAPITest.kt, full/src/test/kotlin/apoc/nlp/aws/AWSProceduresAPIWithDummyClientTest.kt, full/src/test/kotlin/apoc/nlp/aws/AWSVirtualSentimentVirtualGraphTest.kt, full/src/test/kotlin/apoc/nlp/azure/AzureProceduresAPITest.kt, full/src/test/kotlin/apoc/nlp/azure/AzureProceduresAPIWithDummyClientTest.kt, full/src/test/kotlin/apoc/nlp/gcp/GCPProceduresAPITest.kt, full/src/test/kotlin/apoc/nlp/gcp/GCPProceduresAPIWithDummyClientTest.kt
Fixes #2252
- Added doc about update virtual entities
- Added test in nlp with `write: true` to check that there aren't regressions
=> Fixes #2252: Updates on a virtual node created from a real node should not update the original node

full/src/main/java/apoc/cypher/CypherExtended.java, full/src/test/java/apoc/cypher/CypherExtendedTest.java, full/src/test/resources/call_in_transactions.cypher, full/src/test/resources/periodic.cypher
Fixes test that will start failing when `PERIODIC COMMIT` is removed in neo4j
=> Use CALL {} IN TRANSACTIONS instead of PERIODIC COMMIT in test

core/src/main/java/apoc/schema/Schemas.java, core/src/test/java/apoc/schema/SchemasTest.java
Related Trello card: https://trello.com/c/rmXko1UQ/914-s4-enedis-hdr-project-behaviour-of-apocschemaassert-in-42
Drop existing should drops only OTHER indexes, consistent with the documentation and with constraint behaviour.
Instead currently drop also indexes included in the 1st parameter of `apoc.schema.assert()`, and subsequently recreates them.
=> Apoc.schema.assert should drops only indexes not included in the 1st parameter

core/src/main/java/apoc/schema/Schemas.java, core/src/test/java/apoc/schema/SchemasTest.java
Cherry pick for 4.2 https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/5886f7b53a2c629888bac5af257bd54a6347f903
=> Apoc.schema.assert should drops only indexes not included in the 1st parameter (#2523)

.github/workflows/auto-cherry-pick.yml
Auto cherry-pick dev PRs to 4.4 instead of 4.3
=> Simplify APOC auto-cherry-picking (dev)

.github/workflows/auto-cherry-pick.yml
Stop to auto cherry-pick 4.3 PRs to 4.1 and dev
4.1 is not supported anymore and dev will happen through 4.4.
=> Simplify APOC auto-cherry-picking (4.3)

.github/workflows/auto-cherry-pick.yml
Stop to auto cherry-pick 4.2 PRs to 4.1
4.1 is not supported anymore
=> Simplify APOC auto-cherry-picking (4.2)

.github/workflows/CI.yaml, full/src/main/resources/extended.txt
Checks full API listings and archives more test results.
There's a file called `full/src/main/resources/extended.txt` that contains the procedures and functions included in apoc full. It's important this file is up to date in the PRs cause it will be used to package apoc, and if not updated, the `apoc.help` method indicate something is in core while it's not (cause it uses that `extended.txt` file internally).
It is bad practice as that file is kept up to date by a test: `./gradlew test --tests HelpExtendedTest`, but that's a different problem.
This PR ensures we archive all tests from all projects but also that the aforementioned file is kept up to date.
=> Checks full API listings and archives more test results. No AUTO cherry-pick

docs/gradle/wrapper/gradle-wrapper.properties, extra-dependencies/couchbase/gradle/wrapper/gradle-wrapper.properties, extra-dependencies/email/gradle/wrapper/gradle-wrapper.properties, extra-dependencies/mongodb/gradle/wrapper/gradle-wrapper.properties, extra-dependencies/nlp/gradle/wrapper/gradle-wrapper.properties, extra-dependencies/redis/gradle/wrapper/gradle-wrapper.properties, extra-dependencies/xls/gradle/wrapper/gradle-wrapper.properties, full/build.gradle
This PR fixes some Kotlin procedures not being included in the packaging of apoc.
Kotlin procedures weren't being included in the package due to kotlin version targetting old jvm.
=> Fixes Kotlin procedures not being listed in full package. No AUTO cherry-pick

core/src/main/java/apoc/refactor/rename/Rename.java, core/src/test/java/apoc/refactor/CloneSubgraphTest.java, core/src/test/java/apoc/refactor/rename/RenameTest.java, core/src/test/java/apoc/schema/SchemasTest.java, core/src/test/java/apoc/spatial/SpatialTest.java, docs/asciidoc/modules/ROOT/pages/export/gephi.adoc, docs/asciidoc/modules/ROOT/pages/misc/spatial.adoc, docs/asciidoc/modules/ROOT/partials/periodic-commit.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.periodic.commit.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.schema.relationships.adoc, docs/guide.html, docs/index.html
Update APOC syntax to adapt to removal of exists(property) in Neo4j.
=> Rewrite exists(property) to property IS NOT NULL. No AUTO cherry-pick

docs/asciidoc/modules/ROOT/pages/database-integration/bolt-neo4j.adoc, full/src/main/java/apoc/bolt/BoltConfig.java, full/src/test/java/apoc/bolt/BoltTest.java
=> Fixes #2285: apoc.bolt.load from neo4j 4.3.6 to 3.5.29 does not work

core/src/main/java/apoc/schema/Schemas.java, core/src/test/java/apoc/schema/SchemasTest.java
=> Fixes #2405: The apoc.schema.assert procedure fails with multi-label fulltext index

core/src/main/java/apoc/meta/Meta.java, core/src/main/java/org/neo4j/cypher/export/DatabaseSubGraph.java, core/src/main/java/org/neo4j/cypher/export/SubGraph.java
Improve performance apoc.meta.stats 4.x
Changed implementation to leverage on `org.neo4j.internal.kernel.api.TokenRead`,
much faster than "classic" count(n) queries because of planner overhead
=> Improve performance apoc.meta.stats 4.x

core/src/main/java/apoc/util/FileUtils.java, full/src/main/java/apoc/load/LoadDirectory.java, full/src/test/java/apoc/load/LoadDirectoryTest.java
Fixes #2334 (cherry-pick of https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/1973, same cause).
This solves https://trello.com/c/PCtmfQod/861-apocloaddirectory-not-working-in-apoc-4300 issue too.
=> Fixes #2334: apoc.load.directory() fails on Windows

core/src/main/java/apoc/convert/ConvertConfig.java, core/src/main/java/apoc/convert/Json.java, core/src/test/java/apoc/convert/ConvertJsonTest.java, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.convert.toTree.adoc
Fixes #2190
Added `sortPaths` config
=> Fixes #2190: apoc.convert.toTree reorders paths

core/build.gradle, core/src/main/java/apoc/util/FileUtils.java, core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java, core/src/test/java/apoc/trigger/TriggerTest.java, docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc, docs/asciidoc/modules/ROOT/partials/usage/draft/apoc.trigger.add.adoc, full/build.gradle
Fix var tests dev.
- Updated `com.fasterxml.jackson.dataformat` to fix some `ExportCsvTest` java.
- Fixed trigger tests (see `background-operations/triggers.adoc` note)
- Fixed Schemas enterprise tests (due to `SHOW CONSTRAINTS YIELD createStatement` instead of `db. constraints()`, with a different resutl)
- Fixed Metric test 
- Removed unused `jackson-databind`
same as #2647 as @vga91 doesn't have the rights to push on neo4j-contrib repo
=> Fix var tests dev

core/build.gradle, full/build.gradle
- Use the jackson-databind version from Neo4j, to get updated versions of the dependency automatically.
=> Use the jackson-databind version from Neo4j.

core/build.gradle, full/build.gradle
Fixes #2468
Removed `jackson-mapper-asl`, not used (old jackson-databind package)
Removed duplicated  `compile group: 'commons-beanutils', name: 'commons-beanutils', version: '1.9.4'`
=> Fixes #2468: APOC uses Jackson version prior to 2.11 not compatible with latest spring-boot

core/build.gradle, extra-dependencies/nlp/build.gradle, full/build.gradle, test-utils/build.gradle
Fixes CVE-2020-25649
Upgrading some dependencies to mitigate CVE-2020-25649 and another vulnerability
- Upgrade org.reflections from 0.9.11 to 0.9.12
- Upgrade guava from 20.0 to 31.0.1
- Upgrade jackson-module-kotlin to 2.13.1
- Upgrade kotlin from 1.3.71 to 1.6.0
=> Upgrade dependencies to mitigate vulnerabilities

core/src/main/java/apoc/meta/Meta.java, core/src/test/java/apoc/meta/MetaTest.java, docs/asciidoc/modules/ROOT/partials/usage/apoc.meta.stats.adoc
apoc.meta.stats() displays incorrect relationship counts with multi-label nodes
Related Trello card: https://trello.com/c/EMTTTZY4/862-apoc-apocmetastats-displays-incorrect-relationship-counts
Changed rel count handling via `MATCH ()-[r:RELATIONSHIP_TYPE]->() RETURN count(r)`
instead of previous `MATCH (:LabelName)-[r:RELATIONSHIP_TYPE]->() RETURN count(r)` 
(the 2nd count returns the count of rels multiplied by the number of start-node labels)
=> apoc.meta.stats() displays incorrect relationship counts with multi-label nodes

core/src/main/java/apoc/util/FileUtils.java
Fixes #2269
Tested in Neo4j Browser with S3 AWS. Anyway I received positive feedback from the person who opened the issue.
`LoadS3Test` with minio doesn't work due to `Unable to calculate MD5 hash: src/test/resources/ma%25p.json (No such file or directory)` with `%` char.
=> Fixes #2269: apoc.load procedures don't work anymore with urls containing %

docs/asciidoc/modules/ROOT/partials/usage/apoc.coll.sortNodes.adoc
Missing ^ in the documentation for sortNodes ascendingOrder.
- Added ^ in the example for the sortNodes function - ascending order
=> Missing ^ in the example for ascending order

full/src/main/java/apoc/cypher/CypherExtended.java, full/src/test/java/apoc/cypher/CypherExtendedTest.java, full/src/test/resources/create_delete_with_sleep.cypher, full/src/test/resources/create_with_sleep.cypher
Fixes `runFiles` so that the execution happens sequentially, rather than in parallel. 
It wasn't working because of two reasons:
* We were creating a list with streams produced by `runManyStatements`, which starts a thread. Which means all threads were started effectively at the same time for the different files it receives as input.
* `Stream.reduce` doesn't have good semantics to achieve the sequential execution either. On the one hand it's eager (or terminal as they call it in the docs), which means the threads are fired when we call the reduce phase and not when the stream is consumed. On the other hand it asks for associativity, which means we could group operations like (read the `+` as in execute the operation, not just concatenating them, since we have said it's eager):
```
a + b …
```
=> Fixes the Cypher files execution not happening sequentially

core/src/main/java/apoc/export/json/ImportJsonConfig.java, core/src/main/java/apoc/export/json/JsonImporter.java, core/src/test/java/apoc/export/json/ImportJsonTest.java, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.import.json.adoc
Fixes #2325
Added a cleanup config to remove `neo4jImportId`
=> Fixes #2325: added config cleanup

core/src/main/java/apoc/export/json/ImportJsonConfig.java, core/src/main/java/apoc/export/json/JsonImporter.java, core/src/test/java/apoc/export/json/ImportJsonTest.java, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.import.json.adoc
Fixes #2325
Added `nodePropFilter` and `relPropFilter`, 
with key the label / rel-type consistently with `nodePropertyMappings` and `relPropertyMappings`.
The values are the property keys to be filtered.
Resolve the linked issue together with the #2592
=> Fixes #2325: added property filters

.github/workflows/auto-cherry-pick.yml
Uses a personal access token for the service account https://github.com/neo4j-oss-build  when cherry picking.
That should trigger the CI for us automatically when creating the automatic cherry-picks PR, according to the solutions proposed in https://github.com/peter-evans/create-pull-request/issues/48, contrary to what's happening at the moment.
=> Uses service account token when cherry-picking

build.gradle
It ignores the test failures in TeamCity
Because we may have tests muted there and we don't want to see `Process exited with code 1 (Step: gen-artifacts (Gradle))` there in those cases.
=> Ignores test failures only in TeamCity

build.gradle
Cherry-picks #2743 
It ignores the test failures in TeamCity
Because we may have tests muted there and we don't want to see `Process exited with code 1 (Step: gen-artifacts (Gradle))` there in those cases.
=> NO AUTO Ignores test failures only in TeamCity

core/src/main/java/apoc/refactor/util/PropertiesManager.java, core/src/main/java/apoc/refactor/util/RefactorConfig.java, core/src/test/java/apoc/refactor/GraphRefactoringTest.java, docs/asciidoc/modules/ROOT/pages/graph-updates/graph-refactoring/merge-nodes.adoc
Trello issue: https://trello.com/c/7yO7mniS/924-s2cast-softwareapocrefactormergenodes-is-not-producing-desired-output
Added clearer documentation and fixed `mergeRels:true` bug (it should combine also rel-prop):
If properties is a map, properties with a name not included in parameter map are overridden (with an empty map too).
Instead, if properties is null, relationship properties are combined and node properties are overridden (coherently with https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/1051)
=> apoc.refactor.mergeNodes is not producing desired output

core/src/main/java/apoc/load/Mapping.java, core/src/test/java/apoc/export/csv/ImportCsvTest.java
Fixes #2645
Related Trello issue: https://trello.com/c/9kk5cLwh/958-s4govtech-singapore-csv-import-fails-when-parse-an-empty-string-as-a-date
=> Fixes #2645: csv import fails when parse an empty string as a date

core/src/main/java/apoc/path/RelationshipSequenceExpander.java
The public API for PathExpanders will be changing to return a ResourceIterable instead of a simple Iterable.
This will allow the path expansions to be closed and the underlying resources to be released. Currently, any iterators
created during the traversal are not closed and resources could potentially be leaked. The ResourceIterable returned
in this commit will track any iterators created and close them when it is itself closed.
The change needs to be made in APOC first to allow the main neo4j build to proceed.
=> Make PathExpander return ResourceIterable in readiness for Core API changes

core/src/main/java/apoc/algo/PathFinding.java, core/src/test/java/apoc/algo/PathFindingTest.java, docs/asciidoc/modules/ROOT/pages/algorithms/path-finding-procedures.adoc, full/src/main/java/apoc/algo/PathFindingFull.java, full/src/main/resources/extended.txt, full/src/test/java/apoc/algo/PathFindingFullTest.java, test-utils/src/main/java/apoc/algo/AlgoUtil.java
Fixes #2402
Added config 'pointPropName'  in `apoc.algo.aStarConfig` procedure.
Extracted code from org.neo4j.graphalgo.impl.util.GeoEstimateEvaluator
=> Fixes #2402: See if we can make the aStar algorithm support spatial points

core/import/testCypherShellWithCompoundConstraint.cypher, core/import/testNeo4jShellWithCompoundConstraint.cypher, core/import/testPlainFormatWithCompoundConstraint.cypher, core/src/test/java/apoc/export/cypher/ExportCypherEnterpriseFeaturesTest.java, core/src/test/java/apoc/export/cypher/ExportCypherTest.java, core/src/test/resources/init_neo4j_export_csv.cypher
Fix ExportFeatureTests
- Providing constraint names explicitly so that we can check the export contains those explicit names
- In the CI, stop comparing the response's CypherStatement against our expectations: apoc.export.all populates a file and does not return a CypherStatement
=> Exports tests

build.gradle, test-utils/src/main/java/apoc/util/TestContainerUtil.java
Set the neo4j docker image to the latest 4.3 image.
=> Fix Essential Builds 4.3 in TeamCity

build.gradle
Attempt to fix the TeamCity build by reverting the parallelisation of the tests.
- Unparallelise tests
=> Unparallelise tests

docs/asciidoc/modules/ROOT/pages/graph-updates/graph-refactoring/rename-label-type-property.adoc, docs/asciidoc/modules/ROOT/partials/periodic-iterate.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.periodic.iterate.adoc
Trello issues
https://trello.com/c/ugPLYvA1/967-s3wolter-kluwer-apocperiodiciterate-is-blocking
https://trello.com/c/aQgu8Ha6/890-s3deutsches-zentrum-f%C3%BCr-diabetesforschung
=> Missing documentation for apoc.periodic.iterate, regarding the parallel config

docs/asciidoc/modules/ROOT/pages/graph-querying/config-params.adoc, docs/asciidoc/modules/ROOT/pages/graph-querying/expand-spanning-tree.adoc, docs/asciidoc/modules/ROOT/pages/graph-querying/expand-subgraph-nodes.adoc, docs/asciidoc/modules/ROOT/pages/graph-updates/ttl.adoc, docs/asciidoc/modules/ROOT/pages/import/import-csv.adoc, docs/asciidoc/modules/ROOT/pages/overview/apoc.nodes/apoc.nodes.group.adoc, docs/asciidoc/modules/ROOT/pages/virtual/graph-grouping.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.nodes.group.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.nodes.link.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.path.spanningTree.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.path.subgraphNodes.adoc
- Changed `whiteListNodes` to `whitelistNodes` and `blackListNodes` to `blacklistNodes` in `apoc.path.expandConfig` (https://community.neo4j.com/t/apoc-doc-wrong/53319)
- Changed `expireAtInstant` and `expireAfterTimeLength` to `expire` and  `expireIn` (https://trello.com/c/rA9P8JxA/532-docs-bug-ttl-documentation-out-of-date)
- Changed, in `apoc.group.nodes` docs,  default parameter from `[{*=count}, {*=count}]` to ``[{`*`:"count"},{`*`:"count"}]`` and escaped backtick to `&#96`; where needed
- Wrong link in `apoc.group.nodes` overview page
- Added `|===` in `apoc.nodes.link` config adoc
- `ignoreBlankString` absent in `import-csv.adoc`. Anyway I substitute the table with the `config/apoc.import.csv` table, to maintain consistency.
=> Var docs fixes for apoc.path.expand,  apoc.ttl, apoc.import.csv and apoc.nodes

docs/asciidoc/modules/ROOT/pages/import/html.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.load.html.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.load.html.adoc, full/src/main/java/apoc/load/HtmlResultInterface.java, full/src/main/java/apoc/load/LoadHtml.java, full/src/main/java/apoc/load/PlainText.java, full/src/main/java/apoc/load/SelectElement.java, full/src/main/resources/extended.txt, full/src/test/java/apoc/load/LoadHtmlTest.java
Fixes #2384
- Added documentation to explain how to emulate the functions provided by https://github.com/szenyo/neo4jscraperproc with the custom jsoup selectors
- Added `htmlText` configuration to pass an html string as 1st parameter
- Added procedure `apoc.load.htmlPlainText`, with the same syntax as apoc.load.html, to retrieve the plain text similarly to `scraper.getPlainText()` in https://github.com/szenyo/neo4jscraperproc
=> Fixes #2384: Add Scraper procedures to apoc.load.html

core/src/main/java/apoc/result/VirtualRelationship.java, core/src/main/java/apoc/trigger/TriggerMetadata.java, core/src/test/java/apoc/trigger/TriggerTest.java, docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc, full/src/main/java/apoc/trigger/TriggerExtended.java, full/src/main/resources/extended.txt, full/src/test/java/apoc/trigger/TriggerExtendedTest.java
Fixes #2247
Changed TriggerMetadata.rebindDeleted(), not to leverage on `node.getLabels()`, `node.getAllProperties()`, `rel.getAllProperties()` (these fail),
but respectively on `txData.removedLabels()`, `txData.removedNodeProperties()` and `txData.removedRelationshipProperties()`.
- added `rebindDeleted` in `TriggerMetadata.from(..)` to removedRelationshipProperties, removedNodeProperties and removedLabels to leverage on virtual entities.
- added tests in `TriggerTest.java`
Fixes #1152
- added `apoc.trigger.toNode` and `apoc.trigger.toRelationship`  to retrieve labels and props entity infos with phase 'before' and 'after' (via `apoc.any.properties` and `apoc.node.labels` functions), similarly to `TriggerMetadata.rebindDeleted()` function (which is called only with phase 'afterAsync')
- …
=> Fixes #1152 and #2247: Deleting nodes when having an apoc.trigger registered returns Neo.DatabaseError.Transaction.TransactionCommitFailed

docs/asciidoc/modules/ROOT/pages/graph-querying/expand-subgraph-nodes.adoc
Relationship Filters and Label Filters properties are both comma-separated sequences. This is explained, but only in the sequences section, at the very end of the page. I've tried to make the reader aware of sequences earlier, while still allowing them to initially focus on the simpler use-cases.
-
-
-
=> Relationship/Label Filters properties are comma-separated lists

core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java, core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java, core/src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java, core/src/main/java/apoc/export/cypher/formatter/CypherFormatter.java, core/src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java, core/src/main/java/apoc/export/util/ExportConfig.java, core/src/test/java/apoc/export/cypher/ExportCypherTest.java, docs/asciidoc/modules/ROOT/pages/export/cypher.adoc
Fixes #2223
Added configs `saveIndexNames` and `saveConstraintNames`
=> Fixes #2223: Add config option for schema exports to retain the index and/or constraint names

extra-dependencies/build.gradle
JCenter shouldn't be used as a repository for dependencies anymore
Cause it was deprecated and shutdown, as described [here](https://blog.gradle.org/jcenter-shutdown). It's causing problems with our internal builds.
=> Removes jcenter from the repositories used for dependencies

core/src/main/java/apoc/RegisterComponentFactory.java, core/src/main/java/apoc/cypher/CypherInitializer.java, core/src/test/java/apoc/cypher/CypherIsVersionDifferentTest.java, docs/asciidoc/modules/ROOT/pages/installation/index.adoc
Fixes #558
Added a check between neo4j and apoc version. If versions are different, a log warn will be returned.
=> Fixes #558: Check for neo4j version being compatible with neo version

full/src/main/java/apoc/load/LoadHtmlBrowser.java
Forced geckodriver version for selenium,
otherwise a `No proper candidate URL to download geckodriver 0.31.0` will throws.
There seems to be some problem possibly related to this https://github.com/mozilla/geckodriver/issues/2009.
Indeed, on the release page https://github.com/mozilla/geckodriver/releases there is 0.30.0 as latest (instead of 0.31.0), this  appears to be suspicious.
=> Forced geckodriver version

core/src/test/java/apoc/cypher/CypherInitializerTest.java, full/src/test/java/apoc/monitor/TransactionProcedureTest.java, test-utils/src/main/java/apoc/util/CypherInitializerUtil.java
Fix flaky `TransactionProcedureTest.testGetStoreInfo` test after https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/2700.
The `db.executeTransactionally` executed in the pr changed the `apoc.monitor.tx` procedure results.
- Moved `CypherInitializerTest.getInitializer()` to `test-utils`.
- Handled `peakTx`, `lastTxId`, `totalOpenedTx`, `totalTx` differenced before and after `db.executeTransactionally("create ()");` via atomicLong to manage any future changes easier
=> Fix flaky TransactionProcedureTest

core/build.gradle
To avoid confusions that `json-path` 2.4 could be importing `json-smart` 2.3, that included [this](https://nvd.nist.gov/vuln/detail/CVE-2021-27568) security vulnerability and that's why we overrode `json-smart` to 2.4.2 more than one year ago: https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1860
The dependency tree shows 2.3 is evicted by 2.4.8:
```
./gradlew -q full:dependencies // or ./gradlew -q core:dependencies
+--- com.jayway.jsonpath:json-path:2.4.0
|    +--- net.minidev:json-smart:2.3 -> 2.4.8
|    |    \--- net.minidev:accessors-smart:2.4.8
|    |         \--- org.ow2.asm:asm:9.1 -> 9.2
|    \--- org.slf4j:slf4j-api:1.7.25 -> 1.7.30
```
=> Bumps json path to 2.7.0

docs/asciidoc/modules/ROOT/pages/graph-querying/config-params.adoc, docs/asciidoc/modules/ROOT/pages/graph-querying/expand-spanning-tree.adoc, docs/asciidoc/modules/ROOT/pages/graph-querying/expand-subgraph-nodes.adoc, docs/asciidoc/modules/ROOT/pages/import/import-csv.adoc, docs/asciidoc/modules/ROOT/pages/overview/apoc.nodes/apoc.nodes.group.adoc, docs/asciidoc/modules/ROOT/pages/virtual/graph-grouping.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.nodes.group.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.nodes.link.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.path.spanningTree.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.path.subgraphNodes.adoc
Cherry-pick `d12ef6d12e5bd48bb56f3de96a255887dd91a4b2`
I cannot push in `neo4j-contrib`,
anyway it should be not needed to trigger the CI because is a documentation-only pr.
=> Var docs fixes: path.expand, ttl, import.csv and group.nodes

docs/asciidoc/modules/ROOT/pages/graph-querying/config-params.adoc, docs/asciidoc/modules/ROOT/pages/graph-querying/expand-spanning-tree.adoc, docs/asciidoc/modules/ROOT/pages/graph-querying/expand-subgraph-nodes.adoc, docs/asciidoc/modules/ROOT/pages/import/import-csv.adoc, docs/asciidoc/modules/ROOT/pages/overview/apoc.nodes/apoc.nodes.group.adoc, docs/asciidoc/modules/ROOT/pages/virtual/graph-grouping.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.nodes.group.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.nodes.link.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.path.spanningTree.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.path.subgraphNodes.adoc
Cherry pick `d12ef6d12e5bd48bb56f3de96a255887dd91a4b2`
=> Var docs fixes: path.expand, ttl, import.csv and group.nodes (for 4.2)

core/src/main/java/apoc/util/FileUtils.java
Cherry pick: [b6e3c7f38d72aff3b789a7468e87be9c3e90a03d](https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/b6e3c7f38d72aff3b789a7468e87be9c3e90a03d)
=> Fixes #2269: (4.2) apoc.load procedures don't work anymore with urls containing %

core/src/main/java/apoc/util/FileUtils.java
Cherry pick b6e3c7f38d72aff3b789a7468e87be9c3e90a03d
=> apoc.load procedures don't work anymore with urls containing %

core/src/main/java/apoc/result/VirtualRelationship.java, core/src/main/java/apoc/trigger/TriggerMetadata.java, core/src/test/java/apoc/trigger/TriggerTest.java, docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc, full/src/main/java/apoc/trigger/TriggerExtended.java, full/src/main/resources/extended.txt, full/src/test/java/apoc/trigger/TriggerExtendedTest.java
Cherry pick 36b036afd73f69c75eb7324b2fbf81108c1d7a59, Fixes https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1152 and https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/2247
=> Deleting nodes when having an apoc.trigger registered returns Neo.DatabaseError.Transaction.TransactionCommitFailed (#2596)

docs/asciidoc/modules/ROOT/pages/graph-updates/graph-refactoring/rename-label-type-property.adoc, docs/asciidoc/modules/ROOT/partials/periodic-iterate.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.periodic.iterate.adoc
Cherry pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/015f6778f39f6ebd514f852a8e376b8ade807682
=> Missing documentation for apoc.periodic.iterate, regarding the parallel config for 4.2 (#2818)

core/src/test/java/apoc/load/XmlTest.java, docs/asciidoc/modules/ROOT/partials/usage/apoc.load.xml.adoc
Fixes #2723
Added more doc and tests about xpath, in order to use streaming
=> Fixes #2723: apoc.load.xml on large file generates OoM Errors

core/src/main/java/apoc/refactor/GraphRefactoring.java, core/src/test/java/apoc/refactor/GraphRefactoringTest.java
=> Fixes #2699: The apoc.refactor.mergeNodes remove entities if a list with 2 equal nodes is passed

full/src/main/java/apoc/load/LoadHtmlBrowser.java
restore forced firefoxdriver
Now the issue related to https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/2859 no longer seems present
=> restore forced firefoxdriver

docs/asciidoc/modules/ROOT/pages/temporal/datetime-conversions.adoc, docs/asciidoc/modules/ROOT/pages/temporal/temporal-conversions.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.nodes.cycles.adoc
Fixes #2748
Other docs fixes:
- image in `apoc.nodes.cycles.adoc`
=> Fixes #2748: apoc.temporal.toZonedTemporal missing in temporal docs page

core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java, core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java, core/src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java, core/src/main/java/apoc/export/cypher/formatter/CypherFormatter.java, core/src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java, core/src/main/java/apoc/export/util/ExportConfig.java, core/src/test/java/apoc/export/cypher/ExportCypherTest.java, docs/asciidoc/modules/ROOT/pages/export/cypher.adoc
Fixes #2223
Same as https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/2652 for 4.3.
Since starting from 4.3 there are indexes on relations, I added the possibility to save the names of the indexes on them as well.
In this case `saveIndexName` saves both nodes and rels indexes.
Maybe it's worth inserting a `saveRelIndexName` (and / or renaming `saveIndexName` to `saveNodeIndexName`), 
to differentiate between saving node indexes and relations?
=> Fixes #2223: Add config option for schema exports to retain the index and/or constraint names (#2652)

docs/asciidoc/modules/ROOT/pages/graph-updates/graph-refactoring/rename-label-type-property.adoc, docs/asciidoc/modules/ROOT/partials/periodic-iterate.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.periodic.iterate.adoc
I cannot push in `neo4j-contrib`,
anyway it is not needed to trigger the CI because is a documentation-only pr.
Cherry pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/015f6778f39f6ebd514f852a8e376b8ade807682
=> Missing documentation for apoc.periodic.iterate, regarding the parallel config for dev (#2818) 

docs/asciidoc/modules/ROOT/pages/graph-updates/graph-refactoring/rename-label-type-property.adoc, docs/asciidoc/modules/ROOT/partials/periodic-iterate.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.periodic.iterate.adoc
Cherry pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/015f6778f39f6ebd514f852a8e376b8ade807682
=> Missing documentation for apoc.periodic.iterate, regarding the parallel config for 4.3 (#2818)

core/src/main/java/apoc/export/csv/CsvLoaderConfig.java, core/src/main/java/apoc/export/csv/CsvPropertyConverter.java, core/src/test/java/apoc/export/csv/ImportCsvTest.java, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.import.csv.adoc
Fixes #2817
Also, added tests for arrays, to check consistency with `neo4j-admin import` tool.
=> Fixes #2817: When importing a string array field with a blank value, the attribute value is interpreted as [""] instead of NULL as expected

core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java, core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java, core/src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java, core/src/main/java/apoc/export/cypher/formatter/CypherFormatter.java, core/src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java, core/src/main/java/apoc/export/util/ExportConfig.java, core/src/test/java/apoc/export/cypher/ExportCypherTest.java, docs/asciidoc/modules/ROOT/pages/export/cypher.adoc
Cherry pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/b28604a7f23b473931590a1fb9fc21a3b9127274
=> Fixes #2223: Add config option for schema exports to retain the index constraint names (#2892)

core/src/main/java/apoc/cypher/CypherInitializer.java, core/src/test/java/apoc/cypher/CypherIsVersionDifferentTest.java
=> Fixes #2878: apoc 4.4.0.4 is reported as incompatible with neo4j-community-4.4.6 in neo4j.log

core/src/main/java/apoc/refactor/GraphRefactoring.java, core/src/main/java/apoc/util/Util.java, core/src/test/java/apoc/refactor/GraphRefactoringEnterpriseTest.java, core/src/test/java/apoc/refactor/GraphRefactoringTest.java
Fixes #2797
Fixes #2780
Tested in the procedures with `tx.createNode()` and `tx.createNode(label)`, 
excluding those concerning the system db and virtual entities.
The error is not present in `apoc.create. *`,, `apoc.generate. *`
`apoc.nodes.link`,` apoc.refactor. * `. `apoc.generate.`
The error is instead present, as well as in the `apoc.refactor. *` also in `apoc.import.graphml / csv` (created separated issue for export procs).
Regarding the refactor procs the error is caused by the catch that silently fails the procedure:
```
try {
final Node node = tx.createNode(Util.labels(labelNames));
.....
return Stream.of(new NodeResult(setProperties(node, props)));
} catch (Exception e) {
return result.withError(e);
}
```
Note that regarding the issue `2797` case, even with this pr `cloneNodes` …
=> Fixes #2797 and #2780: Graph Refactoring procedures internally handle errors instead of throwing them, leaving half-created results

core/src/main/java/apoc/export/graphml/ExportGraphML.java, core/src/main/java/apoc/export/graphml/XmlGraphMLReader.java, core/src/main/java/apoc/export/graphml/XmlGraphMLWriter.java, core/src/main/java/apoc/export/graphml/XmlNodeExport.java, core/src/main/java/apoc/export/util/ExportConfig.java, core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java, docs/asciidoc/modules/ROOT/pages/export/graphml.adoc, docs/asciidoc/modules/ROOT/partials/roundtripSeparatedGraphml.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.import.graphml.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.import.graphml.adoc
Fixes #2659
Added 2 configs `source` and `target` with keys `label` and (optional) `id` to import rel-only files, e.g.:
```
call apoc.import.graphml("rels.graphml", {startLabel: 'Person', endLabel: 'Movie'})
```
Added same config for export graphml procs (currently with only `id` key) to export a custom property instead of current "n<internalId>" as a source / target attribute value
=> Fixes #2659: Apoc.import.graphml doesn't work for edges

docs/asciidoc/modules/ROOT/pages/graph-updates/graph-refactoring/rename-label-type-property.adoc, docs/asciidoc/modules/ROOT/partials/periodic-iterate.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.periodic.iterate.adoc
Cherry pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/015f6778f39f6ebd514f852a8e376b8ade807682
=> Missing documentation for apoc.periodic.iterate, regarding the parallel config for 4.1 (#2818)

docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc
Currently the config `apoc.trigger.refresh` is not present [in the main page](https://neo4j.com/labs/apoc/4.4/background-operations/triggers/).
Added `apoc.trigger.refresh` note, as for [the add page](https://neo4j.com/labs/apoc/4.4/overview/apoc.trigger/apoc.trigger.add/#_enable_triggers)
=> Added apoc.trigger.refresh note in the trigger adoc initial page

extra-dependencies/bolt/build.gradle, extra-dependencies/hadoop/build.gradle, extra-dependencies/selenium/build.gradle, full/build.gradle
Fix failing extra-dependencies in dev
- Changed `compile` to `implementation`
- Changed `bolt` dependency consistently with `full/build.gradle` dep.
- Updated `neo4j-java-driver-slim` to `4.4.5` in `extra-dependencies` and `full` gradle
=> Fix failing extra-dependencies in dev

extra-dependencies/bolt/build.gradle, extra-dependencies/bolt/gradle/wrapper/gradle-wrapper.properties, extra-dependencies/hadoop/build.gradle, extra-dependencies/hadoop/gradle/wrapper/gradle-wrapper.properties, extra-dependencies/selenium/build.gradle, extra-dependencies/selenium/gradle/wrapper/gradle-wrapper.properties
Fix shadow and java version for dev 5.0
Update `javaVersion`, `distributionUrl` and `com.github.johnrengelman.shadow` consistent with the other `gradle`
=> Fix shadow and java version for dev 5.0

core/src/test/java/apoc/schema/SchemasTest.java
Adapts test expectations to changes in https://github.com/neo-technology/neo4j/pull/15722 where 'GENERAL', 'UNIQUE' and 'TOKEN' prefixes are removed from index type descriptions.
=> Remove 'GENERAL' and 'TOKEN' prefixes from test

docs/asciidoc/modules/ROOT/pages/cypher-execution/cypher-based-procedures-functions.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.custom.asFunction.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.custom.asProcedure.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.custom.declareFunction.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.custom.declareProcedure.adoc
Fixes #2895
- Moved deprecated parts on the specific `apoc.custom.asFunction/Procedure` usage pages
- Fixed some wrong queries  (e.g. `CALL custom.answer YIELD row`)
- Updated deprecated queries
- Added `defaultValue` explanation 
- Added example for `mode` parameter (declareProcedure) and `forceSingle` (declareFunctiom) and `description` (both)
=> Fixes #2895: update apoc.custom.* documentation

core/build.gradle
Cherry-picks #2881 
To avoid confusions that `json-path` 2.4 could be importing `json-smart` 2.3, that included [this](https://nvd.nist.gov/vuln/detail/CVE-2021-27568) security vulnerability and that's why we overrode `json-smart` to 2.4.2 more than one year ago: https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1860
The dependency tree shows 2.3 is evicted by 2.4.8:
```
./gradlew -q full:dependencies // or ./gradlew -q core:dependencies
+--- com.jayway.jsonpath:json-path:2.4.0
|    +--- net.minidev:json-smart:2.3 -> 2.4.8
|    |    \--- net.minidev:accessors-smart:2.4.8
|    |         \--- org.ow2.asm:asm:9.1 -> 9.2
|    \--- org.slf4j:slf4j-api:1.7.25 -> 1.7.30
```
=> NO AUTO: Bumps json path to 2.7.0 (#2881)

build.gradle
Excludes selenium tests from TeamCity if flag passed. The idea is to have two steps in the build:
```
1. gradlew test -PexcludeSeleniumTests
2. gradlew test --tests LoadHtmlTest --tests LoadHtmlTestParameterized
```
So that we are able to have a different docker image for 1. and 2. The reason for that is some tests in 1. need to span a new docker container (dependencies, neo4j itself, etc), which requires root containers, and 2. explicitly requires non root access for emulating Chrome browsers (for safety reasons)
=> Excludes selenium tests in TeamCity

core/src/main/java/apoc/refactor/GraphRefactoring.java, core/src/test/java/apoc/refactor/GraphRefactoringTest.java
Fixes #3000
The bug appeared with [this pr](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/2845/files), in which i've added explicit transaction where needed.
In the issue case, the nodes included in the `apoc.refactor.cloneNodes` are connected to each other,
so we have to close the node creation's transaction first, 
and after we can create "mixed" relationships between the original and cloned nodes.
=> Fixes #3000: apoc.refactor.cloneNodes withRelationships = true - hangs and does not complete call

core/src/main/java/apoc/export/csv/CsvEntityLoader.java, core/src/main/java/apoc/export/csv/CsvLoaderConfig.java, core/src/test/java/apoc/export/csv/ImportCsvTest.java
Fixes #2932
- Leverage on `CsvReader` to skipLines, 
because `CountingReader.skip(n)` calls `java.io.FilterReader.skip(n)`, which skip characters instead of lines.
removing the `CountingReader.skip` is not a breaking-change because by default is `skip(0)`, so the `CountingReader` skip nothing actually. 
- changed deprecated API `CSVReader` to `CSVReaderBuilder`
=> Fixes #2932: The apoc.import.csv skipLines config doesn't work correctly

full/src/test/java/apoc/ttl/TTLMultiDbTest.java
In 5.0 the ddl to create database in "standalones" became async, and this is causing
some tests to fail.
=> Add wait to create databases

core/src/main/java/apoc/export/csv/CsvEntityLoader.java, core/src/main/java/apoc/export/graphml/XmlGraphMLReader.java, core/src/main/java/apoc/export/util/BatchTransaction.java, core/src/test/java/apoc/export/csv/ImportCsvTest.java, core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java
=> Fixes #2826: The apoc.import.csv/graphml procedures create empty wrong empty nodes with UNIQUE constraint violation

test-utils/src/main/java/org/neo4j/test/rule/DbmsRule.java
=> Add mode to DbmsRule

full/src/main/java/apoc/custom/Signatures.java, full/src/test/java/apoc/custom/CypherProceduresTest.java
=> Fixes #2966: apoc.custom.declareProcedure does not accept default float values

core/build.gradle, docs/asciidoc/modules/ROOT/pages/database-integration/bolt-neo4j.adoc, docs/asciidoc/modules/ROOT/pages/database-integration/couchbase.adoc, docs/asciidoc/modules/ROOT/pages/database-integration/mongo.adoc, docs/asciidoc/modules/ROOT/pages/database-integration/mongodb.adoc, docs/asciidoc/modules/ROOT/partials/mongodb-dependencies.adoc, extra-dependencies/couchbase/build.gradle, extra-dependencies/hadoop/build.gradle, extra-dependencies/mongodb/build.gradle, extra-dependencies/nlp/build.gradle, full/build.gradle, full/src/main/java/apoc/couchbase/CouchbaseManager.java, full/src/main/java/apoc/mongodb/MongoDBColl.java, full/src/main/kotlin/apoc/nlp/aws/AWSVirtualSentimentVirtualGraph.kt, test-utils/build.gradle
Cherry pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/c6595221354b38dfbc6f776b305c33a38a03b475
=> (NO AUTO) Upgrades packages and adocs for CVE extra-deps (#2989)

core/src/test/java/apoc/convert/ConvertJsonTest.java
Implied grouping keys are deprecated and will be removed in a future version. Read more about it here: https://neo4j.com/docs/cypher-manual/current/deprecations-additions-removals-compatibility/#_deprecated_features
- Update test which uses deprecated implied grouping keys.
=> Update test using ambiguous aggregation expression

core/build.gradle
Solves https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/3048
Also checked that this problem is present in dev, so this will be cherry picked there.
=> Forces dependency to especific version to avoid binary incompatibilities

.github/workflows/CI.yaml, build.gradle, full/build.gradle, test-utils/build.gradle
* Bumps neo4j and driver version.
* Forces cache refresh in CI, because the current key would not pick up changes in .gradle files for example.
=> NO AUTO Bump neo4j and driver version, force cache refresh in CI

.github/workflows/CI.yaml
Removes the fallback of the cache in the CI.
The cache works by getting a combined hash of the `.gradle` and `.gradle-wrapper.properties` files.
If you modify .gradle files, and the hash is xyz, then if the cache does not find that key linux-gradle-xyz, this line was making it default to the latest hash available for linux-gradle, which would still have old dependencies.
=> NO AUTO Forces cache refresh in the CI

test-utils/src/main/java/apoc/util/Neo4jContainerExtension.java, test-utils/src/main/java/apoc/util/TestContainerUtil.java
Neo4j 5.x reconciler is eventually consistent now, which means on startup we cannot assume neo4j will be ready and we have to wait for it to be.
The inspiration for this came from the official [neo4j-docker](https://github.com/neo4j/docker-neo4j/blob/e3ed8c1c21709e6108f909d7ec7a2477e02d2fb9/src/test/java/com/neo4j/docker/utils/StartupDetector.java) test utils. Thanks @gfx54b for the help.
=> NO AUTO Makes container wait for neo4j database ready

build.gradle
Upgrades json-smart to 2.4.8, 2.4.2 had a vulnerability
=> Upgrades json-smart dependency

full/src/test/java/apoc/ttl/TTLMultiDbTest.java, full/src/test/java/apoc/uuid/UUIDMultiDbTest.java
Opens a session against `system` database directly before the `CREATE DATABASE` statements.
Reconcilarion and instance startup are async in Neo4j 5.x. In 5.x when the DBMS is started and bolt port is opened the only guarantee is that system is available.
=> NO AUTO Tries to deflake CREATE DATABASE tests

core/src/main/java/apoc/diff/Diff.java, core/src/test/java/apoc/diff/DiffTest.java
Fixes #2992
- Changed `equals` with `deepEquals`, in order to compare arrays
=> Fixes #2992: apoc.diff.nodes() returns list-type properties as different when they are the same

core/src/main/java/apoc/export/cypher/FileManagerFactory.java, core/src/test/java/apoc/export/csv/ExportCsvNeo4jAdminTest.java, core/src/test/java/apoc/export/csv/ExportCsvTest.java
Fixes #3070
If the file has at leas one dots, eg "test.ccc" / "test.foo.bar.ccc", 
via `FilenameUtils.getExtension` we consider the "ccc" part to be appended to `fileName.nodes.LABELNAME`.
If the file has no dots, I simply attach `.nodes.LABELNAME` to it.
- Added tests with multiple points in the filename
- Changed `DbmsRule` from `@ClassRule` to `@Rule` in order to recreate the dataset and avoid conflicts
=> Fixes #3070: The apoc.export.csv.all with bulkImport config doesn't work with a file name without extension

common/src/main/java/apoc/log/Neo4jLogStream.java
cherry-pick: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3080
=> vuln-fix: Partial Path Traversal Vulnerability (#3080)

core/build.gradle, core/src/main/java/apoc/ApocConfig.java, core/src/main/java/apoc/ApocSettings.java, core/src/main/java/apoc/load/Xml.java, core/src/main/java/apoc/util/FileUtils.java, core/src/main/java/apoc/util/Util.java, core/src/test/java/apoc/load/LoadJsonTest.java, readme.adoc
Cherry picks #2467
Uses Neo4j internal option `unsupported.dbms.cypher_ip_blocklist`, which consists on a list of ip addresses in CDIR notation, i.e. ip + mask for subnets, e.g. `192.167.2.3/8, 192.234.3.123/16`. When using the `apoc.load.json(url)` command, the url will be looked up in a DNS resolver and we will fail if it is on the list of blocked ip addresses.
To prevent users trying to load data from any url. To completely block all ipv4 and ipv6 addresses one should use:
```
unsupported.dbms.cypher_ip_blocklist=0.0.0.0/0,::/0
```
=> NO AUTO Adds blocklist for load methods

build.gradle
Jackson-databind was removed in https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/2668 (probably by mistake), so ever since 3.5 produces a runtime error when using this apoc version:
```
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'apoc.ApocKernelExtensionFactory$ApocLifecycle@6e495b48' was successfully initialized, but failed to start. Please see the attached cause exception "com.fasterxml.jackson.core.type.TypeReference".
at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
at org.neo4j.kernel.extension.AbstractKernelExtensions.start(AbstractKernelExtensions.java:82)
at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:45 …
```
=> NO AUTO Brings back jackson databind

.github/CODEOWNERS
To control who approves workflows that touch sensible things, like CI workflows, by request of the security team
=> NO AUTO Adds CODEOWNERS

extended/src/test/java/apoc/systemdb/SystemDbTest.java
Declare all the columns we are using in YIELD. There is no reason for this test to fail just because we added a column to SHOW DATABASES.
- As above
=> Make SystemDbTest less fragile

common/src/main/java/apoc/util/Util.java, extended/src/test/java/apoc/systemdb/SystemDbTest.java
SHOW DATABASES has a couple of breaking changes in 5.x
* role is now simply 'primary' or 'secondary'
* writer is used to determine the leader
* error is now statusMessage
I made the SystemDBTest even simpler than before, which I think is fine because it's just really testing the ability to execute _something_ there.
=> Adapt to breaking changes to SHOW DATABASES

core/src/main/java/apoc/refactor/GraphRefactoring.java, core/src/main/java/apoc/refactor/rename/Rename.java, core/src/main/java/apoc/schema/Schemas.java, core/src/main/java/apoc/util/Util.java, core/src/test/java/apoc/refactor/GraphRefactoringTest.java, core/src/test/java/apoc/refactor/rename/RenameTest.java, core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java, core/src/test/java/apoc/schema/SchemasTest.java, core/src/test/java/apoc/util/UtilTest.java
Cherry Picked: https://github.com/neo4j/apoc/pull/2
=> Sanitize back-ticks in strings when there is a possibility of Cypher injection 

full/src/main/java/apoc/custom/CypherProcedures.java, full/src/test/java/apoc/custom/CypherProceduresTest.java
=> Fixes #2605: The apoc.custom.declareProcedure throws exception "Query results do not match requested output" with some queries

extended/src/main/java/apoc/uuid/Uuid.java
This method has been removed from core, but was still used from this single file,
so re-added it as a private method so it will still compile when we release
a new APOC core.
=> Add private method removed from APOC core

core/src/main/java/apoc/meta/Meta.java
Fixed `nodes.next()` in `apoc.meta.graph`.
In 4.4 the `apoc.meta.graph` is sometimes slower because of different retrieve order of `tx.findNodes()` (line 1114).
This causes several more iterations to return the condition ` if (otherNode.hasLabel(labelToLabel)) return true;` (line 1126), because the `next()` method is called after the `if(count % sample == 0)` and then the `while (nodes.hasNext())` cycles empty several times.
This decrease performance significantly, according to the order of `findNodes`.
Most important thing, the `next()` inside the `count % sample == 0` block is a bug because we only extrapolate the first n nodes instead of a node each n.
=> Fixed nodes.next() in `apoc.meta.graph`

core/src/main/java/apoc/temporal/TemporalProcedures.java, core/src/main/java/apoc/util/DateFormatUtil.java, core/src/main/java/apoc/util/DurationFormatUtil.java, core/src/test/java/apoc/temporal/TemporalProceduresTest.java, docs/asciidoc/modules/ROOT/partials/usage/apoc.temporal.formatDuration.adoc
Fixes neo4j/apoc#25
Cherry-pick of https://github.com/neo4j/apoc/commit/6b7436530410c996c310e99357cb0c7b920799db and https://github.com/neo4j/docs-apoc/commit/ff8605b1f639e3e15d039df52ea8ea666243de79
=> Fixes neo4j/apoc#25: Incorrect behaviours for format durations (neo4j/docs-apoc#29) (neo4j/apoc#179)

full/build.gradle
Fixes CVE-2022-25857
Fixes CVE-2022-38749
Fixes CVE-2022-38750
Fixes CVE-2022-38751
Fixes CVE-2022-38752
=> [d7Ivq7cM] Bump snakeyaml in extended APOC

core/src/test/java/apoc/text/StringsTest.java
Before this PR test was expecting the incorrect value of distance. 
As a result, https://issues.apache.org/jira/browse/TEXT-191 and the new commons-text test is updated with the correct expected value.
=> Update testJaroWinklerDistance test expectation

core/build.gradle
Update commons-text version
In order to fix `testJaroWinklerDistance` after [this pr](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3231) ,
because in 4.4, if we don't explicit it, version 1.9` is picked
=> Update commons-text version

core/src/main/java/apoc/refactor/rename/Rename.java, core/src/test/java/apoc/refactor/rename/RenameTest.java
Cherry-pick https://github.com/neo4j/apoc/commit/d54b804af2e259b50af51b8e33b7ec6475b3250a
=> [pDw6xmRG] Fixes neo4j/apoc#26: apoc.refactor.rename.label delets label if oldLabel is equal to newLabel

full/src/main/java/apoc/metrics/Metrics.java, full/src/test/java/apoc/metrics/MetricsTest.java
Added check to prevent reading from outside metrics directory
=> [H10zCpAQ] Fix CWE-73: Added check to prevent reading from outside metrics directory

core/src/main/java/apoc/cypher/CypherInitializer.java, core/src/test/java/apoc/cypher/CypherIsVersionDifferentTest.java, full/src/test/java/apoc/monitor/TransactionProcedureTest.java
This has been requested by Neo4j Aura, which couldn't see if the procedure call came from APOC or a user
Cherry-pick of https://github.com/neo4j/apoc/pull/219
=> [4HrPR2Rm] Use internal function instead of procedure for compatibility

core/src/main/java/apoc/export/json/JsonImporter.java, core/src/test/java/apoc/export/json/ImportJsonEnterpriseTest.java, core/src/test/java/apoc/export/json/ImportJsonTest.java
Fixes #2930
Excluded node key and unique constraints
=> Fixes #2930: The apoc.import.json constraint check should works only when an unique constraint exists

core/src/main/java/apoc/util/Util.java, full/src/main/java/apoc/cypher/CypherExtended.java, full/src/test/java/apoc/cypher/CypherExtendedTest.java, full/src/test/resources/constraints.cypher, full/src/test/resources/schema.cypher
Cherry pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/3cb7b7d062adfd86b96596618594731fd5c70f9d
=> Fixes #2395: The apoc.cypher.runSchemaFile doesn't support full text indexes (#3084)

docs/asciidoc/modules/ROOT/pages/import/load-csv.adoc
Adds a section to LOAD CSV with the new escaping behaviour introduced by https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3258
=> [NOID] Updates docs for apoc.load.csv new escape + delimiter behaviour

full/src/test/java/apoc/load/LoadCsvTest.java
Because we have tests failing intermitently in GitHub Actions. Possibly because they are using links in the apoc-core (lives in another organization) and GitHub API rates limit you for different organizations.
Changes links for load csv tests.
=> Makes load csv tests less flaky

.gitmodules, extended/src/test/java/apoc/systemdb/SystemDbTest.java, readme.adoc
* Fixes `SystemDbTest` that was failing in TeamCity with:
```
org.neo4j.graphdb.QueryExecutionException: Failed to invoke procedure `apoc.systemdb.execute`: Caused by: org.neo4j.exceptions.InvalidArgumentException: A password must be at least 8 characters.
```
* Changes release number from 5.1.0.0 to 5.1.0 in the docs.
* Points the apoc-core submodule to the 5.1 branch
=> Solves some problems with the 5.1 build

extra-dependencies/build.gradle
Because our TeamCity build are failing when doing `./gradlew buildDependencies` inside `extra-dependencies` folder.
It's unclear to me why it started failing now, probably because those dependencies were removed from the gradle-libs repo.
=> Makes gradle go to Maven Central for extra-dependencies project

core/build.gradle, full/build.gradle
changelog: [4.3, security] Bumped snakeyaml to 1.32 to mitigate CVE-2022-25857, CVE-2022-38749, CVE-2022-38750, CVE-2022-38751, CVE-2022-38752
=> [NOID] Bump snakeyaml to latest release

core/src/test/java/apoc/load/LoadJsonTest.java
Cherry-picks https://github.com/neo4j/apoc/pull/243
The `json` disappeared from the external service. There's still another test that loads a json from stackexchange, so that should be enough to test the functionality.
These files should be moved to the repo probably and accessed through a github url rather than depending on external services.
=> [NOID] Removes load json test, the data is not in the external API anymore

docs/asciidoc/functions.adoc, docs/asciidoc/jmh.adoc, docs/asciidoc/modules/ROOT/pages/config/index.adoc, docs/asciidoc/modules/ROOT/pages/cypher-execution/index.adoc, docs/asciidoc/modules/ROOT/pages/database-integration/bolt-neo4j.adoc, docs/asciidoc/modules/ROOT/pages/database-integration/couchbase.adoc, docs/asciidoc/modules/ROOT/pages/database-integration/index.adoc, docs/asciidoc/modules/ROOT/pages/database-integration/redis.adoc, docs/asciidoc/modules/ROOT/pages/database-introspection/index.adoc, docs/asciidoc/modules/ROOT/pages/export/index.adoc, docs/asciidoc/modules/ROOT/pages/general-considerations/index.adoc, docs/asciidoc/modules/ROOT/pages/graph-updates/index.adoc, docs/asciidoc/modules/ROOT/pages/import/index.adoc, docs/asciidoc/modules/ROOT/pages/import/web-apis.adoc, docs/asciidoc/modules/ROOT/pages/index.adoc, docs/asciidoc/modules/ROOT/pages/introduction/index.adoc, docs/asciidoc/modules/ROOT/pages/misc/index.adoc, docs/asciidoc/modules/ROOT/pages/operational/index.adoc, docs/asciidoc/modules/ROOT/pages/overview/index.adoc, docs/asciidoc/modules/ROOT/pages/transaction/index.adoc, docs/asciidoc/modules/ROOT/pages/virtual-resource/index.adoc, docs/asciidoc/modules/ROOT/partials/docker.adoc, docs/asciidoc/modules/ROOT/partials/email-dependencies.adoc, docs/asciidoc/modules/ROOT/partials/mongodb-dependencies.adoc, docs/asciidoc/modules/ROOT/partials/nlp-dependencies.adoc
Rename APOC library to APOC Extended library
Original PR: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3308
=> Rename APOC library to APOC Extended library  (#3308)

core/src/test/java/apoc/trigger/TriggerClusterRoutingTest.java, core/src/test/java/apoc/trigger/TriggerTestUtil.java, full/src/test/java/apoc/trigger/TriggerNewProceduresExtendedTest.java
Try fix flaky TriggerClusterRoutingTest
=> [gRNAet7B] Try fix flaky TriggerClusterRoutingTest

core/src/test/java/apoc/spatial/GeocodeTest.java
Cherry-pick https://github.com/neo4j/apoc/commit/73e7dae61303fba994b0675c43fbc9516ac6a972
=> [4Bmcyc2U] Fix ignored testGeocodeGoogle (neo4j/apoc#239)

core/src/test/java/apoc/meta/MetaEnterpriseFeaturesTest.java
Cherry-pick of test fix here https://github.com/neo4j/apoc/pull/252
=> [4Bmcyc2U] Un-ignore and clean up working test.

docs/asciidoc/modules/ROOT/partials/usage/apoc.text.jaroWinklerDistance.adoc
There was a bugfix in apache text commons that we use that fixed this bug for us, so here is the updated docs on it :)
=> Update JaroWinkler examples

core/src/main/java/apoc/ApocConfig.java, core/src/main/java/apoc/util/FileUtils.java, core/src/main/java/apoc/util/Util.java, core/src/test/java/apoc/load/XmlTest.java, core/src/test/java/apoc/util/UtilIT.java
Also fix Ignored UtilIT
Cherry-pick of https://github.com/neo4j/apoc/pull/240
=> [eOxJMLMv] Checks redirects for blocked IPs instead of just final location.

docs/asciidoc/modules/ROOT/pages/cypher-execution/cypher-based-procedures-functions.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.custom.declareFunction.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.custom.declareProcedure.adoc
Cherry-pick (except for `apoc.custom.asProcedure` and `apoc.custom.asFunction` stuff) 
https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/b05f8259f221d9b3663510344dee4bebc1349630
=> Fixes #2895: update apoc.custom.* documentation (#2937)

readme.adoc
Fixes #3344 
Fix links in readme.adoc to go to the correct labs pages.
=> fix links to apoclabs docs

core/src/main/java/apoc/trigger/Trigger.java, core/src/main/java/apoc/trigger/TriggerNewProcedures.java, core/src/test/java/apoc/trigger/TriggerClusterRoutingTest.java, docs/asciidoc/modules/ROOT/pages/background-operations/triggers.adoc
- Added `@Admin` annotation to trigger procedures
- Added `testTriggersAllowedOnlyWithAdmin`
---
Please note that this is a breaking change
that we've introduced in order to improve procedures security.
---
Better to use `@Admin` check instead of `Util.checkAdmin`, like [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/8a9d0ca3758817ad92dc61b39cc7e54451cfcc44) :
- it will most likely be compatible with future versions
- it doesn't require additional contexts:
- we don't have to specify the procedure name, e.g. `Util.checkAdmin(securityContext, callContext,"apoc.trigger.install");`
```
@Context
public SecurityContext securityContext;
@Context
public ProcedureCallContext callContext;
```
- similar error, but with more details
```
// with Admin annotation
Executing admin …
```
=> [qwJFy8pp] Add @Admin to trigger procedures

core/src/main/java/apoc/algo/PathFinding.java, docs/asciidoc/modules/ROOT/pages/algorithms/path-finding-procedures.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.algo.travellingSalesman.adoc, full/src/main/java/apoc/algo/PathFindingFull.java, full/src/main/java/apoc/algo/TravellingSalesman.java, full/src/main/resources/extended.txt, full/src/test/java/apoc/algo/PathFindingFullTest.java
Fixes #1622
Implemented via simulated annealing algo, i.e. https://www.baeldung.com/java-simulated-annealing-for-traveling-salesman
=> Fixes #1622: Add a traveling salesman procedure to apoc

core/src/main/java/apoc/export/json/JsonFormat.java, core/src/main/java/apoc/meta/Meta.java, core/src/test/java/apoc/export/json/ExportJsonTest.java
Cherry-picked: https://github.com/neo4j/apoc/pull/265
Fixes a bug where serialisation of arrays with primitive values was causing a class exception in export json procedure calls.
=> [3KXXQazJ] Fix bug with serializing arrays of primitive values for json export query

extra-dependencies/build.gradle
Cherry-picks #3287
Because our TeamCity build are failing when doing `./gradlew buildDependencies` inside `extra-dependencies` folder.
It's unclear to me why it started failing now, probably because those dependencies were removed from the gradle-libs repo.
=> Makes gradle go to Maven Central for extra-dependencies project 

core/src/main/java/apoc/trigger/TriggerNewProcedures.java, core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java, core/src/test/java/apoc/trigger/TriggerTest.java
- Fix typo
- Ensure old triggers can't add triggers to "system"
- Ensure new triggers can't add triggers to "system"
=> [coZSswV2] Fixes triggers

.github/workflows/CI.yaml, build.gradle, docs/asciidoc/antora.yml, docs/asciidoc/modules/ROOT/pages/installation/index.adoc, docs/build.gradle, extended/build.gradle, extended/src/main/java/apoc/load/LoadCsv.java, extended/src/test/java/apoc/bolt/BoltTest.java, extended/src/test/java/apoc/couchbase/CouchbaseTestUtils.java, extended/src/test/java/apoc/load/LoadCsvTest.java, extended/src/test/java/apoc/load/LoadHtmlTest.java, extended/src/test/java/apoc/load/LoadHtmlTestParameterized.java, extended/src/test/java/apoc/systemdb/SystemDbTest.java, extended/src/test/java/apoc/ttl/TTLMultiDbTest.java, extended/src/test/java/apoc/util/s3/S3Container.java, extended/src/test/resources/test-escape.csv, extended/src/test/resources/test-escaped-delimiters.csv, extra-dependencies/build.gradle, extra-dependencies/xls/build.gradle, readme.adoc, teamcity-repository.gradle
- Various changes for 5.x releases (Cherry pick of https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3284)
- Bumps neo4j version
- Updated branch numbers in readme
- Fix failing testWriteStatements in TeamCity (See #3289)
- Fix various tests in 5.x (Cherry pick of #3286)
- Fixes CVE-2022-42889 in transitive dependencies [5.x, extended] (Cherry pick of #3258)
- Fixed BoltTest after neo4j/apoc#242 pwd change
- Fixed `CoreExtendedTest` by making teamcity-repository.gradle consistent with the core one
- Fixed assertions LoadHtmlTest
=> Various changes for 5.x releases

extended/src/main/java/apoc/TTLConfig.java, extended/src/main/java/apoc/uuid/UuidHandler.java
Fixes #3358
Added default values to `apoc.ttl.enabled` and `apoc.uuid.enabled` configs.
=> Fixes #3358: apoc extended on 5.2 throws errors for missing config values

build.gradle, docs/asciidoc/antora.yml, docs/asciidoc/modules/ROOT/pages/installation/index.adoc, docs/build.gradle, extra-dependencies/build.gradle, readme.adoc
Equivalent to https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3388, but pushed directly in `neo4j-contrib`.
---
- 5.3.1 bump
=> Release 5.3.1

build.gradle
- Removed neo4jVersionOverride from apoc gradle version
In TC we execute various `./gradlew ... Pneo4jVersionOverride=<neo4jVersion> ... taskName`,
The `neo4jVersionOverride` property should only be present with the neo4j version, not with the apoc version
=> Removed neo4jVersionOverride from apoc gradle version

full/src/main/java/apoc/custom/CypherProcedures.java, full/src/main/java/apoc/custom/CypherProceduresHandler.java, full/src/test/java/apoc/custom/CypherProceduresTest.java
Fixes #3349
Extended Cypher Procedures in order to support `DBMS` and `SCHEMA` procedures.
- Added the new modes
- Added Test
=> fixes #3349: Can not create custom procedure with void return type using apoc.custom.declareProcedure

core/build.gradle, extra-dependencies/nlp/build.gradle, full/build.gradle
vuln-fix: Update dependencies which import jackson-databind that had the following vulnerabilities: CVE-2020-36518, CVE-2022-42004, CVE-2022-42003.
=> [qZZ3O2uX] Updates jackson-databind to fix CVE-2020-36518, CVE-2022-42004, CVE-2022-42003  

build.gradle
Since the flakiness doesn't appear to be present in 5.x 
and there doesn't seem to be substantial differences between the two versions, 
maybe it makes sense to try to fix the problem by updating the testcontainer with the same version as the 5.x.
TODO - try retrigger multiple times
=> [21wxsujh] Try to fix APOC redirect test

build.gradle
In order to compile cherry-picks to 5.4 and https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3397,
waiting for neo4j 5.4 public release
=> Change neo4j reference to 5.3.0

core/src/main/antlr/apoc/custom/Signature.g4, docs/asciidoc/modules/ROOT/pages/cypher-execution/cypher-based-procedures-functions.adoc, full/src/main/java/apoc/custom/Signatures.java, full/src/test/java/apoc/custom/CypherProceduresTest.java
Fixes #2978
- Updated `SIGNATURE_SYNTAX_ERROR`
- Fixed default string handling
- Added `getDefaultParameterValue` to differentiate between plain text and other data types
With these changes the `apoc.custom.declareFunction/Procedure` should be able to accept any kind of default value, except for `float` type fixed [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3033).
=> [NOID] Fixes #2978: The apoc.custom.declareProcedure does not accept default string values

core/src/main/java/apoc/trigger/TriggerNewProcedures.java, core/src/main/java/apoc/util/Util.java, core/src/test/java/apoc/trigger/TriggerNewProceduresTest.java
Added QueryType validations in validateQuery() method,
so as to fail if the procedure tries to execute schema operations.
See point 2 here: https://github.com/neo4j/apoc/pull/208#pullrequestreview-1145222227
Only for 4.4, since the `apoc.trigger.add` is deprecated and in 5.x the `validateQuery()` is not longer present.
=> [hDJkPkOQ] Add QueryType validation in apoc.trigger.add

docs/asciidoc/modules/ROOT/nav.adoc, docs/asciidoc/modules/ROOT/pages/import/web-apis.adoc, docs/asciidoc/modules/ROOT/pages/installation/index.adoc
improves documentation
cherry-picked: https://github.com/neo4j/docs-apoc/pull/93/files
=> [xc2oVWgi] document warnings for dependencies excluded from APOC Core jar

extended/src/main/java/apoc/systemdb/SystemDb.java, extended/src/test/java/apoc/systemdb/SystemDbEnterpriseTest.java
[LMyH0Fi7] apoc.systemdb.graph leaks passwords/hashes
=> [LMyH0Fi7] apoc.systemdb.graph leaks passwords/hashes

docs/asciidoc/modules/ROOT/partials/usage/allowed.configs.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.config.list.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.config.map.adoc, extended/src/main/java/apoc/config/Config.java, extended/src/test/java/apoc/config/ConfigTest.java
The following configurations have been excluded:
- `bolt.url`
- `apoc.jdbc.`
- `apoc.static.` : can have sensitive info, like [in this case](https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1325#issuecomment-853664781)
- `apoc.loadldap.`
- `apoc.json.` : can have url with credentials
- `apoc.initializer` : can be used to manage users, e.g. [in this case](https://github.com/vga91/neo4j-apoc-procedures/blob/4.1/core/src/test/java/apoc/cypher/CypherInitializerTest.java#L122)
- `apoc.mongodb.`
- `apoc.couchbase.`
=> [PL7XdSMV] apoc.config.list and apoc.config.map leak evars

extended/src/main/java/apoc/systemdb/SystemDb.java, extended/src/test/java/apoc/systemdb/SystemDbEnterpriseTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/e133dbb216b7f416df14ca147d89b0d86f3497ab
=> [LMyH0Fi7] apoc.systemdb.graph leaks passwords/hashes (#3414)

readme.adoc
Remove old unsupported versions and fix typo for 4.4.x series
=> [NOID] Clean up APOC matrix list

extra-dependencies/selenium/build.gradle
Updated `webdrivermanager` to prevent the following error with apoc 5.4+, with `apoc.load.html(url, {..}, {browser: 'CHROME'})`
```
Failed to invoke procedure `apoc.load.html`: Caused by: java.lang.NoSuchMethodError: 'io.github.bonigarcia.wdm.WebDriverManager io.github.bonigarcia.wdm.WebDriverManager.gitHubToken(java.lang.String)'
```
=> [NOID] Update selenium extra-deps' webdrivermanager

extended/src/main/java/apoc/custom/CypherProcedures.java, extended/src/main/java/apoc/custom/CypherProceduresHandler.java, extended/src/test/java/apoc/custom/CypherProceduresTest.java
Cherry pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/3dfd8ae5463cff37dcd35f2d55a94496d79f29b1
=> [NOID] fixes #3349: Can not create custom procedure with void return type using apoc.custom.declareProcedure (#3356)

docs/asciidoc/modules/ROOT/partials/usage/allowed.configs.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.config.list.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.config.map.adoc, extended/build.gradle, extended/src/main/java/apoc/config/Config.java, extended/src/test/java/apoc/config/ConfigTest.java, extra-dependencies/nlp/build.gradle, extra-dependencies/selenium/build.gradle
=> Cherry picks from 5.4 to dev

core/build.gradle, full/build.gradle, test-utils/build.gradle
cherry-pick: https://github.com/neo4j/apoc/pull/308
=> [4cnpX39y] Bump mockserver-netty version and org.apache.arrow version

core/src/main/java/apoc/meta/Meta.java, core/src/main/java/apoc/meta/MetaConfig.java, core/src/main/java/apoc/meta/SampleMetaConfig.java, core/src/test/java/apoc/meta/MetaTest.java
cherry-pick: https://github.com/neo4j/apoc/pull/306
=> [04b6IYYB] Fix sampling in apoc.meta procedures

core/src/main/java/apoc/ApocConfig.java, core/src/main/java/apoc/util/Util.java
Cherry picked from https://github.com/neo4j/apoc/pull/315
Avoids an extra DNS resolve by replacing the domain with the resolved ip address.
=> [mIPA5H7K] Avoids double DNS lookup in the load methods (#315)

extra-dependencies/hadoop/build.gradle, test-startup/src/test/java/StartupTest.java, test-utils/src/main/java/apoc/util/TestContainerUtil.java
- Excluded packages from hadoop extra-deps
- added `addExtraDependencies()` in TestContainerUtil
- added tests with core/full jar together with all extra-dependencies
=> [TOQo1n9M] apoc-hadoop dependency is conflicting

docs/asciidoc/modules/ROOT/nav.adoc, docs/asciidoc/modules/ROOT/pages/installation/index.adoc, docs/asciidoc/modules/ROOT/partials/restricted.adoc, readme.adoc
NB: **Not cherry-picked in 5.4.0 to be consistent with APOC Core docs (which has been updated this docs in 5.5+ version)**
- Cherry-pick https://github.com/neo4j/docs-apoc/commit/08d5a1150d3a4b536ca8e04f666fcaab9b3448b6
- Cherry-pick https://github.com/neo4j/apoc/commit/91176749d317aa64c6650af8fc2c5d8de02f5861
- Added note to specify that unrestricting / loading an `apoc.package.name` will unrestrict / load Apoc Core ones as well.
=> [iREBdGuF] Stop recommending loading/unrestricting all procedures

build.gradle, docs/asciidoc/antora.yml, docs/asciidoc/modules/ROOT/pages/installation/index.adoc, docs/build.gradle, extra-dependencies/build.gradle, readme.adoc
- Bump dev version to 5.6.0
- Cherry-picked and updated versions of https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/b859284edd85dbc0daeefbedb39226df5be49695
=> Bump version 5.6.0

extended/build.gradle, extended/src/test/java/apoc/load/LoadLdapTest.java, extended/src/test/resources/ldap/example.ldif
The new extended PRs fail both on 4.x and 5.x,
it seems for the same reason as this other pr: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3022.
To avoid other problems in the future, 
I created an embedded mock server instead of using remote url.
Also I noticed that the actual procedure (ie `call apoc.load.ldap($conn, $search)`) is not tested,
but just the internal method calling the config is checked,
so I added a test that does the procedure query, to verify that it really works.
=> [aNcPaEFK] Fix LoadLdapTest.testLoadLDAP

extended/src/test/java/apoc/export/ExportExtendedSecurityTest.java
~TODO - WAITING FOR BUMP 5.5.0 MERGE~
Manual cherry-pick of https://github.com/neo4j/apoc/commit/340573a95991c38f44879cb2673e93336b71be84
Only the test: `core/src/test/java/apoc/export/ExportCoreSecurityTest.java`, 
since the implementation's fix is in common
=> [GE2QhC9X] Fix path traversal vulnerability (CVE-2022-23532)

docs/antora/package-lock.json
- Bump convict from 6.2.3 to 6.2.4 in /docs/antora: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3396
- Bump json5 from 2.2.1 to 2.2.3 in /docs/antora: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3392
=> Bump package.json antora 5.5

docs/antora/package-lock.json
- Bump convict from 6.2.3 to 6.2.4 in /docs/antora: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3396
- Bump json5 from 2.2.1 to 2.2.3 in /docs/antora: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3392
=> [NOID] Bump package.json antora

extended/build.gradle, extended/src/main/java/apoc/load/LoadHtml.java, extended/src/test/java/apoc/load/LoadHtmlTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3460
=> [EHgXqsEW] Upgraded jsoup to v.1.15.3 to mitigate CVE-2022-36033 (#3305) (#3460)

extended/build.gradle, init.gradle
Ignore git submodule via `git update-index --assume-unchanged apoc-core`,
in `build.core` and init script, so that after building the project or executing an `./gradlew --init-script init.gradle <cmd>` will be hidden from a later `git add .`.
Note that if I directly `git add .` before either of these 2 steps above, 
the sumbodule will appear in the staging area
---
Alternative:
Document somewhere ([maybe here](https://github.com/neo4j-contrib/neo4j-apoc-procedures#build--install-the-current-development-branch-from-source))  that e.g. `git add .` also adds the submodule, 
so we possibly need to remove it with `git restore --staged apoc-core`.
---
Other attempts:
`ignore=all` or `ignore = dirty` in `.gitmodules` hide the submodule with `git status` but not with `git add .`.
`.gitignore` …
=> Ignore git submodule from commits

extra-dependencies/hadoop/build.gradle, extra-dependencies/selenium/build.gradle, extra-dependencies/xls/build.gradle
- Excluded some depencendies from hadoop and selenium jars, 
to prevent some warn logs which could mean potential conflict errors, 
that is:
```
INFO org.apache.commons.beanutils.FluentPropertyBeanIntrospector - Error when creating PropertyDescriptor for public final void org.apache.commons.configuration2.AbstractConfiguration.setProperty(java.lang.String,java.lang.Object)! Ignoring this property.
INFO org.apache.commons.beanutils.FluentPropertyBeanIntrospector - Error when creating PropertyDescriptor for public final void org.apache.commons.configuration2.AbstractConfiguration.setProperty(java.lang.String,java.lang.Object)! Ignoring this property.
```
and:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in …
```
=> [NOID] Excluded duplicated libs in extra-dependencies

core/build.gradle
Snakeyaml looks unused, and as it contains vulnerabilities it looks bad to keep it in core for no reason
=> [NOID] Remove SnakeYaml as not used and vulnerable

test-utils/src/main/java/apoc/util/TestcontainersCausalCluster.java
`<ADDRESS>:<PORT>` instead of `<ADDRESS><PORT>`
=> [NOID] Fix cluster routing conf

.github/workflows/CI.yaml
Because it's the jdk being used by Neo4j in its docker images.
=> [NOID] Uses Temurin jdk 11

.github/workflows/CI.yaml
Because it's the jdk being used by Neo4j in its docker images.
=> [NOID] Uses Temurin jdk 8

full/src/main/java/apoc/load/LoadHtml.java, full/src/test/java/apoc/load/LoadHtmlTest.java
Fixes #3477
If the baseUrl is not defined href is not returned.
- Added test
=> [NOID] fixes #3477: apoc.load.html does not always report href

extended/src/main/java/apoc/load/LoadHtml.java, extended/src/test/java/apoc/load/LoadHtmlTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/fdcc1e5284ef7966debe0fe4ba5092cd40f89b83
=> [NOID] fixes #3477: apoc.load.html does not always report href (#3478)

extended/src/main/java/apoc/periodic/PeriodicExtended.java, extended/src/main/resources/extended.txt, extended/src/test/java/apoc/periodic/PeriodicExtendedTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3211
=> Fixes neo4j/apoc#126: apoc.periodic.submit fails with schema operations (extended) (#3211)

extended/build.gradle
To make sure `apoc.bolt*` works correctly with the version included in neo4j `lib`,
since we no longer use `extra-dependencies/bolt` jar
=> [NOID] Changed bolt driver version

core/build.gradle, docs/asciidoc/antora.yml, extra-dependencies/hadoop/build.gradle, test-utils/build.gradle
Updates Hadoop and JsonPath dependencies to their newest releases. The test coverage for these isn't great, but I couldn't see any breaking changes in the changelogs for them.
=> [tq7tdrWZ] Update Hadoop and JsonPath dependencies

index.html
Because GitHub Pages have started to fail for symlinks due to https://github.blog/changelog/2023-02-21-github-pages-deprecating-symlinks-in-non-actions-builds/
=> Removes symlink index.html temporarily

full/src/test/java/apoc/uuid/UUIDClusterRoutingTest.java, test-utils/src/main/java/apoc/util/TestContainerUtil.java, test-utils/src/main/java/apoc/util/TestcontainersCausalCluster.java
To solve the card with id `xEcl2dHs`:
- moved the `CREATE CONSTRAINT ..` only where needed (i.e. `apoc.uuid.install`) and added an assertEventually to check that the constraint is really propagated to the current core member
----
Attempts to solve the other flaky tests:
- changed number of cores to 3,  to decrease the failure probablity
- in `TestContainerUtil.checkLeadershipBalanced()` added a try-catch to prevent from potential errors (e.g. `NullPointer`)
- in `TestcontainersCausalCluster.java` added `causal_clustering.minimum_core_cluster_size_at_formation` and `causal_clustering.minimum_core_cluster_size_at_runtime` configs
=> [xEcl2dHs] Fix some flaky tests in UUIDClusterRoutingTest

core/src/test/java/apoc/spatial/GeocodeTest.java
Added `waitForServerResponseOK` to prevent sporadic OpenStreetMap server errors.
See: https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/4629830341/jobs/8190593821#step:7:1189
=> [NOID] Fix flaky geocode server errors

core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java, core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java, core/src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java, core/src/main/java/apoc/export/cypher/formatter/CypherFormatter.java, core/src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java, core/src/main/java/apoc/export/util/NodesAndRelsSubGraph.java, core/src/main/java/org/neo4j/cypher/export/DatabaseSubGraph.java, core/src/test/java/apoc/export/cypher/ExportCypherEnterpriseFeaturesTest.java, core/src/test/java/apoc/export/cypher/ExportCypherS3Test.java, core/src/test/java/apoc/export/cypher/ExportCypherTest.java, core/src/test/java/apoc/export/cypher/ExportCypherTestUtils.java, core/src/test/resources/init_neo4j_export_csv.cypher
Fixes https://github.com/neo4j/apoc/issues/345
`apoc.export.cypher.all` exported some constraints with wrong type or not at all
- Stop classifying composite UNIQUE constraints as NODE KEY.
- Stop classifying single NODE KEY constraints as UNIQUE.
- Support existence constraints.
- Support relationship constraints.
=> [f46vahOr] Fix #345 where exported Cypher constraints had wrong type.

build.gradle, docs/asciidoc/antora.yml, docs/asciidoc/modules/ROOT/pages/installation/index.adoc, docs/build.gradle, extra-dependencies/build.gradle, readme.adoc
Bump dev version to 5.8.0 
Cherry-pick of https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/ea144746b83416e2eb6367b7567a8ae6d6d71436
=> Bump version 5.8.0 (#3456)

core/src/main/java/apoc/export/json/JsonImporter.java, core/src/test/java/apoc/export/json/ImportJsonEnterpriseFeaturesTest.java, core/src/test/java/apoc/export/json/ImportJsonTest.java, test-utils/src/main/java/apoc/util/TestContainerUtil.java
Cherry picked: https://github.com/neo4j/apoc/pull/366
=> [VYidKhdO] The required constraint on import key for import.json is unique

core/src/main/java/apoc/cypher/CypherInitializer.java, test-startup/src/test/java/StartupTest.java
This PR waits for the dbms procedures to be completely initialized in `CypherInitializer`
When doing:
```
docker run --restart always --publish=7474:7474 --publish=7687:7687  --env NEO4JLABS_PLUGINS='["apoc"]' \
--env apoc.import.file.use_neo4j_config=true \
--env apoc.initializer.system.0='CREATE USER neo4j IF NOT EXISTS SET PASSWORD "pass" CHANGE NOT REQUIRED' \
--env apoc.initializer.system.1='CREATE USER dummy IF NOT EXISTS SET PASSWORD "pass" CHANGE NOT REQUIRED' \
--env apoc.initializer.system.2='GRANT ROLE reader TO dummy' \
--env=NEO4J_ACCEPT_LICENSE_AGREEMENT=yes \
neo4j:4.4.17-enterprise
```
we were failing in the `CypherInitializer` because it could not find the built-in role:
```
2023-03-23 13:15:51.229+0000 INFO  This instance is ServerId{40d2109e} …
```
=> [Fb3ZFQbn] Fixes bug in cypher initializer to wait for systemdb

core/src/main/java/apoc/export/cypher/MultiStatementCypherSubGraphExporter.java, core/src/main/java/apoc/export/cypher/formatter/AbstractCypherFormatter.java, core/src/main/java/apoc/export/cypher/formatter/AddStructureCypherFormatter.java, core/src/main/java/apoc/export/cypher/formatter/CypherFormatter.java, core/src/main/java/apoc/export/cypher/formatter/UpdateStructureCypherFormatter.java, core/src/test/java/apoc/export/cypher/ExportCypherTest.java
Added index type to nodes and rels.
In 5.x has been implemented [here](https://github.com/neo4j/apoc/commit/3ac9ef43674778f6b54833abc39df4a80b5be22b)
=> [qWQ33yT5] apoc.export.cypher.all rel indexes exported incorrectly

core/src/main/java/apoc/cypher/CypherInitializer.java, core/src/main/java/apoc/util/LogsUtil.java, core/src/main/java/apoc/util/QueryUtil.java, core/src/test/java/apoc/util/LogsUtilTest.java, core/src/test/java/apoc/util/QueryUtilTest.java, test-startup/src/test/java/StartupTest.java
We should obfuscate passwords when logging information in CypherInitializer
Because if we used:
```
apoc.initializer.system.1=CREATE USER dummy IF NOT EXISTS SET PASSWORD pass12345
```
we were getting an entry in neo4j.log with the password in plaintext:
```
INFO  [system/00000000] successfully initialized: alter user neo4j SET PASSWORD "pass12345" CHANGE NOT REQUIRED
```
We should get a redacted password instead:
```
INFO  [system/00000000] successfully initialized: alter user neo4j SET PASSWORD "*****" CHANGE NOT REQUIRED
```
=> [UNKBKte1] Redacts passwords in CypherInitializer

core/src/main/java/apoc/util/FileUtils.java, core/src/main/java/apoc/util/Util.java
Cherry-pick https://github.com/neo4j/apoc/commit/c226380dc5d26787e7ca6d0a196cbbfecfa23728
=> [ZkSGN6PO] apoc.export.graphml.all doesn't accept absolute Windows paths (neo4j/apoc#381)

core/src/main/java/apoc/export/cypher/ExportCypher.java, core/src/main/java/apoc/export/graphml/ExportGraphML.java, core/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java, core/src/test/java/apoc/export/cypher/ExportCypherTest.java, core/src/test/java/apoc/export/graphml/ExportGraphMLTest.java, core/src/test/java/apoc/export/graphml/ExportGraphMLTestUtil.java
Cherry-pick https://github.com/neo4j/apoc/commit/c3af4ce01eeb4fae93a731f83505cbbe15199cba
=> [Q8q7GXdk] apoc.export.graphml imports unwanted nodes (neo4j/apoc#380)

build.gradle
A dedicated property `neo4jDockerVersionOverride` has been created in TeamCity so we can pass a different version for neo4j and neo4j docker. This means we could be building with neo4j 4.4.22 when docker is still at 4.4.21
Because in some instances the docker job will not have the same neo4j version, since there's a circular dependency where in apoc we depend on docker and to build a docker container we depend on apoc been built and packaged with the database.
https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3588 seemed to broke the TeamCity CI for 4.4
=> [NOID] Fixes circular docker dependency in TeamCity

full/src/main/java/apoc/diff/DiffFull.java
Changed parallel: false in `DiffFull.java`, 
to prevent occasional concurrency errors.
See: https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/4938604111/jobs/8841865125?pr=3551#step:7:16320
=> [rF3PTDby] Fix shouldFindDifferencesInTheSameDb

settings.gradle
In teamcity is firstly executed a `./gradlew shadow` in the root folder, which creates an `apoc-5.8.1-core.jar`, 
where 5.8.1 is the current APOC Extended version.
But when `StartupExtendedTest.checkCoreAndFullWithExtraDependenciesJars` is executed, 
this runs the `:core:shadowJar` task on the apoc-core folder (via https://github.com/neo4j/apoc/blob/dev/test-utils/src/main/java/apoc/util/TestContainerUtil.java#L133), 
which create an  `apoc-5.8.0-core.jar` (5.8.0: current APOC Core version), 
this causes an error due to duplicated packages: 
```
procedure `apoc.periodic.iterate` is already in use
```
In this pr I excluded `:core:shadowJar`, when running on the root folder, 
since it is actually only needed when running integration tests with both core and extended.
---
FOLLOW UP:
Anyway, …
=> Exclude :core:shadowJar task from extended

core/src/main/java/apoc/coll/Coll.java, core/src/main/java/apoc/util/Util.java, core/src/test/java/apoc/coll/CollTest.java
Cherry pick https://github.com/neo4j/apoc/commit/2c1f37c4a3629fdfe939318e004b8dcfef53fea6
=> [dITjfMpu] apoc.coll.indexOf unexpectedly treats collections differently than the same hardcoded list (neo4j/apoc#422)

docs/asciidoc/modules/ROOT/nav.adoc, docs/asciidoc/modules/ROOT/pages/operational/index.adoc, docs/asciidoc/modules/ROOT/pages/operational/rebind.adoc, extended/src/main/java/apoc/nodes/NodesExtended.java, extended/src/main/java/apoc/util/EntityUtil.java, extended/src/main/resources/extended.txt, extended/src/test/java/apoc/nodes/NodesExtendedTest.java, extended/src/test/java/apoc/periodic/PeriodicExtendedTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/4e8ac253608a9b5f2e60423f71b0f8b7ae01273f
=> Fixes #1582: rebind flag in apoc.periodic.iterate (#3098)

core/src/main/java/apoc/schema/Schemas.java, core/src/main/java/apoc/util/Util.java, core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
Cherry Picked: https://github.com/neo4j/apoc/pull/424
Picked only the fix related to 4.4, which was the unique column always being true even if the constraint was not a uniqueness constraint
=> [NOID] apoc.schema.* Fix unique constraint column

core/src/main/java/apoc/ApocConfig.java, core/src/main/java/apoc/export/arrow/ExportArrowService.java, core/src/test/java/apoc/export/ExportCoreSecurityTest.java, core/src/test/java/apoc/export/arrow/ArrowTest.java, core/src/test/java/apoc/export/arrow/ExportArrowSecurityTest.java
Cherry-pick https://github.com/neo4j/apoc/commit/89ad884989814b873ba1216d6271b24edb2abe59
=> [3QAbWQds] apoc.export.arrow.all ignores export file config (neo4j/apoc#349)

extended/src/main/java/apoc/ttl/TTLLifeCycle.java
Fixes #3607
For the nodes deletion statement, just to be safe if any new relationships have sneaked in since the rel-deletion that they would be caught as well.
=> DETACH DELETE in TTLLifeCycle.java

LICENSES.txt, NOTICE.txt, core/build.gradle, full/build.gradle, test-utils/build.gradle
Also removes unused snakeyaml dependency
=> [NOID] Mitigate CVE-2022-42003 by upgrading  org.apache.arrow to version 12.0.1.

.github/workflows/CI.yaml, LICENSES.txt, NOTICE.txt
Chery-picks https://github.com/neo4j/apoc/pull/451
`./gradlew check` has this wired, but since the checks are done per project in the CI, the global check is never run 😢, so we need to add this manually.
=> [VpC8nqNz] Adds license and notice validation to the CI (#451)

LICENSES.txt, NOTICE.txt, core/build.gradle, core/src/main/java/io/netty/buffer/PooledByteBufAllocatorL.java
Cherry-picks https://github.com/neo4j/apoc/pull/450
This PR needs to be merged in conjunction with the latest version of the database
It makes possible to use the latest version of netty.
The issue is reproduced in [a592576](https://github.com/neo4j/apoc/pull/450/commits/a592576a4f54301222d021b13730245189163e0b) and we can see how [2f0a268](https://github.com/neo4j/apoc/pull/450/commits/2f0a2683f487bcbaa23f1fd7b764fb94a48cf843) solves it.
A class was renamed changed between the `4.1.93.Final` version of netty and `4.1.94.Final`, which neo4j is intending to use. We depend on arrow, which was only [updated](https://github.com/dremio/arrow/pull/27) (but not released) 2 weeks ago, so the netty dependency there needs to be an old one.
The only way to do this is to copy the file available in …
=> [TFMonhHx] Forces new version of netty

build.gradle, docs/asciidoc/antora.yml, docs/asciidoc/modules/ROOT/pages/installation/index.adoc, docs/build.gradle, extra-dependencies/build.gradle, readme.adoc
- Bump dev version to 5.11.0
- Cherry-picked and updated versions of https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/b859284edd85dbc0daeefbedb39226df5be49695
=> Bump version 5.11.0 (#3456) (#3536)

.github/workflows/CI.yaml, .gitmodules, build.gradle, docs/asciidoc/modules/ROOT/pages/installation/index.adoc, readme.adoc
-  [x] Waiting for apoc 5.10.0 release
-  [x] Waiting for neo4j mvn 5.10.0 release
-  [x] Waiting for neo4j docker 5.10.0 release
---
Changed `neo4j:5.10.0-enterprise-debian` to `neo4j:5.10.0-enterprise` and `neo4j:5.10.0-debian` to `neo4j:5.10.0`
=> [NOID] Release 5.10.0 (#3455)

docs/asciidoc/modules/ROOT/nav.adoc, docs/asciidoc/modules/ROOT/pages/config/index.adoc, docs/asciidoc/modules/ROOT/pages/index.adoc, docs/asciidoc/modules/ROOT/pages/installation/index.adoc, docs/asciidoc/modules/ROOT/pages/security-guidelines/index.adoc
- Manual cherry pick ok https://github.com/neo4j/docs-apoc/commit/a7cfd5f82ab84b900feb981a2190ea1514e01445
- Updated Extended config formatting
=> [kfkbAyTs] Added Security Guidance docs page

docs/asciidoc/modules/ROOT/pages/installation/index.adoc, docs/asciidoc/modules/ROOT/partials/docker.adoc, docs/asciidoc/modules/ROOT/partials/neo4j-desktop.adoc, docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc, readme.adoc
- Update docker docs, by adding `NEO4J_PLUGINS=apoc-extended` env variable
- Added Neo4j Desktop section, saying that it is not possible to install it via APOC button
- Refactored common readme.adoc and installation codes, with the addition of some partial files
- Fixed `go TO here` (see image)
- Fixed double `Since APOC relies ...`  (see image)
Image from [here](https://neo4j.com/labs/apoc/5/installation/):
=> [RY28NjPX] Update installation docs with docker and desktop, created partial and small fixes

extended/build.gradle, extended/src/main/java/apoc/load/LoadHtml.java, extended/src/main/java/apoc/load/LoadHtmlBrowser.java, extended/src/test/java/apoc/load/LoadHtmlTest.java, extended/src/test/java/apoc/load/LoadHtmlTestParameterized.java, extra-dependencies/selenium/build.gradle
- Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3663
- Added skip if ChromeDriver is incompatible with Chrome version (to cherry-pick in dev)
- Forced `mockito` version to fix the following error (to cherry-pick in dev). See [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/5642032860/job/15282309661#step:5:591): 
```
apoc.load.LoadHdfsTest > testLoadCsvFromHDFS FAILED
java.lang.IncompatibleClassChangeError: class org.apache.hadoop.hdfs.server.namenode.NameNodeAdapter$2 can not implement org.mockito.ArgumentMatcher, because it is not an interface (org.mockito.ArgumentMatcher is in unnamed module of loader 'app')
```
=> [BqvAC2FK] Update selenium dependencies

docs/asciidoc/modules/ROOT/pages/ml/openai.adoc, extended/src/main/java/apoc/ExtendedApocConfig.java, extended/src/main/java/apoc/ml/OpenAI.java, extended/src/main/java/apoc/ml/Prompt.java, extended/src/test/java/apoc/ml/OpenAIIT.java, extended/src/test/java/apoc/ml/PromptIT.java
For review
Uses OpenAI with a potentially configured API (`apoc.openai.key`) in `apoc.conf` (e.g. for Sandbox)
Extracts the database schema using `apoc.meta.data`
- Uses a system prompt for base grounding
- Adds a schema prompt
- Provides the user question
- adds `apoc.ml.schema` for describing  the schema of the database
- adds `apoc.ml.cypher` for generating N cypher queries for the user question
- adds `apoc.ml.query` for generating and executing cypher queries (with generation-retries (3 by default) if the query failed)  
- Still needs docs and tests (a bit tricky due to the probabalistic nature)
=> First LLM prompt for cypher, query and schema in APOC

docs/asciidoc/modules/ROOT/pages/overview/apoc.cypher/apoc.cypher.runFile.adoc, docs/asciidoc/modules/ROOT/pages/overview/apoc.cypher/apoc.cypher.runFiles.adoc, docs/asciidoc/modules/ROOT/pages/overview/apoc.cypher/apoc.cypher.runSchemaFile.adoc, docs/asciidoc/modules/ROOT/pages/overview/apoc.cypher/apoc.cypher.runSchemaFiles.adoc, docs/asciidoc/modules/ROOT/partials/usage/config/apoc.cypher.runExtended.adoc, extended/src/main/java/apoc/cypher/CypherExtended.java, extended/src/test/java/apoc/cypher/CypherExtendedTest.java, extended/src/test/resources/create_delete.cypher, extended/src/test/resources/long-create.cypher, extended/src/test/resources/wrong_call_in_transactions.cypher, extended/src/test/resources/wrong_schema_statements_runtime.cypher, extended/src/test/resources/wrong_statements.cypher, extended/src/test/resources/wrong_statements_runtime.cypher
- Added `reportError` config to retrieve a `Map.of("error", "<ERROR_OBTAINED>")`, if any
- Updated config docs
=> [V8keNXu0] error details while using apoc.cypher.run* procedures

.github/actions/setup-jdk/action.yaml, core/src/test/java/apoc/export/ExportCoreSecurityTest.java, core/src/test/java/apoc/export/arrow/ExportArrowSecurityTest.java, full/src/test/java/apoc/export/ExportFullSecurityTest.java
Checks sequences of `%e%e%f%f%e%e` do not fail but stay on the same directory when trying to do path traversals.
Commit [0421c2b](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3703/commits/0421c2b632e60af3f008496ff85b0808c0ff675f) reproduces the problem, [eec4def](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3703/commits/eec4def43b334fac0ea8793948af61b1e8b4a6de) amends the tests to solve it.
The tests were failing in our TeamCity CI. This treats them as we were treating sequences like `..//..//`
They've solved an issue with OpenJDK where it wasn't properly detecting double slashes in a path and turning them into a single one: https://github.com/openjdk/jdk11u-dev/commit/18939b76259456e85cfa051dc595e57242ca4ef8, https://nvd.nist.gov/vuln/detail/CVE-2023-22049 …
=> [NOID] Fixes failing path traversal TeamCity tests

core/src/main/java/apoc/ApocConfig.java
This was a mistake made when backporting to 4.4, the 5.x version was correct but must have auto imported googles one over Neo's :| This means that if a user tries to use expand config with APOC installed, there is a missing dependency, the workaround is to use just pop the google jar into plugins, but this is the real fix :)
=> [NOID] Apoc Config import fix

docs/asciidoc/modules/ROOT/pages/index.adoc
Trello: https://trello.com/c/KCe7hriJ/5150-rename-the-apoc-extended-documentation-title
The current confusion between APOC Core and APOC Extended
Remove mention of Neo4j in title of start page, and make the status of APOC Extended as a "Labs project" explicit
=> Change start page title

build.gradle, extended/build.gradle, extended/src/main/java/apoc/export/parquet/ApocParquetReader.java, extended/src/main/java/apoc/export/parquet/ExportParquet.java, extended/src/main/java/apoc/export/parquet/ExportParquetFileStrategy.java, extended/src/main/java/apoc/export/parquet/ExportParquetGraphFileStrategy.java, extended/src/main/java/apoc/export/parquet/ExportParquetGraphStreamStrategy.java, extended/src/main/java/apoc/export/parquet/ExportParquetResultFileStrategy.java, extended/src/main/java/apoc/export/parquet/ExportParquetResultStreamStrategy.java, extended/src/main/java/apoc/export/parquet/ExportParquetStrategy.java, extended/src/main/java/apoc/export/parquet/ExportParquetStreamStrategy.java, extended/src/main/java/apoc/export/parquet/ImportParquet.java, extended/src/main/java/apoc/export/parquet/ParquetConfig.java, extended/src/main/java/apoc/export/parquet/ParquetExportType.java, extended/src/main/java/apoc/export/parquet/ParquetReadUtil.java, extended/src/main/java/apoc/export/parquet/ParquetUtil.java, extended/src/main/java/apoc/load/LoadParquet.java, extended/src/test/java/apoc/ComparePerformancesTest.java, extended/src/test/java/apoc/export/parquet/ParquetHdfsTest.java, extended/src/test/java/apoc/export/parquet/ParquetS3Test.java, extended/src/test/java/apoc/export/parquet/ParquetTest.java, extended/src/test/java/apoc/export/parquet/ParquetTestUtil.java, extra-dependencies/hadoop/build.gradle
Fixes #3589
This PR adds the support for Apache Parquet export/import/load
---
- Added 4 export procedures that streams a list of byte[] one per each batch: `apoc.export.parquet.all.stream`, `apoc.export.parquet.graph.stream`, `apoc.export.parquet.query.stream`, `apoc.export.parquet.data.stream`
- Added 4 export procedures which create a Parquet file and return a `ProgressInfo` result, like the CSV ones: `apoc.export.parquet.all`, `apoc.export.parquet.graph`, `apoc.export.parquet.query`,  `apoc.export.parquet.data`
- Added one load procedure `apoc.load.parquet` that reads a Parquet byte[] or a Parquet file and returns a map for each row
-  Added one import procedure `apoc.import.parquet` that import data from a Parquet byte[] or a Parquet file
In order to load/import complex data not …
=> Fixes #3589: Add support for Parquet files similar to CSV/Arrow

docs/antora/package-lock.json, docs/antora/package.json, docs/antora/preview.yml, docs/asciidoc/modules/ROOT/pages/deprecations-and-additions/index.adoc, docs/asciidoc/modules/ROOT/pages/index.adoc, docs/asciidoc/modules/ROOT/pages/overview/index.adoc, docs/asciidoc/modules/notes/partials/notes.adoc
APOC extended is not supported. APOC Core is supported, and documented separately. This PR adds a warning to this effect to every page in the APOC extended docs, and provides a link to the APOC Core documentation.
The warning is added by the [antora-add-notes extension](https://www.npmjs.com/package/@neo4j-antora/antora-add-notes).
=> Add core vs extended warning

build.gradle, docs/asciidoc/antora.yml, docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc, docs/build.gradle, extra-dependencies/build.gradle, readme.adoc
Bump dev version to 5.12.0 
Cherry-pick of https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/ea144746b83416e2eb6367b7567a8ae6d6d71436
=> Bump version 5.12.0 (#3456) (#3536)

docs/antora/package-lock.json, docs/antora/package.json, docs/antora/preview.yml, docs/asciidoc/modules/ROOT/pages/deprecations-and-additions/index.adoc, docs/asciidoc/modules/ROOT/pages/index.adoc, docs/asciidoc/modules/ROOT/pages/overview/index.adoc, docs/asciidoc/modules/notes/partials/notes.adoc
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/9a7cad91f28eef02eab5e815967fba2044652291
=> Add core vs extended warning (#3719)

extended/src/main/java/apoc/custom/CypherProceduresHandler.java, extended/src/main/java/apoc/custom/Signatures.java
~WIP: in 5.10.0 the Signature is changed again. Waiting for release to check what is changed~
Fixes #3640
The issue affects any `5.x` version.
Sporadically [the reflection](https://github.com/vga91/neo4j-apoc-procedures/compare/dev...vga91:neo4j-apoc-procedures:issue-3640?expand=1#diff-7a6794bc38939217b5b8ca0f55b06b9cfd4bfd59ebd1be9e2a4709f12c2c3304L248) finds 2 constructors and cycles starting with the one having 13 parameters, but in that case the following error is thrown, because it finds [this constructor](https://github.com/neo4j/neo4j/blob/5.9.0/community/kernel-api/src/main/java/org/neo4j/internal/kernel/api/procs/ProcedureSignature.java#L54) (which is btw `Deprecated`) before the next non-deprecated one.
```
Caused by: java.lang.RuntimeException: …
```
=> Fixes #3640: Custom procedures declaration fails in 5.x

.github/workflows/CI.yaml, build.gradle, extended/build.gradle, extended/src/main/java/apoc/custom/CypherProceduresHandler.java, extended/src/main/java/apoc/export/parquet/ImportParquet.java, extended/src/main/java/apoc/load/LoadParquet.java, extended/src/main/java/org/neo4j/procedure/impl/ProcedureHolderUtils.java, extended/src/main/resources/extended.txt, extended/src/test/java/apoc/StartupExtendedTest.java, extended/src/test/java/apoc/custom/CypherProceduresStorageTest.java, extended/src/test/java/apoc/export/ExportExtendedSecurityTest.java, extended/src/test/java/apoc/load/LoadHtmlTest.java, extended/src/test/resources/long-create.cypher, extra-dependencies/hadoop/build.gradle
No parquet procs found in `checkCoreAndExtendedWithExtraDependenciesJars` and `checkExtendedWithExtraDependenciesJars` tests.
Added parquet procs in extended.txt.
Added `@Extended` to LoadParquet and ImportParquet classes.
---
It could depend on the driver version
---
Manual cherry-pick of https://github.com/neo4j/apoc/pull/464
CI Error solved: https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/5925227756/job/16064237048#step:5:2069
---
Excluded some `extra-dependencies/hadoop/build.gradle` sub-dependencies which are included in 5.11 lib as well, to prevent conflict exception like [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/5693341463/job/15432238158).
CI Error solved: https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/569334 …
=> Fix various 5.11 build errors

extended/src/main/java/apoc/load/LoadLdap.java, extended/src/test/java/apoc/load/LoadLdapTest.java
- Added support `apoc.loadldap<KEY>.conf` to `apoc.loadldap.<KEY>.conf` (with dot after `loadldap`)
- Added tests with correct and wrong config key
- Added log warn with fallback: `apoc.loadldap<KEY>.conf` and changed `DbsmRule` to `TestDatabaseManagementServiceBuilder` to check logs via `FileUtils.getLogDirectory()`
=> [qxkr2RlZ] apoc.load.ldap cant find config value due to missing

docs/asciidoc/modules/ROOT/pages/cypher-execution/cypher-based-procedures-functions.adoc
Fixes https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/3695
See here: https://github.com/neo4j/neo4j/commit/4b023a03fe2b3cbdc57b34f6a6cd1d7b6be28db6
=> Fixes #3695: Improvement docs for Cypher Procedures on 5.11

.github/workflows/codeql.yml
To make green the `CodeQL / Analyze (java) (pull_request)` CI job.
See here: https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/5109791018/jobs/9184959523?pr=3584#step:4:166
```
Error: 5-29 07:59:43] [ERROR] Spawned process exited abnormally (code 1; tried to run: [./gradlew, --no-daemon, -S, -Dorg.gradle.dependency.verification=off, --init-script, /tmp/semmleTempDir/init.gradle, clean])
Error: We were unable to automatically build your code. Please replace the call to the autobuild action with your custom build steps. Failure invoking /opt/hostedtoolcache/CodeQL/2.13.1-20230428/x64/codeql/java/tools/autobuild.sh with arguments .
```
----
- Added env variable like in `ci.yaml` file
- Workaround as explained here: …
=> Fix CodeQl error

extended/src/main/java/apoc/custom/CypherProcedures.java, extended/src/main/java/apoc/custom/CypherProceduresHandler.java, extended/src/test/java/apoc/custom/CypherProceduresStorageTest.java, extended/src/test/java/apoc/custom/CypherProceduresTest.java
Currently, if we overload a procedure/function, when `CypherProcedures.javarestoreProceduresAndFunctions()` is executed in background, 
firstly the new procedure/function is [registered](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/a9d8f0670fed7e37d5b10c1cbc27eef27a37a355/extended/src/main/java/apoc/custom/CypherProceduresHandler.java#L214), and secondly the old one is [unregistered](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/a9d8f0670fed7e37d5b10c1cbc27eef27a37a355/extended/src/main/java/apoc/custom/CypherProceduresHandler.java#L225).
Since neo4j considers, with the same name, the last register done, i.e. the de-register,
the new procedure/function will not be detected by executing `call custom.yyy` or `return call.yyy`
Removing the old procedure from the …
=> [XWc7tBAb] Custom procedures with overload fail after refresh

extended/src/main/java/apoc/custom/CypherProceduresHandler.java, extended/src/test/java/apoc/custom/CypherProceduresTest.java
With `if (!result.hasNext()) return null;`, the custom function hangs and logs a:
```
[Neo.DatabaseError.Statement.ExecutionFailed]: null
```
=> Fixes #3708: Neo4j APOC custom function hangs when nothing is found

docs/antora/publish.yml
Updates the `preview.yml` playbook to allow for local building in a consistent way with neo4j.com/docs content.
Adds a new `publish.yml` playbook to allow for publishing in a consistent way with neo4j.com/docs content.
=> Update playbooks for docs publish

extra-dependencies/aws/build.gradle
Depends on the answer from https://github.com/neo4j/apoc/issues/482
For the service accounts to work sts needs to be in the classpath, as described in https://github.com/aws/aws-sdk-java/issues/2136.
=> [iBQzFOoI] Adds sts to the list of aws extra-dependencies

build.gradle, extended/src/test/java/apoc/CoreExtendedTest.java
Sometimes the CI fails without specifying a test, with a generic ["The Operation was canceled"](https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/6249290975/job/16969904191?pr=3778#step:5:2891).
Usually during or right after a Docker test.
Maybe it can be a heap memory issue.
- Added auto-close to StartupTest, 
otherwise the `neo4jContainer` would not be closed in case of uncaught exception, 
and could flakily cause other CI failures.
- Decreased `maxHeapSize` [as in Core](https://github.com/neo4j/apoc/blob/dev/build.gradle#L77)
=> Solve flaky test 5.12

docs/asciidoc/modules/ROOT/partials/periodic-iterate.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.periodic.iterate.adoc
Using the id function will improve memory usage when using apoc.periodic.iterate.
See also [knoledge base artice](https://neo4j.com/developer/kb/a-significant-change-in-apoc-periodic-iterate-in-apoc-4-0/)
cherry-pick: https://github.com/neo4j/docs-apoc/pull/181, https://github.com/neo4j/docs-apoc/pull/200
=> [rCBSQkmb] recommend using id function in apoc.periodic.iterate

build.gradle, docs/asciidoc/antora.yml, docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc, docs/build.gradle, extra-dependencies/build.gradle, readme.adoc
=> Bump version 5.14.0 (#3726)

docs/asciidoc/modules/ROOT/partials/usage/config/apoc.import.csv.adoc
cherry-picked: https://github.com/neo4j/docs-apoc/pull/208
=> [EZdf8JTx] document missing config parameters for apoc.import.csv

.github/workflows/CI.yaml, build.gradle
Restore parallelization if not in TeamCity (where it could cause problems).
See [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/2825/commits/005a4a44975ae36c1ef0fb583155daac0e470c13)
Added the flag `--parallel` to `gradlew build` command
=> Parallelize test if not in TeamCity

docs/asciidoc/modules/ROOT/pages/config/index.adoc
As per https://neo4j.slack.com/archives/C136J23GE/p1698854430024199 I've removed the leading dots from the index.
It looks like it maybe came across via copy-paste from the tables bit below? It seems those entries start with a dot for numbered list
-
-
-
=> Fixed the dots

full/src/main/java/apoc/uuid/UUIDHandlerNewProcedures.java, full/src/main/java/apoc/uuid/UuidHandler.java, full/src/test/java/apoc/uuid/UUIDTest.java, test-utils/src/main/java/apoc/util/TestContainerUtil.java
- Stop using tmpfs, it is known to cause issues with neo4j (https://github.com/neo4j/apoc/pull/512).
- Fix bug in `apoc.uuid.*` procedures (similar to https://github.com/neo4j/apoc/pull/513).
=> [zH04aIIy] Fix UUID bug

docs/asciidoc/modules/ROOT/pages/cypher-execution/cypher-based-procedures-functions.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.custom.declareFunction.adoc, extended/src/main/antlr/apoc/custom/Signature.g4, extended/src/main/java/apoc/ExtendedSystemPropertyKeys.java, extended/src/main/java/apoc/custom/CypherProcedures.java, extended/src/main/java/apoc/custom/CypherProceduresHandler.java, extended/src/main/java/apoc/custom/Signatures.java, extended/src/test/java/apoc/custom/CypherProceduresStorageTest.java
Fixes #2612: Added `MAPRESULT` type to custom functions.
See: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/2704#issuecomment-1346354805
=> Fixes #2612: Added MAPRESULT type to custom functions

.github/workflows/CI.yaml, .gitmodules, build.gradle, docs/antora/publish.yml, docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc, extended/src/test/java/apoc/StartupExtendedTest.java, extended/src/test/java/apoc/util/ExtendedTestContainerUtil.java, extra-dependencies/build.gradle, extra-dependencies/couchbase/build.gradle, extra-dependencies/gcs/build.gradle, extra-dependencies/hadoop/build.gradle, extra-dependencies/mongodb/build.gradle, extra-dependencies/nlp/build.gradle, extra-dependencies/redis/build.gradle, extra-dependencies/selenium/build.gradle, readme.adoc
- Bump 5.14.0 (Manual cherry-pick of: https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/1f0e07eb55e6b8c85a433e0a5f28638bd23f5fd1)
- de-ignored StartupExtendedTest
- added `commonExclusions` to `extra-dependencies/build.gradle` to solve various conflicts with Neo4j `/lib` jars, (alternatively, they can be excluded individually as done in [this commit](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3844/commits/f12ee49ab4ee8df51fd2b6befd82b4e06ffdc1aa), but there are several). That is:
- hadoop: apache-commons and gson
- redis: projectreactor
- selenium: apache-commons and projectreactor
- gcs: guava
- Added `io-netty` and `com.sun.jersey` with subpackages to prevent wrong exclusion.
=> Release 5.14.0 (#3803)

extended/src/test/java/apoc/nodes/NodesExtendedTest.java
TODO - waiting for 5.14 init release pr, to trigger CI Build
=> Fixes #3367: Test to check return type of apoc.any.rebind with a Path

extended/src/main/java/apoc/cypher/CypherExtended.java, extended/src/main/java/apoc/es/ElasticSearch.java, extended/src/main/java/apoc/gephi/Gephi.java, extended/src/main/java/apoc/load/LoadCsv.java, extended/src/main/java/apoc/load/LoadDirectory.java, extended/src/main/java/apoc/load/LoadHtml.java, extended/src/main/java/apoc/load/xls/LoadXls.java, extended/src/main/java/apoc/metrics/Metrics.java, extended/src/main/java/apoc/ml/OpenAI.java, extended/src/main/java/apoc/ml/Prompt.java, extended/src/main/java/apoc/ml/VertexAI.java, extended/src/main/java/apoc/ml/bedrock/Bedrock.java, extended/src/test/java/apoc/load/LoadCsvTest.java, extended/src/test/java/apoc/load/LoadS3Test.java
- added `@Context URLAccessChecker urlAccessChecker` where needed
Fixes due to [this Core breaking-change](https://github.com/neo4j/apoc/commit/e01a29d66dbd753382581ad20462587330120d5d):
- changed `http://bit.ly` with `https://bit.ly`,
otherwise the [checkUrl](https://github.com/neo4j/apoc/commit/e01a29d66dbd753382581ad20462587330120d5d#diff-320bd28396c4b4bd53b5add80a9df3e893d495562119ac81aeba0aa163fffadbR303) throws a `java.io.FileNotFoundException: http://67.199.248.10/2nXgHA2`
- added `LoadS3Test.removeRegionFromUrl(url)`,
since the URL with the region,
e.g. `s3://us-east-1.127.0.0.1:60082/test-bucket/test.csv?accessKey=accesskey&secretKey=secretkey`, 
throws an `java.net.UnknownHostException: us-east-1.127.0.0.1: nodename nor servname provided, or not known`,
and we cannot change the …
=> Fix 5.15 CI errors

extended/src/test/java/apoc/nodes/NodesExtendedTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/38a3479bcb82ecf04808174aa79722195b06b056
=> Fixes #3367: Test to check return type of apoc.any.rebind with a Path (#3848)

extended/src/main/java/apoc/ml/OpenAI.java
Replaced Open AI model which will be deprecated, as explained here: https://platform.openai.com/docs/deprecations/instructgpt-models
=> Replaced Open AI model

full/src/main/java/apoc/ml/OpenAI.java
Replaced Open AI model which will be deprecated, as explained here: https://platform.openai.com/docs/deprecations/instructgpt-models
=> [NOID] Replaced Open AI model

.github/actions/gradle-command-on-pr/action.yaml, .github/workflows/ChatOps.yml, .github/workflows/generateLicenses-command.yml, .github/workflows/spotlessApply-command.yml
Cherry-picks https://github.com/neo4j/apoc/pull/520, https://github.com/neo4j/apoc/pull/524, https://github.com/neo4j/apoc/pull/552, https://github.com/neo4j/apoc/pull/553
Adds a job to run formatting in PRs by writting `/spotlessApply` and `generateLicenses` in it
Because especially for the licensing it's really annoying to have to update neo4j locally every time the license check fails 😢 .
=> [NOID] Adds format and license PR bot jobs

build.gradle
Cherry-picks https://github.com/neo4j/apoc/pull/559
Uses the [`maven-metadata`](https://repo1.maven.org/maven2/org/neo4j/neo4j-kernel/maven-metadata.xml) file to generate the versions.json instead of parsing the [`html`](https://repo1.maven.org/maven2/org/neo4j/neo4j-kernel/).
Because that's a better source of truth. Right now https://repo1.maven.org/maven2/org/neo4j/neo4j-kernel/maven-metadata.xml is showing 5.15.0 but there's no 5.15.0 listed under https://repo1.maven.org/maven2/org/neo4j/neo4j-kernel/
=> [NOID] Adjusts versions job

docs/asciidoc/modules/ROOT/pages/ml/openai.adoc, extended/src/main/java/apoc/ml/OpenAI.java, extended/src/main/java/apoc/ml/OpenAIRequestHandler.java, extended/src/main/java/apoc/util/ExtendedUtil.java, extended/src/test/java/apoc/ml/OpenAIAnyScaleIT.java, extended/src/test/java/apoc/ml/OpenAIAzureIT.java, extended/src/test/java/apoc/ml/OpenAIIT.java, extended/src/test/java/apoc/ml/OpenAILLMaticIT.java, extended/src/test/java/apoc/ml/OpenAILocalAIIT.java, extended/src/test/java/apoc/ml/OpenAIOpenLMIT.java, extended/src/test/java/apoc/ml/OpenAITest.java, extended/src/test/java/apoc/ml/OpenAITestResultUtils.java
Fixes #3858
- Added path configurations to manipulate the url suffix (which by default is /embeddings, /completions and /chat/completions)
- Added tests for https://app.endpoints.anyscale.com/
- Added tests for Local AI
- Added tests for LLMatic (with assertEventually as they are very slow and often go into SocketTimeout)
- Added tests to simulate the behavior of https://github.com/r2d4/openlm, which manipulates APIs to have an OpenAI-compatible format. Tested with Cohere and HuggingFace. As with the library, only test for the Completions API
- An OpenAIRequestHandler.Type has been added for HuggingFace, to transform the input into a format consistent with the HuggingFace Api (i.e. `{"inputs": ["text...."]}`) and change the jsonPath to `$[0]`. With this API, we need to explicit the config …
=> Fixes #3858: Allow configuration of openai base URL as parameter

full/src/test/java/apoc/nodes/NodesExtendedTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/38a3479bcb82ecf04808174aa79722195b06b056
=> [NOID] Fixes #3367: Test to check return type of apoc.any.rebind with a Path (#3848)

build.gradle, extended/src/main/java/apoc/cypher/CypherExtended.java, extended/src/main/java/apoc/es/ElasticSearch.java, extended/src/main/java/apoc/export/parquet/ImportParquet.java, extended/src/main/java/apoc/export/parquet/ParquetReadUtil.java, extended/src/main/java/apoc/gephi/Gephi.java, extended/src/main/java/apoc/load/LoadCsv.java, extended/src/main/java/apoc/load/LoadDirectory.java, extended/src/main/java/apoc/load/LoadHtml.java, extended/src/main/java/apoc/load/LoadParquet.java, extended/src/main/java/apoc/load/xls/LoadXls.java, extended/src/main/java/apoc/metrics/Metrics.java, extended/src/main/java/apoc/ml/OpenAI.java, extended/src/main/java/apoc/ml/Prompt.java, extended/src/main/java/apoc/ml/VertexAI.java, extended/src/main/java/apoc/ml/bedrock/Bedrock.java, extended/src/test/java/apoc/load/LoadCsvTest.java, extended/src/test/java/apoc/load/LoadS3Test.java
- Solve dev (currently 5.16) CI error (similar to https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3860)
- [fix System.getProperty NullPointerException in TestContainerUtil](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3847/commits/210cfa0be0c7d1414bfc1df69c16a77f517a68bd)
See [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/7246972833/job/19781969218?pr=3847).
It happens because of [this change](https://github.com/neo4j/apoc/pull/550). Since it only affect Core (as we can check [here](https://github.com/neo4j/apoc/blob/dev/test-utils/src/main/java/apoc/util/TestContainerUtil.java#L162)), we can always declare the `testDockerBundle` property equal to `false`.
=> Solve dev CI error (with neo4j 5.16.0)

docs/asciidoc/modules/ROOT/pages/ml/openai.adoc, extended/src/main/java/apoc/ExtendedApocConfig.java, extended/src/main/java/apoc/ml/OpenAI.java, extended/src/main/java/apoc/ml/OpenAIRequestHandler.java, extended/src/test/java/apoc/ml/OpenAIAzureIT.java, extended/src/test/java/apoc/ml/OpenAIIT.java, extended/src/test/java/apoc/ml/OpenAITest.java, extended/src/test/java/apoc/ml/OpenAITestResultUtils.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/0ad5ecd2b29d9b1e931288dcd5f5a0bc13443df8
Tested locally, since the OpenAI tests are ignored in CI (because of some `assumeNotNull(<envVarForApiKeys>)`)
=> Fixes #3634: Updated ML procs for Azure OpenAI services (#3850) (#3863)

core/src/main/java/apoc/export/csv/CsvEntityLoader.java, core/src/test/java/apoc/export/csv/ExportCsvTest.java
Uses `RFC4180Parser` instead of `CSVParser` as suggested [here](https://stackoverflow.com/questions/46139735/why-csvwriter-and-csvreader-uses-different-default-escape-characters)
Because the case where we have a quote `"` in a value we want to export / import from csv was not working:
```
CREATE (n:Test {name: 'Test', value: '{"new":"4\'10\\\""}'});
CALL apoc.export.csv.all("test.csv", {bulkImport:'true'});
MATCH (n) DETACH DELETE n;
CALL apoc.import.csv([{fileName: 'file:test.nodes.Test.csv', labels: ['Test']}],[],{});
```
```
MATCH (n: Test) RETURN n.value
```
should give us a roundtrip where the result is `"{"new":"4'10\""}"`
=> [SGrPWNEf] Fixes backslashes parsing in csv import / export

docs/asciidoc/modules/ROOT/partials/mongodb-dependencies.adoc, extended/build.gradle, extended/src/main/java/apoc/mongodb/MongoDBColl.java, extended/src/main/java/apoc/mongodb/MongoDBUtils.java, extended/src/test/java/apoc/mongodb/MongoDBTest.java, extended/src/test/java/apoc/mongodb/MongoDBVersion4Test.java, extended/src/test/java/apoc/mongodb/MongoTest.java, extended/src/test/java/apoc/mongodb/MongoTestBase.java, extended/src/test/java/apoc/mongodb/MongoVersion4Test.java, extra-dependencies/mongodb/build.gradle
Fixes #3203
- Updated java driver and API
- Changed [`MongoCommandException` to `Exception`](https://github.com/vga91/neo4j-apoc-procedures/pull/411/files#diff-7a0bb39849237cd94862ba6b51f30b78a7b80de77d130b061778e6509b7de5d4R108), otherwise the client is not closed on exception
- Added [adaptLegacyDocument](https://github.com/vga91/neo4j-apoc-procedures/pull/411/files#diff-f083578af56ec4397c0a59e00584ae8fe68cac67eebfd78db094e914b530c4f0R26) in case someone uses `$sub Type` for binaries (which is no longer compatible, replaced with `$type`). Alternatively you could write a `NOTE` on the documentation
- Added tests with mongodb 7 and created test classes to check compatibility with mongodb 4
- Code clean
=> Fixes #3203: apoc.mongo dependencies are outdated with current mongodb

extended/src/test/java/apoc/help/HelpExtendedTest.java
The [HelpExtendedTest.indicateNotCore()](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/dev/extended/src/test/java/apoc/help/HelpExtendedTest.java#L68) test currently changes the `extended.txt` file when executed.
Therefore, if some classes have / do not have the `@Extended` annotation, [like in this case](https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/83199902017ac9e89d699954a6f581147fa7e8b6),
the result of `StartupExtendedTest` (which [leverage the extended.txt](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/dev/extended/src/test/java/apoc/StartupExtendedTest.java#L39))
may change if it is run before (which happens with gh action) or after (with TC) HelpExtendedTest.
Changed the HelpExtendedTest so that doesn't change the txt file, 
but checks …
=> Fix HelpExtendedTest not to edit extended.txt when executed

docs/asciidoc/modules/ROOT/pages/ml/index.adoc, docs/asciidoc/modules/ROOT/pages/ml/watsonai.adoc, extended/src/main/java/apoc/ExtendedApocConfig.java, extended/src/main/java/apoc/ml/Watson.java, extended/src/main/resources/extended.txt, extended/src/test/java/apoc/ml/WatsonIT.java, extended/src/test/java/apoc/ml/WatsonTest.java, extended/src/test/resources/watson.json
Fixes #3891
To emulate chatCompletion API, the `apoc.ml.watson.chat` creates strings of type `<role Value>: <content Value>`, joins the results with `\n` and calls the `apoc.ml.watson.completion`.
Hence, for example, these two are equivalent:
```
CALL apoc.ml.watson.chat([
{role:"system", content:"Only answer with a single word"},
{role:"user", content:"What planet do humans live on?"}
], $apiKey) yield value
#completion
CALL apoc.ml.watson.completion(
"system: Only answer with a single word\nuser: What planet do humans live on?", content:"Only answer with a single word",
$apiKey) yield value
```
Similarly to what is reported on some examples reported on the IBM Prompt Lab:
---
I didn't include the `apoc.ml.watson.embeddings` procedure because all [ foundation models …
=> Fixes #3891: Add IBM Watson Foundation model integration

docs/asciidoc/modules/ROOT/pages/ml/openai.adoc, extended/src/main/java/apoc/ml/OpenAI.java, extended/src/main/java/apoc/ml/OpenAIRequestHandler.java, extended/src/test/java/apoc/ml/OpenAIAnyScaleIT.java, extended/src/test/java/apoc/ml/OpenAIAzureIT.java, extended/src/test/java/apoc/ml/OpenAIIT.java, extended/src/test/java/apoc/ml/OpenAILLMaticIT.java, extended/src/test/java/apoc/ml/OpenAILocalAIIT.java, extended/src/test/java/apoc/ml/OpenAIOpenLMIT.java, extended/src/test/java/apoc/ml/OpenAITest.java, extended/src/test/java/apoc/ml/OpenAITestResultUtils.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/63f4bf7c729575219f9a5974609eeef5ee4d37b0
=> Fixes #3858: Allow configuration of openai base URL as parameter (#3880)

extended/src/main/java/apoc/ml/OpenAI.java
Added this code https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/0ad5ecd2b29d9b1e931288dcd5f5a0bc13443df8#diff-1ffff1937373b4ee7110a07d75c545ff173f521fd6e830c9ac04ace3240fc167R53,
mistakenly not inserted in the PR of the cherry-pick, 
after having done the rebase with the other ml PRs
=> Restored configuration.getOrDefault(APIKEY_CONF_KEY, ...)

extended/src/main/java/apoc/cypher/CypherExtended.java, extended/src/test/java/apoc/cypher/CypherEnterpriseExtendedTest.java, extended/src/test/java/apoc/cypher/CypherExtendedTest.java, extended/src/test/resources/parallel.cypher
Fixes #3751
- Added fix like https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3810
- Changed transaction handling from try-with-res to [`transactions.add(transaction);`](https://github.com/vga91/neo4j-apoc-procedures/pull/420/files#diff-0be321a488b8e1a039cef51ff786b8142a2eac4a76f7585ff6121e4fc588dfc9R383)
- Added `SHOW TRANSACTIONS` tests
- Tested the `https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/3899` case as well
=> Fixes #3751: Failed to invoke procedure apoc.cypher.mapParallel2: Caused by:RuntimeException: Error polling, timeout

extended/build.gradle, extended/src/test/java/apoc/bolt/BoltTest.java, extended/src/test/java/apoc/custom/CypherProceduresClusterTest.java, extended/src/test/java/apoc/cypher/CypherEnterpriseExtendedTest.java, extended/src/test/java/apoc/metrics/MetricsTest.java, extended/src/test/java/apoc/trigger/TriggerClusterTest.java, extended/src/test/java/apoc/ttl/TTLMultiDbTest.java, extended/src/test/java/apoc/util/ExtendedTestContainerUtil.java, extended/src/test/java/apoc/uuid/UUIDClusterRoutingTest.java, extended/src/test/java/apoc/uuid/UUIDMultiDbTest.java
Equivalent to APOC Core PR: https://github.com/neo4j/apoc/pull/579.
- Updated the java-driver to 5.16.0
- Migrated deprecated `readTransaction` and `writeTransaction` to `executeRead` and `executeWrite` 
- Added `consume()` where needed
- Removed `tx.commit()` as in the Core PR 
- Changed `next()` to `single()`, to make sure the queries are consumed
=> Upgrade driver and syntax to 5.16.0

extended/src/main/java/apoc/bolt/BoltConnection.java, extended/src/test/java/apoc/bolt/BoltTest.java
Fixes #3945
- Fixes issue case, by adding `convertRecursive` to handle maps and collections (https://github.com/vga91/neo4j-apoc-procedures/pull/424/files#diff-c0b63ee9409cc47b02b4dac7a4386af00b6ccef90d10fa251f564af5abb14937R137)
- Tested `apoc.bolt.load` returning map and list
- Tested with other apoc.bolt.* procedures
- Verified that you can use, 
subsequent to the `apoc.bolt.load` procedure, the `apoc.refactor.cloneSubgraph` as requested [by the user on slack here](https://neo4j.slack.com/archives/C136J23GE/p1707239672283549), i.e.:
```
Hello,
I have a question.
Do you have anything like apoc.refactor.cloneSubgraph but that can clone a subgraph from a db to another one?
Thanks.
...
And when calling apoc.refactor.cloneSubgraph I get
MERGE (rootB:CVE {id:'CVE-ROOT'})
WITH rootB
call …
```
=> Fixes #3945: The apoc.bolt.* procedures fail together with the apoc.path.subgraphAll one

extended/src/test/java/apoc/mongodb/MongoTestBase.java
The assertEventually should solve the following flaky TC assertion error.
Replicated locally executing the test ~20/30 times.
=> Fix flaky MongoDBTest

extended/src/test/java/apoc/ml/VertexAITest.java
Added `mockServer.stop()` to `@AfterClass` in `VertexAITest, like other tests e.g. OpenAITest.
To fix these CI errors: https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/8018948759/job/21905882192?pr=3957#step:6:1518
Most likely the [VertexAITest PR](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3940) did not fail because, in that case, the VertexAITest was the last test with mockServer launched.
=> Added mockServer.stop() to  in VertexAITest

extended/src/test/java/apoc/custom/CypherProceduresClusterRoutingTest.java
Increased timeout to be used in assertEventually, e.g [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3959/files#diff-36b2342b2cc6ef75cf3dc8d562f1c998f42ce4185b7f8aadb1a61abe7232887fR97), as In clusters, since the changes are sometimes updated more slowly.
It should solve this flaky CI error: https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/8021701219/job/21914372905?pr=3957#step:6:1371
=> Fix flaky CypherProceduresClusterRoutingTest - dev

extended/src/main/java/apoc/ExtendedApocGlobalComponents.java, extended/src/main/java/apoc/ttl/TTLLifeCycle.java
Fixes #3777:
- removed apoc.schema and apoc.periodic
Code clean: 
- removed unused ApocConfig
=> Fixes #3777: Remove APOC Core procedures from TTLLifeCycle.java

extended/src/main/java/apoc/custom/CypherProcedures.java, extended/src/main/java/apoc/util/ExtendedUtil.java, extended/src/test/java/apoc/VersionUpdateChecksTest.java, extended/src/test/java/apoc/custom/CypherProceduresTest.java
Fixes #3072
- Improved check to verify inner procedure `Mode`
- Improved `Result.getQueryExecutionType()` check: there is not anymore a 1-1 correspondence (e.g. WRITE and WRITE), but now a query supposed to be WRITE can accept a READ query as well
- Added `VersionUpdateChecksTest` to check possible future additions
=> Fixes #3072: apoc.custom.declareProcedure fails with java.lang.RuntimeException if provided mode is SCHEMA

extended/src/main/java/apoc/ExtendedApocConfig.java, extended/src/main/java/apoc/ExtendedApocConfigExtensionFactory.java, extended/src/main/java/apoc/dv/DataVirtualizationCatalog.java, extended/src/test/java/apoc/ExtendedApocConfigTest.java
On Windows service, 'sun.java.command' is not supported. The fallback default path to the config folder was set to '.' which is not the actual default. With this solution, the home folder of Neo4j is instead used to calculate the default.
This is the extended version of the APOC core fix from https://github.com/neo4j/apoc/pull/586
=> [4Bece3wd] Use Neo4j home to determine default config location.

core/src/main/java/apoc/meta/Meta.java, core/src/test/java/apoc/meta/MetaTest.java
Cherry-picks https://github.com/neo4j/apoc/pull/584
Because a node named `NODE` or a relationship named `RELATIONSHIP` could not be used.
When doing
```
CREATE (a:NODE)-[r:RELATIONSHIP]->(m:Movie)
CALL apoc.meta.data()
```
we were getting:
```
java.lang.IllegalArgumentException: duplicate element: RELATIONSHIP
```
=> [wbVWvi0y] Solves apoc.meta.data bug with reserved names for relationships and nodes

full-it/src/test/java/apoc/full/it/BoltTest.java, full/src/main/java/apoc/bolt/BoltConnection.java
cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/6174c7e997c2f3d63db689e67a2b792bd207c07f
=> [NOID] Fixes #3945: The apoc.bolt.* procedures fail together with the apoc.path.subgraphAll one (#3949)

build.gradle, extended/src/main/java/apoc/ExtendedApocConfig.java, extended/src/test/java/apoc/custom/CypherProceduresClusterRoutingTest.java, extended/src/test/java/apoc/cypher/CypherEnterpriseExtendedTest.java, extended/src/test/java/apoc/cypher/CypherExtendedTest.java
Fixed the following CI  errors:
- Commit https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3977/commits/c8a7c679540eb6716c7783fd04d00758de13a892
Added `apacheArrowVersion` like in [APOC Core](https://github.com/neo4j/apoc/commit/97135914bafa630bf12f7e0dd832090fdbb6afd6) to fix CI error.
See https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/8099150501/job/22134234538?pr=3976#step:6:35
```
FAILURE: Build failed with an exception.
* Where:
Build file '/home/runner/work/neo4j-apoc-procedures/neo4j-apoc-procedures/apoc-core/test-utils/build.gradle' line: 46
* What went wrong:
A problem occurred evaluating project ':test-utils'.
> Could not get unknown property 'apacheArrowVersion' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependency …
```
=> Fix apacheArrowVersion failing test and apoc-config.xml test error

docs/asciidoc/modules/ROOT/pages/database-integration/load-ldap.adoc, extended/build.gradle, extended/src/main/java/apoc/load/LoadLdap.java, extended/src/test/java/apoc/load/LoadLdapContainerTest.java, extended/src/test/java/apoc/load/LoadLdapTest.java
Fixes #3775
With the current library, it fails to use SSL, as it gives the same error reported on the issue, either using SSLUtil as currently done, or using a method similar to this, which I tried to use here: https://github.com/vga91/neo4j-apoc-procedures/pull/431/commits/5585b9173f053d3a7a59af23050e5cb1babf0f54.
So I think the ideal solution is to change the library with the one already included in the `LoadLdapTest.java` and it works similarly to the current library.
The two libraries should report compatible results, since the [`setMaxResults(0)`](https://github.com/vga91/neo4j-apoc-procedures/pull/431/files#diff-fd085351886560eb5c6ae3773b61ab72ac44e6f9bb24b39bb8fb6e030b541492L145) given in the old library is not necessary since with the new library the sizeLimit is 0. As well as …
=> Fixes #3775: apoc.load.ldap doesn't work with SSL

extended/src/test/java/apoc/ml/OpenAIIT.java, extended/src/test/java/apoc/ml/OpenAITestResultUtils.java
Fixes #3952
Added integration tests with default parameters 
and with custom embedding size by adding `dimensions: 256`to the configuration
=> Fixes #3952: check if the new openai embedding models work in an integration test

docs/asciidoc/modules/ROOT/pages/ml/openai.adoc, extended/src/test/java/apoc/ml/OpenAIGroqAPIsIT.java
Fixes #3972
The procedures are completely compatible with OpenAI, 
both the endpoint final parts (i.e. `/chat/completions` and `/embeddings`) and the headers,
so the integration test has just been created.
=> Fixes #3972: Add support for Groq AI for ml procedures

extended/src/main/java/apoc/cypher/CypherExtended.java, extended/src/test/java/apoc/cypher/CypherExtendedTest.java, extended/src/test/resources/return.cypher, extended/src/test/resources/schemaWithCommentsAndEmptyRows.cypher
Fixes #3798
- fixed bug and added tests with comments and empty rows / spaces, for both schema and non-schema files
- added white spaces to `scanner.useDelimiter(...);`,
as it should work even if there is a semicolon with whitespace at the end of the line, i.e. `;  `
=> Fixes #3798: apoc.cypher.runFile() - Unexpected behaviour with commented ;

extended/src/test/java/apoc/load/LoadCsvTest.java, extended/src/test/java/apoc/util/ExtendedTestUtil.java, extended/src/test/resources/test-mapping-many-types.csv
Fixes https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/3218
Up to 5.16 we had to use a workaround not to throw a NullPointerException with datetime/time mappings, since the bug is in Core. 
E.g.
```
CALL apoc.load.csv('test.csv', {mapping:{name:{type: "datetime", optionalData: {}}}})
```
But, as this PR https://github.com/neo4j/apoc/pull/571 is merged,
we can use `datetime` without `optionalData: {}` workaround, e.g.:
```
CALL apoc.load.csv('test.csv', {mapping:{name:{type: "datetime"}}})
```
- added test with multiple types and optionalData
- added test with multiple types and without optionalData, to check that the APOC Core's fix works correctly
- added `assertMapEquals` util, to check more easily the possible failied entry map
=> Fixes #3218: java.lang.NullPointerException when setting the type of a property to datetime in the mapping config of apoc.load.csv()

extended/src/main/java/apoc/load/LoadCsv.java, extended/src/main/java/apoc/load/util/LoadCsvConfig.java, extended/src/test/java/apoc/load/LoadCsvTest.java, extended/src/test/resources/faulty.csv
Fixes #3156
- Added `if (failOnError) { throws new RuntimeException(...)}` in CSVSpliterator
- Consistent with [apoc.load.json](https://github.com/neo4j/apoc/blob/dev/common/src/main/java/apoc/load/LoadJsonUtils.java#L68), it doesn't log anything
- Removed `ignoreErrors` config, which is unused, not documented anywhere, and can get confusing as there is the config `failOnError`.
- Skip `lineNo` counter in case of an invalid row
=> Fixes #3156: apoc.load.csv, failure despite failOnError:false

extended/src/test/java/apoc/ml/OpenAIMistralApiIT.java, extended/src/test/java/apoc/ml/OpenAITestResultUtils.java
Fixes #3970
The procedures are completely compatible with OpenAI, 
both the endpoint final parts (i.e. `/chat/completions` and `/embeddings`) and the headers,
so the integration test has just been created.
=> Fixes #3970: Add support for Mistral AI

extended/src/test/java/apoc/custom/CypherProceduresClusterRoutingTest.java, extended/src/test/java/apoc/cypher/CypherEnterpriseExtendedTest.java, extended/src/test/java/apoc/cypher/CypherExtendedTest.java
De-ignored tests which fail in dev (5.19.x) but not in 5.18.x.
Created an issue to solve them in 5.19: https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/3998
=> De-ignored tests which fail in dev (5.19.x) but not in 5.18.x

extended/build.gradle, extended/src/main/java/apoc/load/Jdbc.java, extended/src/main/java/apoc/load/util/JdbcUtil.java, extended/src/main/java/apoc/model/Model.java, extended/src/test/java/apoc/load/MySQLJdbcTest.java, extended/src/test/java/apoc/model/ModelTest.java, extended/src/test/java/apoc/util/s3/MySQLContainerExtension.java, extended/src/test/resources/init_mysql.sql
Fixes #3496 
The problem occurs with the latest versions of the mysql Jdbc connector
- Updated `schemacrawler-mysql` (which downloads the mysql jdbc connector), 
also because of the current version has some vulnerable dependencies
- Fixed the problem via code block: `if (value instanceof LocalDateTime ...`
- Added tests for date and time
- Duplicated tests with the latest version of mysql
=> Fixes #3496: Simple mysql select now(); Throws class java.time.LocalDateTime cannot be cast to class java.sql.Timestamp

extended/src/main/java/apoc/uuid/UuidHandler.java, extended/src/test/java/apoc/uuid/UUIDNewProceduresTest.java
Fixes #3840
Added check `txData.isDeleted(entity)` at the start of the forEach properties.
=> Fixes #3840: UUID handler throws warnings when deleting nodes

extended/src/test/java/apoc/custom/CypherProceduresClusterRoutingTest.java
To stabilize the test, added `db.clearQueryCaches()` before assertions, 
and improved assertEventually(..) with a try-catch which doesn't fail in case of procedure/function not found exception:
https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/8021701219/job/21914372905?pr=3957#step:6:1371
=> Fix flaky CypherProceduresClusterRoutingTest

extended/src/test/java/apoc/mongodb/MongoTestBase.java
Fixes #3964
Now the problem seems not to be present anymore.
Hence, increased the timeout of the assertEventually and added the output of `db.serverStatus().connections` as a println, to check in case of potential future similar problems.
=> Fixes #3964: Solve flaky mongodb test

docs/asciidoc/modules/ROOT/pages/ml/openai.adoc, extended/src/main/java/apoc/ml/Prompt.java, extended/src/test/java/apoc/ml/PromptIT.java
Fixes #4002
- In case of error, add the error messages in the `otherPrompts` list
- Used `transaction.execute` via `var transaction = db.beginTx()` instead of `tx.execute`, since the latter throws an error `The transaction has been terminated. Retry your operation in a new transaction, and you should see a successful result.`, in case of retried prompt.
=> Fixes #4002: In case of the llm generates a wrong query, improve by sending the query with the error

LICENSES.txt, NOTICE.txt, core/build.gradle, extra-dependencies/hadoop/build.gradle, licenses-3rdparties.gradle, test-utils/build.gradle
This PR will mitigate the following vulnerabilities:
CVE 2019-10172 (high)
CVE-2019-10202 (critical)
CVE-2019-16869 (medium)
CVE-2019-17571 (critical)
CVE-2020-9488 (low)
CVE-2020-29582 (low)
CVE-2021-4104 (medium)
CVE-2022-23302 (high)
CVE-2022-23305 (high)
CVE-2022-23307 (high)
CVE-2022-24329 (medium)
CVE-2023-3635 (medium)
CVE-2023-26464 (medium)
CVE-2023-34453 (medium)
CVE-2023-34454 (medium)
CVE-2023-34455 (high)
CVE-2023-34462 (medium)
CVE-2023-36478 (high)
CVE-2023-40167 (medium)
CVE-2023-43642 (high)
CVE-2023-44487 (high)
CVE-2023-44981 (high)
CVE-2024-23944 (medium)
CWE-310 (medium)
CWE-611 (low)
4.4 version of https://github.com/neo4j/apoc/pull/612
=> [3f8zK8nS] Upgrade hadoop from 3.3.6 to 3.4.0 to mitigate multiple vulnerabilities

build.gradle, docs/asciidoc/antora.yml, docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc, docs/build.gradle, extended/build.gradle, extended/src/test/java/apoc/ml/VertexAITest.java, extended/src/test/java/apoc/ml/aws/BedrockTest.java, extended/src/test/java/apoc/ml/sagemaker/SageMakerTest.java, extra-dependencies/build.gradle, readme.adoc
- Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/11c94f34b339cbe475bb92a9f122e06456342de4 (bump version)
---
- Fixed [several CI errors](https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/8685106098/job/23816840835), like this:
```
apoc.custom.CypherProceduresStorageTest > testMultipleOverrideWithFunctionAndProcedures FAILED
org.neo4j.graphdb.QueryExecutionException: Failed to invoke procedure `apoc.custom.declareProcedure`: Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsupportedOperationException: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with version 3 (expected 4). [in thread "Test worker"]
at app//org.neo4j.kernel.impl.query.QueryExecutionKernelException.asUserException(Qu …
```
=> Fixed several CI errors and bump version 5.20.0 (#3456) (#3536) (#3726)

extended/src/main/java/apoc/ml/MLUtil.java, extended/src/main/java/apoc/ml/OpenAI.java, extended/src/main/java/apoc/ml/VertexAI.java, extended/src/main/java/apoc/ml/Watson.java, extended/src/main/java/apoc/ml/aws/Bedrock.java, extended/src/test/java/apoc/ml/MLTestUtil.java, extended/src/test/java/apoc/ml/OpenAIIT.java, extended/src/test/java/apoc/ml/VertexAIIT.java, extended/src/test/java/apoc/ml/WatsonIT.java, extended/src/test/java/apoc/ml/aws/BedrockIT.java, extended/src/test/java/apoc/ml/sagemaker/SageMakerIT.java
Fixes #3611 
- vertexai and openai embeddings return null rows with null list values
- embeddings, chat completion, completion and image procedures return null if the input parameter is null
- not implemented null check in apoc.ml.<type>.custom procedures, since we can potentially pass a null parameter (e.g. to call [this RestAPI](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_GetModelInvocationLoggingConfiguration.html))
- Added trello card (id: G2oExgfb) for the above issue.
Would be great to handle errors like these, but we cannot implement it since is part of APOC Core:
`CALL apoc.ml.openai.chat([ {role:"user", content:null}], $apiKey, $conf)`
We should do something like this:
```
@Override
public InputStream getInputStream() throws IOException {
if (con instanceof …
```
=> Fixes #3611: ML API procedures handle null values being passed in better

docs/asciidoc/modules/ROOT/pages/database-integration/elasticsearch.adoc, extended-it/src/test/java/apoc/es/ElasticSearchTest.java, extended-it/src/test/java/apoc/es/ElasticVersionEightTest.java, extended-it/src/test/java/apoc/es/ElasticVersionSevenTest.java, extended/src/main/java/apoc/es/ElasticSearch.java, extended/src/main/java/apoc/es/ElasticSearchConfig.java, extended/src/main/java/apoc/es/ElasticSearchHandler.java
Fixes #3360
Created a trello card (id: uHLecigr), to add the certificate handling [here](https://github.com/neo4j/apoc/blob/dev/common/src/main/java/apoc/util/Util.java#L334).  
Since we cannot use certificates, see below, I created tests using basic authentication with the `xpack.security.http.ssl.enabled: false` configuration
- Create factory ElasticSearchHandler
- Split test to test both Elastic 7.9.2 (default tag) and Elastic 8.12.1, where the ElasticSearchTest.java is now the Base Test
- Tried several Elastic 8 APIs
- Some refactoring / code cleaning
=> Fixes #3360: Add support for newer Elasticsearch search api

extended-it/src/test/java/apoc/neo4j/docker/CypherEnterpriseExtendedTest.java, extended/src/main/java/apoc/cypher/CypherExtended.java, extended/src/test/java/apoc/cypher/CypherExtendedTest.java
Fixes #3998
Solved the first 2 test errors, CypherEnterpriseExtendedTest and CypherExtendedTest.
The 3rd one depends on the Core.
- De-ignored and solved tests with neo4j 5.19+ version.
The following error is possibly due to the transaction closing, which has to be done with try-with-res, instead of via onClose(..) 
```
The transaction has been terminated. Retry your operation in a new transaction, 
and you should see a successful result. 
The transaction was marked as failed because a query failed. org.neo4j.graphdb.TransactionTerminatedException: The transaction has been terminated. 
Retry your operation in a new transaction, and you should see a successful result. 
The transaction was marked as failed because a query failed. 
```
=> Fixes #3998: Solve CypherExtendedTest and CypherEnterpriseExtendedTest

extended/src/main/kotlin/apoc/nlp/aws/AWSProcedures.kt, extended/src/main/kotlin/apoc/nlp/aws/RealAWSClient.kt, extended/src/test/kotlin/apoc/nlp/aws/AWSProceduresAPIWithEnvVarsTest.kt, extended/src/test/kotlin/apoc/nlp/aws/AWSProceduresErrorsTest.kt
Fixes #1596
Now the apoc.nlp, in case of key and secret config not defined, leverage [com.amazonaws.auth.DefaultAWSCredentialsProviderChain](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html), so it look for env vars, system properties, etc..
=> Fixes #1596: Change key/secret to optional in apoc.nlp calls for AWS

extended/src/main/java/apoc/ml/Prompt.java, extended/src/test/java/apoc/ml/PromptIT.java
Fixes #4070
Change apoc.ml.fromCypher prompt,
as it should focus on the actual query and not on explaining the schema.
=> Fixes #4070: Change apoc.ml.fromCypher prompt

docs/asciidoc/modules/ROOT/nav.adoc, docs/asciidoc/modules/ROOT/pages/ml/index.adoc, docs/asciidoc/modules/ROOT/pages/ml/mixedbread.adoc, docs/asciidoc/modules/ROOT/pages/ml/openai.adoc, extended/src/main/java/apoc/ml/MixedbreadAI.java, extended/src/main/java/apoc/ml/OpenAI.java, extended/src/main/java/apoc/ml/OpenAIRequestHandler.java, extended/src/main/resources/extended.txt, extended/src/test/java/apoc/ml/MixedbreadAIIT.java
Fixes #4058
- New procedures instead of apoc.ml.openai since it behaves a bit different, and we can use other APIs, like reranking
- They leverage the openAI ones
=> Fixes #4058: Add support for mixedbread.ai Embedding API

extended/build.gradle, extra-dependencies/hadoop/build.gradle
Fixes #4055
- Updated and tested hadoop new dependencies
----
- [removed unnecessary hadoop-aws package](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4063/commits/61c64def3da2ea5b5b8e7ba851a5c0ce9d8fafd5) commit: removed the hadoop-aws, since it cause a strange [heap space error](https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/9079399293/job/24995551577?pr=4063#step:7:276) with the 3.4.0 version,
but it's unnecessary anyway, as with the `hadoop-*` 3.4.0 packages, the hadoop procedures work also without that package,
e.g. `call apoc.load.parquet("s3://s3.us-east-2.amazonaws.com:443/aws-public-blockchain/v1.0/btc/transactions/date=2010-05-01/part-00000-8829a06f-164c-4e33-a24a-780316e09cc6-c000.snappy.parquet?accessKey=<accessKey>&secretKey=<secretKey>")`
=> Fixes #4055: Upgrade hadoop to 3.4.0

extended-it/src/test/java/apoc/neo4j/docker/BoltTest.java, extended-it/src/test/java/apoc/neo4j/docker/CoreExtendedTest.java, extended-it/src/test/java/apoc/neo4j/docker/StartupExtendedTest.java
Some tests fail with the new neo4j version.
Provisionally ignored failing test, to be fixed later 
See https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/9230611333/job/25399125287
=> Provisionally ignored failing docker tests in 5.20

extra-dependencies/mongodb/build.gradle
Fixes #4054
- upgraded driver version
- tested in Neo4j Desktop with mongo:4 and mongo:7.0.4 images (the ones present in the integration tests)
=> Fixes #4054: Broken Dependencies with apoc.mongo

docs/asciidoc/modules/ROOT/pages/ml/openai.adoc, extended/src/main/java/apoc/ml/Prompt.java, extended/src/main/java/apoc/ml/RagConfig.java, extended/src/main/resources/extended.txt, extended/src/test/java/apoc/ml/PromptIT.java, extended/src/test/resources/rag.cypher
Fixes #4005
Added a procedure for RAG you pass the user question plus a graph pattern (paths) and relevant attributes and it creates a prompt to answer the user question using the data on those paths and executes that with the llm provider and returns the answer
Retrieval-augmented generation (RAG) is a technique that reduces hallucinations and enhances the accuracy and reliability of generative AI models with facts fetched from external sources.
See here: https://aws.amazon.com/it/what-is/retrieval-augmented-generation/
- Created `apoc.ml.rag(paths, attributes, question, conf)` procedure
- `paths` can be a list of paths to retrieve and augment the prompt, it can also be a matching query or a vector index name
- `attributes` is the list of relevant attributes useful to retrieve and …
=> Fixes #4005: Add a procedure for RAG

extended/build.gradle, extra-dependencies/aws/build.gradle, extra-dependencies/build.gradle, extra-dependencies/yaml/build.gradle
Upgraded `com.fasterxml.jackson.dataformat` version and excluded `jackson-core` from `extra-dependencies`, 
to solve the below conflict errors, 
since the `jackson-core:2.17.0` jar is already present in the `/lib` folder of the new neo4j version.
Conflict error:
----
Also verified that procedures using the `s3://` protocol still work.
=> Solve 5.20 extra-dependencies conflict errors

docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/chroma.adoc, docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/milvus.adoc, docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/pinecone.adoc, docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/qdrant.adoc, docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/weaviate.adoc, extended-it/src/test/java/apoc/vectordb/ChromaDbTest.java, extended-it/src/test/java/apoc/vectordb/MilvusTest.java, extended-it/src/test/java/apoc/vectordb/QdrantTest.java, extended-it/src/test/java/apoc/vectordb/WeaviateTest.java, extended/src/main/java/apoc/vectordb/ChromaDb.java, extended/src/main/java/apoc/vectordb/Milvus.java, extended/src/main/java/apoc/vectordb/Pinecone.java, extended/src/main/java/apoc/vectordb/Qdrant.java, extended/src/main/java/apoc/vectordb/VectorDb.java, extended/src/main/java/apoc/vectordb/VectorDbUtil.java, extended/src/main/java/apoc/vectordb/VectorMappingConfig.java, extended/src/main/java/apoc/vectordb/Weaviate.java, extended/src/test/java/apoc/vectordb/PineconeTest.java, extended/src/test/java/apoc/vectordb/VectorDbTestUtil.java
Fixes #4090
The apoc.vectordb.*.get/query procedures show nodes/rels that can be updated with mapping config
=> Fixes #4090: The apoc.vectordb.*.get/query procedures should search for nodes/relationships with mapping config

extended-it/src/test/java/apoc/vectordb/ChromaDbTest.java, extended-it/src/test/java/apoc/vectordb/QdrantTest.java, extended/build.gradle
- vectordb tests:
changed `"localhost"` to `<CONTAINER>.getHost()`
- hadoop tests:
restored hadoop dependencies to those present in version 5.19.0, that has been changed [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4063) and [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4094)
=> Try to solve 5.20 TC errors

.gitmodules, extended/src/main/java/apoc/custom/CypherProceduresHandler.java, extended/src/main/java/apoc/cypher/CypherExtended.java, extended/src/main/java/apoc/export/arrow/ImportArrow.java, extended/src/main/java/apoc/export/parquet/ExportParquet.java, extended/src/main/java/apoc/export/parquet/ParquetReadUtil.java, extended/src/main/java/apoc/load/LoadCsv.java, extended/src/main/java/apoc/load/LoadDirectory.java, extended/src/main/java/apoc/load/LoadHtml.java, extended/src/test/java/apoc/export/parquet/ParquetTest.java, extended/src/test/java/apoc/load/LoadCsvTest.java, extended/src/test/java/apoc/util/ExtendedTestUtil.java, extended/src/test/java/apoc/util/FileUtilsTest.java
- [Fixed various 5.21 compile errors after restoring submodule version](https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/ccaa5615eb089add531fc3ae52fa151fa448afc0)
See [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/9226836558/job/25387484476)
- [Solved error: cannot find symbol, due to `org.neo4j.kernel.api.procedure.ProcedureView` 5.21 changes](https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/39dc06071354e176504876a8651ce9d01115103a)
See [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/9364741459/job/25778380117#step:7:224)
- [Changed ParquetTest.testStreamRoundtripParquetAllWithImportExportConfsDisabled](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4100/commits/ceb2380aa420e51df6def8bed6d5599c4f …
=> Solve dev 5.21 compile errors

extended/src/main/java/apoc/custom/CypherProceduresHandler.java, extended/src/main/java/apoc/custom/CypherProceduresUtil.java, extended/src/main/java/apoc/custom/Signatures.java, extended/src/main/java/apoc/cypher/CypherExtended.java, extended/src/main/java/apoc/export/arrow/ImportArrow.java, extended/src/main/java/apoc/export/parquet/ExportParquet.java, extended/src/main/java/apoc/export/parquet/ParquetReadUtil.java, extended/src/main/java/apoc/load/LoadCsv.java, extended/src/main/java/apoc/load/LoadDirectory.java, extended/src/main/java/apoc/load/LoadHtml.java, extended/src/test/java/apoc/export/parquet/ParquetTest.java, extended/src/test/java/apoc/load/LoadCsvTest.java, extended/src/test/java/apoc/systemdb/SystemDbTest.java, extended/src/test/java/apoc/util/ExtendedTestUtil.java, extended/src/test/java/apoc/util/FileUtilsTest.java
Solve 5.21 compile errors
- Added CypherScope.CYPHER_5, added [here](https://github.com/neo4j/neo4j/blob/5.21/community/kernel-api/src/main/java/org/neo4j/kernel/api/CypherScope.java), which annotates procedures usable in Cypher 5.x
- Changed [namespace](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4126/files#diff-7a6794bc38939217b5b8ca0f55b06b9cfd4bfd59ebd1be9e2a4709f12c2c3304R97) from List<String> to String[], as in neo4j 5.21 the QualifiedName [no longer accept List<String>](https://github.com/neo4j/neo4j/blob/5.21/community/kernel-api/src/main/java/org/neo4j/internal/kernel/api/procs/QualifiedName.java#L34)
- Fixed various 5.21 compile errors due to APOC Core changes,
See [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/9226836558/job/2538748447 …
=> Solve 5.21 compile errors

extended-it/src/test/java/apoc/neo4j/docker/BoltTest.java, extended-it/src/test/java/apoc/neo4j/docker/CoreExtendedTest.java, extended-it/src/test/java/apoc/neo4j/docker/StartupExtendedTest.java
Fixes #4086
Tried several times, but the problems no longer seem to be present, 
maybe because the neo4j present in dev at the time differed from the 5.21 publicly released.
=> Fixes #4086: De ignore and solve failing docker tests in 5.21

extra-dependencies/build.gradle, extra-dependencies/xls/build.gradle
Fixes #4102: Make Apache Commons libraries that are now part of neo4jas provided or exclude them
- Upgraded dependencies to solve conflict errors and fix sub-dependencies vulnerabilities
- Added `'org.apache.logging.log4j'` to `commonExclusions` and changed exclusions in `extra-dependencies/xls/build.gradle` to `commonExclusions`
=> Fixes #4102: make apache commons libraries that are now part of neo4j as provided or exclude them

docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/chroma.adoc, docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/milvus.adoc, docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/qdrant.adoc, docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/weaviate.adoc, extended-it/src/test/java/apoc/vectordb/ChromaDbTest.java, extended-it/src/test/java/apoc/vectordb/MilvusTest.java, extended-it/src/test/java/apoc/vectordb/QdrantTest.java, extended-it/src/test/java/apoc/vectordb/WeaviateTest.java, extended/src/test/java/apoc/util/ExtendedTestUtil.java, extended/src/test/java/apoc/vectordb/VectorDbTestUtil.java
Fixes #4101
Added performance tests with different vector sizes, since each vector db has a different infrastructural limit,
for example, ChromaDb's upsert API is limited to 41666
=> Fixes #4101: Add Vector Db performance tests

docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/chroma.adoc, docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/custom.adoc, docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/milvus.adoc, docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/pinecone.adoc, docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/qdrant.adoc, docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/weaviate.adoc, extended-it/src/test/java/apoc/vectordb/MilvusTest.java, extended-it/src/test/java/apoc/vectordb/WeaviateTest.java, extended/src/main/java/apoc/vectordb/Milvus.java, extended/src/main/java/apoc/vectordb/VectorDb.java, extended/src/main/java/apoc/vectordb/VectorDbUtil.java, extended/src/main/java/apoc/vectordb/VectorEmbeddingConfig.java, extended/src/main/java/apoc/vectordb/Weaviate.java
Fixes #4121
Added errors field to EmbeddingResult, 
which will be returned in case of JSON response with 200 OK having a value with key "errors", like happening with `apoc.vectordb.milvus.query` and `apoc.vectordb.weaviate.query` endpoints, and with `apoc.vectordb.milvus.get` endpoint
=> Fixes #4121: Better error messaging with vectordb query/get procedures

docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/index.adoc, extended-it/src/test/java/apoc/vectordb/MilvusTest.java, extended-it/src/test/java/apoc/vectordb/WeaviateTest.java, extended/src/main/java/apoc/vectordb/MilvusHandler.java, extended/src/main/java/apoc/vectordb/VectorDbUtil.java, extended/src/main/java/apoc/vectordb/WeaviateHandler.java, extended/src/test/java/apoc/vectordb/VectorDbTestUtil.java
Fixes #4134
Now the `fields` config is added with the `metadataKey` value, if present.
So, in case `mapping` config is defined, the `fields` key is no longer needed.
=> Fixes #4134: The apoc.vectordb.weaviate.query and the apoc.vectordb.milvus.query/get should populate the fields config with the metadataKey if present

.gitignore, extended-it/src/test/java/apoc/vectordb/ChromaDbTest.java, extended-it/src/test/java/apoc/vectordb/QdrantTest.java, gradle.properties
- commit https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4137/commits/aaab44ed254fa7614f2df71b3ea37d527b47036a, vectordb tests:
changed `"localhost"` to `<CONTAINER>.getHost()` to solve the connection refused error in TeamCity
- commit https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4137/commits/2087e9d88fc589cd80fdb628c0bb9be2d2048561, de-ignored gradle.properties,[ to be consistent with the Core one, which has the gradle.properties explicit](https://github.com/neo4j/apoc/blob/dev/gradle.properties), and to try to solve the heap space error in TeamCity:
=> Try to solve 5.21 TC errors

build.gradle, docs/asciidoc/antora.yml, docs/asciidoc/modules/ROOT/partials/neo4j-server.adoc, docs/build.gradle, extra-dependencies/build.gradle, readme.adoc
Bump dev version to 5.21.0 
Cherry-pick of https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/ea144746b83416e2eb6367b7567a8ae6d6d71436
=> Bump version 5.21.0 (#3456) (#3536) (#3726)

docs/asciidoc/modules/ROOT/pages/ml/genai.adoc, docs/asciidoc/modules/ROOT/pages/ml/openai.adoc, extended/src/main/java/apoc/ml/OpenAI.java, extended/src/main/java/apoc/ml/Prompt.java, extended/src/test/java/apoc/ml/PromptIT.java
Fixes #4133
- Changed default model
- Added test with old model, to make sure they continue to work afterwards
=> Fixes #4133: switch default model for cypher/schema interactions to gpt-4o

docs/asciidoc/modules/ROOT/pages/database-integration/elasticsearch.adoc, docs/asciidoc/modules/ROOT/pages/overview/apoc.es/apoc.es.post.adoc, extended-it/src/test/java/apoc/es/ElasticVersionEightTest.java, extended/src/main/java/apoc/es/ElasticSearch.java
Fixes #4110
- Updated ElasticSearch container version to 8.14.3 to support Reciprocal Rank Fusion (RRF)
- Changed license version to `trial` to use RRF search
- Changed input type from Map to Object to procedure `apoc.es.post` to support empty string input for **payload** because passing null produces an empty map `{}`
=> Fixes #4110: Add support for the Reciprocal rank fusion in the Elastic procedures

extended/src/test/java/apoc/systemdb/SystemDbTest.java, extended/src/test/java/apoc/trigger/TriggerExtendedTest.java
Added `systemPropertyRule` to the `apoc.trigger.*` related tests, to solve tests that fail [due to these changes](https://github.com/neo4j/apoc/pull/637/files).
Otherwise, we will have a NullPointer, since the `triggerHandler` variable won't be assigned.
This happens since, using the `apocConfig().setProperty(ApocConfig.APOC_TRIGGER_ENABLED, true);` currently present, this [if condition](https://github.com/neo4j/apoc/pull/637/files#diff-e9c5851b9e9eaf8bf7fc7c3873340b49e22d840d0b7caba1b9fda8562006f02cR41) is false, because the `apocConfig` will be evaluated later, unlike the `systemPropertyRule` mechanism.
- removed unused start field
=> Solve dev with APOC 5.22 build errors

extended-it/src/test/java/apoc/s3/LoadS3Test.java, extended/src/test/java/apoc/load/LoadCsvTest.java, extended/src/test/java/apoc/ml/WatsonTest.java
Try to solve TC 5.22 errors:
- BindException: Address already in use
Changed 1080 with PortFactory.findFreePort() in WatsonTest and LoadCsvTest to avoid the error.
- queryReadOnlyVectorsWithMapping FAILED, Caused by: java.net.SocketTimeoutException: Read timed out
Tried several time but not replicated, it could be a sporadic flaky error
----
- mock server error:
See [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/10181988389/job/28163453948?pr=4163#step:6:3351).
Copied assertion to LoadS3Test, since otherwise there is the following error,
as the `org/mockserver/socket/PortFactory` module is not included in `extended-it`, that is where the LoadS3Test is located
```
apoc.s3.LoadS3Test > testLoadCsvS3 FAILED
java.lang.NoClassDefFoundError: …
```
=> Try to solve TC 5.22 errors

docs/asciidoc/modules/ROOT/partials/docker.adoc
User's are getting confused why APOC core isn't automatically installed with APOC extended, this adds a note to the docs about it.
=> [NOID] Add note about how to install APOC Core

full/src/main/java/apoc/cypher/CypherExtended.java, full/src/test/resources/wrong_statements.cypher, full/src/test/resources/wrong_statements_runtime.cypher
RunFile is not allowed to run schema operations, in 4.4.0.9 the validation check for this was a regex that was very basic, then in 4.4.0.11 this was updated to be more accurate, what happens is that every query gets run through an explain which checks if the query is a Schema operation, and if it is, it will ignore it. 
The problem I see with this is that it will now run this potentially time consuming check for every query in the file as well as actually running the query.
This PR removes this check and instead checks the errors thrown, if a schema error is thrown then it will handle this there to keep old behaviour.
=> [aYPLiTQG] Remove isSchema check to be more performant

docs/asciidoc/modules/ROOT/nav.adoc, docs/asciidoc/modules/ROOT/pages/import/gexf.adoc, docs/asciidoc/modules/ROOT/pages/import/index.adoc, extended/src/main/java/apoc/load/Gexf.java, extended/src/main/java/apoc/load/util/XmlReadUtil.java, extended/src/main/java/apoc/util/ExtendedUtil.java, extended/src/main/resources/extended.txt, extended/src/test/java/apoc/load/GexfTest.java, extended/src/test/java/apoc/util/ExtendedTestUtil.java, extended/src/test/resources/gexf/data.gexf, extended/src/test/resources/gexf/malformed.gexf, extended/src/test/resources/gexf/single-node.gexf, extended/src/test/resources/gexf/single-rel.gexf
Fixes #4138
- Added procedures for reading GEXF files. 
- Copied and pasted code from APOC Core and put it into `XmlUtil.java`
- Changed parseXML method to be able to handle properties of gexf files. To handle the name of relations we parse the `kind` tag. While for node properties we change from doing the parse of the `data` tag to the `attvalue` tag. Also, to parse the label in the `node` tag you parse `labels` instead of `labels` as compared to how it is done for graphml.
- Multiple label support for nodes. Example `<node id=“0” label=“:Gephi:Webatlas”>`.
- Types tested: `string, integer, long, foat, double, boolean, liststring, listboolean`
- Improved `ExtendedUtil.convertValue` with toLowerCase(), to be used by both Parquet/Arrow and Gefx formats
- Improved ExtendedTestUtil
- added …
=> Fixes #4138: Add support for loading Gephi GEXF file format

core-it/src/test/java/apoc/core/it/ExportCsvS3Test.java, core/src/main/java/apoc/export/csv/CsvFormat.java, core/src/main/java/apoc/export/util/ExportConfig.java, core/src/test/java/apoc/export/csv/ExportCsvTest.java
[uRFsgcuC] Backports fix from 5.x so that quotes are correctly applied when the `ifNeeded` flag is used. Inspired by [fix](https://github.com/neo4j/apoc/pull/645).
=> [uRFsgcuC] Backport of 5.x ifNeeded quote fix

full/src/main/kotlin/apoc/nlp/aws/AWSProcedures.kt, full/src/main/kotlin/apoc/nlp/aws/RealAWSClient.kt, full/src/test/kotlin/apoc/nlp/aws/AWSProceduresAPIWithEnvVarsTest.kt, full/src/test/kotlin/apoc/nlp/aws/AWSProceduresErrorsTest.kt
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/22c2d04c15e86ea48b0f48c5b342b04cab06c05a
=> [NOID] Fixes #1596: Change key/secret to optional in apoc.nlp calls for AWS (#4062)

.github/actions/test-gradle-project/action.yml, .github/workflows/CI.yaml, .gitmodules, build.gradle, extended/src/main/java/apoc/custom/CypherProceduresHandler.java
Created another PR, waiting for: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4179,
which fails due to timeout exception.
- Changed references and gitmodule to 5.24
- Fixed compile error with 5.24 version due to Neo4j change, see here: https://github.com/neo4j/neo4j/commit/2f2dc348047c02036a3ded6d01dae4c74b9579e1
- Removed code artifact implementation from ci.yaml, so that we download neo4j from mvn repository and dockerhub
- updated `upload-artifact` version (which is not valid anymore)
~try solving https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/11167910649/job/31045136258?pr=4199#step:9:2191~
=> Fixed compile error with 5.24 and provisionally fixed docker and upload-artifact errors

extended-it/src/test/java/apoc/load/PostgresJdbcTest.java, extended/build.gradle, extended/src/main/java/apoc/load/Jdbc.java, extended/src/main/java/apoc/load/util/JdbcUtil.java, extended/src/main/java/apoc/model/Model.java, extended/src/test/resources/init_postgres.sql
Fixes #4141
The problem should be related to [this change](https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/f978417fb40085269ca23ed18dc317d6bef7b587), using the `DatabaseConnectionSources` the issue error is (flakily) caused,
while with `Connection` it works correctly.
Strangely using the Postgres' issue version, the error is not replicable via `TestContainer`,
while can be replicated with the default present version: 9.6.12.
Maybe because the user version has some special configuration, or the test container is slightly different from the non-test version.
In any case, even with that version, the problem occurs infrequently, about 1 time every 10/15, most of the time you get a `“FATAL: sorry, too many clients already”` instead of an `"idle"` connection,
which is not the case …
=> Fixes #4141: apoc.load.jdbcUpdate inside apoc.periodic.iterate leaves idle connections from 5.19 and forward

extended-it/build.gradle, extended/build.gradle
With newer versions of IntelliJ (from 2024.1.x),
the imports of other java classes in extended are not properly detected without this fix.
See the Slack discussion: https://neo4j.slack.com/archives/C136J23GE/p1723459229156629
----
EDIT:
Added another commit, since a similar problem occurs in `extended-it` module, 
that is, we cannot import classes, if they are from the module`extended`, in another package name.
Therefore, without the change committed,
```
testImplementation project(':extended').sourceSets.main.allJava
```
we cannot e.g. import `JdbcUtil` (coming from package `apoc.load.util`) into class `` (package `apoc.load`), 
even if this line is present:
```
implementation project(":extended")
```
=> Fix unresolved imports with IntelliJ 2024.1+

docs/asciidoc/modules/ROOT/pages/ml/openai.adoc, extended/src/main/java/apoc/ml/OpenAI.java, extended/src/test/java/apoc/ml/OpenAIOpenLMIT.java
Fixes #4182
With `gpt2` and similar, the answers are not always valid.
Changed test case to `google-bert/bert-base-uncased`
Added `PATH_CONF_KEY` and `METHOD_KEY` as optional configurations, if not present, since some models fail with `method: 'GET'`, 
and the `path: ''` causes a fail or an incorrect result depending on the model.
=> Fixes #4182: The huggingface examples return strange results

docs/asciidoc/modules/ROOT/pages/ml/openai.adoc, extended/src/test/java/apoc/ml/OpenAILocalAIIT.java, extended/src/test/java/apoc/ml/OpenAITestResultUtils.java
Test some [tomasonjo](https://huggingface.co/tomasonjo) models for text2cypher with LocalAI
We have to deploy the model (with LocalAI in this case), as we cannot use the public remote [HF Inference API](https://huggingface.co/docs/api-inference/index), see e.g. [here](https://github.com/huggingface/chat-ui/issues/230), 
For instance, by using inference we receive:
```
.. Request
$ curl https://api-inference.huggingface.co/models/tomasonjo/text2cypher-codestral-16bit \
-d '{"inputs": "What color is the sky?"}' \
-H 'Content-Type: application/json' \
-H "Authorization: Bearer <API_TOKEN>"
.. response 
{"error":"The model tomasonjo/text2cypher-codestral-16bit is too large to be loaded automatically (44GB > 10GB). Please use Spaces (https://huggingface.co/spaces) or Inference Endpoints …
```
=> Fixes #4145: Add support for huggingface models

extended-it/src/test/java/apoc/couchbase/CouchbaseTestUtils.java, extended/src/test/java/apoc/export/csv/ExportCsvTest.java, extended/src/test/java/apoc/load/LoadLdapContainerTest.java
Try solving the following errors which happens in TeamCity, but not with GitHub Action.
- Exception in `apoc.export.csv.ExportCsvTest`
Non replicated locally.
It could be a corrupt folder or one that requires special permissions for some reason.
To try to fix it, we changed the folder to junit's `TemporaryFolder`
```
org.apache.hadoop.hdfs.server.common.InconsistentFSStateException: Directory /opt/teamcity-agent/work/af99a1b2d35610b6/neo4j-apoc-procedures/extended/hadoop/hdfs/name-0-1 is in an inconsistent state: file VERSION has layoutVersion missing.
at app//org.apache.hadoop.hdfs.server.common.StorageInfo.getProperty(StorageInfo.java:256)
at app//org.apache.hadoop.hdfs.server.common.StorageInfo.setLayoutVersion(StorageInfo.java:218)
at …
```
=> Try fixing 5.24 TeamCity errors

build.gradle, extended-it/src/test/java/apoc/couchbase/CouchbaseTestUtils.java, extended-it/src/test/java/apoc/load/PostgresJdbcTest.java, extended/src/test/java/apoc/export/csv/ExportCsvTest.java, extended/src/test/java/apoc/export/parquet/ParquetHdfsTest.java, extended/src/test/java/apoc/load/LoadHdfsTest.java, extended/src/test/java/apoc/load/LoadLdapContainerTest.java, extended/src/test/java/apoc/util/HdfsTestUtils.java
- [postgres error](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4206/files#diff-6ed3fdf3d5797eee9c7a40a83c97f842d06b51fa65fd349e90c4bca1326af1e9R135): added periodical check to idle connection, as the result of `pg_stat_activity` Is not always immediately updated
```
, stderr=)
java.lang.AssertionError: Current pg_stat_activity is: Container.ExecResult(exitCode=0, stdout= state
--------
idle
active
(2 rows)
, stderr=)
```
- [couchbase error](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4206/files#diff-7ef8b14be52bbb28a69e471aa541a4401063f38c4f23bf6b4be6855c15132610R68): the error could be the initial bucket not being properly loaded when I call the subsequent methods, as there is a BUCKET_OPEN_IN_PROGRESS, added a waitUntilReady to try to fix it 
``` …
```
=> Try again to solve remaining TeamCity errors

docs/asciidoc/modules/ROOT/partials/xls-dependencies.adoc, extended/build.gradle, extended/src/main/java/apoc/agg/Rollup.java, extended/src/main/java/apoc/coll/CollExtended.java, extended/src/main/java/apoc/dv/VirtualizedResource.java, extended/src/main/java/apoc/export/xls/ExportXlsHandler.java, extended/src/main/java/apoc/util/ExtendedListUtils.java, extended/src/main/java/apoc/util/ExtendedMapUtils.java, extended/src/main/java/apoc/uuid/UuidHandler.java, extended/src/main/java/apoc/vectordb/ChromaDb.java, extended/src/main/java/apoc/vectordb/VectorDb.java, extended/src/main/java/apoc/vectordb/VectorDbUtil.java, extra-dependencies/xls/build.gradle
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/fcbdae96110fbadee2561d1df7310aca3c7cd697
=> Fixes #4108: Remove org.apache.commons.collections* imports (#4129)

.github/workflows/CI.yaml, build.gradle, extended-it/src/test/java/apoc/neo4j/docker/BoltTest.java, extended-it/src/test/java/apoc/neo4j/docker/CoreExtendedTest.java, extended-it/src/test/java/apoc/neo4j/docker/StartupExtendedTest.java, extra-dependencies/build.gradle, extra-dependencies/hadoop/build.gradle
Manual cherry-pick of https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4215
=> Change Docker download based on branch name

extended-it/src/test/java/apoc/vectordb/QdrantTest.java, extended/src/test/java/apoc/gephi/GephiMock.java, extended/src/test/java/apoc/load/LoadCsvTest.java, extended/src/test/java/apoc/ml/WatsonTest.java, extended/src/test/java/apoc/util/ExtendedTestUtil.java
- try solving qdrant query tests by adding testResultEventually, to retry it in case of errors [like this on](https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/11681558222/job/32529169731#step:10:4603)
```
org.neo4j.graphdb.QueryExecutionException: Failed to invoke procedure `apoc.vectordb.qdrant.query`: Caused by: java.net.SocketTimeoutException: Read timed out
```
they are very flaky and seems to happen only with query procedures.
- try solving WatsonTest by adding `PortFactory.findFreePort()` instead of `1080`
- changed the remaining tests with fixed port `1080` as well, except the GephiMock since the gephi procedures has a default port value equal to 8080, so we should change each test to make them work (they don't seem to fail on TC anyway).
- put …
=> Try solving TeamCity errors in 5.25

LICENSES.txt, NOTICE.txt, core/build.gradle
Bumps the commons-io dependency to 2.17.0
Bumps the commons-io dependency to 2.17.0. Ask for by a support case. In passing, it also fixes a typo in a related code comment.
=> [UHlskzgQ] Upgrade commons-io dependency to 2.17.0

extended/src/main/java/apoc/export/arrow/ExportArrowExtended.java, extended/src/main/java/apoc/load/LoadJsonExtended.java, extended/src/main/java/apoc/load/arrow/LoadArrowExtended.java, extended/src/main/java/apoc/log/Neo4jLogStreamExtended.java, extended/src/test/java/apoc/export/arrow/ArrowExtendedTest.java, extended/src/test/java/apoc/export/arrow/ImportArrowExtendedTest.java, extended/src/test/java/apoc/log/Neo4jLogStreamExtendedTest.java
This is needed in the 5.26 branch, or if someone has both Core and Extended installed, there will be missing procedures!
=> Update moved procedures to have new class names

extended-it/src/test/java/apoc/vectordb/WeaviateTest.java, extended/src/main/java/apoc/vectordb/Weaviate.java
Fixes #4233
Added clearer error messages when response has `"errors"` field populated, instead of returning NullPointerException
=> Fixes #4233: Improve Weaviate error handling

extended-it/src/test/java/apoc/monitor/StoreInfoProcedureEnterpriseTest.java, extended/src/main/java/apoc/monitor/Store.java
Fixes #4197
The `RecordDatabaseLayout.cast()` method works only for embedded, 
while `RecordDatabaseLayout.convert()` works both with embedded db and with neo4j enterprise docker / desktop.
Therefore, added a dockerized test as well.
=> Fixes #4197: apoc.monitor.store fails for block stores

docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/pinecone.adoc, extended/src/main/java/apoc/vectordb/Pinecone.java, extended/src/main/java/apoc/vectordb/PineconeHandler.java, extended/src/main/java/apoc/vectordb/VectorDbUtil.java, extended/src/main/java/apoc/vectordb/VectorEmbeddingHandler.java, extended/src/test/java/apoc/vectordb/PineconeTest.java
Fixes #4242
- Changed collection references to indexe ones, 
except to createCollection and deleteCollection names, to be consistent with other vector db procedures
- Moved `NOTE` about collection naming on the top of the documentation.
The Pinecone APIs are changed meanwhile, therefore we:
- increased `Thread.sleep`s where needed
- changed endpoints
- changed testCall to testRetryCallEventually where needed
=> Fixes #4242: The Pinecone APOC implementation is misleading

extended/build.gradle
Similar to [this one](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4193),
with newer version we have another unresolved import in extended test classes.
For example, without the `testImplementation sourceSets.main.java`, from `apoc.vectordb.PineconeTest` we cannot resolve the `apoc.ml.RestAPIConfig` imports
=> Fix another unresolved imports with IntelliJ 2024.1+

extended-it/src/test/java/apoc/vectordb/WeaviateTest.java, extended/src/main/java/apoc/vectordb/VectorDb.java, extended/src/main/java/apoc/vectordb/VectorDbUtil.java
Fixes #4232
Added appendVersionUrlIfNeeded method in VectorDbUtil used in apoc.vectordb.configure
If host does not terminate for /vNUMBER add /v1
=> Fixes #4232: The apoc.vectordb.configure(WEAVIATE', ..) procedure should append /v1 to url

full-it/src/test/java/apoc/full/it/monitor/StoreInfoProcedureEnterpriseTest.java, full/src/main/java/apoc/monitor/Store.java
Fixes #4197
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/4044f236bd6644c9247e32a510b7cf3b9111e99c
=> [NOID] Fixes #4197: apoc.monitor.store fails for block stores (#4223)

docs/asciidoc/modules/ROOT/pages/ml/openai.adoc, full/src/main/java/apoc/ml/OpenAI.java, full/src/main/java/apoc/ml/Prompt.java, full/src/test/java/apoc/ml/OpenAIAzureIT.java, full/src/test/java/apoc/ml/PromptIT.java
Fixes #4133
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/83358f5781539d6b73ba933e761066c6574c417f
=> [NOID] Fixes #4133: switch default model for cypher/schema interactions to gpt-4o (#4143)

docs/asciidoc/modules/ROOT/pages/ml/openai.adoc, full/src/test/java/apoc/ml/OpenAIIT.java
Fixes #4122
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/fd4a4ec10cfee1660410e7ba24aac4dc4a8264e4
=> [NOID] Fixes #4122: Test if gemini-flash and gpt-4o work (#4158)

extended/src/main/java/apoc/load/Jdbc.java, extended/src/main/java/apoc/load/util/JdbcUtil.java, extended/src/test/java/apoc/load/JdbcTest.java, extended/src/test/java/apoc/load/LoadLdapTest.java, extended/src/test/java/apoc/util/ExtendedTestUtil.java
Fixex #4256
To solve the related issue, we suggest the user to use these 2 parameters:
```
db.logs.query.obfuscate_literals=true
db.logs.query.parameter_logging_enabled=false
```
and he agrees with the tip.
In any case, even with these changes, we still need to handle some errors correctly.
Added a custom exception to obfuscate in logs and the returning RuntimeException, 
since the connection string may contain the password.
Therefore, executing:
```
CALL apoc.load.jdbc("jdbc:notexistent://localhost:3306/data_mart?user=root&password=root","products")
```
the following exception (and log) will be returned:
```
java.sql.SQLException:
No suitable driver found for jdbc:notexistent://***
```
instead of the previous one:
```
java.sql.SQLException:
No suitable driver found for …
```
=> Fixex #4256: Obfuscate JDBC Password in query.log

docs/asciidoc/modules/ROOT/pages/overview/apoc.dv/apoc.dv.queryAndLink.adoc, docs/asciidoc/modules/ROOT/pages/virtual-resource/index.adoc, extended-it/src/test/java/apoc/dv/DataVirtualizationCatalogTest.java, extended-it/src/test/java/apoc/dv/DataVirtualizationCatalogTestUtil.java, extended/src/main/java/apoc/dv/DataVirtualizationCatalog.java
=> Fixes #4157: apoc.dv.queryAndLink how to specify direction

docs/asciidoc/modules/ROOT/pages/ml/openai.adoc, extended/src/main/java/apoc/ml/MLUtil.java, extended/src/main/java/apoc/ml/OpenAI.java, extended/src/test/java/apoc/ml/MLTestUtil.java, extended/src/test/java/apoc/ml/OpenAIIT.java
Fixes #4156
Added input validation to prevent unnecessary API calls toOpenAI when the input is empty or null.
Introduced a boolean flag to allow configuration of the behaviour:
- If set to `true`, an exception is raised when an empty (or blank) input is encountered.
- If `false`, the API call is silently skipped.
This change improves efficiency by streamlining the process and giving flexibility in handling empty input.
=> Fixes #4156: Improves handling of empty or blank input for openai procedures

.github/workflows/CI.yaml, .gitmodules, build.gradle, extended-it/src/test/java/apoc/neo4j/docker/StartupExtendedTest.java, extended/src/main/java/apoc/ExtendedApocGlobalComponents.java, extended/src/main/java/apoc/custom/CypherProceduresHandler.java
Instead of storing a map of the custom procedure handler to reference as a listener, which can cause a memory leak, common has been updated to find listeners and then add them. This means we can remove the map.
=> Remove stored map of Procedure Handlers

docs/asciidoc/modules/ROOT/nav.adoc, docs/asciidoc/modules/ROOT/pages/export/arrow.adoc, docs/asciidoc/modules/ROOT/pages/export/index.adoc, docs/asciidoc/modules/ROOT/pages/import/arrow.adoc, docs/asciidoc/modules/ROOT/pages/import/index.adoc, docs/asciidoc/modules/ROOT/pages/import/load-json.adoc, docs/asciidoc/modules/ROOT/pages/overview/apoc.export/apoc.export.arrow.all.adoc, docs/asciidoc/modules/ROOT/pages/overview/apoc.export/apoc.export.arrow.graph.adoc, docs/asciidoc/modules/ROOT/pages/overview/apoc.export/apoc.export.arrow.query.adoc, docs/asciidoc/modules/ROOT/pages/overview/apoc.export/apoc.export.arrow.stream.all.adoc, docs/asciidoc/modules/ROOT/pages/overview/apoc.export/apoc.export.arrow.stream.graph.adoc, docs/asciidoc/modules/ROOT/pages/overview/apoc.export/apoc.export.arrow.stream.query.adoc, docs/asciidoc/modules/ROOT/pages/overview/apoc.import/apoc.import.arrow.adoc, docs/asciidoc/modules/ROOT/pages/overview/apoc.load/apoc.load.arrow.adoc, docs/asciidoc/modules/ROOT/pages/overview/apoc.load/apoc.load.arrow.stream.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.export.arrow.all.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.export.arrow.graph.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.export.arrow.query.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.export.arrow.stream.all.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.export.arrow.stream.graph.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.export.arrow.stream.query.adoc, docs/asciidoc/modules/ROOT/partials/usage/apoc.load.jsonParams.adoc, extended/src/main/java/apoc/export/arrow/ImportArrow.java, extended/src/main/java/apoc/load/arrow/LoadArrowExtended.java
=> Fixes #4253: Missing apache arrow/jsonParams documentation

extended/src/main/java/apoc/cypher/CypherExtended.java, extended/src/test/java/apoc/cypher/CypherExtendedTest.java, extended/src/test/resources/wrong_statements.cypher, extended/src/test/resources/wrong_statements_runtime.cypher
Fixes #4243
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/b4ebf3fff84fa00d5d6e7288bfb662821ad4ffcc
=> Fixes #4243: Cherry pick of Fix performance for runFile (#4251)

extended-it/src/test/java/apoc/util/WeaviateTestUtil.java, extended-it/src/test/java/apoc/vectordb/WeaviateEnterpriseTest.java, extended-it/src/test/java/apoc/vectordb/WeaviateTest.java, extended/src/test/java/apoc/vectordb/VectorDbTestUtil.java
Fixes #4245
Created TestContainer's network using Weaviate and Neo4j containers,
to check that the Apache error is no longer present with enterprise neo4j too.
Created WeaviateTestUtil.java
With neo4j embedded it works even with `org.apache.commons.collections.MapUtils` imported.
=> Fixes #4245: Add integration test to check that apache.commons.collections is not present anymore

extended-it/src/test/java/apoc/couchbase/CouchbaseTestUtils.java, extended-it/src/test/java/apoc/vectordb/WeaviateTest.java
- Fix `apoc.vectordb.WeaviateTest.queryVectorsWithSystemDbStorageWithUrlV3Version`
- Changed `Caused by: java.io.FileNotFoundException: http://127.0.0.1:` with `Caused by: java.io.FileNotFoundException`, since the error can be either `"FileNotFoundException: http://localhost"`, or `"FileNotFoundException: http://127.0.0.1"` / other address, therefore generalized it.
The TC error is:
```
java.lang.AssertionError: Actual err. message is: Failed to invoke procedure `apoc.vectordb.weaviate.queryAndUpdate`: Caused by: java.io.FileNotFoundException: http://172.17.0.1:32897/v3/graphql
at org.junit.Assert.fail(Assert.java:89)
```
- Fix `apoc.couchbase.CouchbaseIT.classMethod`
- Upgraded image version
- ~Separated container startup and bucket creation handling~ it works locally but not in gh …
=> Fix TeamCity errors for 5.26

core/src/main/java/apoc/load/util/JdbcUtil.java, full/src/main/java/apoc/load/Jdbc.java, full/src/test/java/apoc/load/JdbcTest.java, full/src/test/java/apoc/load/LoadLdapTest.java, full/src/test/java/apoc/periodic/PeriodicExtendedTest.java, full/src/test/java/apoc/util/ExtendedTestUtil.java
Fixex #4256
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/32192dbcfee84661fd43caa52fa6f641f5b39c84
=> [NOID] Fixex #4256: Obfuscate JDBC Password in query.log

docs/asciidoc/modules/ROOT/pages/ml/openai.adoc, full/src/main/java/apoc/ml/MLUtil.java, full/src/main/java/apoc/ml/OpenAI.java, full/src/test/java/apoc/ml/OpenAIIT.java
Fixes #4156
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/d6b31c3017656306f01060d038af7deda36e3134
=> [NOID] Fixes #4156: Improves handling of empty or blank input for openai procedures (#4228)

extended-it/src/test/java/apoc/vectordb/QdrantTest.java, extended/src/test/java/apoc/gephi/GephiMock.java, extended/src/test/java/apoc/gephi/GephiTest.java, extended/src/test/java/apoc/load/LoadCsvTest.java, extended/src/test/java/apoc/ml/WatsonTest.java, extended/src/test/java/apoc/util/ExtendedTestUtil.java
- Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/c686650295ff9de91d5f6de9ebf22eaa2299cebe
- Added the same `PortFactory.findFreePort()` fix to `GephiMock` (by also changing the tests), 
to prevent future `port already used` errors
=> Try solving TeamCity errors in 5.26 (#4220)

extended-it/src/test/java/apoc/neo4j/docker/StartupExtendedTest.java
Added `NOTE` in StartupExtendedTest, 
to solve a potential `ModuleVersionNotFoundException` via an environment variable in case of Neo4j inconsistencies.
For instance, this error happened with the 5.25 branch, where [the Extended Neo4j version is 5.25.1](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/5.25/build.gradle#L155) (existing),
[while the Core one is 5.25.0](https://github.com/neo4j/apoc/blob/5.25/build.gradle#L172) (not existing).
Therefore, we added a comment with the resolution, in case of potential similar errors in the future.
=> Added note to solve a potential ModuleVersionNotFoundException in case of Neo4j inconsistencies

extended-it/build.gradle, extended-it/src/test/java/apoc/neo4j/docker/StartupExtendedTest.java
Fixes #4262
Add the equivalent of this test: https://github.com/neo4j/apoc/pull/274/files
for ApocStartupExtendedTest.java,
to check that the SLF4J: Failed to load class is not present
=> Fixes #4262: Add startup test for SLF4J

docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/pinecone.adoc, full/src/main/java/apoc/vectordb/Pinecone.java, full/src/main/java/apoc/vectordb/PineconeHandler.java, full/src/main/java/apoc/vectordb/VectorDbHandler.java, full/src/main/java/apoc/vectordb/VectorDbUtil.java, full/src/main/resources/extended.txt, full/src/test/java/apoc/vectordb/PineconeTest.java, full/src/test/java/apoc/vectordb/VectorDbTestUtil.java
Fixes #4242
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/b24d7746e41673d81fb698cc16a45a9793419817
Re-check the cherry-pick, pinecone procs missing
=> [NOID] Fixes #4242: The Pinecone APOC implementation is misleading (#4250)

core/src/main/java/apoc/export/graphml/XmlGraphMLReader.java, core/src/main/java/apoc/load/Xml.java, core/src/main/java/apoc/util/ConvertUtil.java, docs/asciidoc/modules/ROOT/nav.adoc, docs/asciidoc/modules/ROOT/pages/import/gexf.adoc, docs/asciidoc/modules/ROOT/pages/import/index.adoc, full/src/main/java/apoc/export/arrow/ImportArrow.java, full/src/main/java/apoc/load/Gexf.java, full/src/main/java/apoc/util/ExtendedUtil.java, full/src/main/resources/extended.txt, full/src/test/java/apoc/load/GexfTest.java, full/src/test/java/apoc/util/ExtendedTestUtil.java, full/src/test/resources/gexf/data.gexf, full/src/test/resources/gexf/single-node.gexf, full/src/test/resources/gexf/single-rel.gexf
Fixes #4138
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/487d97073e91745924fb8af2b5d7151b895ef493
=> [NOID] Fixes #4138: Add support for loading Gephi GEXF file format (#4171)

docs/asciidoc/modules/ROOT/pages/database-integration/elasticsearch.adoc, docs/asciidoc/modules/ROOT/pages/overview/apoc.es/apoc.es.post.adoc, full-it/src/test/java/apoc/full/it/es/ElasticVersionEightTest.java, full/src/main/java/apoc/es/ElasticSearch.java, full/src/test/java/apoc/mongodb/MongoDBTest.java
Fixes #4110
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/7693af7c5266f6b42576a0799bbc2fbd22ead06d
=> [NOID] Fixes #4110: Add support for the Reciprocal rank fusion in the Elastic procedures (#4155)

extra-dependencies/selenium/build.gradle, full/build.gradle, full/src/main/java/apoc/load/LoadHtml.java, full/src/main/java/apoc/load/LoadHtmlBrowser.java, full/src/test/java/apoc/load/LoadHtmlTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/c9c4fcbc9e70419665d83122e654dfef792bd786
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/e8d90e85505bbd731ecddfbdeb0b5ae2ec9e023a (only `LoadHtmlTest`)
=> [BqvAC2FK] Update selenium dependencies (#3663)

docs/asciidoc/modules/ROOT/pages/ml/genai.adoc, extended/src/main/java/apoc/ml/Prompt.java, extended/src/main/java/apoc/util/ExtendedUtil.java, extended/src/test/java/apoc/ml/PromptIT.java, extended/src/test/resources/northwind_dataset.cypher, extended/src/test/resources/northwind_schema.cypher
Fixes #4000
- Improved schema prompt to retrieve slightly better results
- Added `additionalPrompts` config which can accept list of maps with other request messages
- we can use it together with apoc.ml.schema to improve the results
- added examples with Northwind database: https://neo4j.com/docs/getting-started/appendix/tutorials/guide-import-relational-and-etl/
=> Fixes #4000: Add self-explanation to the model, include the verbal schema description to the flow

.github/actions/setup-gradle-cache/action.yaml, .github/workflows/CI.yaml, extended/src/main/java/apoc/agg/AggregationExtended.java
Test CI
Fix this error: https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/13266561703/job/37035384043?pr=4339#step:1:25
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: v2`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
```
=> Fix CI - update cache version

extended-it/src/test/java/apoc/neo4j/docker/MetricsTest.java, extended/src/main/java/apoc/metrics/Metrics.java
Fixes #4355
The problem is due to the Mode of the procedure.
With DBMS, the [URLAccessChecker.checkURL(url)](https://github.com/neo4j/apoc/blob/dev/common/src/main/java/apoc/util/FileUtils.java#L70) blocks the execution and throws the `LOAD ... is not allowed for user ...` error, because reading CSVs requires the procedure to be `READ`  (which is the default mode). 
Consistently with apoc.load.csv and the other load procedures
- Fixed the bug removing the `Procedure.Mode` annotation [from the 3 procedures](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4357/files#diff-3715b84a6cdfdc34f78575e994d7f1176b4282b4403db476949ab11e6d3128d3R120)
- De-ignored the `shouldGetMetrics` test
- The `neo4j.system.check_point.total_time` doesn't work, as has been replaced by …
=> Fixes #4355: The apoc.metrics.get throws an URLAccessChecker error

.github/actions/test-gradle-project/action.yml, .github/workflows/CI.yaml, extended/src/main/java/apoc/cypher/CypherExtended.java, extended/src/test/java/apoc/systemdb/SystemDbTest.java
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/96b1bd11c184d785416d0bf3b38c333fced390ef
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/f3bb30d7da680ea887e796acce8f55b3b991c0e7
Reverted https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/96b1bd11c184d785416d0bf3b38c333fced390ef#diff-0be321a488b8e1a039cef51ff786b8142a2eac4a76f7585ff6121e4fc588dfc9 , no longer valid in 5.26
=> Fixing CODEARTIFACT_DOWNLOAD_URL to be able to retrieve both CI and Release artifacts (#4354)

extended-it/src/test/java/apoc/couchbase/CouchbaseTestUtils.java, extended-it/src/test/java/apoc/vectordb/WeaviateTest.java
- Fix `apoc.vectordb.WeaviateTest.queryVectorsWithSystemDbStorageWithUrlV3Version`
- Changed `Caused by: java.io.FileNotFoundException: http://127.0.0.1:` with `Caused by: java.io.FileNotFoundException`, since the error can be either `"FileNotFoundException: http://localhost"`, or `"FileNotFoundException: http://127.0.0.1"` / other address, therefore generalized it.
The TC error is:
```
java.lang.AssertionError: Actual err. message is: Failed to invoke procedure `apoc.vectordb.weaviate.queryAndUpdate`: Caused by: java.io.FileNotFoundException: http://172.17.0.1:32897/v3/graphql
at org.junit.Assert.fail(Assert.java:89)
```
- Fix `apoc.couchbase.CouchbaseIT.classMethod`
- Upgraded image version
- Increased timeout to wait for the bucket to be ready
- Added `waitOptions` to …
=> Fix TeamCity errors for 2025.01.0

extended-it/src/test/java/apoc/mongodb/MongoTest.java, extended-it/src/test/java/apoc/mongodb/MongoTestBase.java
Try fixing flaky MongoDb TeamCity tests 2025.01.
Unfortunately, the error does not seem replicable either locally or on Gh action.
Try these two ways that could alleviate the problems:
- Added maxSize and maxConnectionIdleTime
- Upgraded mongo 7.x.x version
The TeamCity problem is:
```
apoc.mongodb.MongoTest.shouldNotFailsIfUriHasNotCollectionNameButIsPresentInConfig
java.lang.AssertionError: 
Expecting actual:
false
to satisfy:
Generic condition. See predicate for condition details.
java.lang.AssertionError:
Expecting actual:
false
to satisfy:
Generic condition. See predicate for condition details.
at org.neo4j.test.assertion.Assert.lambda$assertEventually$0(Assert.java:73)
at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
at …
```
=> Try fixing flaky MongoDb TeamCity tests 2025.01

docs/asciidoc/modules/ROOT/partials/s3-protocol.adoc, extended-it/src/test/java/apoc/s3/LoadS3MinioTest.java
Fixed [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4351#:~:text=try%20with%20clearProperty)
---
Fixes #4321
The test with a minio instance present [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/4.3.0.2/full/src/test/java/apoc/load/LoadS3Test.java) does not work as a "real" instance.
In fact, using an instance pointing to localhost, it fails with TODO error.
To fix it, just put the java property `Dcom.amazonaws.sdk.disableCertChecking=true` that executes the if present [here](https://github.com/neo4j/apoc/blob/dev/common/src/main/java/apoc/util/s3/S3ParamsExtractor.java#L132).
Therefore, added test and docs.
Used [bitnami/minio](https://hub.docker.com/r/bitnami/minio) since the official [minio](https://hub.docker.com/r/minio/minio) image doesn't …
=> Fixes #4321: support s3 for non-aws storage

extended-it/src/test/java/apoc/couchbase/CouchbaseTestUtils.java, extended-it/src/test/java/apoc/neo4j/docker/BoltTest.java, extended-it/src/test/java/apoc/vectordb/WeaviateTest.java, extended/src/test/kotlin/apoc/nlp/aws/AWSProceduresAPIWithDummyClientTest.kt, extended/src/test/kotlin/apoc/nlp/azure/AzureProceduresAPIWithDummyClientTest.kt, extended/src/test/kotlin/apoc/nlp/gcp/GCPProceduresAPIWithDummyClientTest.kt
- Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4370
- [provisionally ignored *ProceduresAPIWithDummyClientTest](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4371/commits/ed3f77bec40677f9723caa950cd5bf951af96c06)
- ~TODO: flaky test? https://github.com/neo4j-contrib/neo4j-apoc-procedures/actions/runs/13694182462/job/38295066619#step:10:6814~
- [provisionally ignored testBoltLoadReturningMapAndList](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4371/commits/1e5e2b9c51280cfdfc77503789e317d0edf087b2)
=> Fix TeamCity errors for 2025.01.0 (cherry-pick)

docs/asciidoc/modules/ROOT/partials/s3-protocol.adoc, extended-it/src/test/java/apoc/s3/LoadS3MinioTest.java
Fixes #4321
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/e1be352f7a146ca2eb559d1e8c3d8533152fb2fc
=> Fixes #4321: support s3 for non-aws storage (#4351)

docs/asciidoc/modules/ROOT/pages/cypher-execution/cypher-based-procedures-functions.adoc, extended/src/main/java/apoc/custom/CypherNewProcedures.java, extended/src/main/java/apoc/custom/CypherProcedures.java, extended/src/main/java/apoc/custom/CypherProceduresHandler.java, extended/src/main/java/apoc/custom/CypherProceduresUtil.java, extended/src/test/java/apoc/custom/CypherNewProceduresTest.java
Fixes #1431
it makes sense to create a config option, for consistency with other procedures that work similarly (apoc.trigger, uuid, ttl..), as disabling periodic refresh increases performance a bit.
The config name is `apoc.custom.procedures.enabled` instead of e.g. `apoc.custom.enabled`,
to be consistent with the `apoc.custom.procedures.refresh` setting.
But we can't disable it by default, because that would be a breaking change, so the default is true.
=> Fixes #1431: Disable custom procedure config

docs/asciidoc/modules/ROOT/pages/ml/openai.adoc, extended/src/test/java/apoc/ml/OpenAIGroqAPIsIT.java
Fix invalid Groq models
The groq models, mixtral and llama2, don't work anymore because they were removed
Changed with new ones and refactored the test by parameterizing it.
=> Fix invalid Groq models

extended/build.gradle, settings.gradle
```
[09:32:46]W:	 [Step 3/4] > Could not resolve all files for configuration ':core:testCompileClasspath'.
[09:32:46] :	 [Step 3/4] 18 actionable tasks: 18 executed
[09:32:46]W:	 [Step 3/4]    > Could not find com.neo4j:enterprise-it-test-support:2025.04.0.
[09:32:46]W:	 [Step 3/4]      Searched in the following locations:
[09:32:46] :	 [Step 3/4] Some of the file system contents retained in the virtual file system are on file systems that Gradle doesn't support watching. The relevant state was discarded to ensure changes to these locations are properly detected. You can override this by explicitly enabling file system watching.
[09:32:46]W:	 [Step 3/4]        - https://repo.maven.apache.org/maven2/com/neo4j/enterprise-it-test-support/2025.04.0/enterprise-it-test-support-2025.04.0.pom …
```
=> Fix enterprise-it-test-support not found in TeamCity

settings.gradle
Not sure why this error has not occurred previously (maybe because of [this core change](https://github.com/neo4j/apoc/pull/755/commits/e53797f2c917fb971d314a7bf1d8cf38219dd26c#diff-00d5c5c00ed3cf7739c15c300a5fee228e88590bf4c026e719b2732c07ffc3bfR25)?)
Since the following errors are all about core's jar not found with testcontainer, 
I tried to remove `':core:shadowJar'` from the excluded task for test, 
because probably by not building the core jar when `./gradlew test <args>` is executed in TeamCity, 
it is not created, hence the errors.
I guess we still need to exclude it for `shadow` and `build` as before, 
because this error could happen again: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3597
They are all similar and cover some tests using both extended and core jar, …
=> Try fixing tests with core jars in 2025.04

build.gradle, versions.json
Fixes to allow for the new 2025.x to be added to the versions.json.
Originally fixed here: https://github.com/neo4j/apoc/pull/785
=> Fix versions for calver

settings.gradle
Fixes https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4432
Fixes https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4430
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/643dbc12d86d5f2bdae5b4a5d966a16d3e523e62
Cherry-pick https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/0db6844b2387c441387cfbc874cd5b0e211f21ea
=> Fix enterprise-it-test-support not found in TeamCity (#4430)

extended/src/main/java/apoc/bolt/BoltConnection.java
Fix TeamCity BoltConnection compilation error for release 5.26.1.
The error is:
```
[14:50:27]W:	 [Step 5/7]                      ^
[14:50:27]W:	 [Step 5/7] /opt/teamcity-agent/work/af99a1b2d35610b6/neo4j-apoc-procedures/extended/src/main/java/apoc/bolt/BoltConnection.java:162: error: no suitable constructor found for VirtualNode(long,String,Label[],Map<String,Object>)
[14:50:27]W:	 [Step 5/7]             VirtualNode virtualNode = new VirtualNode(node.id(), node.elementId(), labels.toArray(new Label[0]), node.asMap());
[14:50:27]W:	 [Step 5/7]                                       ^
[14:50:27]W:	 [Step 5/7]     constructor VirtualNode.VirtualNode(Label[],Map<String,Object>) is not applicable
[14:50:27]W:	 [Step 5/7]       (actual and formal argument lists differ in length)
[14:50:27]W: …
```
=> Fix TeamCity BoltConnection compilation error for release 5.26.1

docs/asciidoc/modules/ROOT/pages/comparing-graphs/graph-difference.adoc, docs/asciidoc/modules/ROOT/pages/comparing-graphs/index.adoc, docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/index.adoc, docs/asciidoc/modules/ROOT/pages/operational/rebind.adoc
Various small docs fixes
- Added tag titles to solve errors like this:
- Fixed subheading formatting in vector db overview page: docs/asciidoc/modules/ROOT/pages/database-integration/vectordb/index.adoc
- Added missing overview page of comparing graph section
=> Various small docs fixes

docs/asciidoc/modules/ROOT/pages/export/index.adoc, docs/asciidoc/modules/ROOT/pages/import/index.adoc, docs/asciidoc/modules/ROOT/pages/index.adoc
Fixes #4444
- Updated file formats on the export and import pages, removing those that refer to APOC Core.
- Removed file format from overview page to avoid potential inconsistencies
=> Fixes #4444: update import/export documentation with correct extended formats
